-- flowd tests: formula parity with packages/contract/formula-vectors.json
-- GENERATED by supabase/tools/gen-formula-tests.mjs (npm run supabase:gen). Do not edit by hand.
--
-- 45 vector cases replayed against the SQL formulas of 0003_functions.sql. 6 further vectors (expected_earnings, hook_score,
-- flow_score) have no SQL implementation by design: they run in services/ml and in the web and iOS engines.
--
-- Run:  psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/tests/00_helpers.sql -f supabase/tests/formulas.test.sql
--       node supabase/tools/verify-pglite.mjs            (no Docker: in-process Postgres 18 with pgvector)
-- Every *.test.sql file is plain SQL that rolls back, so it is safe against a dev database.

begin;

-- funding (5 vectors): fee reserve, escrow total, matched budget, processing, card charge
do $t$
begin
  perform tap.same('funding[0]', (select to_jsonb(f) from public.funding(500000, 0.12::numeric, 0) f), '{"budget_cents":500000,"take_rate":0.12,"fee_reserve_cents":60000,"escrow_total_cents":560000,"matched_cents":0,"brand_funded_cents":560000,"processing_cents":16270,"card_charge_cents":576270}'::jsonb);
  perform tap.same('funding[1]', (select to_jsonb(f) from public.funding(300000, 0.1::numeric, 0) f), '{"budget_cents":300000,"take_rate":0.1,"fee_reserve_cents":30000,"escrow_total_cents":330000,"matched_cents":0,"brand_funded_cents":330000,"processing_cents":9600,"card_charge_cents":339600}'::jsonb);
  perform tap.same('funding[2]', (select to_jsonb(f) from public.funding(120000, 0.06::numeric, 0) f), '{"budget_cents":120000,"take_rate":0.06,"fee_reserve_cents":7200,"escrow_total_cents":127200,"matched_cents":0,"brand_funded_cents":127200,"processing_cents":3719,"card_charge_cents":130919}'::jsonb);
  perform tap.same('funding[3]', (select to_jsonb(f) from public.first_bounty_funding(150000) f), '{"budget_cents":200000,"take_rate":0,"fee_reserve_cents":0,"escrow_total_cents":200000,"matched_cents":50000,"brand_funded_cents":150000,"processing_cents":4380,"card_charge_cents":154380}'::jsonb);
  perform tap.same('funding[4]', (select to_jsonb(f) from public.first_bounty_funding(30000) f), '{"budget_cents":60000,"take_rate":0,"fee_reserve_cents":0,"escrow_total_cents":60000,"matched_cents":30000,"brand_funded_cents":30000,"processing_cents":900,"card_charge_cents":30900}'::jsonb);
end
$t$;

-- settle_post (4 vectors): stacked CPM + CPA pay, per-video cap, fee per leg
do $t$
begin
  perform tap.same('settle_post[0]', (select to_jsonb(s) from public.settle_post_math(48200, 200, 14, 6, 2, 40, 150, 400, 25000, 0.1::numeric, 0) s), '{"cpm_uncapped_cents":9640,"cpa_uncapped_cents":2260,"cpm_pay_cents":9640,"cpa_pay_cents":2260,"pay_cents":11900,"capped":false,"cap_remaining_cents":13100,"fee_cpm_cents":964,"fee_cpa_cents":226,"fee_cents":1190,"brand_cost_cents":13090}'::jsonb);
  perform tap.same('settle_post[1]', (select to_jsonb(s) from public.settle_post_math(150000, 200, 40, 10, 3, 40, 150, 400, 25000, 0.1::numeric, 0) s), '{"cpm_uncapped_cents":30000,"cpa_uncapped_cents":4300,"cpm_pay_cents":25000,"cpa_pay_cents":0,"pay_cents":25000,"capped":true,"cap_remaining_cents":0,"fee_cpm_cents":2500,"fee_cpa_cents":0,"fee_cents":2500,"brand_cost_cents":27500}'::jsonb);
  perform tap.same('settle_post[2]', (select to_jsonb(s) from public.settle_post_math(9999, 50, 0, 0, 0, 0, 0, 0, 25000, 0.12::numeric, 0) s), '{"cpm_uncapped_cents":500,"cpa_uncapped_cents":0,"cpm_pay_cents":500,"cpa_pay_cents":0,"pay_cents":500,"capped":false,"cap_remaining_cents":24500,"fee_cpm_cents":60,"fee_cpa_cents":0,"fee_cents":60,"brand_cost_cents":560}'::jsonb);
  perform tap.same('settle_post[3]', (select to_jsonb(s) from public.settle_post_math(12345, 175, 3, 0, 0, 40, 0, 0, 1500, 0.08::numeric, 0) s), '{"cpm_uncapped_cents":2160,"cpa_uncapped_cents":120,"cpm_pay_cents":1500,"cpa_pay_cents":0,"pay_cents":1500,"capped":true,"cap_remaining_cents":0,"fee_cpm_cents":120,"fee_cpa_cents":0,"fee_cents":120,"brand_cost_cents":1620}'::jsonb);
end
$t$;

-- instant_payout (8 vectors): 1.5% fee, $0.50 floor, $15 cap, free allowances
do $t$
begin
  perform tap.same('instant_payout[0]', (select to_jsonb(p) from public.instant_payout_math(16000, 'silver'::public.tier, false, 0) p), '{"ok":true,"fee_cents":240,"net_cents":15760,"free_instant":false,"list_fee_cents":240}'::jsonb);
  perform tap.same('instant_payout[1]', (select to_jsonb(p) from public.instant_payout_math(2000, 'silver'::public.tier, false, 0) p), '{"ok":true,"fee_cents":50,"net_cents":1950,"free_instant":false,"list_fee_cents":50}'::jsonb);
  perform tap.same('instant_payout[2]', (select to_jsonb(p) from public.instant_payout_math(200000, 'silver'::public.tier, false, 0) p), '{"ok":true,"fee_cents":1500,"net_cents":198500,"free_instant":false,"list_fee_cents":1500}'::jsonb);
  perform tap.same('instant_payout[3]', (select to_jsonb(p) from public.instant_payout_math(16000, 'gold'::public.tier, false, 0) p), '{"ok":true,"fee_cents":0,"net_cents":16000,"free_instant":true,"list_fee_cents":240}'::jsonb);
  perform tap.same('instant_payout[4]', (select to_jsonb(p) from public.instant_payout_math(16000, 'gold'::public.tier, false, 1) p), '{"ok":true,"fee_cents":240,"net_cents":15760,"free_instant":false,"list_fee_cents":240}'::jsonb);
  perform tap.same('instant_payout[5]', (select to_jsonb(p) from public.instant_payout_math(50000, 'platinum'::public.tier, false, 3) p), '{"ok":true,"fee_cents":0,"net_cents":50000,"free_instant":true,"list_fee_cents":750}'::jsonb);
  perform tap.same('instant_payout[6]', (select to_jsonb(p) from public.instant_payout_math(16000, 'bronze'::public.tier, true, 0) p), '{"ok":true,"fee_cents":0,"net_cents":16000,"free_instant":true,"list_fee_cents":240}'::jsonb);
  perform tap.same('instant_payout[7]', (select to_jsonb(p) from public.instant_payout_math(499, 'silver'::public.tier, false, 0) p), '{"ok":false,"reason":"below_minimum","fee_cents":0,"net_cents":0,"free_instant":false}'::jsonb);
end
$t$;

-- tier (5 vectors): highest tier whose thresholds are all met, progress to the next
do $t$
begin
  perform tap.eq('tier[0].tier', public.tier_for(164000, 21, 0.78::numeric, 93, false)::text, 'silver');
  perform tap.same('tier[0].progress', public.tier_progress(164000, 21, 0.78::numeric, 93, false), '{"current":"silver","next":"gold","criteria":[{"key":"lifetime_cleared","label":"Lifetime cleared","have":164000,"need":200000,"met":false},{"key":"approved","label":"Approved posts","have":21,"need":25,"met":false},{"key":"approval_rate","label":"Approval rate","have":0.78,"need":0.75,"met":true}],"progress":0.82}'::jsonb);
  perform tap.eq('tier[1].tier', public.tier_for(250000, 30, 0.8::numeric, 70, false)::text, 'gold');
  perform tap.same('tier[1].progress', public.tier_progress(250000, 30, 0.8::numeric, 70, false), '{"current":"gold","next":"platinum","criteria":[{"key":"lifetime_cleared","label":"Lifetime cleared","have":250000,"need":1000000,"met":false},{"key":"approved","label":"Approved posts","have":30,"need":80,"met":false},{"key":"approval_rate","label":"Approval rate","have":0.8,"need":0.8,"met":true},{"key":"reliability","label":"Reliability","have":70,"need":90,"met":false}],"progress":0.25}'::jsonb);
  perform tap.eq('tier[2].tier', public.tier_for(1200000, 90, 0.82::numeric, 91, false)::text, 'platinum');
  perform tap.same('tier[2].progress', public.tier_progress(1200000, 90, 0.82::numeric, 91, false), '{"current":"platinum","next":"elite","criteria":[{"key":"lifetime_cleared","label":"Lifetime cleared","have":1200000,"need":5000000,"met":false},{"key":"approved","label":"Approved posts","have":90,"need":250,"met":false},{"key":"approval_rate","label":"Approval rate","have":0.82,"need":0.85,"met":false},{"key":"reliability","label":"Reliability","have":91,"need":95,"met":false},{"key":"review","label":"Manual review","have":0,"need":1,"met":false}],"progress":0.24}'::jsonb);
  perform tap.eq('tier[3].tier', public.tier_for(6000000, 300, 0.9::numeric, 97, true)::text, 'elite');
  perform tap.same('tier[3].progress', public.tier_progress(6000000, 300, 0.9::numeric, 97, true), '{"current":"elite","criteria":[],"progress":1}'::jsonb);
  perform tap.eq('tier[4].tier', public.tier_for(6000000, 300, 0.9::numeric, 97, false)::text, 'platinum');
  perform tap.same('tier[4].progress', public.tier_progress(6000000, 300, 0.9::numeric, 97, false), '{"current":"platinum","next":"elite","criteria":[{"key":"lifetime_cleared","label":"Lifetime cleared","have":6000000,"need":5000000,"met":true},{"key":"approved","label":"Approved posts","have":300,"need":250,"met":true},{"key":"approval_rate","label":"Approval rate","have":0.9,"need":0.85,"met":true},{"key":"reliability","label":"Reliability","have":97,"need":95,"met":true},{"key":"review","label":"Manual review","have":0,"need":1,"met":false}],"progress":1}'::jsonb);
end
$t$;

-- fraud (3 vectors): score = min(100, sum(round(max_points x severity))), band
do $t$
begin
  perform tap.same('fraud[0]', public.fraud_score('[{"signal":"view_spike_no_engagement","severity":0.8},{"signal":"bought_views_pattern","severity":0.9},{"signal":"traffic_source_anomaly","severity":0.7},{"signal":"curve_shape","severity":0.6}]'::jsonb), '{"score":60,"band":"review","signals":[{"signal":"view_spike_no_engagement","severity":0.8,"points":20,"detail":"Hourly views at least 10x the post baseline while engagement stays under 0.5% of views."},{"signal":"bought_views_pattern","severity":0.9,"points":27,"detail":"Step-function curve: 80% or more of views arrive in two hourly buckets, flat otherwise, and over 60% of views come from the \"other\" source."},{"signal":"traffic_source_anomaly","severity":0.7,"points":7,"detail":"More than 50% of views from external or \"other\" sources."},{"signal":"curve_shape","severity":0.6,"points":6,"detail":"No natural decay: hourly views flat or rising for more than 24 hours."}]}'::jsonb);
  perform tap.same('fraud[1]', public.fraud_score('[{"signal":"new_account","severity":1},{"signal":"engagement_anomaly","severity":0.5}]'::jsonb), '{"score":15,"band":"clean","signals":[{"signal":"new_account","severity":1,"points":10,"detail":"Social account younger than 30 days."},{"signal":"engagement_anomaly","severity":0.5,"points":5,"detail":"Likes under 0.4% of views, or comment ratio an outlier against the account''s 28-day norm."}]}'::jsonb);
  perform tap.same('fraud[2]', public.fraud_score('[]'::jsonb), '{"score":0,"band":"clean","signals":[]}'::jsonb);
end
$t$;

-- money_clock (4 vectors): window end, clearing run, weekly payout ETA
do $t$
begin
  perform tap.ok('money_clock[0]', (select r.state::text = 'cleared' and r.reason::text = 'awaiting_weekly_payout' and r.window_ends_at = '2026-10-02T21:00:00Z'::timestamptz and r.eta_at = '2026-10-09T18:00:00Z'::timestamptz and r.cleared_at = '2026-10-03T14:00:00Z'::timestamptz from public.money_clock_state_for('2026-09-29T21:00:00Z'::timestamptz, '2026-10-03T14:00:00Z'::timestamptz) r));
  perform tap.ok('money_clock[1]', (select r.state::text = 'cleared' and r.reason::text = 'awaiting_weekly_payout' and r.window_ends_at = '2026-10-03T09:00:00Z'::timestamptz and r.eta_at = '2026-10-09T18:00:00Z'::timestamptz and r.cleared_at = '2026-10-03T14:00:00Z'::timestamptz from public.money_clock_state_for('2026-09-30T09:00:00Z'::timestamptz, '2026-10-03T14:00:00Z'::timestamptz) r));
  perform tap.ok('money_clock[2]', (select r.state::text = 'accruing' and r.reason::text = 'window_open' and r.window_ends_at = '2026-10-05T18:30:00Z'::timestamptz and r.eta_at = '2026-10-06T14:00:00Z'::timestamptz and r.cleared_at is null from public.money_clock_state_for('2026-10-02T18:30:00Z'::timestamptz, '2026-10-03T14:00:00Z'::timestamptz) r));
  perform tap.ok('money_clock[3]', (select r.state::text = 'accruing' and r.reason::text = 'window_open' and r.window_ends_at = '2026-10-06T13:59:00Z'::timestamptz and r.eta_at = '2026-10-07T14:00:00Z'::timestamptz and r.cleared_at is null from public.money_clock_state_for('2026-10-03T13:59:00Z'::timestamptz, '2026-10-03T14:00:00Z'::timestamptz) r));
end
$t$;

-- conversion_clearing (3 vectors): install 24 h, trial 72 h, paid 168 h, then the next 14:00Z run
do $t$
begin
  perform tap.ok('conversion_clearing[0]', public.conversion_clearing_run('install'::public.conversion_kind, '2026-10-02T09:00:00Z'::timestamptz) = '2026-10-03T14:00:00Z'::timestamptz);
  perform tap.ok('conversion_clearing[1]', public.conversion_clearing_run('trial'::public.conversion_kind, '2026-10-01T08:15:00Z'::timestamptz) = '2026-10-04T14:00:00Z'::timestamptz);
  perform tap.ok('conversion_clearing[2]', public.conversion_clearing_run('paid'::public.conversion_kind, '2026-09-28T20:00:00Z'::timestamptz) = '2026-10-06T14:00:00Z'::timestamptz);
end
$t$;

-- sla (5 vectors): on_track under 48 h, stale to 72 h, breached after
do $t$
begin
  perform tap.eq('sla[0]', public.sla_state_for(0::numeric)::text, 'on_track');
  perform tap.eq('sla[1]', public.sla_state_for(47.99::numeric)::text, 'on_track');
  perform tap.eq('sla[2]', public.sla_state_for(48::numeric)::text, 'stale');
  perform tap.eq('sla[3]', public.sla_state_for(72::numeric)::text, 'stale');
  perform tap.eq('sla[4]', public.sla_state_for(72.01::numeric)::text, 'breached');
end
$t$;

-- brand_reliability (3 vectors): weights, bands, "new" under 10 decisions
do $t$
begin
  perform tap.same('brand_reliability[0]', public.brand_reliability_calc(64, 49, 11.2::numeric, 1, 0.99::numeric, 0.93::numeric, 4.5::numeric), '{"score":97,"band":"excellent","components":[{"key":"decision_speed","label":"Decision speed","value":1,"weight":0.3,"points":30,"reason":"Median 11.2 h to decide (best 12 h, worst 72 h)."},{"key":"approval_fairness","label":"Approval fairness","value":0.97,"weight":0.25,"points":24.17,"reason":"23% of decisions were rejections; 1 overturned on appeal."},{"key":"pays_on_time","label":"Pays on time","value":0.99,"weight":0.2,"points":19.8,"reason":"99% of commissions, offers and top-ups funded on time."},{"key":"run_rate","label":"Runs what it approves","value":0.93,"weight":0.15,"points":13.95,"reason":"93% of approved work was posted or used within 30 days."},{"key":"reply_speed","label":"Reply speed","value":0.95,"weight":0.1,"points":9.46,"reason":"Median 4.5 h to reply."}],"rejection_rate":0.23}'::jsonb);
  perform tap.same('brand_reliability[1]', public.brand_reliability_calc(22, 9, 58::numeric, 3, 0.8::numeric, 0.5::numeric, 30::numeric), '{"score":38,"band":"poor","components":[{"key":"decision_speed","label":"Decision speed","value":0.23,"weight":0.3,"points":7,"reason":"Median 58.0 h to decide (best 12 h, worst 72 h)."},{"key":"approval_fairness","label":"Approval fairness","value":0.16,"weight":0.25,"points":3.93,"reason":"59% of decisions were rejections; 3 overturned on appeal."},{"key":"pays_on_time","label":"Pays on time","value":0.8,"weight":0.2,"points":16,"reason":"80% of commissions, offers and top-ups funded on time."},{"key":"run_rate","label":"Runs what it approves","value":0.5,"weight":0.15,"points":7.5,"reason":"50% of approved work was posted or used within 30 days."},{"key":"reply_speed","label":"Reply speed","value":0.39,"weight":0.1,"points":3.91,"reason":"Median 30.0 h to reply."}],"rejection_rate":0.59}'::jsonb);
  perform tap.same('brand_reliability[2]', public.brand_reliability_calc(6, 6, 8::numeric, 0, 1::numeric, 1::numeric, 1::numeric), '{"score":100,"band":"new","components":[{"key":"decision_speed","label":"Decision speed","value":1,"weight":0.3,"points":30,"reason":"Median 8.0 h to decide (best 12 h, worst 72 h)."},{"key":"approval_fairness","label":"Approval fairness","value":1,"weight":0.25,"points":25,"reason":"0% of decisions were rejections; 0 overturned on appeal."},{"key":"pays_on_time","label":"Pays on time","value":1,"weight":0.2,"points":20,"reason":"100% of commissions, offers and top-ups funded on time."},{"key":"run_rate","label":"Runs what it approves","value":1,"weight":0.15,"points":15,"reason":"100% of approved work was posted or used within 30 days."},{"key":"reply_speed","label":"Reply speed","value":1,"weight":0.1,"points":10,"reason":"Median 1.0 h to reply."}],"rejection_rate":0}'::jsonb);
end
$t$;

-- price_curve (2 vectors): p50 / p80 fill hours and confidence at six CPMs
do $t$
begin
  perform tap.same('price_curve[0]', public.price_curve(240, 31, 38), '[{"cpm_cents":144,"fill_hours_p50":70.2,"fill_hours_p80":126.35,"confidence":0.33,"sample_n":38},{"cpm_cents":192,"fill_hours_p50":44.3,"fill_hours_p80":79.74,"confidence":0.51,"sample_n":38},{"cpm_cents":240,"fill_hours_p50":31,"fill_hours_p80":55.8,"confidence":0.66,"sample_n":38},{"cpm_cents":288,"fill_hours_p50":23.16,"fill_hours_p80":41.68,"confidence":0.54,"sample_n":38},{"cpm_cents":360,"fill_hours_p50":16.2,"fill_hours_p80":29.17,"confidence":0.39,"sample_n":38},{"cpm_cents":480,"fill_hours_p50":10.23,"fill_hours_p80":18.41,"confidence":0.33,"sample_n":38}]'::jsonb);
  perform tap.same('price_curve[1]', public.price_curve(170, 52, 6), '[{"cpm_cents":102,"fill_hours_p50":117.75,"fill_hours_p80":211.95,"confidence":0.12,"sample_n":6},{"cpm_cents":136,"fill_hours_p50":74.31,"fill_hours_p80":133.76,"confidence":0.18,"sample_n":6},{"cpm_cents":170,"fill_hours_p50":52,"fill_hours_p80":93.6,"confidence":0.23,"sample_n":6},{"cpm_cents":204,"fill_hours_p50":38.84,"fill_hours_p80":69.92,"confidence":0.19,"sample_n":6},{"cpm_cents":255,"fill_hours_p50":27.18,"fill_hours_p80":48.92,"confidence":0.14,"sample_n":6},{"cpm_cents":340,"fill_hours_p50":17.15,"fill_hours_p80":30.88,"confidence":0.12,"sample_n":6}]'::jsonb);
end
$t$;

-- match_score (3 vectors): niche 40, platform 15, region 15, price 15, brand 10, recency 5; null when a gate fails
do $t$
begin
  perform tap.eq('match_score[0]', public.match_score(true, 1, 1, 1, 1.2, 94, 2)::text, '96');
  perform tap.ok('match_score[1]', public.match_score(false, 1, 1, 1, 1.2, 94, 2) is null);
  perform tap.eq('match_score[2]', public.match_score(true, 0.5, 1, 0.6, 0.7, 60, 20)::text, '59');
end
$t$;

select 'formulas.test.sql: 45 vector cases passed' as result;
rollback;
