// GENERATED by scripts/gen-ios-models.mjs from packages/contract/schema/*.mjs. Do not edit by hand: change the schema, then run  node scripts/gen-ios-models.mjs
// Names, enum values and field types mirror packages/contract/DOMAIN.md sections 5 to 7. Decoded with .convertFromSnakeCase.

import Foundation

// Entities (one per fixture file) and their nested value types: Rights.

// MARK: - RightsGrant (rights_grants)

/// A usage-rights grant on a post: organic (always), paid-ad usage (default 90 days), a Spark code or a partnership permission. Powers the Rights Vault with expiry alerts at 30, 14 and 7 days.
struct RightsGrant: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var postId: String
    var submissionId: String
    var bountyId: String
    var brandId: String
    var appId: String
    var creatorId: String
    var scope: RightsScope
    var status: RightsGrantStatus
    var platform: AdPlatform?
    /// Fictional Spark authorization code (spark_code scope).
    var sparkCode: String?
    /// One of 7, 30, 60, 365.
    var codeDurationDays: Int?
    var startsAt: Date
    /// Absent for organic posting, which has no end.
    var endsAt: Date?
    /// The fee renewals are priced from: the post's settled creator pay (or the flat fee for direct bounties).
    var baseFeeCents: Int
    /// Default 0.25.
    var renewalPctPer30d: Double
    /// round(base_fee_cents x renewal_pct_per_30d) per 30 days.
    var renewalPriceCents: Int
    var renewals: [Renewal]
    /// Subset of 30, 14, 7: the expiry alerts already sent.
    var alertsSent: [Int]
    /// The ad that depends on this grant.
    var adId: String?
    /// Always false in this build.
    var aiLikeness: Bool
    var revokedAt: Date?
    var revokeReason: String?
    var createdAt: Date
    var updatedAt: Date
}

// MARK: - Value types used by Rights entities

// MARK: - Renewal

/// A rights renewal.
struct Renewal: Codable, Hashable, Sendable {
    var at: Date
    /// Extension in days (multiples of 30).
    var days: Int
    var feeCents: Int
    var ledgerTxnId: String?
    var requestedByMemberId: String?
}
