// GENERATED by scripts/gen-ios-models.mjs from packages/contract/schema/*.mjs. Do not edit by hand: change the schema, then run  node scripts/gen-ios-models.mjs
// Names, enum values and field types mirror packages/contract/DOMAIN.md sections 5 to 7. Decoded with .convertFromSnakeCase.

import Foundation

// Entities (one per fixture file) and their nested value types: Market.

// MARK: - MarketSeriesPoint (market_series)

/// Daily market data per category (the clearing CPM series). "Clearing CPM" = median CPM of bounties that filled or are live and receiving submissions.
struct MarketSeriesPoint: Codable, Hashable, Identifiable, Sendable {
    /// mkt_<category>_<YYYY-MM-DD>.
    var id: String
    var category: AppCategory
    var date: String
    /// Median.
    var clearingCpmCents: Int
    var p25CpmCents: Int
    var p75CpmCents: Int
    var openBounties: Int
    var openBudgetCents: Int
    var newBounties: Int
    var submissions: Int
    var medianFillHours: Double
    /// Median verified views per post in the category (7-day trailing).
    var medianViews: Int
    /// Trials per install (7-day trailing).
    var trialRate: Double
    var sampleN: Int
}

// MARK: - Ticker (ticker)

/// The public live payout ticker: totals plus recent events. Object-shaped file.
struct Ticker: Codable, Hashable, Sendable {
    var totals: TickerTotals
    /// Newest first; 40 to 80 events.
    var events: [TickerEvent]
}

// MARK: - Offer (offers)

/// An offer between a brand and a creator: an invite to an open bounty, a direct offer bought from a rate card, or a re-buy of a winner. Carries the negotiation thread (max 3 counter rounds, 7-day expiry). Accepting a direct offer funds a private direct bounty from the brand wallet.
struct Offer: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var kind: OfferKind
    /// Says who has the ball: awaiting_creator or awaiting_brand.
    var status: OfferStatus
    var brandId: String
    var appId: String
    var creatorId: String
    var createdByMemberId: String
    /// e.g. "Two new hooks on Glow-up reveal".
    var title: String
    /// Invite: the open bounty. Direct / re-buy: the private direct bounty, set when the offer is accepted.
    var bountyId: String?
    /// The rate card the offer was bought from.
    var rateCardId: String?
    /// Re-buy: the winning post the new hooks are based on.
    var rebuyOfPostId: String?
    /// Current total price for the deliverables (the latest counter). 0 for invites, which pay the bounty's rates.
    var amountCents: Int
    /// The opening amount.
    var originalAmountCents: Int
    /// The creator's rate-card ask at the time, for comparison.
    var askCents: Int?
    /// The market-suggested band shown inside the offer.
    var suggested: RateSuggestion?
    /// Brand plan take rate applied on top of the amount.
    var takeRate: Double
    /// amount_cents + round(amount_cents x take_rate): what the brand pays in total.
    var allInCents: Int
    var deliverables: Deliverables
    var rightsCard: RightsCard
    var turnaroundDays: Int
    /// The brand's opening note.
    var message: String
    /// Counter rounds used (0 to 3).
    var rounds: Int
    /// True once the brand wallet funded the direct bounty (on accept).
    var escrowFunded: Bool
    /// Oldest first. The first message is the opening offer.
    var thread: [OfferMessage]
    /// created_at + 7 days (reset on each counter).
    var expiresAt: Date
    var createdAt: Date
    var updatedAt: Date
    var acceptedAt: Date?
    /// Declined, expired, withdrawn or completed.
    var closedAt: Date?
}

// MARK: - Auction (auctions)

/// A creator's sealed-bid auction for a few weekly slots (Platinum and Elite). Second price: the k highest bids win and all pay the highest losing bid, or the reserve if no losing bid exists.
struct Auction: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var creatorId: String
    var title: String
    var description: String
    var status: AuctionStatus
    /// 1 to 5.
    var slots: Int
    /// Minimum bid and the clearing price floor.
    var reserveCents: Int
    var deliverables: Deliverables
    var rightsCard: RightsCard
    var opensAt: Date
    /// At least 72 hours after opens_at, at most 7 days.
    var closesAt: Date
    var art: ArtSeed
    /// All bids. Sealed: the API only shows a brand its own bid until the auction closes.
    var bids: [Bid]
    var bidsCount: Int
    /// The uniform price winners pay. Set when awarded.
    var clearingPriceCents: Int?
    var winningBidIds: [String]?
    /// The private direct bounties created for the winners.
    var resultingBountyIds: [String]?
    var awardedAt: Date?
    var createdAt: Date
    var updatedAt: Date
}

// MARK: - Spec (specs)

/// A pre-made, pre-scored video that brands can license off the shelf (Spec Market). Either made speculatively by a creator or released from a bounty after 30 unused days (the original brand keeps first refusal for 7 days).
struct Spec: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var creatorId: String
    var title: String
    var description: String
    var status: SpecStatus
    var source: SpecSource
    /// Generated spec cover.
    var art: ArtSeed
    var video: VideoMeta
    var formatId: FormatId?
    var hookText: String
    var hookType: HookType
    /// Best-fit app category.
    var category: AppCategory
    var flowBand: ScoreBand
    /// Must be 55 or more to list.
    var flowPoints: Int
    var hookBand: ScoreBand
    var hookPoints: Int
    var qaPass: Int
    var qaWarn: Int
    var qaFail: Int
    var tags: VideoTags
    /// Licence price to the creator (the brand pays the take rate on top).
    var priceCents: Int
    /// Paid-ad usage included. Default 90.
    var paidAdsDays: Int
    var exclusive: Bool
    var rightsCard: RightsCard
    var stats: SpecStats
    /// stats.licenses equals licenses.length.
    var licenses: [SpecLicense]
    /// Released-from-bounty specs only.
    var sourceSubmissionId: String?
    var sourceBountyId: String?
    /// The brand holding first refusal.
    var sourceBrandId: String?
    /// released_at + 7 days.
    var firstRefusalEndsAt: Date?
    var listedAt: Date?
    var createdAt: Date
    var updatedAt: Date
}

// MARK: - Value types used by Market entities

// MARK: - TickerTotals

/// Totals on the public payout ticker.
struct TickerTotals: Codable, Hashable, Sendable {
    var totalPaidCents: Int
    var paidTodayCents: Int
    var paid7dCents: Int
    var creatorsPaid: Int
    var payoutsCount: Int
    var postsCleared: Int
    /// Median 30-day cleared earnings of active creators (always shown beside top earners). Demo target about $62.
    var typicalCreator30dCents: Int
    /// p25 of the same distribution.
    var p25Creator30dCents: Int
    /// p75 of the same distribution.
    var p75Creator30dCents: Int
    /// p90: the "top 10%" figure that is always shown beside the median.
    var topDecileCreator30dCents: Int
    /// Creators with at least one post or cleared earning in 30 days (the distribution's population).
    var activeCreators30d: Int
    var updatedAt: Date
}

// MARK: - OfferMessage

/// One message in an offer negotiation thread.
struct OfferMessage: Codable, Hashable, Identifiable, Sendable {
    /// omsg_<n>.
    var id: String
    var authorRole: AuthorRole
    var authorUserId: String?
    var type: OfferMessageType
    var amountCents: Int?
    var rightsDays: Int?
    var body: String?
    var at: Date
    /// Scam Shield annotation on a risky message (e.g. an off-platform request).
    var warningCode: ScamReason?
}

// MARK: - SpecStats

/// Spec engagement.
struct SpecStats: Codable, Hashable, Sendable {
    var previews: Int
    var saves: Int
    var licenses: Int
}

// MARK: - TickerEvent

/// One event on the public payout ticker. Creator identity is public handle only or anonymised.
struct TickerEvent: Codable, Hashable, Identifiable, Sendable {
    /// tick_<n>.
    var id: String
    var kind: TickerKind
    var at: Date
    /// Ready to render: "@kai.frames was paid $84.20".
    var text: String
    var amountCents: Int?
    var creatorId: String?
    /// Public handle; absent when anonymous.
    var handle: String?
    var tier: Tier?
    var bountyId: String?
    var appName: String?
    /// prf_ id of a public proof page.
    var proofId: String?
}

// MARK: - Bid

/// A sealed bid in an auction. Bidders see only their own bid until the auction closes.
struct Bid: Codable, Hashable, Identifiable, Sendable {
    /// bid_<n>.
    var id: String
    var brandId: String
    var bidderMemberId: String
    /// The maximum the brand will pay per slot (second price: winners pay the highest losing bid).
    var amountCents: Int
    var status: BidStatus
    var placedAt: Date
    /// Held from the brand wallet while the auction is open.
    var escrowHoldCents: Int
    /// The uniform clearing price a winner actually paid.
    var paysCents: Int?
    var note: String?
}

// MARK: - SpecLicense

/// A brand's licence of a spec.
struct SpecLicense: Codable, Hashable, Sendable {
    var brandId: String
    var licensedAt: Date
    /// Creator price (the brand also pays the take rate on top).
    var priceCents: Int
    var paidAdsDays: Int
    var endsAt: Date?
    var ledgerTxnId: String?
}
