// GENERATED by scripts/gen-ios-models.mjs from packages/contract/schema/*.mjs. Do not edit by hand: change the schema, then run  node scripts/gen-ios-models.mjs
// Names, enum values and field types mirror packages/contract/DOMAIN.md sections 5 to 7. Decoded with .convertFromSnakeCase.

import Foundation

// Entities (one per fixture file) and their nested value types: Ads.

// MARK: - Ad (ads)

/// Winner promotion: an organic post run as a Spark / partnership ad. Commission is 10% of ad-attributed revenue for 60 days; the platform fee is 1% of spend.
struct Ad: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var postId: String
    var brandId: String
    var appId: String
    var bountyId: String
    var creatorId: String
    var platform: AdPlatform
    var kind: AdKind
    var status: AdStatus
    /// Fictional ad-platform id.
    var externalAdId: String?
    /// Fictional Spark authorization code.
    var sparkCode: String?
    /// One of 7, 30, 60, 365.
    var codeDurationDays: Int?
    var codeExpiresAt: Date?
    var permissionRequestedAt: Date
    var permissionGrantedAt: Date?
    var startedAt: Date?
    var endedAt: Date?
    var dailyBudgetCents: Int
    /// Lifetime spend. Equals the sum of daily.spend_cents.
    var spendCents: Int
    var impressions: Int
    var clicks: Int
    var installs: Int
    var trials: Int
    var paid: Int
    /// Ad-attributed revenue (lifetime).
    var revenueCents: Int
    var commissionRate: Double
    /// started_at + 60 days.
    var commissionWindowEndsAt: Date?
    /// Commission accrued inside the window: commission_rate x revenue inside the window.
    var commissionCents: Int
    /// 1% of spend_cents.
    var platformFeeCents: Int
    var daily: [AdDaily]
    var fatigue: FatigueInfo?
    /// Ads stop automatically at this time.
    var rightsEndsAt: Date?
}

// MARK: - Value types used by Ads entities

// MARK: - AdDaily

/// One day of a promoted ad.
struct AdDaily: Codable, Hashable, Sendable {
    var date: String
    var spendCents: Int
    var impressions: Int
    var clicks: Int
    var installs: Int
    var trials: Int
    var paid: Int
    var revenueCents: Int
}

// MARK: - FatigueInfo

/// Fatigue snapshot on an ad.
struct FatigueInfo: Codable, Hashable, Sendable {
    var peakTrialRate: Double
    var currentTrialRate: Double
    /// 1 - current / peak.
    var dropRatio: Double
    var flaggedAt: Date?
}
