// GENERATED by scripts/gen-ios-models.mjs from packages/contract/schema/*.mjs. Do not edit by hand: change the schema, then run  node scripts/gen-ios-models.mjs
// Names, enum values and field types mirror packages/contract/DOMAIN.md sections 5 to 7. Decoded with .convertFromSnakeCase.

import Foundation

// Entities (one per fixture file) and their nested value types: Posts.

// MARK: - Post (posts)

/// A posted video on a creator's own account. Opens the 72-hour view window. Money legs settle on the ledger.
struct Post: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var submissionId: String
    var creatorId: String
    var brandId: String
    var appId: String
    var bountyId: String
    var socialAccountId: String
    var platform: Platform
    /// Fictional platform id.
    var platformPostId: String
    /// Fictional post URL on the platform domain (text only).
    var url: String
    /// Includes the auto-disclosure (#ad + brand wording).
    var caption: String
    var hashtags: [String]
    var thumb: ArtSeed
    var durationMs: Int
    var postedAt: Date
    /// posted_at + 72 hours.
    var windowEndsAt: Date
    var status: PostStatus
    /// Required when status = held.
    var holdReason: HoldReason?
    var clearedAt: Date?
    var paidAt: Date?
    var removedAt: Date?
    var trackingLinkId: String
    var promoCode: String?
    /// Latest verified views (lifetime, as of now). Equals the sum of post_metrics_daily.views; never less than window_views and never less than the last view snapshot.
    var views: Int
    /// Verified views counted for CPM pay: views at window_ends_at (or so far, while live). Never more than views.
    var windowViews: Int
    /// Views reversed after proven fraud (0 normally).
    var viewsInvalid: Int
    var likes: Int
    var comments: Int
    var shares: Int
    var saves: Int
    var retention: Retention
    /// Lifetime funnel. Equals the sum of post_metrics_daily and tracked conversions.
    var funnel: FunnelCounts
    var earnings: EarningsBreakdown
    var fraud: FraudAssessment
    /// Band at submission.
    var flowBand: ScoreBand
    var adId: String?
    /// Flagged as a winner (top decile on trial rate for its bounty); eligible for Winner promotion.
    var isWinner: Bool
    /// Plain-English "why it won" reasons written after settlement, e.g. "Hook landed at 1.4 s", "App on screen by 0:02".
    var whyItWon: [String]?
    var tags: VideoTags
}

// MARK: - ViewSnapshot (view_snapshots)

/// A View Ledger snapshot: a timestamped, source-labelled view count of a post. 13 snapshots across the 72h window (every 6h, t = 0..72h, fewer while the window is still open), then one every 7 days until now. The snapshot at window_ends_at has views_verified equal to the post's window_views.
struct ViewSnapshot: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var postId: String
    var takenAt: Date
    /// What the platform reported.
    var viewsReported: Int
    /// After fraud filtering. Non-decreasing per post.
    var viewsVerified: Int
    /// Cumulative views excluded at this snapshot: views_reported - views_verified.
    var viewsInvalid: Int
    /// Why views were excluded, in plain words. When present, the views add up to views_invalid.
    var exclusions: [ViewExclusion]?
    /// views_verified minus the previous snapshot.
    var deltaVerified: Int
    var source: SnapshotSource
    /// Traffic-source mix summing to 1.
    var sources: [String: Double]?
    /// Audience country mix summing to 1.
    var geo: [String: Double]?
    var flags: [SnapshotFlag]
    var fraudScore: Int
    var note: String?
}

// MARK: - PostMetricsDaily (post_metrics_daily)

/// Per-post daily metrics (UTC day). Sums equal the post's lifetime numbers. Key: (post_id, date).
struct PostMetricsDaily: Codable, Hashable, Identifiable, Sendable {
    var postId: String
    var date: String
    var views: Int
    var likes: Int
    var comments: Int
    var shares: Int
    var saves: Int
    /// Tracked visits (link clicks + code lookups).
    var clicks: Int
    /// Tracked (link + code) installs.
    var installs: Int
    var trials: Int
    var paid: Int
    /// MMP + survey + modelled.
    var estInstalls: Int
    var estTrials: Int
    var estPaid: Int

    /// Composite identity (post_id + date).
    var id: String {
        return [postId, date].joined(separator: "|")
    }
}

// MARK: - PostMetricsHourly (post_metrics_hourly)

/// Per-post hourly deltas for the most recent days (UTC dates from 2026-09-30 to now), the training-data grain. Sums over a UTC day equal the daily row. Key: (post_id, ts).
struct PostMetricsHourly: Codable, Hashable, Identifiable, Sendable {
    var postId: String
    /// Start of the hour.
    var ts: Date
    /// Views during this hour (delta).
    var views: Int
    var likes: Int
    var comments: Int
    var shares: Int
    var fraudScore: Int

    /// Composite identity (post_id + ts).
    var id: String {
        return [postId, String(Int(ts.timeIntervalSince1970))].joined(separator: "|")
    }
}

// MARK: - AppMetricsDaily (app_metrics_daily)

/// Per-app daily rollup of post metrics and spend (derived; equals the sum of its posts' daily rows). Key: (app_id, date).
struct AppMetricsDaily: Codable, Hashable, Identifiable, Sendable {
    var appId: String
    var date: String
    var views: Int
    var clicks: Int
    var installs: Int
    var trials: Int
    var paid: Int
    var estInstalls: Int
    var estTrials: Int
    var estPaid: Int
    /// First-payment revenue of tracked paid conversions that day.
    var revenueCents: Int
    /// Posts in their window that day.
    var postsLive: Int
    var newPosts: Int
    var newSubmissions: Int
    var approvals: Int
    /// Creator earnings settled out of escrow that day.
    var creatorPayCents: Int
    /// Platform fees settled that day.
    var feeCents: Int

    /// Composite identity (app_id + date).
    var id: String {
        return [appId, date].joined(separator: "|")
    }
}

// MARK: - Value types used by Posts entities

// MARK: - FraudSignalHit

/// A fraud signal that fired.
struct FraudSignalHit: Codable, Hashable, Sendable {
    var signal: FraudSignal
    /// points = max_points x severity, rounded.
    var points: Int
    var severity: Double
    var detail: String
}

// MARK: - FraudAssessment

/// Fraud score composition for a post.
struct FraudAssessment: Codable, Hashable, Sendable {
    /// min(100, sum of signal points).
    var score: Int
    var band: FraudBand
    var signals: [FraudSignalHit]
    var assessedAt: Date
}

// MARK: - EarningsBreakdown

/// Earnings so far on a post (accrued for live posts, settled afterwards).
struct EarningsBreakdown: Codable, Hashable, Sendable {
    var cpmCents: Int
    var cpaCents: Int
    var commissionCents: Int
    var flatCents: Int
    var totalCents: Int
    /// True when the per-video cap limited pay.
    var capped: Bool
    var capRemainingCents: Int
}

// MARK: - Retention

/// Retention curve of a post.
struct Retention: Codable, Hashable, Sendable {
    /// 10 points: share of viewers still watching at 0%, 10% ... 90% of the video.
    var curve: [Double]
    var avgWatchRatio: Double
    var biggestDropAtS: Double?
}

// MARK: - ViewExclusion

/// Views excluded from the verified count, with the cause and a plain-language detail (View Ledger).
struct ViewExclusion: Codable, Hashable, Sendable {
    var cause: ExclusionCause
    var views: Int
    /// e.g. "62% of views in two hours came from an unknown external source".
    var detail: String
}
