// GENERATED by scripts/gen-ios-models.mjs from packages/contract/schema/*.mjs. Do not edit by hand: change the schema, then run  node scripts/gen-ios-models.mjs
// Names, enum values and field types mirror packages/contract/DOMAIN.md sections 5 to 7. Decoded with .convertFromSnakeCase.

import Foundation

// Entities (one per fixture file) and their nested value types: Money.

// MARK: - LedgerEntry (ledger)

/// One leg of a double-entry transaction. Rows with the same txn_id sum to exactly 0 (signed amounts: credit +, debit -). Append-only: only status, cleared_at, paid_at and payout_id change.
struct LedgerEntry: Codable, Hashable, Identifiable, Sendable {
    var id: String
    /// "txn_<n>". All legs of one transaction share it; the legs net to 0.
    var txnId: String
    var entryType: LedgerType
    /// "<kind>:<id>": wallet:br_x | escrow:bnty_x | creator:cr_x | platform:fees|subscriptions|matching|promo|processing | external:card|bank.
    var account: String
    /// Signed. Credit to the account is positive.
    var amountCents: Int
    /// Meaningful on creator-account earning rows; everything else is cleared (or paid once withdrawn).
    var status: LedgerStatus
    var postedAt: Date
    var clearedAt: Date?
    var paidAt: Date?
    var brandId: String?
    var bountyId: String?
    var postId: String?
    var submissionId: String?
    var creatorId: String?
    var conversionId: String?
    var adId: String?
    var payoutId: String?
    var invoiceId: String?
    /// Set on clawback rows.
    var reversesTxnId: String?
    /// Plain-English line shown in the wallet ledger.
    var memo: String
}

// MARK: - Payout (payouts)

/// Money leaving flowd to a creator's bank. Weekly (Fri 18:00 UTC, free) or instant (1.5% fee, min $0.50, max $15).
struct Payout: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var creatorId: String
    var kind: PayoutKind
    var status: PayoutStatus
    /// Sum of the cleared earning rows included.
    var grossCents: Int
    /// Instant fee; 0 for weekly and for free instant perks.
    var feeCents: Int
    /// gross_cents - fee_cents.
    var netCents: Int
    /// Weekly run id "run_YYYY-MM-DD" (the Friday). Matches payout_runs.
    var runId: String?
    var requestedAt: Date
    /// For weekly: the Friday 18:00 UTC run. For instant: requested_at.
    var scheduledFor: Date
    var initiatedAt: Date?
    var paidAt: Date?
    var failedReason: String?
    var holdReason: HoldReason?
    /// e.g. "Bank account ••4821".
    var methodLabel: String
    /// Mock "tr_<n>".
    var stripeTransferId: String?
    /// The payout transaction (creator -gross, bank +net, fees +fee).
    var ledgerTxnId: String?
    /// Earning rows included.
    var itemCount: Int
    var tierAtPayout: Tier
    /// A tier perk made this instant payout free.
    var freeInstant: Bool
    /// "prf_<8 chars>". Public proof page joinflowd.io/p/<proof_id>; ext proofs.json has the row.
    var proofId: String
}

// MARK: - Invoice (invoices)

/// A brand invoice (funding, subscription, ad fee, renewals) with finance-pack fields.
struct Invoice: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var brandId: String
    /// "FD-2026-0042".
    var number: String
    var kind: InvoiceKind
    var status: InvoiceStatus
    var bountyId: String?
    var lineItems: [LineItem]
    var subtotalCents: Int
    var processingCents: Int
    var taxCents: Int
    /// subtotal + processing + tax. For funding invoices this is the card charge.
    var totalCents: Int
    var poNumber: String?
    var costCenter: String?
    var vatId: String?
    var reverseCharge: Bool
    var issuedAt: Date
    var dueAt: Date
    var paidAt: Date?
    var ledgerTxnId: String?
    /// Mock file name, e.g. "FD-2026-0042.pdf".
    var pdfRef: String
}

// MARK: - MoneyClockRow (money_clock)

/// The Money Clock: one earning row with its state, a dated ETA and a named reason. A projection of posts, conversions and the ledger. Never a bare "pending".
struct MoneyClockRow: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var creatorId: String
    var bountyId: String
    var appId: String
    var postId: String?
    var conversionId: String?
    var source: MoneyClockSource
    var state: MoneyClockState
    /// Current amount. For accruing rows a live estimate.
    var amountCents: Int
    /// True while accruing.
    var estimated: Bool
    /// When the earning started accruing.
    var earnedAt: Date
    /// When it moves to the next state. Required for accruing, pending and cleared rows.
    var etaAt: Date?
    var reason: MoneyClockReason
    /// Plain English with the date, e.g. "Clears Sat 2:00 PM UTC after the view check."
    var reasonText: String
    /// e.g. "Lumi: Glow-up reveal".
    var label: String
    /// The creator earning row; absent while accruing.
    var ledgerId: String?
    var payoutId: String?
    var clearedAt: Date?
    var paidAt: Date?
}

// MARK: - PayoutRun (payout_runs)

/// A weekly payout run: Fridays 18:00 UTC. A projection of the payouts it created, with named holds. id = run_<YYYY-MM-DD> of the Friday.
struct PayoutRun: Codable, Hashable, Identifiable, Sendable {
    /// run_<YYYY-MM-DD>.
    var id: String
    var runDate: String
    /// Friday 18:00:00Z.
    var scheduledFor: Date
    var status: RunStatus
    /// Equals the count of payouts with this run_id.
    var payoutsCount: Int
    var totalGrossCents: Int
    /// Always 0 for weekly runs.
    var totalFeeCents: Int
    var totalNetCents: Int
    var paidCount: Int
    var failedCount: Int
    var heldCount: Int
    var heldCents: Int
    var holds: [HoldSummary]
    var initiatedAt: Date?
    var completedAt: Date?
}

// MARK: - Value types used by Money entities

// MARK: - LineItem

/// An invoice line.
struct LineItem: Codable, Hashable, Sendable {
    var description: String
    var quantity: Int
    var unitCents: Int
    var amountCents: Int
    var bountyId: String?
    var adId: String?
}

// MARK: - HoldSummary

/// Holds in a payout run, grouped by named reason.
struct HoldSummary: Codable, Hashable, Sendable {
    var reason: HoldReason
    var count: Int
    var cents: Int
}
