// GENERATED by scripts/gen-ios-models.mjs from packages/contract/schema/*.mjs. Do not edit by hand: change the schema, then run  node scripts/gen-ios-models.mjs
// Names, enum values and field types mirror packages/contract/DOMAIN.md sections 5 to 7. Decoded with .convertFromSnakeCase.

import Foundation

// Entities (one per fixture file) and their nested value types: Admin.

// MARK: - AdminMetrics (admin_metrics)

/// The admin control tower: 90-day targets vs actuals, market health, queue counts, next payout run and the money summary. Object-shaped file.
struct AdminMetrics: Codable, Hashable, Sendable {
    var asOf: Date
    /// The six day-90 targets (CONSTANTS.launch_targets) with actuals and trend series.
    var targets: [MetricTarget]
    var marketHealth: MarketHealth
    var queues: QueueCounts
    var nextPayoutRun: NextPayoutRun
    var summary: AdminSummary
    /// The 11 Promise proof metrics (public on /promise and /trust).
    var promiseMetrics: [PromiseMetric]
    /// Plain-English alerts, e.g. "3 submissions at Brightloop passed 72 hours".
    var alerts: [String]
}

// MARK: - Value types used by Admin entities

// MARK: - MetricTarget

/// A day-90 target vs actual.
struct MetricTarget: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var label: String
    var target: Double
    var targetMax: Double?
    /// "lt" | "gt" | "between".
    var op: String
    var unit: String
    var actual: Double
    var status: MetricStatus
    /// Daily or weekly series ending at "now".
    var series: [ChartPoint]
}

// MARK: - PromiseMetric

/// The public proof metric of one of the 11 flowd Promise commitments (shown on /promise and /trust, computed from the ledger).
struct PromiseMetric: Codable, Hashable, Sendable {
    /// 1 to 11.
    var number: Int
    /// e.g. "cleared_on_eta".
    var key: String
    var label: String
    var value: Double
    /// "ratio", "hours", "count" or "cents".
    var unit: String
    /// Preformatted, e.g. "97.4% cleared on or before the ETA".
    var display: String
    var target: Double?
    var note: String
}

// MARK: - MarketHealth

/// Market health metrics on the admin control tower.
struct MarketHealth: Codable, Hashable, Sendable {
    /// Share of bounties that filled within 48 hours.
    var fillRate48h: Double
    var medianFillHours: Double
    var medianDecisionHours: Double
    var decidedInSlaRatio: Double
    var clearedOnEtaRatio: Double
    var disputesResolved48hRatio: Double
    /// Always 1.0: no bounty goes live unfunded.
    var fundedLiveRatio: Double
    var firstDollarMedianHours: Double
    var activeCreatorsPerLiveBounty: Double
}

// MARK: - QueueCounts

/// Open items per admin queue.
struct QueueCounts: Codable, Hashable, Sendable {
    var fraudOpen: Int
    var disputesOpen: Int
    var verificationOpen: Int
    var safetyNew: Int
    var slaStale: Int
    var slaBreached: Int
    var payoutsHeld: Int
}

// MARK: - NextPayoutRun

/// Preview of the next Friday payout run.
struct NextPayoutRun: Codable, Hashable, Sendable {
    /// run_YYYY-MM-DD.
    var runId: String
    var scheduledFor: Date
    var creators: Int
    var totalCents: Int
    var holds: Int
    var heldCents: Int
}

// MARK: - AdminSummary

/// Money summary on the control tower.
struct AdminSummary: Codable, Hashable, Sendable {
    /// Creator pay + fees settled in 30 days.
    var gmv30dCents: Int
    var fees30dCents: Int
    var paidTotalCents: Int
    var activeCreators30d: Int
    var liveBounties: Int
    var brandsActive30d: Int
}
