// GENERATED by scripts/gen-ios-models.mjs from packages/contract/schema/*.mjs. Do not edit by hand: change the schema, then run  node scripts/gen-ios-models.mjs
// Names, enum values and field types mirror packages/contract/DOMAIN.md sections 5 to 7. Decoded with .convertFromSnakeCase.

import Foundation

// Entities (one per fixture file) and their nested value types: Trust.

// MARK: - BrandScorecard (brand_scorecards)

/// Brand Scorecard: pay speed, decision time, approval fairness and the share of approved work actually run. Shown to creators before they apply.
struct BrandScorecard: Codable, Hashable, Identifiable, Sendable {
    /// bsc_<brand slug>.
    var id: String
    var brandId: String
    /// 90.
    var windowDays: Int
    var asOf: Date
    /// Decisions in the window.
    var decisionsN: Int
    var approvedN: Int
    var decisionHoursMedian: Double
    var decisionHoursP90: Double
    var slaBreaches: Int
    var approvalRate: Double
    var rejectionRate: Double
    var appealsN: Int
    var appealsOverturned: Int
    /// Share of approved work posted or used within 30 days.
    var runRate: Double
    /// Share of commissions, direct offers and top-ups funded without delay.
    var paysOnTimeRatio: Double
    /// Median hours from payment due to funded (commissions, direct offers).
    var paySpeedHoursMedian: Double
    var replyHoursMedian: Double
    /// Every live bounty was fully escrowed.
    var fundedAlways: Bool
    /// 0..100 (FORMULAS: brand reliability).
    var reliabilityScore: Int
    var band: BrandBand
    var badges: [BrandBadge]
    /// Score change over 30 days.
    var trend30d: Double
}

// MARK: - CreatorReputation (creator_reputation)

/// Fair creator reputation: finished work only, recency-weighted, shown with reasons. Never penalises multi-brand work or pending samples.
struct CreatorReputation: Codable, Hashable, Identifiable, Sendable {
    /// rep_<creator slug>.
    var id: String
    var creatorId: String
    var asOf: Date
    /// Fewer than 5 finished decisions: "Building history". Brands see a range, not a verdict.
    var provisional: Bool
    var reliabilityScore: Int
    /// Recency-weighted (half-life 45 days).
    var approvalRateFinished: Double
    var approvalRateRaw: Double
    var onTimeRatio: Double
    var postThroughRatio: Double
    var complianceRatio: Double
    var cleanRecordRatio: Double
    var finishedN: Int
    var fraudFlags90d: Int
    var clawbacks90d: Int
    var disputesLost90d: Int
    var academyBonusPoints: Double
    var components: [ReliabilityComponent]
    /// Plain-English reasons shown on the creator's own profile.
    var reasons: [String]
    var tierProgress: TierProgress
}

// MARK: - Dispute (disputes)

/// A dispute or appeal. One-tap from a post or a rejection; a human replies within 24 hours and resolves within 5 business days. Undisputed money is never blocked by a dispute on other items.
struct Dispute: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var kind: DisputeKind
    var status: DisputeStatus
    var openedBy: PartyKind
    var creatorId: String?
    /// The brand on the other side of the dispute.
    var brandId: String
    var bountyId: String?
    /// Required for rejection_appeal.
    var submissionId: String?
    var postId: String?
    var payoutId: String?
    /// rejection_appeal: the code being appealed.
    var rejectionReasonCode: ReasonCode?
    /// Snapshot range the dispute covers (view_count and flagged_botting).
    var rangeFrom: Date?
    var rangeTo: Date?
    var reason: String
    var note: String
    /// Ledger and snapshot evidence attached automatically.
    var evidence: [Evidence]
    var amountInDisputeCents: Int
    /// Timeline, oldest first.
    var events: [DisputeEvent]
    var openedAt: Date
    /// opened_at + 24 hours.
    var replyDueAt: Date
    var firstReplyAt: Date?
    /// opened_at + 5 days (appeals: + 72 hours).
    var resolutionDueAt: Date
    var resolvedAt: Date?
    var outcome: DisputeOutcome?
    var outcomeText: String?
    /// Amount released or reversed on a (partly) upheld outcome.
    var adjustmentCents: Int?
    var assignedAdminUserId: String?
    var updatedAt: Date
}

// MARK: - ScamReport (scam_reports)

/// A Scam Shield report from a creator or brand about a brand, bounty, creator, message or offer. Triage SLA 24 hours.
struct ScamReport: Codable, Hashable, Identifiable, Sendable {
    var id: String
    /// "SR-2026-0042".
    var caseId: String
    var reporterKind: PartyKind
    var reporterCreatorId: String?
    var reporterBrandId: String?
    var targetKind: ReportTargetKind
    /// The id of the target (brand, bounty, creator, message or offer).
    var targetId: String
    var reason: ScamReason
    var description: String
    /// Message ids or screenshot names (mock).
    var evidenceRefs: [String]
    var status: ReportStatus
    var createdAt: Date
    /// created_at + 24 hours.
    var slaDueAt: Date
    var triagedAt: Date?
    var resolvedAt: Date?
    /// e.g. "Brand suspended, bounty removed".
    var actionTaken: String?
    var assignedAdminUserId: String?
}

// MARK: - FraudFlag (fraud_flags)

/// A post in the admin fraud queue (fraud score 40 or above): evidence, money at stake and the decision. Delivered legitimate views are always paid; only proven fraud is clawed back.
struct FraudFlag: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var postId: String
    var creatorId: String
    var brandId: String
    var bountyId: String
    var status: FraudFlagStatus
    /// Equals the post's fraud.score at flag time.
    var score: Int
    var band: FraudBand
    var signals: [FraudSignalHit]
    var curveShape: CurveShape
    var curve: HourlyEnvelope
    var moneyAtStakeCents: Int
    var holdPlaced: Bool
    var duplicateOfPostId: String?
    var audienceUsRatio: Double
    var accountAgeDays: Int
    var openedAt: Date
    /// opened_at + 24 hours.
    var slaDueAt: Date
    var reviewedAt: Date?
    var reviewedByUserId: String?
    var decisionNote: String?
    /// Views reversed when confirmed.
    var invalidViews: Int?
}

// MARK: - Verification (verifications)

/// An item in the admin verification queue: creator identity / age, brand business, tax, or payout method. Just-in-time for creators (at first approval).
struct Verification: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var subjectKind: PartyKind
    var creatorId: String?
    var brandId: String?
    var kind: VerificationKind
    var status: VerificationStatus
    /// e.g. "Stripe Identity (mock)".
    var provider: String
    var documents: [DocRef]
    var submittedAt: Date
    /// submitted_at + 24 hours.
    var slaDueAt: Date
    var decidedAt: Date?
    var decidedByUserId: String?
    /// Required when needs_info or rejected.
    var reason: VerificationReason?
    var note: String?
    /// True while the item holds money (creators) or the Verified badge (brands).
    var blocksPayout: Bool
}

// MARK: - TaxProfile (tax_profiles)

/// A creator's Tax Desk profile: just-in-time W-9 or W-8BEN, year-to-date totals, 1099-NEC threshold progress and the set-aside estimate. Not tax advice.
struct TaxProfile: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var creatorId: String
    var status: TaxStatus
    var form: TaxForm?
    var legalName: String?
    var entityType: TaxEntityType?
    /// Only the last four digits are ever stored.
    var tinLast4: String?
    var address: Address?
    var country: Country
    /// 2026.
    var taxYear: Int
    /// Cleared and paid earnings in the tax year (excludes carry-over).
    var ytdClearedCents: Int
    var ytdPaidCents: Int
    /// 200000 ($2,000 for 2026 payments).
    var thresholdCents: Int
    /// ytd_paid_cents / threshold_cents, capped at 1.
    var thresholdProgress: Double
    /// US creators at or above the threshold.
    var form1099Required: Bool
    /// The creator's set-aside percentage (default 0.25).
    var setAsideRate: Double
    /// round(ytd_cleared_cents x set_aside_rate).
    var setAsideCents: Int
    /// First approval time.
    var requestedAt: Date?
    var submittedAt: Date?
    var verifiedAt: Date?
    /// W-8BEN: three years after signing.
    var expiresAt: Date?
    var updatedAt: Date
}

// MARK: - TaxDoc (tax_docs)

/// A tax document: a collected W-9 or W-8BEN, or an issued 1099-NEC.
struct TaxDoc: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var creatorId: String
    var kind: TaxDocKind
    var status: TaxDocStatus
    var taxYear: Int
    /// 1099-NEC box 1.
    var amountCents: Int?
    /// Mock file name, e.g. "W9-cr_maya.pdf".
    var fileRef: String
    var createdAt: Date
    var issuedAt: Date?
}

// MARK: - ComplianceAudit (compliance_checks)

/// The post-level compliance audit (disclosure audio + on-screen, caption, platform label, music, banned claims, AI label, tracking link). A failure blocks settlement until fixed or waived with a logged reason.
struct ComplianceAudit: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var postId: String
    var submissionId: String
    var bountyId: String
    var brandId: String
    var creatorId: String
    /// One item per ComplianceCheckType (8).
    var checks: [ComplianceCheckItem]
    /// fail if any check failed, else warn if any warned, else pass.
    var overall: ComplianceResult
    /// True when overall is fail and not waived or fixed.
    var blocksSettlement: Bool
    var checkedAt: Date
    var waivedByMemberId: String?
    var waiveReason: String?
    var fixedAt: Date?
}

// MARK: - Value types used by Trust entities

// MARK: - ReliabilityComponent

/// One explained part of a reliability score.
struct ReliabilityComponent: Codable, Hashable, Sendable {
    var key: String
    var label: String
    var value: Double
    var weight: Double
    var points: Double
    var reason: String
}

// MARK: - TierCriterion

/// One progress line toward the next tier.
struct TierCriterion: Codable, Hashable, Sendable {
    /// lifetime_cleared | approved | approval_rate | reliability | review.
    var key: String
    var label: String
    var have: Double
    var need: Double
    var met: Bool
}

// MARK: - TierProgress

/// Progress toward the next tier (derived; embedded in creator_reputation).
struct TierProgress: Codable, Hashable, Sendable {
    var current: Tier
    var next: Tier?
    var criteria: [TierCriterion]
    /// The bottleneck: the lowest met/need ratio among numeric criteria.
    var progress: Double
}

// MARK: - DisputeEvent

/// One entry in a dispute timeline.
struct DisputeEvent: Codable, Hashable, Sendable {
    var at: Date
    var actor: ActorKind
    var action: DisputeAction
    var text: String
    var userId: String?
}

// MARK: - HourlyEnvelope

/// Hourly view curve with the expected organic envelope (fraud case evidence). 72 values each, hour 0 = post time.
struct HourlyEnvelope: Codable, Hashable, Sendable {
    /// Verified views per hour.
    var views: [Int]
    var expectedLow: [Int]
    var expectedHigh: [Int]
}

// MARK: - DocRef

/// A mock document attached to a verification.
struct DocRef: Codable, Hashable, Sendable {
    var label: String
    var fileName: String
    /// Generated placeholder, never a real document.
    var art: ArtSeed
}

// MARK: - ComplianceCheckItem

/// One check inside a post-level compliance audit.
struct ComplianceCheckItem: Codable, Hashable, Sendable {
    var type: ComplianceCheckType
    var result: ComplianceResult
    var message: String
    var evidence: Evidence?
    var blocksSettlement: Bool
}
