// GENERATED by scripts/gen-ios-models.mjs from packages/contract/schema/*.mjs. Do not edit by hand: change the schema, then run  node scripts/gen-ios-models.mjs
// Names, enum values and field types mirror packages/contract/DOMAIN.md sections 5 to 7. Decoded with .convertFromSnakeCase.

import Foundation

// Entities (one per fixture file) and their nested value types: Platform.

// MARK: - Notification (notifications)

/// A notification for a creator, brand member or admin. Cash events are delivered immediately outside quiet hours; everything else is batched inside them. Never a bare vanity ping.
struct AppNotification: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var recipientUserId: String
    /// creator, brand or admin.
    var audience: ActorKind
    var kind: NotificationKind
    var priority: NotificationPriority
    var title: String
    var body: String
    /// Cash events: "You just earned +$24".
    var amountCents: Int?
    /// iOS "flowd://payout/pay_x" for creators; web route for brands and admins.
    var deepLink: String
    /// Entity kind, e.g. "post".
    var refKind: String?
    var refId: String?
    /// Held for quiet hours and delivered later.
    var batched: Bool
    var createdAt: Date
    var deliveredAt: Date?
    var readAt: Date?
}

// MARK: - Integration (integrations)

/// A brand integration (RevenueCat, MMPs, ad accounts, Slack, Zapier, App Store Connect). Adapter + realistic mock in this build.
struct Integration: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var brandId: String
    var appId: String?
    var kind: IntegrationKind
    var status: IntegrationStatus
    var label: String
    var scopes: [String]
    /// Non-secret settings (e.g. Slack channel "#growth-ugc").
    var config: [String: String]
    /// RevenueCat ingest URL on api.joinflowd.io.
    var webhookUrl: String?
    var secretLast4: String?
    /// Attribution coverage: share of installs and trials this integration can tie to a creator.
    var coverageRatio: Double?
    var events24h: Int
    var healthNote: String
    var connectedAt: Date?
    var lastSyncAt: Date?
    var lastEventAt: Date?
}

// MARK: - ApiKey (api_keys)

/// A public API key (read, write, financial scopes; writes are drafts by default). Only the prefix and last four characters are ever stored.
struct ApiKey: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var brandId: String
    var name: String
    var mode: KeyMode
    var scopes: [ApiScope]
    /// "fd_live_" or "fd_test_".
    var prefix: String
    var last4: String
    var createdByMemberId: String
    var rateLimitPerMinute: Int
    var requests30d: Int
    var createdAt: Date
    var lastUsedAt: Date?
    var expiresAt: Date?
    var revokedAt: Date?
}

// MARK: - Webhook (webhooks)

/// An outbound webhook endpoint with its subscribed events and recent deliveries. Deliveries are signed.
struct Webhook: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var brandId: String
    /// On a .example host.
    var url: String
    var events: [WebhookEventType]
    var status: WebhookStatus
    var secretLast4: String
    /// Consecutive failures.
    var failureCount: Int
    /// The last 20, newest first.
    var deliveries: [WebhookDelivery]
    var createdAt: Date
    var lastSuccessAt: Date?
}

// MARK: - ActivityEntry (activity_log)

/// The team activity log of a brand workspace (filterable, exportable).
struct ActivityEntry: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var brandId: String
    /// Absent for system actions.
    var actorMemberId: String?
    var action: ActivityAction
    /// Plain English: "Jordan Ellis approved a video from @kai.frames".
    var summary: String
    var targetKind: String?
    var targetId: String?
    var metadata: [String: String]
    var at: Date
}

// MARK: - AutoApproveRule (auto_approve_rules)

/// A guarded auto-approve rule: conditions, scope (organic only), guardrails, a mandatory dry run on the last 50 submissions, a 10% human spot-check and a kill switch.
struct AutoApproveRule: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var brandId: String
    var name: String
    var status: RuleStatus
    var conditions: AutoApproveConditions
    var scope: AutoApproveScope
    var guardrails: RuleGuardrails
    var timeoutPolicy: TimeoutPolicy
    /// Required before status can be active.
    var dryRun: DryRun?
    var stats: RuleStats
    /// Oldest first.
    var audit: [RuleAuditEntry]
    var createdByMemberId: String
    var createdAt: Date
    var updatedAt: Date
    var enabledAt: Date?
    var killedAt: Date?
    var killReason: String?
}

// MARK: - TestPlan (test_plans)

/// A hook x body x CTA test plan: cells assigned to bounties or offers, measured on settled posts. Small samples carry a caution.
struct TestPlan: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var brandId: String
    var appId: String
    var name: String
    var status: TestPlanStatus
    var spendTier: SpendTier
    var budgetCents: Int
    var hooks: [TestAxisItem]
    var bodies: [TestAxisItem]
    var ctas: [CtaType]
    /// hooks x bodies x ctas selected cells.
    var cells: [TestCell]
    var bountyIds: [String]
    var offerIds: [String]
    var winnerCellId: String?
    /// Winner trial rate / median trial rate - 1.
    var liftRatio: Double?
    var confidence: Double?
    /// e.g. "Small sample: 3 videos per hook. Treat as directional."
    var caution: String
    var createdAt: Date
    var updatedAt: Date
}

// MARK: - FatigueAlert (fatigue_alerts)

/// A fatigue alert: a winner whose trial-start rate (or click-through, or install yield) fell 30% from its peak.
struct FatigueAlert: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var brandId: String
    var appId: String
    var bountyId: String
    var postId: String
    var adId: String?
    var creatorId: String
    var metric: FatigueMetric
    var status: FatigueStatus
    var peakValue: Double
    var currentValue: Double
    /// 1 - current / peak; 0.30 or more triggers the alert.
    var dropRatio: Double
    var peakOn: String
    /// Daily metric values around the decay.
    var series: [ChartPoint]
    var message: String
    var detectedAt: Date
    var acknowledgedAt: Date?
    var refreshBountyId: String?
}

// MARK: - FloSuggestion (flo_suggestions)

/// A Flo copilot output (history of scripts, hook rewrites, TL;DRs, captions, score fixes, rate advice, next actions, bounty drafts). Mock engine behind the AIProvider interface.
struct FloSuggestion: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var surface: FloSurface
    var kind: FloKind
    var creatorId: String?
    var brandId: String?
    /// e.g. "bounty", "format", "submission".
    var contextKind: String?
    var contextId: String?
    var prompt: String
    var title: String
    /// E.g. three script options.
    var outputs: [String]
    var actions: [FloAction]
    /// "flo-mock-1".
    var model: String
    var latencyMs: Int
    var helpful: Bool?
    var createdAt: Date
}

// MARK: - MlModel (ml_models)

/// One of the eight ML systems with its stage (heuristic, shadow, learned), monitoring metrics and calibration. The admin ML page reads this.
struct MlModel: Codable, Hashable, Identifiable, Sendable {
    /// mdl_<kind>.
    var id: String
    var kind: ModelKind
    var name: String
    var version: String
    var stage: ModelStage
    var description: String
    /// Settled posts available to learn from (0 for heuristics).
    var trainedOnN: Int
    var metrics: [ModelMetric]
    /// Predicted band vs realised results (creative scorer); empty for the others.
    var calibration: [CalibrationBin]
    var driftScore: Double
    var jobs: ModelJobStats
    /// Video understanding: share of settled posts with format, hook and CTA tags.
    var tagCoverage: [String: Double]
    /// 1000: settled posts before comparing learned vs checklist.
    var learnedReadyAtPosts: Int
    var lastRunAt: Date
    var updatedAt: Date
}

// MARK: - ChatThread (threads)

/// An in-app thread tied to an offer, submission, bounty or support. In-app only: flowd never moves conversations off-platform; Scam Shield warns on risky messages.
struct ChatThread: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var kind: ThreadKind
    var title: String
    var creatorId: String?
    var brandId: String?
    var offerId: String?
    var submissionId: String?
    var bountyId: String?
    /// Oldest first.
    var messages: [ChatMessage]
    var unreadCreator: Int
    var unreadBrand: Int
    /// The one-sided message rate limit is active.
    var rateLimited: Bool
    var lastMessageAt: Date
    var createdAt: Date
}

// MARK: - BrandList (brand_lists)

/// A brand's CRM list of creators (favourites or custom), with notes and tags.
struct BrandList: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var brandId: String
    var name: String
    var isFavourites: Bool
    var members: [ListMember]
    var createdByMemberId: String
    var createdAt: Date
    var updatedAt: Date
}

// MARK: - Value types used by Platform entities

// MARK: - ChartPoint

/// One point of a daily or weekly series.
struct ChartPoint: Codable, Hashable, Sendable {
    var date: String
    var value: Double
}

// MARK: - WebhookDelivery

/// A recent webhook delivery.
struct WebhookDelivery: Codable, Hashable, Identifiable, Sendable {
    /// whd_<n>.
    var id: String
    var event: WebhookEventType
    var status: DeliveryStatus
    var statusCode: Int?
    var at: Date
    var latencyMs: Int
}

// MARK: - AutoApproveConditions

/// All conditions must hold.
struct AutoApproveConditions: Codable, Hashable, Sendable {
    var minFlowBand: ScoreBand
    var requireAllBeats: Bool
    var requireDisclosurePass: Bool
    var requireNoDuplicate: Bool
    var requireMusicPass: Bool
    var maxFraudScore: Int
    var minUsAudienceRatio: Double
    /// First-time creators are always manual.
    var minCreatorApprovedPosts: Int
    var minCreatorApprovalRate: Double
}

// MARK: - AutoApproveScope

/// Where a rule applies. Organic posting only, never paid-ad rights.
struct AutoApproveScope: Codable, Hashable, Sendable {
    var bountyIds: [String]
    var tiers: [Tier]
    var platforms: [Platform]
}

// MARK: - RuleGuardrails

/// Rule guardrails.
struct RuleGuardrails: Codable, Hashable, Sendable {
    var dailyCap: Int
    var budgetCapCents: Int
    /// Default 0.10.
    var spotCheckRatio: Double
    var pauseOnFraud: Bool
}

// MARK: - DryRun

/// Dry run on the last 50 submissions.
struct DryRun: Codable, Hashable, Sendable {
    var ranAt: Date
    var sampleSize: Int
    var wouldApprove: Int
    var wouldSendToHuman: Int
    var wouldBlock: Int
}

// MARK: - RuleStats

/// Rule outcomes.
struct RuleStats: Codable, Hashable, Sendable {
    var autoApproved: Int
    var spotChecked: Int
    var spotCheckOverturned: Int
    var lastTriggeredAt: Date?
}

// MARK: - CellResults

/// Measured results for a test cell.
struct CellResults: Codable, Hashable, Sendable {
    var views: Int
    var installs: Int
    var trials: Int
    var paid: Int
    var trialRate: Double
}

// MARK: - TestCell

/// One hook x body x CTA combination.
struct TestCell: Codable, Hashable, Identifiable, Sendable {
    /// cell_<n>.
    var id: String
    /// A hook_ id or custom hook text.
    var hookRef: String
    var bodyRef: String
    var cta: CtaType
    var status: TestCellStatus
    var submissionId: String?
    var postId: String?
    var results: CellResults?
}

// MARK: - TestAxisItem

/// A hook or body option in a plan.
struct TestAxisItem: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var label: String
}

// MARK: - ModelMetric

/// A monitoring metric.
struct ModelMetric: Codable, Hashable, Sendable {
    var label: String
    var value: Double
    var unit: String
}

// MARK: - CalibrationBin

/// Predicted band vs reality.
struct CalibrationBin: Codable, Hashable, Sendable {
    var band: ScoreBand
    var count: Int
    var medianViews: Int
    var trialRate: Double
}

// MARK: - FloAction

/// A one-tap action Flo offers.
struct FloAction: Codable, Hashable, Sendable {
    var label: String
    /// e.g. "apply_fix", "open_studio", "set_rate".
    var kind: String
    var payload: String?
}

// MARK: - ChatMessage

/// A message in an in-app thread. In-app chat only; Scam Shield annotates risky messages.
struct ChatMessage: Codable, Hashable, Identifiable, Sendable {
    /// msg_<n>.
    var id: String
    var authorRole: AuthorRole
    var authorUserId: String?
    var kind: MessageKind
    var body: String
    var at: Date
    /// Set on kind = warning.
    var warningCode: ScamReason?
    var readAt: Date?
}

// MARK: - RuleAuditEntry

/// One entry in an auto-approve rule audit log.
struct RuleAuditEntry: Codable, Hashable, Sendable {
    var at: Date
    var actorMemberId: String?
    var action: RuleAuditAction
    var note: String
}

// MARK: - ListMember

/// A creator on a brand's CRM list.
struct ListMember: Codable, Hashable, Sendable {
    var creatorId: String
    var note: String?
    var tags: [String]
    var addedAt: Date
}

// MARK: - ModelJobStats

/// Pipeline job stats for a model.
struct ModelJobStats: Codable, Hashable, Sendable {
    var queueDepth: Int
    var jobs24h: Int
    var failed24h: Int
    var medianLatencyS: Double
}
