// GENERATED by scripts/gen-ios-models.mjs from packages/contract/schema/*.mjs. Do not edit by hand: change the schema, then run  node scripts/gen-ios-models.mjs
// Names, enum values and field types mirror packages/contract/DOMAIN.md sections 5 to 7. Decoded with .convertFromSnakeCase.

import Foundation

// Entities (one per fixture file) and their nested value types: Bounties.

// MARK: - Bounty (bounties)

/// A funded offer to creators. Cannot be live until fully escrowed (the Funded badge). Money fields reconcile with the ledger: escrow_funded = reserved + spent + remaining + refunded.
struct Bounty: Codable, Hashable, Identifiable, Sendable {
    var id: String
    var appId: String
    /// Denormalised from the app.
    var brandId: String
    /// The one named owner of the review queue for this bounty. Absent on platform bounties.
    var ownerMemberId: String?
    var createdByMemberId: String?
    var title: String
    var type: BountyType
    var status: BountyStatus
    var visibility: BountyVisibility
    var fundingSource: FundingSource
    /// The brand's first bounty: fee waived and matched budget up to $500.
    var isFirstBounty: Bool
    /// A flowd-funded small starter bounty for new creators (First-Dollar Path).
    var isStarter: Bool
    /// Pinned at the top of the feed (flat weekly fee).
    var featured: Bool
    var featuredUntil: Date?
    /// Cents per 1,000 verified views inside the 72h window. 0 for cpa, install_only and direct.
    var cpmCents: Int
    var cpaInstallCents: Int
    var cpaTrialCents: Int
    var cpaPaidCents: Int
    /// Direct bounties only; 0 otherwise.
    var flatFeeCents: Int
    /// 0.10 default; applies if the post is promoted as an ad (60 days).
    var adCommissionRate: Double
    /// Max pool pay (CPM + CPA) for one post. Default $250.
    var perVideoCapCents: Int
    var perCreatorCapCents: Int?
    /// The creator-pay pool B.
    var budgetCents: Int
    /// Plan take rate at funding time (12% / 10% / 8%, 6% for cpa / install_only, 0 when waived).
    var takeRate: Double
    /// round(budget_cents x take_rate). Held in escrow with the budget.
    var feeReserveCents: Int
    /// Total locked in escrow: wallet funding plus matched_cents. 0 until funded.
    var escrowFundedCents: Int
    /// flowd matched budget included in escrow_funded_cents.
    var matchedCents: Int
    /// The Funded badge. True when escrow_funded_cents >= budget_cents + fee_reserve_cents.
    var funded: Bool
    var fundedAt: Date?
    /// Sum of open submissions' reserved_cents.
    var reservedCents: Int
    /// Creator pay + fees already settled out of escrow.
    var spentCents: Int
    /// Unreserved, unspent escrow available for new reservations.
    var remainingCents: Int
    /// Returned to the wallet at settlement. 0 until settled.
    var refundedCents: Int
    var brief: Brief
    var rightsCard: RightsCard
    var deliverables: Deliverables
    var eligibility: Eligibility
    var briefLint: BriefLint
    /// Ops overrides of lint findings (admin log).
    var lintOverrides: [LintOverride]?
    var payMath: PayMath
    /// Recommended formats, best first.
    var formatIds: [FormatId]
    /// Generated bounty cover.
    var art: ArtSeed
    var startsAt: Date
    var endsAt: Date
    var publishedAt: Date?
    var firstSubmissionAt: Date?
    /// When remaining_cents first fell below one reservation unit.
    var filledAt: Date?
    var timeToFillHours: Double?
    var endedAt: Date?
    var settledAt: Date?
    /// Default 72.
    var reviewSlaHours: Int
    var counts: BountyCounts
    /// Lifetime funnel of the bounty's posts.
    var funnel: FunnelCounts
    /// The brand's all-in effective CPM: round(card_charge x cpm / budget) (FORMULAS: funding). 0 when cpm_cents is 0 (cpa, install_only, direct).
    var allInCpmCents: Int
    var createdAt: Date
    var updatedAt: Date
}

// MARK: - Value types used by Bounties entities

// MARK: - BriefBeat

/// A beat a bounty requires or suggests.
struct BriefBeat: Codable, Hashable, Sendable {
    var beat: BeatId
    var label: String
    var required: Bool
    var hint: String?
}

// MARK: - Brief

/// The creative brief.
struct Brief: Codable, Hashable, Sendable {
    var summary: String
    var talkingPoints: [String]
    var dos: [String]
    var donts: [String]
    var beats: [BriefBeat]
    /// Exactly one call to action.
    var cta: String
    var offerLine: String?
    var hashtags: [String]
    var mentions: [String]
    var tone: String
    /// Auto-added to every posting flow.
    var disclosureText: String
    var bannedClaims: [String]
    /// Top posts from earlier bounties to copy the structure of.
    var examplePostIds: [String]?
    var referenceArt: [ArtSeed]?
}

// MARK: - RightsCard

/// Plain-language licence shown on every bounty. Organic posting is always included.
struct RightsCard: Codable, Hashable, Sendable {
    /// Always true.
    var organic: Bool
    /// 0 = no paid-ad use; default 90.
    var paidAdsDays: Int
    var adPlatforms: [AdPlatform]
    /// Spark code / partnership permission is requested on approval.
    var whitelisting: Bool
    /// Renewal price as a share of the base fee per 30 days; default 0.25.
    var renewalPctPer30d: Double
    var exclusivityDays: Int
    /// Off by default.
    var aiLikeness: Bool
    var territory: String
    /// Plain-English paragraph.
    var summary: String
}

// MARK: - Deliverables

/// What a creator must deliver.
struct Deliverables: Codable, Hashable, Sendable {
    var videosPerCreator: Int
    var minDurationS: Int
    var maxDurationS: Int
    /// "9:16".
    var aspect: String
    var platforms: [Platform]
    var regions: [Country]
    var requireFace: Bool
    var musicPolicy: MusicPolicy
    var aiPolicy: AiContentPolicy
}

// MARK: - Eligibility

/// Who can submit.
struct Eligibility: Codable, Hashable, Sendable {
    var minTier: Tier?
    var minFollowers: Int?
    var countries: [Country]
    var niches: [Niche]
    var minUsAudienceRatio: Double?
    /// Always false: bounties may not require burner accounts.
    var burnerAccountsAllowed: Bool
}

// MARK: - BriefLintIssue

/// One Brief Lint finding.
struct BriefLintIssue: Codable, Hashable, Sendable {
    var code: BriefLintCode
    var severity: LintSeverity
    var message: String
    var field: String?
}

// MARK: - BriefLint

/// Result of Brief Lint on the current brief. Blockers prevent publishing.
struct BriefLint: Codable, Hashable, Sendable {
    /// True when there are no blockers.
    var passed: Bool
    var checkedAt: Date
    var issues: [BriefLintIssue]
}

// MARK: - PayMath

/// Pay Math: what a creator is likely to earn and what the brand really pays. Always an estimate.
struct PayMath: Codable, Hashable, Sendable {
    var expectedViewsP25: Int
    var expectedViewsMedian: Int
    var expectedViewsP75: Int
    /// Expected creator pay per video at p25 views (CPM + CPA, after the cap).
    var p25Cents: Int
    var medianCents: Int
    var p75Cents: Int
    /// Blended creator pay per 1,000 views at the median.
    var creatorCpmCents: Int
    /// Creator CPM + platform fee + card processing.
    var allInCpmCents: Int
    /// Where the estimate comes from (category market series).
    var basis: String
}

// MARK: - BountyCounts

/// Denormalised counters on a bounty (validated against submissions and posts).
struct BountyCounts: Codable, Hashable, Sendable {
    /// Distinct creators who submitted.
    var creators: Int
    var submissions: Int
    var inReview: Int
    var approved: Int
    var rejected: Int
    var posts: Int
    var livePosts: Int
}

// MARK: - FunnelCounts

/// Views to paid. Tracked = link + code (deterministic). est_* = MMP, survey and modelled (never paid).
struct FunnelCounts: Codable, Hashable, Sendable {
    /// Verified views (lifetime).
    var views: Int
    /// Tracked visits: link clicks and code lookups.
    var clicks: Int
    var installs: Int
    var trials: Int
    var paid: Int
    var estInstalls: Int
    var estTrials: Int
    var estPaid: Int
}

// MARK: - LintOverride

/// An Ops override of a Brief Lint finding on a bounty (logged).
struct LintOverride: Codable, Hashable, Sendable {
    var code: BriefLintCode
    var byUserId: String
    var reason: String
    var at: Date
}
