// GENERATED by scripts/gen-ios-models.mjs from packages/contract/schema/*.mjs. Do not edit by hand: change the schema, then run  node scripts/gen-ios-models.mjs
// Names, enum values and field types mirror packages/contract/DOMAIN.md sections 5 to 7. Decoded with .convertFromSnakeCase.

import Foundation

// Enumerations: Market (9). Every enum decodes unknown values to `.unknown`.

// MARK: - OfferKind

/// Kind of an offer.
enum OfferKind: String, Codable, Hashable, Sendable, CaseIterable {
    case invite = "invite"
    case direct = "direct"
    case rebuy = "rebuy"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [OfferKind] {
        return [.invite, .direct, .rebuy]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = OfferKind(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .invite: return "Invite"
        case .direct: return "Direct offer"
        case .rebuy: return "Re-buy"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .invite: return .info
        case .direct: return .sun
        case .rebuy: return .violet
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .invite: return "Brand invites a creator to an existing open bounty."
        case .direct: return "Brand buys from a rate card at the ask (or negotiates)."
        case .rebuy: return "Brand pays the creator of a winner for new hooks or variants."
        case .unknown: return nil
        }
    }
}

// MARK: - OfferStatus

/// Offer / negotiation state: who has the ball.
enum OfferStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case awaitingCreator = "awaiting_creator"
    case awaitingBrand = "awaiting_brand"
    case accepted = "accepted"
    case declined = "declined"
    case expired = "expired"
    case withdrawn = "withdrawn"
    case completed = "completed"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [OfferStatus] {
        return [.awaitingCreator, .awaitingBrand, .accepted, .declined, .expired, .withdrawn, .completed]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = OfferStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .awaitingCreator: return "Awaiting creator"
        case .awaitingBrand: return "Awaiting brand"
        case .accepted: return "Accepted"
        case .declined: return "Declined"
        case .expired: return "Expired"
        case .withdrawn: return "Withdrawn"
        case .completed: return "Completed"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .awaitingCreator: return .info
        case .awaitingBrand: return .info
        case .accepted: return .mint
        case .declined: return .rose
        case .expired: return .neutral
        case .withdrawn: return .neutral
        case .completed: return .mint
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .awaitingCreator: return "The creator needs to accept, counter or decline."
        case .awaitingBrand: return "The creator countered; the brand needs to respond."
        case .accepted: return "Agreed; a private direct bounty is funded from the brand wallet."
        case .declined: return "Declined."
        case .expired: return "No response in 7 days."
        case .withdrawn: return "Withdrawn by the sender."
        case .completed: return "Video delivered, approved and paid."
        case .unknown: return nil
        }
    }
}

// MARK: - OfferMessageType

/// Message types in a negotiation thread.
enum OfferMessageType: String, Codable, Hashable, Sendable, CaseIterable {
    case offer = "offer"
    case counter = "counter"
    case message = "message"
    case accept = "accept"
    case decline = "decline"
    case withdraw = "withdraw"
    case system = "system"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [OfferMessageType] {
        return [.offer, .counter, .message, .accept, .decline, .withdraw, .system]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = OfferMessageType(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .offer: return "Offer"
        case .counter: return "Counter"
        case .message: return "Message"
        case .accept: return "Accept"
        case .decline: return "Decline"
        case .withdraw: return "Withdraw"
        case .system: return "System"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .offer: return .sun
        case .counter: return .ember
        case .message: return .neutral
        case .accept: return .mint
        case .decline: return .rose
        case .withdraw: return .neutral
        case .system: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .offer: return "Opening offer with amount and rights."
        case .counter: return "Counter-offer (max 3 rounds)."
        case .message: return "Free text."
        case .accept: return "Accepted the latest terms."
        case .decline: return "Declined."
        case .withdraw: return "Withdrawn."
        case .system: return "System note (escrow funded, expiry reminder)."
        case .unknown: return nil
        }
    }
}

// MARK: - AuthorRole

/// Who wrote a message.
enum AuthorRole: String, Codable, Hashable, Sendable, CaseIterable {
    case brand = "brand"
    case creator = "creator"
    case system = "system"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [AuthorRole] {
        return [.brand, .creator, .system]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = AuthorRole(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .brand: return "Brand"
        case .creator: return "Creator"
        case .system: return "System"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .brand: return .info
        case .creator: return .accent
        case .system: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .brand: return "A brand member."
        case .creator: return "The creator."
        case .system: return "flowd."
        case .unknown: return nil
        }
    }
}

// MARK: - AuctionStatus

/// Sealed-bid auction lifecycle.
enum AuctionStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case scheduled = "scheduled"
    case open = "open"
    case closed = "closed"
    case awarded = "awarded"
    case noBids = "no_bids"
    case cancelled = "cancelled"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [AuctionStatus] {
        return [.scheduled, .open, .closed, .awarded, .noBids, .cancelled]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = AuctionStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .scheduled: return "Scheduled"
        case .open: return "Open"
        case .closed: return "Closed"
        case .awarded: return "Awarded"
        case .noBids: return "No bids"
        case .cancelled: return "Cancelled"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .scheduled: return .info
        case .open: return .mint
        case .closed: return .info
        case .awarded: return .sun
        case .noBids: return .neutral
        case .cancelled: return .rose
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .scheduled: return "Not open yet."
        case .open: return "Accepting sealed bids. Bidders see only their own bid."
        case .closed: return "Bids sealed; resolving."
        case .awarded: return "The top bids won and pay the uniform clearing price (highest losing bid, or the reserve)."
        case .noBids: return "Closed with no valid bids."
        case .cancelled: return "Cancelled by the creator or Ops before it closed."
        case .unknown: return nil
        }
    }
}

// MARK: - BidStatus

/// State of a sealed bid.
enum BidStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case sealed = "sealed"
    case won = "won"
    case lost = "lost"
    case withdrawn = "withdrawn"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [BidStatus] {
        return [.sealed, .won, .lost, .withdrawn]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = BidStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .sealed: return "Sealed"
        case .won: return "Won"
        case .lost: return "Lost"
        case .withdrawn: return "Withdrawn"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .sealed: return .info
        case .won: return .mint
        case .lost: return .neutral
        case .withdrawn: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .sealed: return "Placed; hidden from other bidders."
        case .won: return "A winning bid; pays the clearing price."
        case .lost: return "Outbid."
        case .withdrawn: return "Withdrawn before close."
        case .unknown: return nil
        }
    }
}

// MARK: - SpecStatus

/// Spec Market listing state.
enum SpecStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case draft = "draft"
    case scoring = "scoring"
    case firstRefusal = "first_refusal"
    case listed = "listed"
    case licensed = "licensed"
    case withdrawn = "withdrawn"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [SpecStatus] {
        return [.draft, .scoring, .firstRefusal, .listed, .licensed, .withdrawn]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = SpecStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .draft: return "Draft"
        case .scoring: return "Scoring"
        case .firstRefusal: return "First refusal"
        case .listed: return "Listed"
        case .licensed: return "Licensed"
        case .withdrawn: return "Withdrawn"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .draft: return .neutral
        case .scoring: return .info
        case .firstRefusal: return .ember
        case .listed: return .mint
        case .licensed: return .sun
        case .withdrawn: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .draft: return "Uploaded by the creator, not submitted."
        case .scoring: return "QA and checklist scoring running."
        case .firstRefusal: return "Released from a bounty; the original brand has 7 days of first refusal."
        case .listed: return "Available to license."
        case .licensed: return "Licensed at least once."
        case .withdrawn: return "Taken down by the creator."
        case .unknown: return nil
        }
    }
}

// MARK: - SpecSource

/// Where a spec video came from.
enum SpecSource: String, Codable, Hashable, Sendable, CaseIterable {
    case creatorUpload = "creator_upload"
    case releasedFromBounty = "released_from_bounty"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [SpecSource] {
        return [.creatorUpload, .releasedFromBounty]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = SpecSource(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .creatorUpload: return "Creator upload"
        case .releasedFromBounty: return "Released from a bounty"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .creatorUpload: return .accent
        case .releasedFromBounty: return .violet
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .creatorUpload: return "Made speculatively by the creator."
        case .releasedFromBounty: return "Approved but unused for 30 days."
        case .unknown: return nil
        }
    }
}

// MARK: - RateCardStatus

/// Creator availability on their rate card.
enum RateCardStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case open = "open"
    case limited = "limited"
    case paused = "paused"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [RateCardStatus] {
        return [.open, .limited, .paused]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = RateCardStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .open: return "Open to offers"
        case .limited: return "Limited slots"
        case .paused: return "Paused"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .open: return .mint
        case .limited: return .ember
        case .paused: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .open: return "Accepting direct offers."
        case .limited: return "A few slots left this month."
        case .paused: return "Not taking offers."
        case .unknown: return nil
        }
    }
}
