// GENERATED by scripts/gen-ios-models.mjs from packages/contract/schema/*.mjs. Do not edit by hand: change the schema, then run  node scripts/gen-ios-models.mjs
// Names, enum values and field types mirror packages/contract/DOMAIN.md sections 5 to 7. Decoded with .convertFromSnakeCase.

import Foundation

// Enumerations: Growth (21). Every enum decodes unknown values to `.unknown`.

// MARK: - DropStatus

/// Daily Drop state. One drop a day at 16:00 UTC; spots_left is a true count.
enum DropStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case upcoming = "upcoming"
    case live = "live"
    case soldOut = "sold_out"
    case closed = "closed"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [DropStatus] {
        return [.upcoming, .live, .soldOut, .closed]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = DropStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .upcoming: return "Upcoming"
        case .live: return "Live"
        case .soldOut: return "Sold out"
        case .closed: return "Closed"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .upcoming: return .info
        case .live: return .ember
        case .soldOut: return .neutral
        case .closed: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .upcoming: return "Pre-drop: countdown, no claims yet."
        case .live: return "Open for claims; inventory is real."
        case .soldOut: return "Every spot claimed."
        case .closed: return "Claim window ended with spots unclaimed (released back to the open feed)."
        case .unknown: return nil
        }
    }
}

// MARK: - TournamentStatus

/// Tournament lifecycle.
enum TournamentStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case announced = "announced"
    case open = "open"
    case live = "live"
    case judging = "judging"
    case complete = "complete"
    case cancelled = "cancelled"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [TournamentStatus] {
        return [.announced, .open, .live, .judging, .complete, .cancelled]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = TournamentStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .announced: return "Announced"
        case .open: return "Open"
        case .live: return "Live"
        case .judging: return "Judging"
        case .complete: return "Complete"
        case .cancelled: return "Cancelled"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .announced: return .info
        case .open: return .mint
        case .live: return .ember
        case .judging: return .accent
        case .complete: return .neutral
        case .cancelled: return .rose
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .announced: return "Visible; entries not open."
        case .open: return "Taking entries."
        case .live: return "Rounds running."
        case .judging: return "Results being verified."
        case .complete: return "Prizes paid."
        case .cancelled: return "Cancelled."
        case .unknown: return nil
        }
    }
}

// MARK: - TournamentFormat

/// How a tournament is structured.
enum TournamentFormat: String, Codable, Hashable, Sendable, CaseIterable {
    case bracket = "bracket"
    case leaderboard = "leaderboard"
    case hookBattle = "hook_battle"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [TournamentFormat] {
        return [.bracket, .leaderboard, .hookBattle]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = TournamentFormat(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .bracket: return "Bracket"
        case .leaderboard: return "Leaderboard"
        case .hookBattle: return "Hook battle"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .bracket: return .accent
        case .leaderboard: return .accent
        case .hookBattle: return .accent
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .bracket: return "Head-to-head hook battles."
        case .leaderboard: return "Ranked by verified results over the period."
        case .hookBattle: return "Best Hook Score and retention on the same brief."
        case .unknown: return nil
        }
    }
}

// MARK: - EntryStatus

/// Tournament entry state.
enum EntryStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case entered = "entered"
    case advancing = "advancing"
    case eliminated = "eliminated"
    case won = "won"
    case disqualified = "disqualified"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [EntryStatus] {
        return [.entered, .advancing, .eliminated, .won, .disqualified]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = EntryStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .entered: return "Entered"
        case .advancing: return "Advancing"
        case .eliminated: return "Eliminated"
        case .won: return "Won"
        case .disqualified: return "Disqualified"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .entered: return .info
        case .advancing: return .mint
        case .eliminated: return .neutral
        case .won: return .sun
        case .disqualified: return .rose
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .entered: return "In."
        case .advancing: return "Through to the next round."
        case .eliminated: return "Out."
        case .won: return "Placed in the prizes."
        case .disqualified: return "Rule breach or fraud."
        case .unknown: return nil
        }
    }
}

// MARK: - CrewRole

/// Role in a crew.
enum CrewRole: String, Codable, Hashable, Sendable, CaseIterable {
    case lead = "lead"
    case coLead = "co_lead"
    case member = "member"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [CrewRole] {
        return [.lead, .coLead, .member]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = CrewRole(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .lead: return "Lead"
        case .coLead: return "Co-lead"
        case .member: return "Member"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .lead: return .sun
        case .coLead: return .accent
        case .member: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .lead: return "Gold or above; runs the crew."
        case .coLead: return "Helps run the crew."
        case .member: return "Member."
        case .unknown: return nil
        }
    }
}

// MARK: - StreakStatus

/// Weekly streak state.
enum StreakStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case new = "new"
    case active = "active"
    case frozen = "frozen"
    case resting = "resting"
    case broken = "broken"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [StreakStatus] {
        return [.new, .active, .frozen, .resting, .broken]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = StreakStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .new: return "New"
        case .active: return "Active"
        case .frozen: return "Frozen"
        case .resting: return "Resting"
        case .broken: return "Broken"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .new: return .neutral
        case .active: return .mint
        case .frozen: return .info
        case .resting: return .info
        case .broken: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .new: return "No streak yet."
        case .active: return "Posted this ISO week or still has the week to go."
        case .frozen: return "A banked freeze covered a missed week."
        case .resting: return "A declared rest week; the streak is preserved."
        case .broken: return "A week was missed with no freeze or rest. No guilt copy."
        case .unknown: return nil
        }
    }
}

// MARK: - WeekOutcome

/// What happened in a streak week.
enum WeekOutcome: String, Codable, Hashable, Sendable, CaseIterable {
    case posted = "posted"
    case freezeUsed = "freeze_used"
    case rest = "rest"
    case missed = "missed"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [WeekOutcome] {
        return [.posted, .freezeUsed, .rest, .missed]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = WeekOutcome(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .posted: return "Posted"
        case .freezeUsed: return "Freeze used"
        case .rest: return "Rest week"
        case .missed: return "Missed"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .posted: return .mint
        case .freezeUsed: return .info
        case .rest: return .info
        case .missed: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .posted: return "At least one post."
        case .freezeUsed: return "A banked freeze covered the week."
        case .rest: return "Declared in advance; streak preserved, week not counted."
        case .missed: return "No post, no freeze, no rest."
        case .unknown: return nil
        }
    }
}

// MARK: - LeaderboardMetric

/// What a leaderboard ranks.
enum LeaderboardMetric: String, Codable, Hashable, Sendable, CaseIterable {
    case earnings = "earnings"
    case conversionRate = "conversion_rate"
    case scoreAccuracy = "score_accuracy"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [LeaderboardMetric] {
        return [.earnings, .conversionRate, .scoreAccuracy]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = LeaderboardMetric(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .earnings: return "Earnings"
        case .conversionRate: return "Conversion rate"
        case .scoreAccuracy: return "Score accuracy"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .earnings: return .mint
        case .conversionRate: return .accent
        case .scoreAccuracy: return .violet
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .earnings: return "Cleared earnings in the week."
        case .conversionRate: return "Installs per 1,000 verified views."
        case .scoreAccuracy: return "How close the creator's Flow Score band predicted real results."
        case .unknown: return nil
        }
    }
}

// MARK: - LeaderboardZone

/// Cohort zone. No demotion zone exists.
enum LeaderboardZone: String, Codable, Hashable, Sendable, CaseIterable {
    case promotion = "promotion"
    case steady = "steady"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [LeaderboardZone] {
        return [.promotion, .steady]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = LeaderboardZone(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .promotion: return "Promotion zone"
        case .steady: return "Steady"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .promotion: return .mint
        case .steady: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .promotion: return "Top 5: moves up to the next cohort next week."
        case .steady: return "Stays in this cohort."
        case .unknown: return nil
        }
    }
}

// MARK: - ReferralKind

/// Who is referring whom.
enum ReferralKind: String, Codable, Hashable, Sendable, CaseIterable {
    case creator = "creator"
    case brand = "brand"
    case agency = "agency"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [ReferralKind] {
        return [.creator, .brand, .agency]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = ReferralKind(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .creator: return "Creator referral"
        case .brand: return "Brand referral"
        case .agency: return "Agency partner"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .creator: return .accent
        case .brand: return .info
        case .agency: return .violet
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .creator: return "A creator invites a creator."
        case .brand: return "A person refers a brand."
        case .agency: return "An agency refers brands (12-month fee share)."
        case .unknown: return nil
        }
    }
}

// MARK: - ReferralStatus

/// Referral progress.
enum ReferralStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case invited = "invited"
    case joined = "joined"
    case firstDollar = "first_dollar"
    case earning = "earning"
    case complete = "complete"
    case expired = "expired"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [ReferralStatus] {
        return [.invited, .joined, .firstDollar, .earning, .complete, .expired]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = ReferralStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .invited: return "Invited"
        case .joined: return "Joined"
        case .firstDollar: return "First dollar"
        case .earning: return "Earning"
        case .complete: return "Complete"
        case .expired: return "Expired"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .invited: return .info
        case .joined: return .accent
        case .firstDollar: return .mint
        case .earning: return .mint
        case .complete: return .neutral
        case .expired: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .invited: return "Invite sent."
        case .joined: return "Signed up."
        case .firstDollar: return "Referee's first cleared earnings."
        case .earning: return "Reward share running (90 days or 12 months)."
        case .complete: return "Reward window ended or cap reached."
        case .expired: return "Invite expired unused."
        case .unknown: return nil
        }
    }
}

// MARK: - LessonTopic

/// flowd Academy topics (free, five minutes or less, never required).
enum LessonTopic: String, Codable, Hashable, Sendable, CaseIterable {
    case firstVideo = "first_video"
    case briefsAndRights = "briefs_and_rights"
    case usageRights = "usage_rights"
    case contractRedFlags = "contract_red_flags"
    case platformRules = "platform_rules"
    case taxes = "taxes"
    case scams = "scams"
    case rateCards = "rate_cards"
    case analytics = "analytics"
    case sustainableCadence = "sustainable_cadence"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [LessonTopic] {
        return [.firstVideo, .briefsAndRights, .usageRights, .contractRedFlags, .platformRules, .taxes, .scams, .rateCards, .analytics, .sustainableCadence]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = LessonTopic(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .firstVideo: return "First video in 15 minutes"
        case .briefsAndRights: return "Reading a brief and a Rights Card"
        case .usageRights: return "Usage rights and what to charge"
        case .contractRedFlags: return "Contract red flags"
        case .platformRules: return "Platform rules and #ad"
        case .taxes: return "Taxes: W-9 and 1099"
        case .scams: return "Spotting scams"
        case .rateCards: return "Rate cards and negotiating"
        case .analytics: return "Reading analytics and retention curves"
        case .sustainableCadence: return "Sustainable cadence and burnout"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .firstVideo: return .accent
        case .briefsAndRights: return .accent
        case .usageRights: return .accent
        case .contractRedFlags: return .rose
        case .platformRules: return .accent
        case .taxes: return .sun
        case .scams: return .rose
        case .rateCards: return .sun
        case .analytics: return .info
        case .sustainableCadence: return .mint
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .firstVideo: return "Hooks and getting started."
        case .briefsAndRights: return "Briefs and licences."
        case .usageRights: return "Whitelisting, paid usage, renewals."
        case .contractRedFlags: return "Perpetual rights, pay-to-join, burner accounts."
        case .platformRules: return "Originality and disclosure."
        case .taxes: return "Not tax advice."
        case .scams: return "Scam Shield."
        case .rateCards: return "Pricing your work."
        case .analytics: return "Retention and funnel."
        case .sustainableCadence: return "Pace and rest."
        case .unknown: return nil
        }
    }
}

// MARK: - LessonBlockKind

/// Kind of a lesson content block.
enum LessonBlockKind: String, Codable, Hashable, Sendable, CaseIterable {
    case text = "text"
    case tip = "tip"
    case warning = "warning"
    case example = "example"
    case steps = "steps"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [LessonBlockKind] {
        return [.text, .tip, .warning, .example, .steps]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = LessonBlockKind(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .text: return "Text"
        case .tip: return "Tip"
        case .warning: return "Watch out"
        case .example: return "Example"
        case .steps: return "Steps"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .text: return .neutral
        case .tip: return .accent
        case .warning: return .ember
        case .example: return .info
        case .steps: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .text: return "Body copy."
        case .tip: return "A practical tip."
        case .warning: return "A pitfall."
        case .example: return "A worked example."
        case .steps: return "A numbered list (one step per line in body)."
        case .unknown: return nil
        }
    }
}

// MARK: - LessonStatus

/// A creator's progress on a lesson.
enum LessonStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case notStarted = "not_started"
    case inProgress = "in_progress"
    case completed = "completed"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [LessonStatus] {
        return [.notStarted, .inProgress, .completed]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = LessonStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .notStarted: return "Not started"
        case .inProgress: return "In progress"
        case .completed: return "Completed"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .notStarted: return .neutral
        case .inProgress: return .info
        case .completed: return .mint
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .notStarted: return "Not opened."
        case .inProgress: return "Started."
        case .completed: return "Quiz passed; badge awarded."
        case .unknown: return nil
        }
    }
}

// MARK: - TrendKind

/// Trend radar item kind.
enum TrendKind: String, Codable, Hashable, Sendable, CaseIterable {
    case format = "format"
    case hook = "hook"
    case topic = "topic"
    case sound = "sound"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [TrendKind] {
        return [.format, .hook, .topic, .sound]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = TrendKind(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .format: return "Format"
        case .hook: return "Hook"
        case .topic: return "Topic"
        case .sound: return "Sound"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .format: return .accent
        case .hook: return .accent
        case .topic: return .accent
        case .sound: return .ember
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .format: return "A video format."
        case .hook: return "A hook pattern."
        case .topic: return "A topic or angle."
        case .sound: return "A trending sound. Not licensed for ads; flag on promotion."
        case .unknown: return nil
        }
    }
}

// MARK: - TrendDirection

/// Direction of a trend.
enum TrendDirection: String, Codable, Hashable, Sendable, CaseIterable {
    case rising = "rising"
    case steady = "steady"
    case fading = "fading"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [TrendDirection] {
        return [.rising, .steady, .fading]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = TrendDirection(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .rising: return "Rising"
        case .steady: return "Steady"
        case .fading: return "Fading"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .rising: return .mint
        case .steady: return .neutral
        case .fading: return .ember
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .rising: return "Growing week on week."
        case .steady: return "Flat."
        case .fading: return "Declining; flagged for refresh."
        case .unknown: return nil
        }
    }
}

// MARK: - BadgeId

/// Creator badges. They mirror real skill or earnings milestones, never invented ones.
enum BadgeId: String, Codable, Hashable, Sendable, CaseIterable {
    case foundingCreator = "founding_creator"
    case firstDollar = "first_dollar"
    case streak4 = "streak_4"
    case streak8 = "streak_8"
    case streak12 = "streak_12"
    case academyGraduate = "academy_graduate"
    case crewLead = "crew_lead"
    case tournamentWinner = "tournament_winner"
    case top10Week = "top_10_week"
    case hookMaster = "hook_master"
    case idVerified = "id_verified"
    case alwaysOnTime = "always_on_time"
    case millionViews = "million_views"
    case firstTrial = "first_trial"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [BadgeId] {
        return [.foundingCreator, .firstDollar, .streak4, .streak8, .streak12, .academyGraduate, .crewLead, .tournamentWinner, .top10Week, .hookMaster, .idVerified, .alwaysOnTime, .millionViews, .firstTrial]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = BadgeId(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .foundingCreator: return "Founding creator"
        case .firstDollar: return "First dollar"
        case .streak4: return "4-week streak"
        case .streak8: return "8-week streak"
        case .streak12: return "12-week streak"
        case .academyGraduate: return "Academy graduate"
        case .crewLead: return "Crew lead"
        case .tournamentWinner: return "Tournament winner"
        case .top10Week: return "Top 10 of the week"
        case .hookMaster: return "Hook master"
        case .idVerified: return "ID verified"
        case .alwaysOnTime: return "Always on time"
        case .millionViews: return "1M verified views"
        case .firstTrial: return "First trial"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .foundingCreator: return .sun
        case .firstDollar: return .mint
        case .streak4: return .mint
        case .streak8: return .mint
        case .streak12: return .sun
        case .academyGraduate: return .accent
        case .crewLead: return .accent
        case .tournamentWinner: return .sun
        case .top10Week: return .sun
        case .hookMaster: return .violet
        case .idVerified: return .mint
        case .alwaysOnTime: return .mint
        case .millionViews: return .sun
        case .firstTrial: return .mint
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .foundingCreator: return "One of the first 200 creators."
        case .firstDollar: return "First cleared earnings."
        case .streak4: return "Posted in 4 consecutive weeks."
        case .streak8: return "Posted in 8 consecutive weeks."
        case .streak12: return "Posted in 12 consecutive weeks."
        case .academyGraduate: return "Completed all 10 Academy lessons."
        case .crewLead: return "Leads a crew."
        case .tournamentWinner: return "Placed in a tournament."
        case .top10Week: return "Top 10 on a weekly board."
        case .hookMaster: return "Hook Score A on five straight submissions."
        case .idVerified: return "Identity verified."
        case .alwaysOnTime: return "10 approved posts, all resubmitted and posted on time."
        case .millionViews: return "One million verified views."
        case .firstTrial: return "First trial started through your link or code."
        case .unknown: return nil
        }
    }
}

// MARK: - WrappedPeriod

/// Wrapped period.
enum WrappedPeriod: String, Codable, Hashable, Sendable, CaseIterable {
    case month = "month"
    case year = "year"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [WrappedPeriod] {
        return [.month, .year]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = WrappedPeriod(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .month: return "Month"
        case .year: return "Year"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .month: return .accent
        case .year: return .sun
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .month: return "Monthly recap."
        case .year: return "Yearly Wrapped."
        case .unknown: return nil
        }
    }
}

// MARK: - ProofKind

/// What a public proof page shows.
enum ProofKind: String, Codable, Hashable, Sendable, CaseIterable {
    case payout = "payout"
    case month = "month"
    case tierUp = "tier_up"
    case wrapped = "wrapped"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [ProofKind] {
        return [.payout, .month, .tierUp, .wrapped]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = ProofKind(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .payout: return "Payout"
        case .month: return "Month"
        case .tierUp: return "Tier up"
        case .wrapped: return "Wrapped"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .payout: return .mint
        case .month: return .mint
        case .tierUp: return .sun
        case .wrapped: return .sun
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .payout: return "A payout."
        case .month: return "A month's cleared earnings."
        case .tierUp: return "A tier-up."
        case .wrapped: return "A Wrapped recap."
        case .unknown: return nil
        }
    }
}

// MARK: - LeaderboardScope

/// Which population a leaderboard ranks.
enum LeaderboardScope: String, Codable, Hashable, Sendable, CaseIterable {
    case cohort = "cohort"
    case niche = "niche"
    case global = "global"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [LeaderboardScope] {
        return [.cohort, .niche, .global]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = LeaderboardScope(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .cohort: return "Peer cohort"
        case .niche: return "Niche board"
        case .global: return "Global board"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .cohort: return .accent
        case .niche: return .info
        case .global: return .sun
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .cohort: return "About 30 creators in the same tier and niche, with a promotion zone."
        case .niche: return "Public weekly board for one niche."
        case .global: return "Public weekly board across all creators."
        case .unknown: return nil
        }
    }
}

// MARK: - WrappedCardKind

/// A story card in Wrapped.
enum WrappedCardKind: String, Codable, Hashable, Sendable, CaseIterable {
    case earnings = "earnings"
    case views = "views"
    case bestPost = "best_post"
    case winningHook = "winning_hook"
    case trials = "trials"
    case streak = "streak"
    case tier = "tier"
    case topBrand = "top_brand"
    case typical = "typical"
    case share = "share"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [WrappedCardKind] {
        return [.earnings, .views, .bestPost, .winningHook, .trials, .streak, .tier, .topBrand, .typical, .share]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = WrappedCardKind(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .earnings: return "Earnings"
        case .views: return "Views"
        case .bestPost: return "Best post"
        case .winningHook: return "Winning hook"
        case .trials: return "Trials started"
        case .streak: return "Streak"
        case .tier: return "Tier"
        case .topBrand: return "Top brand"
        case .typical: return "Typical creator"
        case .share: return "Share"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .earnings: return .mint
        case .views: return .info
        case .bestPost: return .accent
        case .winningHook: return .violet
        case .trials: return .mint
        case .streak: return .mint
        case .tier: return .sun
        case .topBrand: return .info
        case .typical: return .neutral
        case .share: return .accent
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .earnings: return "Cleared earnings in the period."
        case .views: return "Verified views delivered."
        case .bestPost: return "The post with the highest earnings."
        case .winningHook: return "The hook that drove the most trials."
        case .trials: return "Trials started through the creator's links and codes."
        case .streak: return "Weekly streak and freezes."
        case .tier: return "Tier and progress."
        case .topBrand: return "The brand the creator worked with most."
        case .typical: return "The tier median beside the creator's number. Always included."
        case .share: return "The closing share card."
        case .unknown: return nil
        }
    }
}
