// GENERATED by scripts/gen-ios-models.mjs from packages/contract/schema/*.mjs. Do not edit by hand: change the schema, then run  node scripts/gen-ios-models.mjs
// Names, enum values and field types mirror packages/contract/DOMAIN.md sections 5 to 7. Decoded with .convertFromSnakeCase.

import Foundation

// Enumerations: Rights (2). Every enum decodes unknown values to `.unknown`.

// MARK: - RightsScope

/// What a rights grant covers.
enum RightsScope: String, Codable, Hashable, Sendable, CaseIterable {
    case organic = "organic"
    case paidAds = "paid_ads"
    case sparkCode = "spark_code"
    case partnershipPermission = "partnership_permission"
    case aiLikeness = "ai_likeness"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [RightsScope] {
        return [.organic, .paidAds, .sparkCode, .partnershipPermission, .aiLikeness]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = RightsScope(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .organic: return "Organic posting"
        case .paidAds: return "Paid-ad usage"
        case .sparkCode: return "Spark code"
        case .partnershipPermission: return "Partnership permission"
        case .aiLikeness: return "AI likeness"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .organic: return .mint
        case .paidAds: return .accent
        case .sparkCode: return .accent
        case .partnershipPermission: return .accent
        case .aiLikeness: return .rose
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .organic: return "Posting on the creator's own account. Always included."
        case .paidAds: return "Running the video as an ad. Default 90 days, renewable at 25% of base fee per 30 days."
        case .sparkCode: return "TikTok Spark authorization code (7/30/60/365 days)."
        case .partnershipPermission: return "Meta partnership-ad permission."
        case .aiLikeness: return "Off by default; needs explicit separate consent."
        case .unknown: return nil
        }
    }
}

// MARK: - RightsGrantStatus

/// Rights grant lifecycle.
enum RightsGrantStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case pendingPermission = "pending_permission"
    case active = "active"
    case expiring = "expiring"
    case renewalRequested = "renewal_requested"
    case expired = "expired"
    case revoked = "revoked"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [RightsGrantStatus] {
        return [.pendingPermission, .active, .expiring, .renewalRequested, .expired, .revoked]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = RightsGrantStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .pendingPermission: return "Awaiting creator"
        case .active: return "Active"
        case .expiring: return "Expiring"
        case .renewalRequested: return "Renewal requested"
        case .expired: return "Expired"
        case .revoked: return "Revoked"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .pendingPermission: return .info
        case .active: return .mint
        case .expiring: return .ember
        case .renewalRequested: return .info
        case .expired: return .neutral
        case .revoked: return .rose
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .pendingPermission: return "Brand asked for a Spark code or partnership permission."
        case .active: return "In force."
        case .expiring: return "Ends within 30 days (alerts at 30, 14 and 7 days)."
        case .renewalRequested: return "The brand asked to renew (25% of base fee per 30 days)."
        case .expired: return "Ended; the ad stops automatically."
        case .revoked: return "Revoked for misuse by the creator or Ops."
        case .unknown: return nil
        }
    }
}
