// GENERATED by scripts/gen-ios-models.mjs from packages/contract/schema/*.mjs. Do not edit by hand: change the schema, then run  node scripts/gen-ios-models.mjs
// Names, enum values and field types mirror packages/contract/DOMAIN.md sections 5 to 7. Decoded with .convertFromSnakeCase.

import Foundation

// Enumerations: Platform (26). Every enum decodes unknown values to `.unknown`.

// MARK: - NotificationKind

/// Notification types (creator, brand and admin).
enum NotificationKind: String, Codable, Hashable, Sendable, CaseIterable {
    case approval = "approval"
    case changesRequested = "changes_requested"
    case rejection = "rejection"
    case appealDecided = "appeal_decided"
    case postLive = "post_live"
    case viewsMilestone = "views_milestone"
    case cashEvent = "cash_event"
    case payoutCleared = "payout_cleared"
    case payoutPaid = "payout_paid"
    case payoutHeld = "payout_held"
    case tierUp = "tier_up"
    case streakMilestone = "streak_milestone"
    case streakFreezeUsed = "streak_freeze_used"
    case dropLive = "drop_live"
    case dropReminder = "drop_reminder"
    case offerReceived = "offer_received"
    case offerCountered = "offer_countered"
    case offerAccepted = "offer_accepted"
    case tournamentUpdate = "tournament_update"
    case crewInvite = "crew_invite"
    case rightsExpiring = "rights_expiring"
    case rightsRenewed = "rights_renewed"
    case fatigueAlert = "fatigue_alert"
    case reviewWaiting = "review_waiting"
    case reviewSlaWarning = "review_sla_warning"
    case bountyFilled = "bounty_filled"
    case bountyFunded = "bounty_funded"
    case fundingNeeded = "funding_needed"
    case autoApprovePaused = "auto_approve_paused"
    case adLive = "ad_live"
    case disputeUpdate = "dispute_update"
    case taxInfoNeeded = "tax_info_needed"
    case scamWarning = "scam_warning"
    case floTip = "flo_tip"
    case academyBadge = "academy_badge"
    case referralJoined = "referral_joined"
    case systemNotice = "system_notice"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [NotificationKind] {
        return [.approval, .changesRequested, .rejection, .appealDecided, .postLive, .viewsMilestone, .cashEvent, .payoutCleared, .payoutPaid, .payoutHeld, .tierUp, .streakMilestone, .streakFreezeUsed, .dropLive, .dropReminder, .offerReceived, .offerCountered, .offerAccepted, .tournamentUpdate, .crewInvite, .rightsExpiring, .rightsRenewed, .fatigueAlert, .reviewWaiting, .reviewSlaWarning, .bountyFilled, .bountyFunded, .fundingNeeded, .autoApprovePaused, .adLive, .disputeUpdate, .taxInfoNeeded, .scamWarning, .floTip, .academyBadge, .referralJoined, .systemNotice]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = NotificationKind(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .approval: return "Approved"
        case .changesRequested: return "Changes requested"
        case .rejection: return "Not approved"
        case .appealDecided: return "Appeal decided"
        case .postLive: return "Views counting"
        case .viewsMilestone: return "Views milestone"
        case .cashEvent: return "You earned"
        case .payoutCleared: return "Cleared"
        case .payoutPaid: return "Payout sent"
        case .payoutHeld: return "Payout held"
        case .tierUp: return "Tier up"
        case .streakMilestone: return "Streak milestone"
        case .streakFreezeUsed: return "Freeze used"
        case .dropLive: return "Daily Drop is live"
        case .dropReminder: return "Drop soon"
        case .offerReceived: return "New offer"
        case .offerCountered: return "Counter-offer"
        case .offerAccepted: return "Offer accepted"
        case .tournamentUpdate: return "Tournament update"
        case .crewInvite: return "Crew invite"
        case .rightsExpiring: return "Rights expiring"
        case .rightsRenewed: return "Rights renewed"
        case .fatigueAlert: return "Fatigue alert"
        case .reviewWaiting: return "Review waiting"
        case .reviewSlaWarning: return "Review SLA"
        case .bountyFilled: return "Bounty filled"
        case .bountyFunded: return "Bounty funded"
        case .fundingNeeded: return "Funding needed"
        case .autoApprovePaused: return "Auto-approve paused"
        case .adLive: return "Promoted"
        case .disputeUpdate: return "Dispute update"
        case .taxInfoNeeded: return "Tax info needed"
        case .scamWarning: return "Scam warning"
        case .floTip: return "Flo tip"
        case .academyBadge: return "Badge earned"
        case .referralJoined: return "Referral joined"
        case .systemNotice: return "Notice"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .approval: return .mint
        case .changesRequested: return .ember
        case .rejection: return .rose
        case .appealDecided: return .info
        case .postLive: return .info
        case .viewsMilestone: return .info
        case .cashEvent: return .mint
        case .payoutCleared: return .mint
        case .payoutPaid: return .mint
        case .payoutHeld: return .ember
        case .tierUp: return .sun
        case .streakMilestone: return .mint
        case .streakFreezeUsed: return .info
        case .dropLive: return .ember
        case .dropReminder: return .info
        case .offerReceived: return .sun
        case .offerCountered: return .ember
        case .offerAccepted: return .mint
        case .tournamentUpdate: return .info
        case .crewInvite: return .info
        case .rightsExpiring: return .ember
        case .rightsRenewed: return .mint
        case .fatigueAlert: return .ember
        case .reviewWaiting: return .info
        case .reviewSlaWarning: return .ember
        case .bountyFilled: return .mint
        case .bountyFunded: return .mint
        case .fundingNeeded: return .ember
        case .autoApprovePaused: return .ember
        case .adLive: return .accent
        case .disputeUpdate: return .info
        case .taxInfoNeeded: return .ember
        case .scamWarning: return .rose
        case .floTip: return .violet
        case .academyBadge: return .accent
        case .referralJoined: return .mint
        case .systemNotice: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .approval: return "A submission was approved."
        case .changesRequested: return "Timecoded feedback arrived."
        case .rejection: return "Rejected with reason code and evidence."
        case .appealDecided: return "Ops decided an appeal."
        case .postLive: return "A post entered its 72-hour window."
        case .viewsMilestone: return "Batched milestone, not a vanity ping."
        case .cashEvent: return "\"You just earned +$24\": a cash event."
        case .payoutCleared: return "Earnings cleared to the Wallet."
        case .payoutPaid: return "A payout is on its way or arrived."
        case .payoutHeld: return "A hold with a named reason."
        case .tierUp: return "A new tier."
        case .streakMilestone: return "A streak milestone. Never a guilt reminder."
        case .streakFreezeUsed: return "A banked freeze covered a week."
        case .dropLive: return "The 16:00 UTC drop is live."
        case .dropReminder: return "Opt-in reminder before the drop."
        case .offerReceived: return "A direct offer or invite arrived."
        case .offerCountered: return "The other side countered."
        case .offerAccepted: return "An offer was accepted."
        case .tournamentUpdate: return "Round results or prizes."
        case .crewInvite: return "Invited to a crew."
        case .rightsExpiring: return "A licence ends in 30, 14 or 7 days."
        case .rightsRenewed: return "A licence was renewed; a renewal fee is coming."
        case .fatigueAlert: return "A winner is decaying."
        case .reviewWaiting: return "Submissions are waiting in the queue."
        case .reviewSlaWarning: return "A submission is stale or about to breach 72 hours."
        case .bountyFilled: return "A bounty filled."
        case .bountyFunded: return "Escrow is funded; the bounty is live."
        case .fundingNeeded: return "Wallet is short for a bounty or a commission."
        case .autoApprovePaused: return "A rule paused after a fraud event or spot-check failure."
        case .adLive: return "A post is running as an ad."
        case .disputeUpdate: return "A reply or decision on a dispute."
        case .taxInfoNeeded: return "Add a W-9 to release a payout."
        case .scamWarning: return "A contextual Scam Shield warning."
        case .floTip: return "A tip from Flo."
        case .academyBadge: return "An Academy lesson badge."
        case .referralJoined: return "Someone you invited joined."
        case .systemNotice: return "Product or policy notice."
        case .unknown: return nil
        }
    }
}

// MARK: - NotificationPriority

/// Delivery priority (quiet hours batch non-cash items).
enum NotificationPriority: String, Codable, Hashable, Sendable, CaseIterable {
    case cash = "cash"
    case normal = "normal"
    case digest = "digest"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [NotificationPriority] {
        return [.cash, .normal, .digest]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = NotificationPriority(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .cash: return "Cash event"
        case .normal: return "Normal"
        case .digest: return "Digest"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .cash: return .mint
        case .normal: return .neutral
        case .digest: return .info
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .cash: return "Delivered immediately outside quiet hours; batched inside them."
        case .normal: return "Standard."
        case .digest: return "Batched into a daily or weekly digest."
        case .unknown: return nil
        }
    }
}

// MARK: - IntegrationKind

/// Brand integrations (adapter + mock in this build).
enum IntegrationKind: String, Codable, Hashable, Sendable, CaseIterable {
    case revenuecat = "revenuecat"
    case appsflyer = "appsflyer"
    case adjust = "adjust"
    case branch = "branch"
    case metaAds = "meta_ads"
    case tiktokAds = "tiktok_ads"
    case slack = "slack"
    case zapier = "zapier"
    case appStoreConnect = "app_store_connect"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [IntegrationKind] {
        return [.revenuecat, .appsflyer, .adjust, .branch, .metaAds, .tiktokAds, .slack, .zapier, .appStoreConnect]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = IntegrationKind(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .revenuecat: return "RevenueCat"
        case .appsflyer: return "AppsFlyer"
        case .adjust: return "Adjust"
        case .branch: return "Branch"
        case .metaAds: return "Meta Ads"
        case .tiktokAds: return "TikTok Ads"
        case .slack: return "Slack"
        case .zapier: return "Zapier"
        case .appStoreConnect: return "App Store Connect"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .revenuecat: return .neutral
        case .appsflyer: return .neutral
        case .adjust: return .neutral
        case .branch: return .neutral
        case .metaAds: return .neutral
        case .tiktokAds: return .neutral
        case .slack: return .neutral
        case .zapier: return .neutral
        case .appStoreConnect: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .revenuecat: return "Webhook ingest for trials and revenue."
        case .appsflyer: return "MMP."
        case .adjust: return "MMP."
        case .branch: return "MMP."
        case .metaAds: return "Partnership-ad permissions and ad accounts."
        case .tiktokAds: return "Spark codes and ad accounts."
        case .slack: return "Approvals, digests and alerts."
        case .zapier: return "Webhook-based automations."
        case .appStoreConnect: return "Listing metadata and offer codes."
        case .unknown: return nil
        }
    }
}

// MARK: - IntegrationStatus

/// Integration health.
enum IntegrationStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case connected = "connected"
    case needsAttention = "needs_attention"
    case disconnected = "disconnected"
    case error = "error"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [IntegrationStatus] {
        return [.connected, .needsAttention, .disconnected, .error]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = IntegrationStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .connected: return "Connected"
        case .needsAttention: return "Needs attention"
        case .disconnected: return "Not connected"
        case .error: return "Error"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .connected: return .mint
        case .needsAttention: return .ember
        case .disconnected: return .neutral
        case .error: return .rose
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .connected: return "Working."
        case .needsAttention: return "Degraded: stale sync or expiring token."
        case .disconnected: return "Not set up."
        case .error: return "Failing."
        case .unknown: return nil
        }
    }
}

// MARK: - ApiScope

/// API key scopes.
enum ApiScope: String, Codable, Hashable, Sendable, CaseIterable {
    case read = "read"
    case write = "write"
    case financial = "financial"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [ApiScope] {
        return [.read, .write, .financial]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = ApiScope(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .read: return "Read"
        case .write: return "Write"
        case .financial: return "Financial"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .read: return .neutral
        case .write: return .accent
        case .financial: return .sun
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .read: return "Read bounties, submissions, metrics."
        case .write: return "Create drafts, comment, decide submissions. Writes are drafts by default."
        case .financial: return "Fund, spend and pay. Separate scope and separate approval."
        case .unknown: return nil
        }
    }
}

// MARK: - KeyMode

/// API key mode.
enum KeyMode: String, Codable, Hashable, Sendable, CaseIterable {
    case live = "live"
    case test = "test"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [KeyMode] {
        return [.live, .test]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = KeyMode(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .live: return "Live"
        case .test: return "Test"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .live: return .mint
        case .test: return .info
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .live: return "Real money in production."
        case .test: return "Sandbox."
        case .unknown: return nil
        }
    }
}

// MARK: - WebhookStatus

/// Webhook endpoint health.
enum WebhookStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case active = "active"
    case paused = "paused"
    case failing = "failing"
    case disabled = "disabled"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [WebhookStatus] {
        return [.active, .paused, .failing, .disabled]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = WebhookStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .active: return "Active"
        case .paused: return "Paused"
        case .failing: return "Failing"
        case .disabled: return "Disabled"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .active: return .mint
        case .paused: return .neutral
        case .failing: return .ember
        case .disabled: return .rose
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .active: return "Delivering."
        case .paused: return "Paused by the brand."
        case .failing: return "Recent deliveries are failing and retrying."
        case .disabled: return "Disabled after repeated failures."
        case .unknown: return nil
        }
    }
}

// MARK: - DeliveryStatus

/// Webhook delivery result.
enum DeliveryStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case delivered = "delivered"
    case failed = "failed"
    case retrying = "retrying"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [DeliveryStatus] {
        return [.delivered, .failed, .retrying]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = DeliveryStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .delivered: return "Delivered"
        case .failed: return "Failed"
        case .retrying: return "Retrying"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .delivered: return .mint
        case .failed: return .rose
        case .retrying: return .ember
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .delivered: return "2xx."
        case .failed: return "Non-2xx or timeout."
        case .retrying: return "Backing off."
        case .unknown: return nil
        }
    }
}

// MARK: - WebhookEventType

/// Events brands can subscribe to.
enum WebhookEventType: String, Codable, Hashable, Sendable, CaseIterable {
    case bountyFunded = "bounty_funded"
    case bountyLive = "bounty_live"
    case bountyFilled = "bounty_filled"
    case bountyEnded = "bounty_ended"
    case submissionCreated = "submission_created"
    case submissionApproved = "submission_approved"
    case submissionChangesRequested = "submission_changes_requested"
    case submissionRejected = "submission_rejected"
    case postLive = "post_live"
    case postWindowClosed = "post_window_closed"
    case postCleared = "post_cleared"
    case conversionTracked = "conversion_tracked"
    case adLive = "ad_live"
    case adFatigued = "ad_fatigued"
    case rightsExpiring = "rights_expiring"
    case disputeOpened = "dispute_opened"
    case invoicePaid = "invoice_paid"
    case walletLow = "wallet_low"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [WebhookEventType] {
        return [.bountyFunded, .bountyLive, .bountyFilled, .bountyEnded, .submissionCreated, .submissionApproved, .submissionChangesRequested, .submissionRejected, .postLive, .postWindowClosed, .postCleared, .conversionTracked, .adLive, .adFatigued, .rightsExpiring, .disputeOpened, .invoicePaid, .walletLow]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = WebhookEventType(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .bountyFunded: return "Bounty funded"
        case .bountyLive: return "Bounty live"
        case .bountyFilled: return "Bounty filled"
        case .bountyEnded: return "Bounty ended"
        case .submissionCreated: return "Submission created"
        case .submissionApproved: return "Submission approved"
        case .submissionChangesRequested: return "Changes requested"
        case .submissionRejected: return "Submission rejected"
        case .postLive: return "Post live"
        case .postWindowClosed: return "Window closed"
        case .postCleared: return "Post cleared"
        case .conversionTracked: return "Conversion tracked"
        case .adLive: return "Ad live"
        case .adFatigued: return "Ad fatigued"
        case .rightsExpiring: return "Rights expiring"
        case .disputeOpened: return "Dispute opened"
        case .invoicePaid: return "Invoice paid"
        case .walletLow: return "Wallet low"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .bountyFunded: return .neutral
        case .bountyLive: return .neutral
        case .bountyFilled: return .neutral
        case .bountyEnded: return .neutral
        case .submissionCreated: return .neutral
        case .submissionApproved: return .neutral
        case .submissionChangesRequested: return .neutral
        case .submissionRejected: return .neutral
        case .postLive: return .neutral
        case .postWindowClosed: return .neutral
        case .postCleared: return .neutral
        case .conversionTracked: return .neutral
        case .adLive: return .neutral
        case .adFatigued: return .neutral
        case .rightsExpiring: return .neutral
        case .disputeOpened: return .neutral
        case .invoicePaid: return .neutral
        case .walletLow: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .bountyFunded: return "Escrow fully funded."
        case .bountyLive: return "Went live."
        case .bountyFilled: return "Budget fully reserved."
        case .bountyEnded: return "Ended."
        case .submissionCreated: return "A creator submitted."
        case .submissionApproved: return "Approved (manual or auto)."
        case .submissionChangesRequested: return "Revision requested."
        case .submissionRejected: return "Rejected."
        case .postLive: return "A post entered its window."
        case .postWindowClosed: return "The 72-hour window closed."
        case .postCleared: return "Checks passed; earnings cleared."
        case .conversionTracked: return "An install, trial or paid conversion was attributed."
        case .adLive: return "A promoted ad started."
        case .adFatigued: return "Fatigue detected."
        case .rightsExpiring: return "A licence ends soon."
        case .disputeOpened: return "A dispute was opened."
        case .invoicePaid: return "An invoice was paid."
        case .walletLow: return "Wallet below the auto top-up threshold."
        case .unknown: return nil
        }
    }
}

// MARK: - ActivityAction

/// Team activity log actions.
enum ActivityAction: String, Codable, Hashable, Sendable, CaseIterable {
    case bountyCreated = "bounty_created"
    case bountyPublished = "bounty_published"
    case bountyFunded = "bounty_funded"
    case bountyPaused = "bounty_paused"
    case bountyEnded = "bounty_ended"
    case submissionApproved = "submission_approved"
    case submissionChangesRequested = "submission_changes_requested"
    case submissionRejected = "submission_rejected"
    case ruleCreated = "rule_created"
    case ruleEnabled = "rule_enabled"
    case ruleKilled = "rule_killed"
    case memberInvited = "member_invited"
    case memberRoleChanged = "member_role_changed"
    case memberRemoved = "member_removed"
    case apiKeyCreated = "api_key_created"
    case apiKeyRevoked = "api_key_revoked"
    case webhookCreated = "webhook_created"
    case integrationConnected = "integration_connected"
    case integrationDisconnected = "integration_disconnected"
    case planChanged = "plan_changed"
    case walletToppedUp = "wallet_topped_up"
    case autoTopupChanged = "auto_topup_changed"
    case adPromoted = "ad_promoted"
    case rightsRenewed = "rights_renewed"
    case offerSent = "offer_sent"
    case offerAccepted = "offer_accepted"
    case disputeResponded = "dispute_responded"
    case exportCreated = "export_created"
    case invoiceDownloaded = "invoice_downloaded"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [ActivityAction] {
        return [.bountyCreated, .bountyPublished, .bountyFunded, .bountyPaused, .bountyEnded, .submissionApproved, .submissionChangesRequested, .submissionRejected, .ruleCreated, .ruleEnabled, .ruleKilled, .memberInvited, .memberRoleChanged, .memberRemoved, .apiKeyCreated, .apiKeyRevoked, .webhookCreated, .integrationConnected, .integrationDisconnected, .planChanged, .walletToppedUp, .autoTopupChanged, .adPromoted, .rightsRenewed, .offerSent, .offerAccepted, .disputeResponded, .exportCreated, .invoiceDownloaded]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = ActivityAction(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .bountyCreated: return "Created a bounty"
        case .bountyPublished: return "Published a bounty"
        case .bountyFunded: return "Funded a bounty"
        case .bountyPaused: return "Paused a bounty"
        case .bountyEnded: return "Ended a bounty"
        case .submissionApproved: return "Approved a submission"
        case .submissionChangesRequested: return "Requested changes"
        case .submissionRejected: return "Rejected a submission"
        case .ruleCreated: return "Created an auto-approve rule"
        case .ruleEnabled: return "Enabled an auto-approve rule"
        case .ruleKilled: return "Used the kill switch"
        case .memberInvited: return "Invited a teammate"
        case .memberRoleChanged: return "Changed a role"
        case .memberRemoved: return "Removed a teammate"
        case .apiKeyCreated: return "Created an API key"
        case .apiKeyRevoked: return "Revoked an API key"
        case .webhookCreated: return "Added a webhook"
        case .integrationConnected: return "Connected an integration"
        case .integrationDisconnected: return "Disconnected an integration"
        case .planChanged: return "Changed plan"
        case .walletToppedUp: return "Topped up the wallet"
        case .autoTopupChanged: return "Changed auto top-up"
        case .adPromoted: return "Promoted a winner"
        case .rightsRenewed: return "Renewed rights"
        case .offerSent: return "Sent an offer"
        case .offerAccepted: return "Accepted an offer"
        case .disputeResponded: return "Responded to a dispute"
        case .exportCreated: return "Exported data"
        case .invoiceDownloaded: return "Downloaded an invoice"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .bountyCreated: return .neutral
        case .bountyPublished: return .neutral
        case .bountyFunded: return .neutral
        case .bountyPaused: return .neutral
        case .bountyEnded: return .neutral
        case .submissionApproved: return .neutral
        case .submissionChangesRequested: return .neutral
        case .submissionRejected: return .neutral
        case .ruleCreated: return .neutral
        case .ruleEnabled: return .neutral
        case .ruleKilled: return .neutral
        case .memberInvited: return .neutral
        case .memberRoleChanged: return .neutral
        case .memberRemoved: return .neutral
        case .apiKeyCreated: return .neutral
        case .apiKeyRevoked: return .neutral
        case .webhookCreated: return .neutral
        case .integrationConnected: return .neutral
        case .integrationDisconnected: return .neutral
        case .planChanged: return .neutral
        case .walletToppedUp: return .neutral
        case .autoTopupChanged: return .neutral
        case .adPromoted: return .neutral
        case .rightsRenewed: return .neutral
        case .offerSent: return .neutral
        case .offerAccepted: return .neutral
        case .disputeResponded: return .neutral
        case .exportCreated: return .neutral
        case .invoiceDownloaded: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .bountyCreated: return "Logged when a teammate created a bounty."
        case .bountyPublished: return "Logged when a teammate published a bounty."
        case .bountyFunded: return "Logged when a teammate funded a bounty."
        case .bountyPaused: return "Logged when a teammate paused a bounty."
        case .bountyEnded: return "Logged when a teammate ended a bounty."
        case .submissionApproved: return "Logged when a teammate approved a submission."
        case .submissionChangesRequested: return "Logged when a teammate requested changes."
        case .submissionRejected: return "Logged when a teammate rejected a submission."
        case .ruleCreated: return "Logged when a teammate created an auto-approve rule."
        case .ruleEnabled: return "Logged when a teammate enabled an auto-approve rule."
        case .ruleKilled: return "Logged when a teammate used the kill switch."
        case .memberInvited: return "Logged when a teammate invited a teammate."
        case .memberRoleChanged: return "Logged when a teammate changed a role."
        case .memberRemoved: return "Logged when a teammate removed a teammate."
        case .apiKeyCreated: return "Logged when a teammate created an API key."
        case .apiKeyRevoked: return "Logged when a teammate revoked an API key."
        case .webhookCreated: return "Logged when a teammate added a webhook."
        case .integrationConnected: return "Logged when a teammate connected an integration."
        case .integrationDisconnected: return "Logged when a teammate disconnected an integration."
        case .planChanged: return "Logged when a teammate changed plan."
        case .walletToppedUp: return "Logged when a teammate topped up the wallet."
        case .autoTopupChanged: return "Logged when a teammate changed auto top-up."
        case .adPromoted: return "Logged when a teammate promoted a winner."
        case .rightsRenewed: return "Logged when a teammate renewed rights."
        case .offerSent: return "Logged when a teammate sent an offer."
        case .offerAccepted: return "Logged when a teammate accepted an offer."
        case .disputeResponded: return "Logged when a teammate responded to a dispute."
        case .exportCreated: return "Logged when a teammate exported data."
        case .invoiceDownloaded: return "Logged when a teammate downloaded an invoice."
        case .unknown: return nil
        }
    }
}

// MARK: - RuleStatus

/// Auto-approve rule lifecycle (dry run is mandatory before enabling).
enum RuleStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case draft = "draft"
    case dryRun = "dry_run"
    case active = "active"
    case paused = "paused"
    case killed = "killed"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [RuleStatus] {
        return [.draft, .dryRun, .active, .paused, .killed]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = RuleStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .draft: return "Draft"
        case .dryRun: return "Dry run"
        case .active: return "Active"
        case .paused: return "Paused"
        case .killed: return "Killed"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .draft: return .neutral
        case .dryRun: return .info
        case .active: return .mint
        case .paused: return .ember
        case .killed: return .rose
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .draft: return "Being configured."
        case .dryRun: return "Shows what would have been approved among the last 50 submissions."
        case .active: return "Auto-approving within guardrails; 10% spot-checked by a human."
        case .paused: return "Paused by the brand or by a guardrail."
        case .killed: return "Kill switch used; needs a fresh dry run to re-enable."
        case .unknown: return nil
        }
    }
}

// MARK: - TestPlanStatus

/// Hook x body x CTA test plan state.
enum TestPlanStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case draft = "draft"
    case running = "running"
    case complete = "complete"
    case archived = "archived"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [TestPlanStatus] {
        return [.draft, .running, .complete, .archived]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = TestPlanStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .draft: return "Draft"
        case .running: return "Running"
        case .complete: return "Complete"
        case .archived: return "Archived"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .draft: return .neutral
        case .running: return .accent
        case .complete: return .mint
        case .archived: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .draft: return "Matrix being built."
        case .running: return "Cells in production or live."
        case .complete: return "Results measured; winners picked."
        case .archived: return "Archived."
        case .unknown: return nil
        }
    }
}

// MARK: - TestCellStatus

/// One cell (hook x body x CTA) of a plan.
enum TestCellStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case planned = "planned"
    case briefed = "briefed"
    case submitted = "submitted"
    case live = "live"
    case measured = "measured"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [TestCellStatus] {
        return [.planned, .briefed, .submitted, .live, .measured]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = TestCellStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .planned: return "Planned"
        case .briefed: return "Briefed"
        case .submitted: return "Submitted"
        case .live: return "Live"
        case .measured: return "Measured"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .planned: return .neutral
        case .briefed: return .info
        case .submitted: return .info
        case .live: return .accent
        case .measured: return .mint
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .planned: return "Not briefed."
        case .briefed: return "Sent to a creator or bounty."
        case .submitted: return "Video received."
        case .live: return "Posted and counting."
        case .measured: return "Results in."
        case .unknown: return nil
        }
    }
}

// MARK: - FatigueStatus

/// Fatigue alert lifecycle.
enum FatigueStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case open = "open"
    case acknowledged = "acknowledged"
    case refreshing = "refreshing"
    case resolved = "resolved"
    case dismissed = "dismissed"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [FatigueStatus] {
        return [.open, .acknowledged, .refreshing, .resolved, .dismissed]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = FatigueStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .open: return "Open"
        case .acknowledged: return "Acknowledged"
        case .refreshing: return "Refreshing"
        case .resolved: return "Resolved"
        case .dismissed: return "Dismissed"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .open: return .ember
        case .acknowledged: return .info
        case .refreshing: return .accent
        case .resolved: return .mint
        case .dismissed: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .open: return "A winner dropped 30% from its peak."
        case .acknowledged: return "Seen by the brand."
        case .refreshing: return "A refresh bounty was created."
        case .resolved: return "Recovered or replaced."
        case .dismissed: return "Dismissed."
        case .unknown: return nil
        }
    }
}

// MARK: - FatigueMetric

/// Which metric decayed.
enum FatigueMetric: String, Codable, Hashable, Sendable, CaseIterable {
    case trialRate = "trial_rate"
    case ctr = "ctr"
    case installRate = "install_rate"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [FatigueMetric] {
        return [.trialRate, .ctr, .installRate]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = FatigueMetric(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .trialRate: return "Trial-start rate"
        case .ctr: return "Click-through"
        case .installRate: return "Installs per 1,000 views"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .trialRate: return .neutral
        case .ctr: return .neutral
        case .installRate: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .trialRate: return "Trials per install."
        case .ctr: return "Clicks per impression (promoted ads)."
        case .installRate: return "Install yield."
        case .unknown: return nil
        }
    }
}

// MARK: - FloKind

/// Flo copilot output kinds.
enum FloKind: String, Codable, Hashable, Sendable, CaseIterable {
    case script = "script"
    case hookRewrite = "hook_rewrite"
    case briefTldr = "brief_tldr"
    case caption = "caption"
    case scoreFix = "score_fix"
    case rateAdvice = "rate_advice"
    case nextAction = "next_action"
    case bountyDraft = "bounty_draft"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [FloKind] {
        return [.script, .hookRewrite, .briefTldr, .caption, .scoreFix, .rateAdvice, .nextAction, .bountyDraft]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = FloKind(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .script: return "Script"
        case .hookRewrite: return "Hook rewrite"
        case .briefTldr: return "Brief TL;DR"
        case .caption: return "Caption"
        case .scoreFix: return "Score fix"
        case .rateAdvice: return "Rate advice"
        case .nextAction: return "Next action"
        case .bountyDraft: return "Bounty draft"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .script: return .violet
        case .hookRewrite: return .violet
        case .briefTldr: return .violet
        case .caption: return .violet
        case .scoreFix: return .violet
        case .rateAdvice: return .violet
        case .nextAction: return .violet
        case .bountyDraft: return .violet
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .script: return "Three script options for a format and brief."
        case .hookRewrite: return "Rewrites a hook."
        case .briefTldr: return "Short brief summary."
        case .caption: return "Caption ideas with #ad."
        case .scoreFix: return "One-tap fixes for checklist misses."
        case .rateAdvice: return "Rate-card suggestion with the market range."
        case .nextAction: return "What to do next."
        case .bountyDraft: return "Brief, hooks and pay drafted from an App Store page."
        case .unknown: return nil
        }
    }
}

// MARK: - FloSurface

/// Where Flo appears.
enum FloSurface: String, Codable, Hashable, Sendable, CaseIterable {
    case studio = "studio"
    case bountyDetail = "bounty_detail"
    case home = "home"
    case wallet = "wallet"
    case rateCard = "rate_card"
    case builder = "builder"
    case review = "review"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [FloSurface] {
        return [.studio, .bountyDetail, .home, .wallet, .rateCard, .builder, .review]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = FloSurface(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .studio: return "Studio"
        case .bountyDetail: return "Bounty detail"
        case .home: return "Home"
        case .wallet: return "Wallet"
        case .rateCard: return "Rate card"
        case .builder: return "Bounty builder"
        case .review: return "Review"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .studio: return .neutral
        case .bountyDetail: return .neutral
        case .home: return .neutral
        case .wallet: return .neutral
        case .rateCard: return .neutral
        case .builder: return .neutral
        case .review: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .studio: return "Script and hook coach."
        case .bountyDetail: return "TL;DR."
        case .home: return "Next action."
        case .wallet: return "Explaining holds and ETAs."
        case .rateCard: return "Price advice."
        case .builder: return "Brand-side drafting."
        case .review: return "Brand-side review assist."
        case .unknown: return nil
        }
    }
}

// MARK: - ModelKind

/// The eight ML systems.
enum ModelKind: String, Codable, Hashable, Sendable, CaseIterable {
    case videoUnderstanding = "video_understanding"
    case hookCoach = "hook_coach"
    case autoQa = "auto_qa"
    case fraud = "fraud"
    case creativeScorer = "creative_scorer"
    case matching = "matching"
    case pricing = "pricing"
    case fatigue = "fatigue"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [ModelKind] {
        return [.videoUnderstanding, .hookCoach, .autoQa, .fraud, .creativeScorer, .matching, .pricing, .fatigue]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = ModelKind(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .videoUnderstanding: return "Video understanding"
        case .hookCoach: return "Hook coach"
        case .autoQa: return "Auto-QA"
        case .fraud: return "View-fraud detection"
        case .creativeScorer: return "Creative scorer"
        case .matching: return "Matching"
        case .pricing: return "Pricing model"
        case .fatigue: return "Fatigue detection"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .videoUnderstanding: return .violet
        case .hookCoach: return .violet
        case .autoQa: return .violet
        case .fraud: return .violet
        case .creativeScorer: return .violet
        case .matching: return .violet
        case .pricing: return .violet
        case .fatigue: return .violet
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .videoUnderstanding: return "Transcript, scenes, on-screen text, embeddings."
        case .hookCoach: return "On-device first-3-seconds checks."
        case .autoQa: return "Brief, disclosure, duplicate and moderation checks."
        case .fraud: return "Post view curves and account history to a risk score."
        case .creativeScorer: return "Predicted views band and install rate."
        case .matching: return "Ranks the bounty feed for each creator."
        case .pricing: return "Suggested CPM and fill time."
        case .fatigue: return "Refresh alerts."
        case .unknown: return nil
        }
    }
}

// MARK: - ModelStage

/// How a model currently runs.
enum ModelStage: String, Codable, Hashable, Sendable, CaseIterable {
    case heuristic = "heuristic"
    case shadow = "shadow"
    case learned = "learned"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [ModelStage] {
        return [.heuristic, .shadow, .learned]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = ModelStage(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .heuristic: return "Heuristic"
        case .shadow: return "Shadow"
        case .learned: return "Learned"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .heuristic: return .neutral
        case .shadow: return .info
        case .learned: return .mint
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .heuristic: return "Rules or checklist (day one)."
        case .shadow: return "A learned model runs beside the heuristic, unused."
        case .learned: return "The learned model is live."
        case .unknown: return nil
        }
    }
}

// MARK: - ThreadKind

/// What a chat thread is attached to.
enum ThreadKind: String, Codable, Hashable, Sendable, CaseIterable {
    case offer = "offer"
    case submission = "submission"
    case bounty = "bounty"
    case support = "support"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [ThreadKind] {
        return [.offer, .submission, .bounty, .support]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = ThreadKind(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .offer: return "Offer"
        case .submission: return "Submission"
        case .bounty: return "Bounty"
        case .support: return "Support"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .offer: return .neutral
        case .submission: return .neutral
        case .bounty: return .neutral
        case .support: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .offer: return "A direct offer."
        case .submission: return "A submission."
        case .bounty: return "A bounty (creator questions)."
        case .support: return "flowd support."
        case .unknown: return nil
        }
    }
}

// MARK: - MessageKind

/// Chat message kind.
enum MessageKind: String, Codable, Hashable, Sendable, CaseIterable {
    case text = "text"
    case system = "system"
    case warning = "warning"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [MessageKind] {
        return [.text, .system, .warning]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = MessageKind(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .text: return "Text"
        case .system: return "System"
        case .warning: return "Scam Shield warning"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .text: return .neutral
        case .system: return .neutral
        case .warning: return .rose
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .text: return "A person wrote it."
        case .system: return "A system note."
        case .warning: return "A contextual warning (e.g. asked to move off-platform)."
        case .unknown: return nil
        }
    }
}

// MARK: - SaveStage

/// A creator's relationship to a bounty.
enum SaveStage: String, Codable, Hashable, Sendable, CaseIterable {
    case saved = "saved"
    case joined = "joined"
    case submitted = "submitted"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [SaveStage] {
        return [.saved, .joined, .submitted]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = SaveStage(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .saved: return "Saved"
        case .joined: return "Joined"
        case .submitted: return "Submitted"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .saved: return .neutral
        case .joined: return .info
        case .submitted: return .accent
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .saved: return "Bookmarked."
        case .joined: return "Started in Studio."
        case .submitted: return "Submitted."
        case .unknown: return nil
        }
    }
}

// MARK: - ChangelogTag

/// Changelog tags.
enum ChangelogTag: String, Codable, Hashable, Sendable, CaseIterable {
    case new = "new"
    case improved = "improved"
    case fix = "fix"
    case trust = "trust"
    case money = "money"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [ChangelogTag] {
        return [.new, .improved, .fix, .trust, .money]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = ChangelogTag(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .new: return "New"
        case .improved: return "Improved"
        case .fix: return "Fix"
        case .trust: return "Trust"
        case .money: return "Money"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .new: return .accent
        case .improved: return .info
        case .fix: return .neutral
        case .trust: return .mint
        case .money: return .mint
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .new: return "New feature."
        case .improved: return "Improvement."
        case .fix: return "Bug fix."
        case .trust: return "Trust and safety."
        case .money: return "Payments and payouts."
        case .unknown: return nil
        }
    }
}

// MARK: - MetricStatus

/// Admin day-90 target status.
enum MetricStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case achieved = "achieved"
    case onTrack = "on_track"
    case atRisk = "at_risk"
    case offTrack = "off_track"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [MetricStatus] {
        return [.achieved, .onTrack, .atRisk, .offTrack]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = MetricStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .achieved: return "Achieved"
        case .onTrack: return "On track"
        case .atRisk: return "At risk"
        case .offTrack: return "Off track"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .achieved: return .mint
        case .onTrack: return .accent
        case .atRisk: return .ember
        case .offTrack: return .rose
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .achieved: return "Target met."
        case .onTrack: return "Trending to the target."
        case .atRisk: return "Within 15% of missing."
        case .offTrack: return "Missing."
        case .unknown: return nil
        }
    }
}

// MARK: - SpendTier

/// Test planner matrix size by spend.
enum SpendTier: String, Codable, Hashable, Sendable, CaseIterable {
    case starter = "starter"
    case growth = "growth"
    case scale = "scale"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [SpendTier] {
        return [.starter, .growth, .scale]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = SpendTier(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .starter: return "Starter"
        case .growth: return "Growth"
        case .scale: return "Scale"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .starter: return .neutral
        case .growth: return .accent
        case .scale: return .sun
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .starter: return "Up to $1,000: 4 to 6 cells."
        case .growth: return "$1,000 to $5,000: 8 to 12 cells."
        case .scale: return "Over $5,000: 15 to 24 cells."
        case .unknown: return nil
        }
    }
}

// MARK: - RuleAuditAction

/// Entries in an auto-approve rule audit log.
enum RuleAuditAction: String, Codable, Hashable, Sendable, CaseIterable {
    case created = "created"
    case edited = "edited"
    case dryRun = "dry_run"
    case enabled = "enabled"
    case paused = "paused"
    case resumed = "resumed"
    case killed = "killed"
    case spotCheck = "spot_check"
    case spotCheckOverturned = "spot_check_overturned"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [RuleAuditAction] {
        return [.created, .edited, .dryRun, .enabled, .paused, .resumed, .killed, .spotCheck, .spotCheckOverturned]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = RuleAuditAction(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .created: return "Created"
        case .edited: return "Edited"
        case .dryRun: return "Dry run"
        case .enabled: return "Enabled"
        case .paused: return "Paused"
        case .resumed: return "Resumed"
        case .killed: return "Killed"
        case .spotCheck: return "Spot-check"
        case .spotCheckOverturned: return "Spot-check overturned"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .created: return .neutral
        case .edited: return .neutral
        case .dryRun: return .info
        case .enabled: return .mint
        case .paused: return .ember
        case .resumed: return .mint
        case .killed: return .rose
        case .spotCheck: return .info
        case .spotCheckOverturned: return .rose
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .created: return "Rule created."
        case .edited: return "Conditions or guardrails changed."
        case .dryRun: return "Dry run on the last 50 submissions."
        case .enabled: return "Enabled after a dry run."
        case .paused: return "Paused by the brand or a guardrail."
        case .resumed: return "Resumed."
        case .killed: return "Kill switch used."
        case .spotCheck: return "A human reviewed an auto-approved submission."
        case .spotCheckOverturned: return "A human disagreed with an auto-approval; the rule paused."
        case .unknown: return nil
        }
    }
}
