// GENERATED by scripts/gen-ios-models.mjs from packages/contract/schema/*.mjs. Do not edit by hand: change the schema, then run  node scripts/gen-ios-models.mjs
// Names, enum values and field types mirror packages/contract/DOMAIN.md sections 5 to 7. Decoded with .convertFromSnakeCase.

import Foundation

// Enumerations: Posts (6). Every enum decodes unknown values to `.unknown`.

// MARK: - PostStatus

/// Post lifecycle (CPM / flat leg). Conversions and ad commission settle on their own ledger rows.
enum PostStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case live = "live"
    case windowClosed = "window_closed"
    case held = "held"
    case cleared = "cleared"
    case paid = "paid"
    case removed = "removed"
    case clawedBack = "clawed_back"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [PostStatus] {
        return [.live, .windowClosed, .held, .cleared, .paid, .removed, .clawedBack]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = PostStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .live: return "Live"
        case .windowClosed: return "Window closed"
        case .held: return "Held"
        case .cleared: return "Cleared"
        case .paid: return "Paid"
        case .removed: return "Removed"
        case .clawedBack: return "Clawed back"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .live: return .info
        case .windowClosed: return .info
        case .held: return .ember
        case .cleared: return .mint
        case .paid: return .mint
        case .removed: return .neutral
        case .clawedBack: return .rose
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .live: return "Posted; the 72-hour view window is open. Earnings are pending and accruing."
        case .windowClosed: return "72 hours elapsed; the fraud and compliance check is running."
        case .held: return "A fraud, compliance or dispute hold. Reason shown; human decision within 24 hours."
        case .cleared: return "Checks passed. CPM earnings are cleared and wait for the weekly payout."
        case .paid: return "The CPM earnings were included in a payout."
        case .removed: return "Deleted before the window closed; earns nothing."
        case .clawedBack: return "Proven fraud: invalid views reversed (delivered legitimate views still paid)."
        case .unknown: return nil
        }
    }
}

// MARK: - HoldReason

/// Why money or a post is held.
enum HoldReason: String, Codable, Hashable, Sendable, CaseIterable {
    case fraudReview = "fraud_review"
    case disputeOpen = "dispute_open"
    case taxInfoMissing = "tax_info_missing"
    case identityCheck = "identity_check"
    case payoutMethodMissing = "payout_method_missing"
    case complianceFail = "compliance_fail"
    case adminHold = "admin_hold"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [HoldReason] {
        return [.fraudReview, .disputeOpen, .taxInfoMissing, .identityCheck, .payoutMethodMissing, .complianceFail, .adminHold]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = HoldReason(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .fraudReview: return "Fraud review"
        case .disputeOpen: return "Dispute open"
        case .taxInfoMissing: return "Tax info needed"
        case .identityCheck: return "ID check needed"
        case .payoutMethodMissing: return "Payout method needed"
        case .complianceFail: return "Disclosure check failed"
        case .adminHold: return "Manual hold"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .fraudReview: return .ember
        case .disputeOpen: return .ember
        case .taxInfoMissing: return .ember
        case .identityCheck: return .ember
        case .payoutMethodMissing: return .ember
        case .complianceFail: return .rose
        case .adminHold: return .rose
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .fraudReview: return "Fraud score 40 or above; a human review within 24 hours."
        case .disputeOpen: return "A dispute is open on the post or payout."
        case .taxInfoMissing: return "Add a W-9 (or W-8BEN) to release the payout."
        case .identityCheck: return "Identity verification is required before the first payout."
        case .payoutMethodMissing: return "Add a bank account or debit card."
        case .complianceFail: return "The posted video failed the disclosure audit."
        case .adminHold: return "Placed by Ops; the reason is shown to the creator."
        case .unknown: return nil
        }
    }
}

// MARK: - TrafficSource

/// Where views came from (View Ledger source breakdown).
enum TrafficSource: String, Codable, Hashable, Sendable, CaseIterable {
    case fyp = "fyp"
    case following = "following"
    case profile = "profile"
    case search = "search"
    case sound = "sound"
    case share = "share"
    case other = "other"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [TrafficSource] {
        return [.fyp, .following, .profile, .search, .sound, .share, .other]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = TrafficSource(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .fyp: return "For You / Explore"
        case .following: return "Following"
        case .profile: return "Profile"
        case .search: return "Search"
        case .sound: return "Sound page"
        case .share: return "Shares"
        case .other: return "Other / external"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .fyp: return .mint
        case .following: return .neutral
        case .profile: return .neutral
        case .search: return .neutral
        case .sound: return .neutral
        case .share: return .neutral
        case .other: return .ember
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .fyp: return "Recommendation feed."
        case .following: return "The creator's followers."
        case .profile: return "Profile visits."
        case .search: return "Search results."
        case .sound: return "Sound or audio page."
        case .share: return "Direct shares and DMs."
        case .other: return "External or unknown; a high share raises the fraud score."
        case .unknown: return nil
        }
    }
}

// MARK: - SnapshotSource

/// How a View Ledger snapshot was captured.
enum SnapshotSource: String, Codable, Hashable, Sendable, CaseIterable {
    case platformApi = "platform_api"
    case creatorScreenshot = "creator_screenshot"
    case manualAdjust = "manual_adjust"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [SnapshotSource] {
        return [.platformApi, .creatorScreenshot, .manualAdjust]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = SnapshotSource(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .platformApi: return "Platform API"
        case .creatorScreenshot: return "Screenshot proof"
        case .manualAdjust: return "Manual adjustment"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .platformApi: return .mint
        case .creatorScreenshot: return .info
        case .manualAdjust: return .ember
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .platformApi: return "Pulled from the TikTok / Instagram / YouTube API."
        case .creatorScreenshot: return "Creator-supplied screenshot checked by the fraud model (fallback)."
        case .manualAdjust: return "Ops corrected the count after a dispute."
        case .unknown: return nil
        }
    }
}

// MARK: - SnapshotFlag

/// Anomaly markers on a View Ledger snapshot.
enum SnapshotFlag: String, Codable, Hashable, Sendable, CaseIterable {
    case spike = "spike"
    case plateau = "plateau"
    case botPattern = "bot_pattern"
    case geoShift = "geo_shift"
    case reconciled = "reconciled"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [SnapshotFlag] {
        return [.spike, .plateau, .botPattern, .geoShift, .reconciled]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = SnapshotFlag(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .spike: return "Spike"
        case .plateau: return "Plateau"
        case .botPattern: return "Bot pattern"
        case .geoShift: return "Geo shift"
        case .reconciled: return "Reconciled"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .spike: return .ember
        case .plateau: return .info
        case .botPattern: return .rose
        case .geoShift: return .ember
        case .reconciled: return .mint
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .spike: return "Hourly views far above baseline."
        case .plateau: return "Views stopped growing."
        case .botPattern: return "Step-function curve typical of bought views."
        case .geoShift: return "Audience country mix changed abruptly."
        case .reconciled: return "Reported and verified counts agree after review."
        case .unknown: return nil
        }
    }
}

// MARK: - ExclusionCause

/// Why views were excluded from the verified count (View Ledger). Always shown in plain words.
enum ExclusionCause: String, Codable, Hashable, Sendable, CaseIterable {
    case botPattern = "bot_pattern"
    case capClustering = "cap_clustering"
    case duplicate = "duplicate"
    case geoOutlier = "geo_outlier"
    case removedPost = "removed_post"
    case platformAdjustment = "platform_adjustment"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [ExclusionCause] {
        return [.botPattern, .capClustering, .duplicate, .geoOutlier, .removedPost, .platformAdjustment]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = ExclusionCause(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .botPattern: return "Bot pattern"
        case .capClustering: return "Cap clustering"
        case .duplicate: return "Duplicate views"
        case .geoOutlier: return "Audience outside the target region"
        case .removedPost: return "Post removed"
        case .platformAdjustment: return "Platform adjustment"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .botPattern: return .rose
        case .capClustering: return .rose
        case .duplicate: return .ember
        case .geoOutlier: return .ember
        case .removedPost: return .neutral
        case .platformAdjustment: return .info
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .botPattern: return "Step-function curve typical of bought views."
        case .capClustering: return "Views snapped to the per-video cap."
        case .duplicate: return "The platform counted the same viewers twice, or a repost double-counted."
        case .geoOutlier: return "Views from outside the target regions of the bounty."
        case .removedPost: return "The post was deleted before the window closed."
        case .platformAdjustment: return "The platform itself revised its count (spam filtering)."
        case .unknown: return nil
        }
    }
}
