// GENERATED by scripts/gen-ios-models.mjs from packages/contract/schema/*.mjs. Do not edit by hand: change the schema, then run  node scripts/gen-ios-models.mjs
// Names, enum values and field types mirror packages/contract/DOMAIN.md sections 5 to 7. Decoded with .convertFromSnakeCase.

import Foundation

// Enumerations: Bounties (9). Every enum decodes unknown values to `.unknown`.

// MARK: - BountyType

/// How a bounty pays.
enum BountyType: String, Codable, Hashable, Sendable, CaseIterable {
    case cpm = "cpm"
    case cpa = "cpa"
    case stacked = "stacked"
    case direct = "direct"
    case installOnly = "install_only"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [BountyType] {
        return [.cpm, .cpa, .stacked, .direct, .installOnly]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = BountyType(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .cpm: return "Views (CPM)"
        case .cpa: return "Outcomes (CPA)"
        case .stacked: return "Stacked"
        case .direct: return "Direct"
        case .installOnly: return "Install-only"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .cpm: return .accent
        case .cpa: return .mint
        case .stacked: return .violet
        case .direct: return .sun
        case .installOnly: return .info
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .cpm: return "Pays per 1,000 verified views inside the 72-hour window, up to the per-video cap."
        case .cpa: return "Pays only per tracked install, trial or paid sub via link or code. Flat 6% fee on cleared conversions."
        case .stacked: return "CPM floor plus CPA bonuses (and ad commission if promoted) on the same video."
        case .direct: return "A private flat-fee bounty created when a brand buys from a rate card or wins an auction slot."
        case .installOnly: return "No view pay: installs only (trial and paid rates are 0). Risk-free for small teams. Flat 6% fee."
        case .unknown: return nil
        }
    }
}

// MARK: - BountyStatus

/// Bounty lifecycle. See state machine.
enum BountyStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case draft = "draft"
    case awaitingFunding = "awaiting_funding"
    case scheduled = "scheduled"
    case live = "live"
    case paused = "paused"
    case filled = "filled"
    case ended = "ended"
    case settled = "settled"
    case cancelled = "cancelled"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [BountyStatus] {
        return [.draft, .awaitingFunding, .scheduled, .live, .paused, .filled, .ended, .settled, .cancelled]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = BountyStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .draft: return "Draft"
        case .awaitingFunding: return "Awaiting funding"
        case .scheduled: return "Scheduled"
        case .live: return "Live"
        case .paused: return "Paused"
        case .filled: return "Filled"
        case .ended: return "Ended"
        case .settled: return "Settled"
        case .cancelled: return "Cancelled"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .draft: return .neutral
        case .awaitingFunding: return .ember
        case .scheduled: return .info
        case .live: return .mint
        case .paused: return .ember
        case .filled: return .accent
        case .ended: return .neutral
        case .settled: return .neutral
        case .cancelled: return .rose
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .draft: return "Being written. Not visible to creators."
        case .awaitingFunding: return "Brief lint passed; waiting for the full escrow. Cannot go live until funded."
        case .scheduled: return "Funded; will go live at starts_at."
        case .live: return "Funded and open to submissions. Shows the Funded badge."
        case .paused: return "Temporarily closed to new submissions by the brand or Ops. Existing work continues."
        case .filled: return "Budget fully reserved; no new submissions. Reopens if reservations release."
        case .ended: return "Closed to submissions; posts are still in their windows or CPA windows."
        case .settled: return "All windows closed, escrow reconciled, unspent budget refunded."
        case .cancelled: return "Cancelled before any work was approved; escrow refunded."
        case .unknown: return nil
        }
    }
}

// MARK: - Visibility

/// Who can see a bounty.
enum BountyVisibility: String, Codable, Hashable, Sendable, CaseIterable {
    case open = "open"
    case inviteOnly = "invite_only"
    case `private` = "private"
    case drop = "drop"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [BountyVisibility] {
        return [.open, .inviteOnly, .`private`, .drop]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = BountyVisibility(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .open: return "Open"
        case .inviteOnly: return "Invite only"
        case .`private`: return "Private"
        case .drop: return "Daily Drop"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .open: return .mint
        case .inviteOnly: return .info
        case .`private`: return .neutral
        case .drop: return .ember
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .open: return "Any eligible creator can find and join it."
        case .inviteOnly: return "Only invited creators can see it."
        case .`private`: return "A direct bounty visible to one creator."
        case .drop: return "Released through a Daily Drop with limited spots."
        case .unknown: return nil
        }
    }
}

// MARK: - FundingSource

/// Where a bounty's escrow comes from.
enum FundingSource: String, Codable, Hashable, Sendable, CaseIterable {
    case brand = "brand"
    case brandMatched = "brand_matched"
    case platform = "platform"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [FundingSource] {
        return [.brand, .brandMatched, .platform]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = FundingSource(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .brand: return "Brand funded"
        case .brandMatched: return "Brand + match"
        case .platform: return "flowd funded"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .brand: return .neutral
        case .brandMatched: return .mint
        case .platform: return .accent
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .brand: return "Fully funded by the brand wallet."
        case .brandMatched: return "Brand funded; flowd matched up to $500 of the first bounty."
        case .platform: return "Funded from the flowd promo account: starter bounties and the content-about-us bounty."
        case .unknown: return nil
        }
    }
}

// MARK: - LintSeverity

/// Brief Lint issue severity.
enum LintSeverity: String, Codable, Hashable, Sendable, CaseIterable {
    case blocker = "blocker"
    case warning = "warning"
    case info = "info"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [LintSeverity] {
        return [.blocker, .warning, .info]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = LintSeverity(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .blocker: return "Blocker"
        case .warning: return "Warning"
        case .info: return "Tip"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .blocker: return .rose
        case .warning: return .ember
        case .info: return .info
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .blocker: return "The bounty cannot be published until fixed."
        case .warning: return "Allowed, but likely to hurt fill rate or creator trust."
        case .info: return "A suggestion."
        case .unknown: return nil
        }
    }
}

// MARK: - BriefLintCode

/// Brief Lint rule ids.
enum BriefLintCode: String, Codable, Hashable, Sendable, CaseIterable {
    case missingDeliverables = "missing_deliverables"
    case missingPlatforms = "missing_platforms"
    case missingRegions = "missing_regions"
    case viewMinimumBase = "view_minimum_base"
    case unpaidTrial = "unpaid_trial"
    case burnerAccount = "burner_account"
    case freshAccountDemand = "fresh_account_demand"
    case forcedPostingCount = "forced_posting_count"
    case perpetualRights = "perpetual_rights"
    case aiLikenessRequested = "ai_likeness_requested"
    case payToJoin = "pay_to_join"
    case belowFloorCpm = "below_floor_cpm"
    case noDisclosureText = "no_disclosure_text"
    case unclearCta = "unclear_cta"
    case capTooLow = "cap_too_low"
    case lowEffectivePay = "low_effective_pay"
    case budgetBelowMinimum = "budget_below_minimum"
    case shortWindow = "short_window"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [BriefLintCode] {
        return [.missingDeliverables, .missingPlatforms, .missingRegions, .viewMinimumBase, .unpaidTrial, .burnerAccount, .freshAccountDemand, .forcedPostingCount, .perpetualRights, .aiLikenessRequested, .payToJoin, .belowFloorCpm, .noDisclosureText, .unclearCta, .capTooLow, .lowEffectivePay, .budgetBelowMinimum, .shortWindow]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = BriefLintCode(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .missingDeliverables: return "Missing deliverables"
        case .missingPlatforms: return "Missing platforms"
        case .missingRegions: return "Missing regions"
        case .viewMinimumBase: return "View-minimum base pay"
        case .unpaidTrial: return "Unpaid trial"
        case .burnerAccount: return "Burner account demanded"
        case .freshAccountDemand: return "Fresh account demanded"
        case .forcedPostingCount: return "Forced posting count"
        case .perpetualRights: return "Perpetual rights"
        case .aiLikenessRequested: return "AI likeness requested"
        case .payToJoin: return "Pay to join"
        case .belowFloorCpm: return "CPM below floor"
        case .noDisclosureText: return "No disclosure wording"
        case .unclearCta: return "Unclear CTA"
        case .capTooLow: return "Cap too low"
        case .lowEffectivePay: return "Low effective pay"
        case .budgetBelowMinimum: return "Budget below minimum"
        case .shortWindow: return "Short deadline"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .missingDeliverables: return .rose
        case .missingPlatforms: return .rose
        case .missingRegions: return .ember
        case .viewMinimumBase: return .rose
        case .unpaidTrial: return .rose
        case .burnerAccount: return .rose
        case .freshAccountDemand: return .rose
        case .forcedPostingCount: return .rose
        case .perpetualRights: return .rose
        case .aiLikenessRequested: return .rose
        case .payToJoin: return .rose
        case .belowFloorCpm: return .rose
        case .noDisclosureText: return .ember
        case .unclearCta: return .ember
        case .capTooLow: return .ember
        case .lowEffectivePay: return .ember
        case .budgetBelowMinimum: return .rose
        case .shortWindow: return .info
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .missingDeliverables: return "Video count, length and platforms not stated."
        case .missingPlatforms: return "No posting platform chosen."
        case .missingRegions: return "No target regions or audience minimum."
        case .viewMinimumBase: return "Base pay that only unlocks after a view minimum."
        case .unpaidTrial: return "Unpaid test video or free trial work before pay."
        case .burnerAccount: return "Requires a new or dedicated account per brand."
        case .freshAccountDemand: return "Requires a fresh account, no personal posting."
        case .forcedPostingCount: return "Demands a posting count with no pay for it."
        case .perpetualRights: return "Perpetual or unlimited usage rights."
        case .aiLikenessRequested: return "Asks for AI likeness rights (off by default)."
        case .payToJoin: return "Charges creators to enter."
        case .belowFloorCpm: return "CPM under $0.50."
        case .noDisclosureText: return "Required #ad wording not set."
        case .unclearCta: return "More than one call to action or none."
        case .capTooLow: return "Per-video cap under $20; creators will skip it."
        case .lowEffectivePay: return "Median expected pay per video is under $15."
        case .budgetBelowMinimum: return "Budget under $100."
        case .shortWindow: return "Deadline under 5 days leaves little room for revisions."
        case .unknown: return nil
        }
    }
}

// MARK: - TimeoutPolicy

/// What happens when a submission passes the 72h SLA unreviewed.
enum TimeoutPolicy: String, Codable, Hashable, Sendable, CaseIterable {
    case escalate = "escalate"
    case approveIfClean = "approve_if_clean"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [TimeoutPolicy] {
        return [.escalate, .approveIfClean]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = TimeoutPolicy(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .escalate: return "Escalate"
        case .approveIfClean: return "Approve if clean"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .escalate: return .ember
        case .approveIfClean: return .mint
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .escalate: return "Escalate to the bounty owner and workspace owners; brand reliability takes a hit. Default."
        case .approveIfClean: return "Auto-approve when every QA check passes; otherwise escalate."
        case .unknown: return nil
        }
    }
}

// MARK: - MusicPolicy

/// Brand music rule.
enum MusicPolicy: String, Codable, Hashable, Sendable, CaseIterable {
    case originalOnly = "original_only"
    case commercialLibrary = "commercial_library"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [MusicPolicy] {
        return [.originalOnly, .commercialLibrary]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = MusicPolicy(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .originalOnly: return "Original audio only"
        case .commercialLibrary: return "Commercial library"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .originalOnly: return .neutral
        case .commercialLibrary: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .originalOnly: return "No music; original audio."
        case .commercialLibrary: return "Only platform commercial-music-library tracks."
        case .unknown: return nil
        }
    }
}

// MARK: - AiContentPolicy

/// Brand rule on AI-generated content.
enum AiContentPolicy: String, Codable, Hashable, Sendable, CaseIterable {
    case notAllowed = "not_allowed"
    case allowedDisclosed = "allowed_disclosed"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [AiContentPolicy] {
        return [.notAllowed, .allowedDisclosed]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = AiContentPolicy(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .notAllowed: return "Not allowed"
        case .allowedDisclosed: return "Allowed, disclosed"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .notAllowed: return .rose
        case .allowedDisclosed: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .notAllowed: return "No AI-generated video or voice."
        case .allowedDisclosed: return "Allowed with a visible AI label."
        case .unknown: return nil
        }
    }
}
