// GENERATED by scripts/gen-ios-models.mjs from packages/contract/schema/*.mjs. Do not edit by hand: change the schema, then run  node scripts/gen-ios-models.mjs
// Names, enum values and field types mirror packages/contract/DOMAIN.md sections 5 to 7. Decoded with .convertFromSnakeCase.

import Foundation

// Enumerations: Catalogues (5). Every enum decodes unknown values to `.unknown`.

// MARK: - Platform

/// Social platform a creator posts to.
enum Platform: String, Codable, Hashable, Sendable, CaseIterable {
    case tiktok = "tiktok"
    case instagram = "instagram"
    case youtube = "youtube"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [Platform] {
        return [.tiktok, .instagram, .youtube]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = Platform(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .tiktok: return "TikTok"
        case .instagram: return "Instagram"
        case .youtube: return "YouTube"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .tiktok: return .neutral
        case .instagram: return .neutral
        case .youtube: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .tiktok: return "TikTok (text/glyph only, no trademarked logo)."
        case .instagram: return "Instagram Reels."
        case .youtube: return "YouTube Shorts."
        case .unknown: return nil
        }
    }
}

// MARK: - AdPlatform

/// Paid-ad surface for Winner promotion.
enum AdPlatform: String, Codable, Hashable, Sendable, CaseIterable {
    case tiktok = "tiktok"
    case meta = "meta"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [AdPlatform] {
        return [.tiktok, .meta]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = AdPlatform(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .tiktok: return "TikTok"
        case .meta: return "Meta"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .tiktok: return .neutral
        case .meta: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .tiktok: return "TikTok Spark Ads."
        case .meta: return "Meta partnership ads (Instagram, Facebook)."
        case .unknown: return nil
        }
    }
}

// MARK: - Category

/// App category (9). Drives market series, clearing CPMs and matching.
enum AppCategory: String, Codable, Hashable, Sendable, CaseIterable {
    case aiPhoto = "ai_photo"
    case aiAssistant = "ai_assistant"
    case fitness = "fitness"
    case language = "language"
    case productivity = "productivity"
    case finance = "finance"
    case sleepMind = "sleep_mind"
    case musicAudio = "music_audio"
    case lifestyle = "lifestyle"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [AppCategory] {
        return [.aiPhoto, .aiAssistant, .fitness, .language, .productivity, .finance, .sleepMind, .musicAudio, .lifestyle]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = AppCategory(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .aiPhoto: return "AI photo & video"
        case .aiAssistant: return "AI assistants"
        case .fitness: return "Fitness"
        case .language: return "Language & learning"
        case .productivity: return "Productivity"
        case .finance: return "Money & budgeting"
        case .sleepMind: return "Sleep & mind"
        case .musicAudio: return "Music & audio"
        case .lifestyle: return "Lifestyle & travel"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .aiPhoto: return .violet
        case .aiAssistant: return .violet
        case .fitness: return .mint
        case .language: return .accent
        case .productivity: return .info
        case .finance: return .sun
        case .sleepMind: return .info
        case .musicAudio: return .ember
        case .lifestyle: return .ember
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .aiPhoto: return "AI photo editors, headshots, video enhancers."
        case .aiAssistant: return "AI writing, chat and research assistants."
        case .fitness: return "Workouts, running, strength, habit-based fitness."
        case .language: return "Language learning, study and tutoring apps."
        case .productivity: return "Notes, planners, focus and organisation tools."
        case .finance: return "Budgeting, saving and subscription-tracking apps."
        case .sleepMind: return "Sleep, meditation and mental wellbeing apps."
        case .musicAudio: return "Music making, audio editing and listening tools."
        case .lifestyle: return "Travel, food, home and daily-life apps."
        case .unknown: return nil
        }
    }
}

// MARK: - Niche

/// Creator niche (12). Used for matching, cohorts and discovery.
enum Niche: String, Codable, Hashable, Sendable, CaseIterable {
    case aiTools = "ai_tools"
    case tech = "tech"
    case fitness = "fitness"
    case wellness = "wellness"
    case productivity = "productivity"
    case study = "study"
    case money = "money"
    case lifestyle = "lifestyle"
    case beauty = "beauty"
    case travel = "travel"
    case food = "food"
    case parenting = "parenting"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [Niche] {
        return [.aiTools, .tech, .fitness, .wellness, .productivity, .study, .money, .lifestyle, .beauty, .travel, .food, .parenting]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = Niche(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .aiTools: return "AI tools"
        case .tech: return "Tech"
        case .fitness: return "Fitness"
        case .wellness: return "Wellness"
        case .productivity: return "Productivity"
        case .study: return "Study & learning"
        case .money: return "Money"
        case .lifestyle: return "Lifestyle"
        case .beauty: return "Beauty"
        case .travel: return "Travel"
        case .food: return "Food"
        case .parenting: return "Parenting"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .aiTools: return .violet
        case .tech: return .accent
        case .fitness: return .mint
        case .wellness: return .info
        case .productivity: return .info
        case .study: return .accent
        case .money: return .sun
        case .lifestyle: return .ember
        case .beauty: return .ember
        case .travel: return .ember
        case .food: return .ember
        case .parenting: return .info
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .aiTools: return "Reviews and demos of AI apps."
        case .tech: return "Gadgets, apps and tech reviews."
        case .fitness: return "Workouts and training."
        case .wellness: return "Sleep, mindfulness and self-care."
        case .productivity: return "Study systems, notes, organisation."
        case .study: return "Students, languages, exam prep."
        case .money: return "Budgeting, saving and side income."
        case .lifestyle: return "Day-in-the-life and routines."
        case .beauty: return "Selfies, glow-ups, looks."
        case .travel: return "Trips, planning, maps."
        case .food: return "Cooking and meal planning."
        case .parenting: return "Families, kids, routines."
        case .unknown: return nil
        }
    }
}

// MARK: - Country

/// Creator / audience country (ISO 3166-1 alpha-2, 12 supported for v1).
enum Country: String, Codable, Hashable, Sendable, CaseIterable {
    case us = "US"
    case ca = "CA"
    case gb = "GB"
    case au = "AU"
    case ie = "IE"
    case de = "DE"
    case fr = "FR"
    case es = "ES"
    case nl = "NL"
    case br = "BR"
    case mx = "MX"
    case ph = "PH"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [Country] {
        return [.us, .ca, .gb, .au, .ie, .de, .fr, .es, .nl, .br, .mx, .ph]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = Country(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .us: return "United States"
        case .ca: return "Canada"
        case .gb: return "United Kingdom"
        case .au: return "Australia"
        case .ie: return "Ireland"
        case .de: return "Germany"
        case .fr: return "France"
        case .es: return "Spain"
        case .nl: return "Netherlands"
        case .br: return "Brazil"
        case .mx: return "Mexico"
        case .ph: return "Philippines"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .us: return .neutral
        case .ca: return .neutral
        case .gb: return .neutral
        case .au: return .neutral
        case .ie: return .neutral
        case .de: return .neutral
        case .fr: return .neutral
        case .es: return .neutral
        case .nl: return .neutral
        case .br: return .neutral
        case .mx: return .neutral
        case .ph: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .us: return "Primary market. W-9 and 1099 flow."
        case .ca: return "Supported."
        case .gb: return "Supported."
        case .au: return "Supported."
        case .ie: return "Supported."
        case .de: return "Supported."
        case .fr: return "Supported."
        case .es: return "Supported."
        case .nl: return "Supported."
        case .br: return "Supported."
        case .mx: return "Supported."
        case .ph: return "Supported."
        case .unknown: return nil
        }
    }
}
