// GENERATED by scripts/gen-ios-models.mjs from packages/contract/schema/*.mjs. Do not edit by hand: change the schema, then run  node scripts/gen-ios-models.mjs
// Names, enum values and field types mirror packages/contract/DOMAIN.md sections 5 to 7. Decoded with .convertFromSnakeCase.

import Foundation

// Enumerations: Attribution (9). Every enum decodes unknown values to `.unknown`.

// MARK: - ConversionKind

/// Funnel event after a view.
enum ConversionKind: String, Codable, Hashable, Sendable, CaseIterable {
    case install = "install"
    case trial = "trial"
    case paid = "paid"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [ConversionKind] {
        return [.install, .trial, .paid]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = ConversionKind(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .install: return "Install"
        case .trial: return "Trial started"
        case .paid: return "Paid subscription"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .install: return .info
        case .trial: return .accent
        case .paid: return .mint
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .install: return "App installed (first launch)."
        case .trial: return "Free trial started."
        case .paid: return "First paid period, or trial converted to paid."
        case .unknown: return nil
        }
    }
}

// MARK: - ConversionSource

/// How a conversion was attributed. CPA pays only on link and code.
enum ConversionSource: String, Codable, Hashable, Sendable, CaseIterable {
    case link = "link"
    case code = "code"
    case mmp = "mmp"
    case survey = "survey"
    case modelled = "modelled"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [ConversionSource] {
        return [.link, .code, .mmp, .survey, .modelled]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = ConversionSource(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .link: return "Tracked link"
        case .code: return "Promo code"
        case .mmp: return "MMP match"
        case .survey: return "Survey answer"
        case .modelled: return "Modelled"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .link: return .mint
        case .code: return .mint
        case .mmp: return .info
        case .survey: return .info
        case .modelled: return .violet
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .link: return "Deterministic: a per-creator deferred deep link. Payable."
        case .code: return "Deterministic: a promo or offer code redeemed. Payable."
        case .mmp: return "Matched by AppsFlyer / Adjust / Branch. Reported, not paid."
        case .survey: return "\"How did you hear about us?\" Reported, not paid."
        case .modelled: return "Statistical estimate of unattributed lift. Reported separately, never paid."
        case .unknown: return nil
        }
    }
}

// MARK: - ConversionConfidence

/// Confidence label shown next to every conversion count.
enum ConversionConfidence: String, Codable, Hashable, Sendable, CaseIterable {
    case deterministic = "deterministic"
    case matched = "matched"
    case selfReported = "self_reported"
    case modelled = "modelled"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [ConversionConfidence] {
        return [.deterministic, .matched, .selfReported, .modelled]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = ConversionConfidence(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .deterministic: return "Tracked"
        case .matched: return "Matched"
        case .selfReported: return "Self-reported"
        case .modelled: return "Modelled"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .deterministic: return .mint
        case .matched: return .info
        case .selfReported: return .info
        case .modelled: return .violet
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .deterministic: return "Link or code. Counts toward tracked funnel and CPA pay."
        case .matched: return "MMP match. Estimated funnel."
        case .selfReported: return "Survey answer. Estimated funnel."
        case .modelled: return "Estimate. Estimated funnel."
        case .unknown: return nil
        }
    }
}

// MARK: - ConversionStatus

/// Settlement state of a conversion batch.
enum ConversionStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case pending = "pending"
    case cleared = "cleared"
    case rejected = "rejected"
    case refunded = "refunded"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [ConversionStatus] {
        return [.pending, .cleared, .rejected, .refunded]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = ConversionStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .pending: return "Pending"
        case .cleared: return "Cleared"
        case .rejected: return "Rejected"
        case .refunded: return "Refunded"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .pending: return .info
        case .cleared: return .mint
        case .rejected: return .rose
        case .refunded: return .rose
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .pending: return "Inside its clearing window (install 24h, trial 72h, paid 168h)."
        case .cleared: return "Cleared; CPA pay (if payable) is on the ledger."
        case .rejected: return "Duplicate, fraud or not attributable."
        case .refunded: return "Refunded inside the window; CPA reversed."
        case .unknown: return nil
        }
    }
}

// MARK: - AttributionLinkStatus

/// State of a per-creator tracking link.
enum AttributionLinkStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case active = "active"
    case paused = "paused"
    case expired = "expired"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [AttributionLinkStatus] {
        return [.active, .paused, .expired]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = AttributionLinkStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .active: return "Active"
        case .paused: return "Paused"
        case .expired: return "Expired"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .active: return .mint
        case .paused: return .ember
        case .expired: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .active: return "Resolving and attributing."
        case .paused: return "Paused with the bounty."
        case .expired: return "Past the CPA window; still redirects, no longer attributes pay."
        case .unknown: return nil
        }
    }
}

// MARK: - OfferCodeStatus

/// State of a code in the offer-code pool.
enum OfferCodeStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case available = "available"
    case assigned = "assigned"
    case exhausted = "exhausted"
    case expired = "expired"
    case retired = "retired"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [OfferCodeStatus] {
        return [.available, .assigned, .exhausted, .expired, .retired]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = OfferCodeStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .available: return "Available"
        case .assigned: return "Assigned"
        case .exhausted: return "Exhausted"
        case .expired: return "Expired"
        case .retired: return "Retired"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .available: return .mint
        case .assigned: return .accent
        case .exhausted: return .ember
        case .expired: return .neutral
        case .retired: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .available: return "Unassigned and ready."
        case .assigned: return "Assigned to a creator and bounty."
        case .exhausted: return "Hit its redemption cap."
        case .expired: return "Past its validity window."
        case .retired: return "Taken out of rotation."
        case .unknown: return nil
        }
    }
}

// MARK: - RcEventType

/// RevenueCat webhook event types we ingest (lowercase mirror of the RevenueCat names).
enum RcEventType: String, Codable, Hashable, Sendable, CaseIterable {
    case initialPurchase = "initial_purchase"
    case renewal = "renewal"
    case cancellation = "cancellation"
    case uncancellation = "uncancellation"
    case expiration = "expiration"
    case billingIssue = "billing_issue"
    case productChange = "product_change"
    case nonRenewingPurchase = "non_renewing_purchase"
    case test = "test"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [RcEventType] {
        return [.initialPurchase, .renewal, .cancellation, .uncancellation, .expiration, .billingIssue, .productChange, .nonRenewingPurchase, .test]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = RcEventType(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .initialPurchase: return "Initial purchase"
        case .renewal: return "Renewal"
        case .cancellation: return "Cancellation"
        case .uncancellation: return "Un-cancellation"
        case .expiration: return "Expiration"
        case .billingIssue: return "Billing issue"
        case .productChange: return "Product change"
        case .nonRenewingPurchase: return "One-time purchase"
        case .test: return "Test"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .initialPurchase: return .accent
        case .renewal: return .mint
        case .cancellation: return .ember
        case .uncancellation: return .info
        case .expiration: return .neutral
        case .billingIssue: return .ember
        case .productChange: return .neutral
        case .nonRenewingPurchase: return .neutral
        case .test: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .initialPurchase: return "First purchase; with period_type trial this is a trial start."
        case .renewal: return "Renewal; with is_trial_conversion true this is trial to paid."
        case .cancellation: return "Cancelled or refunded."
        case .uncancellation: return "Resubscribed before expiry."
        case .expiration: return "Subscription ended."
        case .billingIssue: return "Payment failed."
        case .productChange: return "Plan change."
        case .nonRenewingPurchase: return "Non-subscription purchase."
        case .test: return "Webhook test event."
        case .unknown: return nil
        }
    }
}

// MARK: - PeriodType

/// RevenueCat period_type.
enum PeriodType: String, Codable, Hashable, Sendable, CaseIterable {
    case trial = "trial"
    case intro = "intro"
    case normal = "normal"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [PeriodType] {
        return [.trial, .intro, .normal]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = PeriodType(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .trial: return "Trial"
        case .intro: return "Intro"
        case .normal: return "Normal"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .trial: return .accent
        case .intro: return .info
        case .normal: return .mint
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .trial: return "Free trial period."
        case .intro: return "Introductory price period."
        case .normal: return "Full price period."
        case .unknown: return nil
        }
    }
}

// MARK: - RcMatchStatus

/// How a RevenueCat event was matched to a creator.
enum RcMatchStatus: String, Codable, Hashable, Sendable, CaseIterable {
    case matched = "matched"
    case unmatched = "unmatched"
    case duplicate = "duplicate"
    case ignored = "ignored"
    /// A value this build does not know yet (decoded from JSON, never sent).
    case unknown = "unknown"

    /// Every value the contract defines (without `.unknown`), in contract order.
    static var allCases: [RcMatchStatus] {
        return [.matched, .unmatched, .duplicate, .ignored]
    }

    init(from decoder: Decoder) throws {
        let container: SingleValueDecodingContainer = try decoder.singleValueContainer()
        let raw: String = try container.decode(String.self)
        self = RcMatchStatus(rawValue: raw) ?? .unknown
    }

    func encode(to encoder: Encoder) throws {
        var container: SingleValueEncodingContainer = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    /// False for `.unknown`.
    var isKnown: Bool {
        return self != .unknown
    }

    /// UI label from the contract ("Views still counting").
    var label: String {
        switch self {
        case .matched: return "Matched"
        case .unmatched: return "Unmatched"
        case .duplicate: return "Duplicate"
        case .ignored: return "Ignored"
        case .unknown: return "Unknown"
        }
    }

    /// Colour tone from the contract; map to a design-system tone with `.flowdTone`.
    var tone: ContractTone {
        switch self {
        case .matched: return .mint
        case .unmatched: return .ember
        case .duplicate: return .neutral
        case .ignored: return .neutral
        case .unknown: return .neutral
        }
    }

    /// Plain-English meaning from the contract, when it has one.
    var meaning: String? {
        switch self {
        case .matched: return "Matched to a conversion by subscriber attributes or offer code."
        case .unmatched: return "No flowd creator attributes or code on the event."
        case .duplicate: return "Seen before (idempotent redelivery)."
        case .ignored: return "Test or irrelevant event type."
        case .unknown: return nil
        }
    }
}
