// flowd design tokens — GENERATED by packages/tokens/build.mjs from tokens.json. Do not edit by hand.
// Target: iOS 17+, Swift 5 language mode. Imports SwiftUI + UIKit only.
// Source of truth: packages/tokens/tokens.json (theme "Black Glass", v1.0.0).
//
// Naming: FlowdColor (semantic, light/dark dynamic), FlowdPrimitive (raw ramps), FlowdGradient, FlowdAurora, FlowdTier,
// FlowdChart, FlowdSpacing, FlowdRadius, FlowdLayout, FlowdElevation, FlowdGlassSpec, FlowdMotion, FlowdFont.
// Feature views must not read these directly for glass: go through the DesignSystem wrappers.

import SwiftUI
import UIKit
import Foundation

// MARK: - Helpers

enum FlowdKit {
    /// sRGB UIColor from 0xRRGGBB.
    static func ui(_ hex: UInt32, _ alpha: CGFloat = 1) -> UIColor {
        let r: CGFloat = CGFloat((hex >> 16) & 0xFF) / 255
        let g: CGFloat = CGFloat((hex >> 8) & 0xFF) / 255
        let b: CGFloat = CGFloat(hex & 0xFF) / 255
        return UIColor(red: r, green: g, blue: b, alpha: alpha)
    }

    /// A colour that resolves to `light` or `dark` from the trait collection (follows the app's colour scheme override too).
    static func dyn(_ light: UIColor, _ dark: UIColor) -> Color {
        let provider: (UITraitCollection) -> UIColor = { (traits: UITraitCollection) -> UIColor in
            return traits.userInterfaceStyle == .dark ? dark : light
        }
        return Color(uiColor: UIColor(dynamicProvider: provider))
    }

    /// A theme-independent sRGB colour.
    static func fixed(_ hex: UInt32, _ alpha: Double = 1) -> Color {
        let r: Double = Double((hex >> 16) & 0xFF) / 255
        let g: Double = Double((hex >> 8) & 0xFF) / 255
        let b: Double = Double(hex & 0xFF) / 255
        return Color(.sRGB, red: r, green: g, blue: b, opacity: alpha)
    }

    /// CSS-style gradient angle (0deg = to top, 90deg = to right, 135deg = to bottom-right) -> unit points.
    static func start(angle: Double) -> UnitPoint {
        let r: Double = angle * Double.pi / 180
        return UnitPoint(x: 0.5 - sin(r) / 2, y: 0.5 + cos(r) / 2)
    }

    static func end(angle: Double) -> UnitPoint {
        let r: Double = angle * Double.pi / 180
        return UnitPoint(x: 0.5 + sin(r) / 2, y: 0.5 - cos(r) / 2)
    }

    static func linear(_ stops: [Gradient.Stop], angle: Double) -> LinearGradient {
        return LinearGradient(stops: stops, startPoint: start(angle: angle), endPoint: end(angle: angle))
    }
}

// MARK: - Primitives (raw ramps; use FlowdColor in product code)

enum FlowdPrimitive {
    static let abyss50: Color = FlowdKit.fixed(0xF3F7FF)
    static let abyss100: Color = FlowdKit.fixed(0xECF0F9)
    static let abyss200: Color = FlowdKit.fixed(0xDEE3EE)
    static let abyss300: Color = FlowdKit.fixed(0xC5CEE2)
    static let abyss400: Color = FlowdKit.fixed(0x9BA8C3)
    static let abyss500: Color = FlowdKit.fixed(0x74809A)
    static let abyss600: Color = FlowdKit.fixed(0x505D7A)
    static let abyss700: Color = FlowdKit.fixed(0x374360)
    static let abyss800: Color = FlowdKit.fixed(0x212D48)
    static let abyss850: Color = FlowdKit.fixed(0x18233D)
    static let abyss900: Color = FlowdKit.fixed(0x101A34)
    static let abyss925: Color = FlowdKit.fixed(0x0C162F)
    static let abyss950: Color = FlowdKit.fixed(0x08112A)
    static let abyss975: Color = FlowdKit.fixed(0x030921)
    static let abyss1000: Color = FlowdKit.fixed(0x010419)
    static let ultraviolet50: Color = FlowdKit.fixed(0xF6F6F9)
    static let ultraviolet100: Color = FlowdKit.fixed(0xEDECF5)
    static let ultraviolet200: Color = FlowdKit.fixed(0xD7D7F1)
    static let ultraviolet300: Color = FlowdKit.fixed(0xBCB8F3)
    static let ultraviolet400: Color = FlowdKit.fixed(0x988BF8)
    static let ultraviolet500: Color = FlowdKit.fixed(0x784FFC)
    static let ultraviolet600: Color = FlowdKit.fixed(0x671AF3)
    static let ultraviolet700: Color = FlowdKit.fixed(0x531EC3)
    static let ultraviolet800: Color = FlowdKit.fixed(0x401D96)
    static let ultraviolet900: Color = FlowdKit.fixed(0x301970)
    static let ultraviolet950: Color = FlowdKit.fixed(0x1F124A)
    static let azure50: Color = FlowdKit.fixed(0xF5F7F9)
    static let azure100: Color = FlowdKit.fixed(0xEAEFF6)
    static let azure200: Color = FlowdKit.fixed(0xD1DEF2)
    static let azure300: Color = FlowdKit.fixed(0xABC7F4)
    static let azure400: Color = FlowdKit.fixed(0x73A5F9)
    static let azure500: Color = FlowdKit.fixed(0x307DFD)
    static let azure600: Color = FlowdKit.fixed(0x0E62E1)
    static let azure700: Color = FlowdKit.fixed(0x1150B3)
    static let azure800: Color = FlowdKit.fixed(0x113E88)
    static let azure900: Color = FlowdKit.fixed(0x0E2F65)
    static let azure950: Color = FlowdKit.fixed(0x081E41)
    static let lagoon50: Color = FlowdKit.fixed(0xF2F8F9)
    static let lagoon100: Color = FlowdKit.fixed(0xE7F6F8)
    static let lagoon200: Color = FlowdKit.fixed(0xCDF1F7)
    static let lagoon300: Color = FlowdKit.fixed(0x9EECF8)
    static let lagoon400: Color = FlowdKit.fixed(0x37E4FA)
    static let lagoon500: Color = FlowdKit.fixed(0x17D2E7)
    static let lagoon600: Color = FlowdKit.fixed(0x1FA7B8)
    static let lagoon700: Color = FlowdKit.fixed(0x22828F)
    static let lagoon800: Color = FlowdKit.fixed(0x1E5F68)
    static let lagoon900: Color = FlowdKit.fixed(0x174147)
    static let lagoon950: Color = FlowdKit.fixed(0x0C2327)
    static let mint50: Color = FlowdKit.fixed(0xF1F9F4)
    static let mint100: Color = FlowdKit.fixed(0xE5F8EE)
    static let mint200: Color = FlowdKit.fixed(0xC7F7DE)
    static let mint300: Color = FlowdKit.fixed(0x89F9C5)
    static let mint400: Color = FlowdKit.fixed(0x39F1AB)
    static let mint500: Color = FlowdKit.fixed(0x18DF9B)
    static let mint600: Color = FlowdKit.fixed(0x20B27C)
    static let mint700: Color = FlowdKit.fixed(0x238A61)
    static let mint800: Color = FlowdKit.fixed(0x1F6447)
    static let mint900: Color = FlowdKit.fixed(0x174531)
    static let mint950: Color = FlowdKit.fixed(0x0C251A)
    static let ember50: Color = FlowdKit.fixed(0xF9F6F5)
    static let ember100: Color = FlowdKit.fixed(0xF7EFEC)
    static let ember200: Color = FlowdKit.fixed(0xF5DFD7)
    static let ember300: Color = FlowdKit.fixed(0xF7C8B7)
    static let ember400: Color = FlowdKit.fixed(0xFBA584)
    static let ember500: Color = FlowdKit.fixed(0xFE7A43)
    static let ember600: Color = FlowdKit.fixed(0xD95715)
    static let ember700: Color = FlowdKit.fixed(0xAA4619)
    static let ember800: Color = FlowdKit.fixed(0x7D3617)
    static let ember900: Color = FlowdKit.fixed(0x592611)
    static let ember950: Color = FlowdKit.fixed(0x341509)
    static let sun50: Color = FlowdKit.fixed(0xF9F7F0)
    static let sun100: Color = FlowdKit.fixed(0xF9F3E6)
    static let sun200: Color = FlowdKit.fixed(0xF8ECCF)
    static let sun300: Color = FlowdKit.fixed(0xFAE2A9)
    static let sun400: Color = FlowdKit.fixed(0xFCD267)
    static let sun500: Color = FlowdKit.fixed(0xF8C216)
    static let sun600: Color = FlowdKit.fixed(0xC59B1D)
    static let sun700: Color = FlowdKit.fixed(0x987820)
    static let sun800: Color = FlowdKit.fixed(0x6D571C)
    static let sun900: Color = FlowdKit.fixed(0x4A3B15)
    static let sun950: Color = FlowdKit.fixed(0x261E09)
    static let rose50: Color = FlowdKit.fixed(0xF9F6F6)
    static let rose100: Color = FlowdKit.fixed(0xF7EDEE)
    static let rose200: Color = FlowdKit.fixed(0xF4DADB)
    static let rose300: Color = FlowdKit.fixed(0xF6BDC1)
    static let rose400: Color = FlowdKit.fixed(0xFA909B)
    static let rose500: Color = FlowdKit.fixed(0xFD5170)
    static let rose600: Color = FlowdKit.fixed(0xDF1B52)
    static let rose700: Color = FlowdKit.fixed(0xB01E42)
    static let rose800: Color = FlowdKit.fixed(0x831C32)
    static let rose900: Color = FlowdKit.fixed(0x5F1624)
    static let rose950: Color = FlowdKit.fixed(0x390E15)
    static let white: Color = FlowdKit.fixed(0xFFFFFF)
    static let black: Color = FlowdKit.fixed(0x000000)
}

// MARK: - Semantic colour (dynamic light / dark)

enum FlowdColor {
    static let bg: Color = FlowdKit.dyn(FlowdKit.ui(0xF3F7FF), FlowdKit.ui(0x000000))
    static let bgElevated: Color = FlowdKit.dyn(FlowdKit.ui(0xFFFFFF), FlowdKit.ui(0x0A0A0C))
    static let bgSunken: Color = FlowdKit.dyn(FlowdKit.ui(0xECF0F9), FlowdKit.ui(0x000000))
    static let surface: Color = FlowdKit.dyn(FlowdKit.ui(0xFFFFFF), FlowdKit.ui(0x141416))
    static let surfaceRaised: Color = FlowdKit.dyn(FlowdKit.ui(0xFBFCFF), FlowdKit.ui(0x1C1C20))
    static let surfaceField: Color = FlowdKit.dyn(FlowdKit.ui(0x08112A, 0.05), FlowdKit.ui(0xFFFFFF, 0.07))
    static let surfaceHover: Color = FlowdKit.dyn(FlowdKit.ui(0x08112A, 0.05), FlowdKit.ui(0xFFFFFF, 0.06))
    static let surfaceActive: Color = FlowdKit.dyn(FlowdKit.ui(0x08112A, 0.09), FlowdKit.ui(0xFFFFFF, 0.1))
    static let surfaceGlass1: Color = FlowdKit.dyn(FlowdKit.ui(0xFFFFFF), FlowdKit.ui(0x1E1E22, 0.62))
    static let surfaceGlass2: Color = FlowdKit.dyn(FlowdKit.ui(0xFFFFFF), FlowdKit.ui(0x1E1E22, 0.74))
    static let surfaceGlass3: Color = FlowdKit.dyn(FlowdKit.ui(0xFFFFFF), FlowdKit.ui(0x141418, 0.82))
    static let scrim: Color = FlowdKit.dyn(FlowdKit.ui(0x08112A, 0.34), FlowdKit.ui(0x000000, 0.62))
    static let fg: Color = FlowdKit.dyn(FlowdKit.ui(0x08112A), FlowdKit.ui(0xF5F5F7))
    static let fgMuted: Color = FlowdKit.dyn(FlowdKit.ui(0x3F4966), FlowdKit.ui(0xC6C6CE))
    static let fgSubtle: Color = FlowdKit.dyn(FlowdKit.ui(0x5B6684), FlowdKit.ui(0xADADB7))
    static let fgDisabled: Color = FlowdKit.dyn(FlowdKit.ui(0x9AA4BC), FlowdKit.ui(0x63636C))
    static let fgInverse: Color = FlowdKit.dyn(FlowdKit.ui(0xFFFFFF), FlowdKit.ui(0x000000))
    static let onAccent: Color = FlowdKit.dyn(FlowdKit.ui(0x030921), FlowdKit.ui(0x030921))
    static let rim: Color = FlowdKit.dyn(FlowdKit.ui(0x08112A, 0.1), FlowdKit.ui(0xFFFFFF, 0.16))
    static let rimStrong: Color = FlowdKit.dyn(FlowdKit.ui(0x08112A, 0.22), FlowdKit.ui(0xFFFFFF, 0.3))
    static let divider: Color = FlowdKit.dyn(FlowdKit.ui(0x08112A, 0.07), FlowdKit.ui(0xFFFFFF, 0.09))
    static let focusRing: Color = FlowdKit.dyn(FlowdKit.ui(0x238A61), FlowdKit.ui(0x39F1AB))
    static let accentSolid: Color = FlowdKit.dyn(FlowdKit.ui(0x20B27C), FlowdKit.ui(0x18DF9B))
    static let accentBright: Color = FlowdKit.dyn(FlowdKit.ui(0x238A61), FlowdKit.ui(0x18DF9B))
    static let accentSolidHover: Color = FlowdKit.dyn(FlowdKit.ui(0x18DF9B), FlowdKit.ui(0x39F1AB))
    static let accentSolidPressed: Color = FlowdKit.dyn(FlowdKit.ui(0x238A61), FlowdKit.ui(0x20B27C))
    static let accent: Color = FlowdKit.dyn(FlowdKit.ui(0x146949), FlowdKit.ui(0x18DF9B))
    static let accentSoft: Color = FlowdKit.dyn(FlowdKit.ui(0x20B27C, 0.12), FlowdKit.ui(0x18DF9B, 0.14))
    static let violetSolid: Color = FlowdKit.dyn(FlowdKit.ui(0x671AF3), FlowdKit.ui(0x784FFC))
    static let violet: Color = FlowdKit.dyn(FlowdKit.ui(0x531EC3), FlowdKit.ui(0xBCB8F3))
    static let violetSoft: Color = FlowdKit.dyn(FlowdKit.ui(0x671AF3, 0.1), FlowdKit.ui(0x784FFC, 0.2))
    static let onViolet: Color = FlowdKit.dyn(FlowdKit.ui(0xFFFFFF), FlowdKit.ui(0xFFFFFF))
    static let mintSolid: Color = FlowdKit.dyn(FlowdKit.ui(0x20B27C), FlowdKit.ui(0x18DF9B))
    static let mint: Color = FlowdKit.dyn(FlowdKit.ui(0x146949), FlowdKit.ui(0x18DF9B))
    static let mintSoft: Color = FlowdKit.dyn(FlowdKit.ui(0x20B27C, 0.16), FlowdKit.ui(0x18DF9B, 0.16))
    static let onMint: Color = FlowdKit.dyn(FlowdKit.ui(0x030921), FlowdKit.ui(0x030921))
    static let emberSolid: Color = FlowdKit.dyn(FlowdKit.ui(0xD95715), FlowdKit.ui(0xFE7A43))
    static let ember: Color = FlowdKit.dyn(FlowdKit.ui(0x983E15), FlowdKit.ui(0xFBA584))
    static let emberSoft: Color = FlowdKit.dyn(FlowdKit.ui(0xD95715, 0.06), FlowdKit.ui(0xFE7A43, 0.17))
    static let onEmber: Color = FlowdKit.dyn(FlowdKit.ui(0x030921), FlowdKit.ui(0x030921))
    static let sunSolid: Color = FlowdKit.dyn(FlowdKit.ui(0xF8C216), FlowdKit.ui(0xF8C216))
    static let sun: Color = FlowdKit.dyn(FlowdKit.ui(0x765D13), FlowdKit.ui(0xF8C216))
    static let sunSoft: Color = FlowdKit.dyn(FlowdKit.ui(0xF8C216, 0.22), FlowdKit.ui(0xF8C216, 0.16))
    static let onSun: Color = FlowdKit.dyn(FlowdKit.ui(0x030921), FlowdKit.ui(0x030921))
    static let roseSolid: Color = FlowdKit.dyn(FlowdKit.ui(0xDF1B52), FlowdKit.ui(0xFD5170))
    static let rose: Color = FlowdKit.dyn(FlowdKit.ui(0xB01E42), FlowdKit.ui(0xFA909B))
    static let roseSoft: Color = FlowdKit.dyn(FlowdKit.ui(0xDF1B52, 0.1), FlowdKit.ui(0xFD5170, 0.17))
    static let onRose: Color = FlowdKit.dyn(FlowdKit.ui(0xFFFFFF), FlowdKit.ui(0x030921))
    static let infoSolid: Color = FlowdKit.dyn(FlowdKit.ui(0x1FA7B8), FlowdKit.ui(0x17D2E7))
    static let info: Color = FlowdKit.dyn(FlowdKit.ui(0x156671), FlowdKit.ui(0x17D2E7))
    static let infoSoft: Color = FlowdKit.dyn(FlowdKit.ui(0x1FA7B8, 0.14), FlowdKit.ui(0x17D2E7, 0.15))
    static let onInfo: Color = FlowdKit.dyn(FlowdKit.ui(0x030921), FlowdKit.ui(0x030921))
}

// MARK: - Gradients

enum FlowdGradient {
    static let flowStops: [Gradient.Stop] = [
            .init(color: FlowdKit.fixed(0x18DF9B), location: 0),
            .init(color: FlowdKit.fixed(0x18DF9B), location: 1)
    ]
    static let flow: LinearGradient = FlowdKit.linear(flowStops, angle: 135)
    static let flowButtonStops: [Gradient.Stop] = [
            .init(color: FlowdKit.fixed(0x18DF9B), location: 0),
            .init(color: FlowdKit.fixed(0x18DF9B), location: 1)
    ]
    static let flowButton: LinearGradient = FlowdKit.linear(flowButtonStops, angle: 135)
    static let flowSoftStops: [Gradient.Stop] = [
            .init(color: FlowdKit.fixed(0x18DF9B, 0.14), location: 0),
            .init(color: FlowdKit.fixed(0x18DF9B, 0.14), location: 1)
    ]
    static let flowSoft: LinearGradient = FlowdKit.linear(flowSoftStops, angle: 135)
    static let moneyStops: [Gradient.Stop] = [
            .init(color: FlowdKit.fixed(0x18DF9B), location: 0),
            .init(color: FlowdKit.fixed(0x18DF9B), location: 1)
    ]
    static let money: LinearGradient = FlowdKit.linear(moneyStops, angle: 135)
    static let emberStops: [Gradient.Stop] = [
            .init(color: FlowdKit.fixed(0xFE7A43), location: 0),
            .init(color: FlowdKit.fixed(0xFE7A43), location: 1)
    ]
    static let ember: LinearGradient = FlowdKit.linear(emberStops, angle: 135)
    static let sunStops: [Gradient.Stop] = [
            .init(color: FlowdKit.fixed(0xF8C216), location: 0),
            .init(color: FlowdKit.fixed(0xF8C216), location: 1)
    ]
    static let sun: LinearGradient = FlowdKit.linear(sunStops, angle: 135)
    static let floStops: [Gradient.Stop] = [
            .init(color: FlowdKit.fixed(0x784FFC), location: 0),
            .init(color: FlowdKit.fixed(0x784FFC), location: 1)
    ]
    static let flo: LinearGradient = FlowdKit.linear(floStops, angle: 135)
}

// MARK: - Aurora (L0 background)
// Each orb is a RadialGradient centred at (x, y) as a fraction of the container, with radius = `radius` x the container's longer side.

struct FlowdAuroraStop {
    let opacity: Double
    let location: Double
}

struct FlowdAuroraOrb: Identifiable {
    let id: String
    let color: Color
    let x: CGFloat
    let y: CGFloat
    let radius: CGFloat
    let stops: [FlowdAuroraStop]
}

enum FlowdAurora {
    static let base: Color = FlowdKit.dyn(FlowdKit.ui(0xF3F7FF), FlowdKit.ui(0x000000))
    static let driftSeconds: Double = 90
    static let darkNoiseOpacity: Double = 0
    static let lightNoiseOpacity: Double = 0

    static let darkOrbs: [FlowdAuroraOrb] = [
        FlowdAuroraOrb(id: "violet", color: FlowdKit.fixed(0x6B3FF5), x: 0.06, y: 0, radius: 0.62, stops: [FlowdAuroraStop(opacity: 0, location: 0), FlowdAuroraStop(opacity: 0, location: 0.45), FlowdAuroraStop(opacity: 0, location: 1)]),
        FlowdAuroraOrb(id: "azure", color: FlowdKit.fixed(0x2F7BFF), x: 0.96, y: 0.02, radius: 0.5, stops: [FlowdAuroraStop(opacity: 0, location: 0), FlowdAuroraStop(opacity: 0, location: 0.45), FlowdAuroraStop(opacity: 0, location: 1)]),
        FlowdAuroraOrb(id: "lagoon", color: FlowdKit.fixed(0x19D3E6), x: 0.84, y: 1.06, radius: 0.52, stops: [FlowdAuroraStop(opacity: 0, location: 0), FlowdAuroraStop(opacity: 0, location: 0.45), FlowdAuroraStop(opacity: 0, location: 1)]),
        FlowdAuroraOrb(id: "rose", color: FlowdKit.fixed(0xFF4D8D), x: -0.04, y: 0.98, radius: 0.38, stops: [FlowdAuroraStop(opacity: 0, location: 0), FlowdAuroraStop(opacity: 0, location: 0.45), FlowdAuroraStop(opacity: 0, location: 1)])
    ]
    static let lightOrbs: [FlowdAuroraOrb] = [
        FlowdAuroraOrb(id: "violet", color: FlowdKit.fixed(0xA99CF2), x: 0.06, y: 0, radius: 0.62, stops: [FlowdAuroraStop(opacity: 0, location: 0), FlowdAuroraStop(opacity: 0, location: 0.45), FlowdAuroraStop(opacity: 0, location: 1)]),
        FlowdAuroraOrb(id: "azure", color: FlowdKit.fixed(0x8DB8F5), x: 0.96, y: 0.02, radius: 0.5, stops: [FlowdAuroraStop(opacity: 0, location: 0), FlowdAuroraStop(opacity: 0, location: 0.45), FlowdAuroraStop(opacity: 0, location: 1)]),
        FlowdAuroraOrb(id: "lagoon", color: FlowdKit.fixed(0x7FE3F2), x: 0.84, y: 1.06, radius: 0.52, stops: [FlowdAuroraStop(opacity: 0, location: 0), FlowdAuroraStop(opacity: 0, location: 0.45), FlowdAuroraStop(opacity: 0, location: 1)]),
        FlowdAuroraOrb(id: "rose", color: FlowdKit.fixed(0xF6B3BA), x: -0.04, y: 0.98, radius: 0.38, stops: [FlowdAuroraStop(opacity: 0, location: 0), FlowdAuroraStop(opacity: 0, location: 0.45), FlowdAuroraStop(opacity: 0, location: 1)])
    ]

    static func orbs(isDark: Bool) -> [FlowdAuroraOrb] {
        return isDark ? darkOrbs : lightOrbs
    }
}

// MARK: - Tiers (Bronze -> Elite)

struct FlowdTierStyle: Identifiable {
    let id: String
    let label: String
    let chevrons: Int
    let hasRing: Bool
    let gradient: LinearGradient
    let ink: Color
    let glow: Color
    let rim: Color
}

enum FlowdTier {
    static let bronze: FlowdTierStyle = FlowdTierStyle(
        id: "bronze", label: "Bronze", chevrons: 1, hasRing: false,
        gradient: FlowdKit.linear([
            .init(color: FlowdKit.fixed(0xF2B98A), location: 0),
            .init(color: FlowdKit.fixed(0xC9803F), location: 0.55),
            .init(color: FlowdKit.fixed(0x9A5E2C), location: 1)
        ], angle: 135),
        ink: FlowdKit.fixed(0x2A1405), glow: FlowdKit.fixed(0xC9803F, 0.4), rim: FlowdKit.fixed(0xFFD9B3)
    )
    static let silver: FlowdTierStyle = FlowdTierStyle(
        id: "silver", label: "Silver", chevrons: 2, hasRing: false,
        gradient: FlowdKit.linear([
            .init(color: FlowdKit.fixed(0xF4F7FC), location: 0),
            .init(color: FlowdKit.fixed(0xC3CBDA), location: 0.55),
            .init(color: FlowdKit.fixed(0x8893AA), location: 1)
        ], angle: 135),
        ink: FlowdKit.fixed(0x131B2E), glow: FlowdKit.fixed(0xC3CBDA, 0.38), rim: FlowdKit.fixed(0xFFFFFF)
    )
    static let gold: FlowdTierStyle = FlowdTierStyle(
        id: "gold", label: "Gold", chevrons: 3, hasRing: false,
        gradient: FlowdKit.linear([
            .init(color: FlowdKit.fixed(0xFFEBA3), location: 0),
            .init(color: FlowdKit.fixed(0xF6C23A), location: 0.52),
            .init(color: FlowdKit.fixed(0xC58A00), location: 1)
        ], angle: 135),
        ink: FlowdKit.fixed(0x2F1F00), glow: FlowdKit.fixed(0xF6C23A, 0.46), rim: FlowdKit.fixed(0xFFF6CF)
    )
    static let platinum: FlowdTierStyle = FlowdTierStyle(
        id: "platinum", label: "Platinum", chevrons: 4, hasRing: false,
        gradient: FlowdKit.linear([
            .init(color: FlowdKit.fixed(0xF6FCFF), location: 0),
            .init(color: FlowdKit.fixed(0xBDD8F6), location: 0.38),
            .init(color: FlowdKit.fixed(0xC2B2F8), location: 0.7),
            .init(color: FlowdKit.fixed(0x9FEAF5), location: 1)
        ], angle: 135),
        ink: FlowdKit.fixed(0x14223F), glow: FlowdKit.fixed(0x9FC8F5, 0.46), rim: FlowdKit.fixed(0xFFFFFF)
    )
    static let elite: FlowdTierStyle = FlowdTierStyle(
        id: "elite", label: "Elite", chevrons: 4, hasRing: true,
        gradient: FlowdKit.linear([
            .init(color: FlowdKit.fixed(0xFFF1B8), location: 0),
            .init(color: FlowdKit.fixed(0xFFB347), location: 0.34),
            .init(color: FlowdKit.fixed(0xFF5C8A), location: 0.68),
            .init(color: FlowdKit.fixed(0x8B5CFF), location: 1)
        ], angle: 135),
        ink: FlowdKit.fixed(0x1A0A33), glow: FlowdKit.fixed(0xFF8C5A, 0.55), rim: FlowdKit.fixed(0xFFF4D6)
    )
    static let all: [FlowdTierStyle] = [bronze, silver, gold, platinum, elite]
}

// MARK: - Charts (validated with the dataviz skill; fixed hue order, never cycled)

enum FlowdChart {
    static let categoricalOrder: [String] = ["azure", "ember", "lagoon", "rose", "violet", "sun", "magenta", "green"]
    static let categorical: [Color] = [
        FlowdKit.dyn(FlowdKit.ui(0x186FE2), FlowdKit.ui(0x1A74EC)),
        FlowdKit.dyn(FlowdKit.ui(0xDC6320), FlowdKit.ui(0xE56722)),
        FlowdKit.dyn(FlowdKit.ui(0x28A3B6), FlowdKit.ui(0x29A6BC)),
        FlowdKit.dyn(FlowdKit.ui(0xDE3A46), FlowdKit.ui(0xF04C55)),
        FlowdKit.dyn(FlowdKit.ui(0x6032BB), FlowdKit.ui(0x9778F7)),
        FlowdKit.dyn(FlowdKit.ui(0xD7AB2C), FlowdKit.ui(0xB08B22)),
        FlowdKit.dyn(FlowdKit.ui(0xD25BCB), FlowdKit.ui(0xC54EBE)),
        FlowdKit.dyn(FlowdKit.ui(0x197F1B), FlowdKit.ui(0x1C891E))
    ]
    static let sequential: [Color] = [
        FlowdKit.dyn(FlowdKit.ui(0xD1DEF2), FlowdKit.ui(0x113E88)),
        FlowdKit.dyn(FlowdKit.ui(0xABC7F4), FlowdKit.ui(0x1150B3)),
        FlowdKit.dyn(FlowdKit.ui(0x73A5F9), FlowdKit.ui(0x0E62E1)),
        FlowdKit.dyn(FlowdKit.ui(0x307DFD), FlowdKit.ui(0x307DFD)),
        FlowdKit.dyn(FlowdKit.ui(0x0E62E1), FlowdKit.ui(0x73A5F9)),
        FlowdKit.dyn(FlowdKit.ui(0x1150B3), FlowdKit.ui(0xABC7F4)),
        FlowdKit.dyn(FlowdKit.ui(0x113E88), FlowdKit.ui(0xD1DEF2))
    ]
    static let ordinal: [Color] = [
        FlowdKit.dyn(FlowdKit.ui(0x73A5F9), FlowdKit.ui(0x1150B3)),
        FlowdKit.dyn(FlowdKit.ui(0x307DFD), FlowdKit.ui(0x0E62E1)),
        FlowdKit.dyn(FlowdKit.ui(0x0E62E1), FlowdKit.ui(0x307DFD)),
        FlowdKit.dyn(FlowdKit.ui(0x1150B3), FlowdKit.ui(0x73A5F9)),
        FlowdKit.dyn(FlowdKit.ui(0x113E88), FlowdKit.ui(0xABC7F4))
    ]
    static let diverging: [Color] = [
        FlowdKit.dyn(FlowdKit.ui(0x1150B3), FlowdKit.ui(0x307DFD)),
        FlowdKit.dyn(FlowdKit.ui(0x307DFD), FlowdKit.ui(0x1150B3)),
        FlowdKit.dyn(FlowdKit.ui(0xABC7F4), FlowdKit.ui(0x0E2F65)),
        FlowdKit.dyn(FlowdKit.ui(0xE3E7F0), FlowdKit.ui(0x2A3452)),
        FlowdKit.dyn(FlowdKit.ui(0xF7C8B7), FlowdKit.ui(0x592611)),
        FlowdKit.dyn(FlowdKit.ui(0xFE7A43), FlowdKit.ui(0xAA4619)),
        FlowdKit.dyn(FlowdKit.ui(0xAA4619), FlowdKit.ui(0xFE7A43))
    ]
    static let good: Color = FlowdKit.dyn(FlowdKit.ui(0x20B27C), FlowdKit.ui(0x18DF9B))
    static let warning: Color = FlowdKit.dyn(FlowdKit.ui(0xF8C216), FlowdKit.ui(0xF8C216))
    static let serious: Color = FlowdKit.dyn(FlowdKit.ui(0xFE7A43), FlowdKit.ui(0xFE7A43))
    static let critical: Color = FlowdKit.dyn(FlowdKit.ui(0xDF1B52), FlowdKit.ui(0xFD5170))
    static let surface: Color = FlowdKit.dyn(FlowdKit.ui(0xFFFFFF), FlowdKit.ui(0x101A34))
    static let grid: Color = FlowdKit.dyn(FlowdKit.ui(0x08112A, 0.08), FlowdKit.ui(0xFFFFFF, 0.08))
    static let axis: Color = FlowdKit.dyn(FlowdKit.ui(0x08112A, 0.22), FlowdKit.ui(0xFFFFFF, 0.22))
    static let lineWidth: CGFloat = 2
    static let barRadius: CGFloat = 4
    static let markGap: CGFloat = 2
}

// MARK: - Spacing (4pt grid)

enum FlowdSpacing {
    static let xxs: CGFloat = 4
    static let xs: CGFloat = 8
    static let sm: CGFloat = 12
    static let md: CGFloat = 16
    static let lg: CGFloat = 20
    static let xl: CGFloat = 24
    static let xxl: CGFloat = 32
    static let xxxl: CGFloat = 40
    static let huge: CGFloat = 48
    static let giant: CGFloat = 64
    static let jumbo: CGFloat = 80
    static let mega: CGFloat = 96
    /// n x 4pt
    static func unit(_ n: CGFloat) -> CGFloat {
        return n * 4
    }
}

// MARK: - Radius (concentric: child = parent - padding)

enum FlowdRadius {
    static let sm: CGFloat = 8
    static let md: CGFloat = 12
    static let lg: CGFloat = 16
    static let xl: CGFloat = 20
    static let xxl: CGFloat = 28
    static let xxxl: CGFloat = 36
    static let pill: CGFloat = 9999
    static func concentric(outer: CGFloat, padding: CGFloat) -> CGFloat {
        return max(0, outer - padding)
    }
}

// MARK: - Layout

enum FlowdLayout {
    static let hitTarget: CGFloat = 44
    static let gutter: CGFloat = 16
    static let tabBarHeight: CGFloat = 64
    static let headerHeight: CGFloat = 64
    static let focusRingWidth: CGFloat = 2
}

// MARK: - Elevation
// CSS blur (px) maps to SwiftUI radius = blur / 2. SwiftUI has no spread: use the layers as-is.

struct FlowdShadow {
    let color: Color
    let radius: CGFloat
    let x: CGFloat
    let y: CGFloat
}

enum FlowdElevation {
    static let level1: [FlowdShadow] = [
            FlowdShadow(color: FlowdKit.dyn(FlowdKit.ui(0x162660, 0.06), FlowdKit.ui(0x010414, 0.5)), radius: 1, x: 0, y: 1),
            FlowdShadow(color: FlowdKit.dyn(FlowdKit.ui(0x162660, 0.12), FlowdKit.ui(0x010414, 0.45)), radius: 8, x: 0, y: 6)
        ]
    static let level2: [FlowdShadow] = [
            FlowdShadow(color: FlowdKit.dyn(FlowdKit.ui(0x162660, 0.06), FlowdKit.ui(0x010414, 0.4)), radius: 2, x: 0, y: 2),
            FlowdShadow(color: FlowdKit.dyn(FlowdKit.ui(0x162660, 0.18), FlowdKit.ui(0x010414, 0.6)), radius: 16, x: 0, y: 14)
        ]
    static let level3: [FlowdShadow] = [
            FlowdShadow(color: FlowdKit.dyn(FlowdKit.ui(0x162660, 0.06), FlowdKit.ui(0x010414, 0.4)), radius: 4, x: 0, y: 4),
            FlowdShadow(color: FlowdKit.dyn(FlowdKit.ui(0x162660, 0.24), FlowdKit.ui(0x010414, 0.65)), radius: 24, x: 0, y: 22),
            FlowdShadow(color: FlowdKit.dyn(FlowdKit.ui(0x0E62E1, 0.14), FlowdKit.ui(0x307DFD, 0.16)), radius: 14, x: 0, y: 8)
        ]
    static let level4: [FlowdShadow] = [
            FlowdShadow(color: FlowdKit.dyn(FlowdKit.ui(0x162660, 0.08), FlowdKit.ui(0x010414, 0.45)), radius: 8, x: 0, y: 8),
            FlowdShadow(color: FlowdKit.dyn(FlowdKit.ui(0x162660, 0.32), FlowdKit.ui(0x010414, 0.75)), radius: 40, x: 0, y: 36),
            FlowdShadow(color: FlowdKit.dyn(FlowdKit.ui(0x671AF3, 0.16), FlowdKit.ui(0x784FFC, 0.2)), radius: 20, x: 0, y: 12)
        ]
    static func level(_ n: Int) -> [FlowdShadow] {
        switch n {
        case 1: return level1
        case 2: return level2
        case 3: return level3
        case 4: return level4
        default: return []
        }
    }
    static let glowFlow: Color = FlowdKit.dyn(FlowdKit.ui(0x0E62E1, 0.32), FlowdKit.ui(0x307DFD, 0.5))
    static let glowMint: Color = FlowdKit.dyn(FlowdKit.ui(0x20B27C, 0.3), FlowdKit.ui(0x18DF9B, 0.42))
    static let glowEmber: Color = FlowdKit.dyn(FlowdKit.ui(0xD95715, 0.3), FlowdKit.ui(0xFE7A43, 0.46))
    static let glowSun: Color = FlowdKit.dyn(FlowdKit.ui(0xC59B1D, 0.34), FlowdKit.ui(0xF8C216, 0.46))
    static let glowViolet: Color = FlowdKit.dyn(FlowdKit.ui(0x671AF3, 0.3), FlowdKit.ui(0x784FFC, 0.5))
}

// MARK: - Glass material spec
// iOS 26+: DesignSystem wrappers call glassEffect and ignore blur/fill. iOS 17-25: Material fallback + tint + rim stroke built from this spec.

struct FlowdGlassLayerSpec {
    let id: String
    let defaultRadius: CGFloat
    let blur: CGFloat
    let saturation: Double
    let fill: Color
    let fillOverMedia: Color
    let sheenFrom: Color
    let sheenTo: Color
    let rimFrom: Color
    let rimMid: Color
    let rimTo: Color
    let rimWidth: CGFloat
    let highlight: Color
    let lowlight: Color
    let edge: Color
    let solid: Color
    let shadows: [FlowdShadow]
    let usesGlassEffect: Bool
    let interactive: Bool
    let fallbackMaterial: Material
    let fallbackTintOpacityLight: Double
    let fallbackTintOpacityDark: Double
    let strokeOpacityLight: Double
    let strokeOpacityDark: Double
}

enum FlowdGlassSpec {
    static let l1: FlowdGlassLayerSpec = FlowdGlassLayerSpec(
        id: "L1", defaultRadius: 28, blur: 16, saturation: 1.4,
        fill: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF), FlowdKit.ui(0x1E1E22, 0.62)),
        fillOverMedia: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0.8), FlowdKit.ui(0x18181C, 0.8)),
        sheenFrom: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0.55), FlowdKit.ui(0xFFFFFF, 0.09)), sheenTo: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0), FlowdKit.ui(0xFFFFFF, 0.015)),
        rimFrom: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0.95), FlowdKit.ui(0xFFFFFF, 0.46)), rimMid: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0.45), FlowdKit.ui(0xFFFFFF, 0.12)), rimTo: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0.6), FlowdKit.ui(0xFFFFFF, 0.07)), rimWidth: 1,
        highlight: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0.95), FlowdKit.ui(0xFFFFFF, 0.22)), lowlight: FlowdKit.dyn(FlowdKit.ui(0x08112A, 0.05), FlowdKit.ui(0x000000, 0.28)), edge: FlowdKit.dyn(FlowdKit.ui(0x08112A, 0.08), FlowdKit.ui(0x020514, 0.45)),
        solid: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF), FlowdKit.ui(0x141416)),
        shadows: FlowdElevation.level(2),
        usesGlassEffect: false, interactive: false, fallbackMaterial: .thinMaterial,
        fallbackTintOpacityLight: 0.3, fallbackTintOpacityDark: 0.4,
        strokeOpacityLight: 0.6, strokeOpacityDark: 0.22
    )
    static let l2: FlowdGlassLayerSpec = FlowdGlassLayerSpec(
        id: "L2", defaultRadius: 9999, blur: 24, saturation: 1.6,
        fill: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF), FlowdKit.ui(0x1E1E22, 0.74)),
        fillOverMedia: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0.78), FlowdKit.ui(0x202026, 0.8)),
        sheenFrom: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0.7), FlowdKit.ui(0xFFFFFF, 0.12)), sheenTo: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0.05), FlowdKit.ui(0xFFFFFF, 0.02)),
        rimFrom: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF), FlowdKit.ui(0xFFFFFF, 0.6)), rimMid: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0.5), FlowdKit.ui(0xFFFFFF, 0.16)), rimTo: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0.7), FlowdKit.ui(0xFFFFFF, 0.1)), rimWidth: 1,
        highlight: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF), FlowdKit.ui(0xFFFFFF, 0.34)), lowlight: FlowdKit.dyn(FlowdKit.ui(0x08112A, 0.06), FlowdKit.ui(0x000000, 0.3)), edge: FlowdKit.dyn(FlowdKit.ui(0x08112A, 0.1), FlowdKit.ui(0x020514, 0.5)),
        solid: FlowdKit.dyn(FlowdKit.ui(0xF7F9FF), FlowdKit.ui(0x1C1C20)),
        shadows: FlowdElevation.level(3),
        usesGlassEffect: true, interactive: true, fallbackMaterial: .ultraThinMaterial,
        fallbackTintOpacityLight: 0.28, fallbackTintOpacityDark: 0.34,
        strokeOpacityLight: 0.8, strokeOpacityDark: 0.32
    )
    static let l3: FlowdGlassLayerSpec = FlowdGlassLayerSpec(
        id: "L3", defaultRadius: 36, blur: 40, saturation: 1.5,
        fill: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF), FlowdKit.ui(0x141418, 0.82)),
        fillOverMedia: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0.9), FlowdKit.ui(0x101014, 0.88)),
        sheenFrom: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0.5), FlowdKit.ui(0xFFFFFF, 0.07)), sheenTo: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0.1), FlowdKit.ui(0xFFFFFF, 0.01)),
        rimFrom: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0.95), FlowdKit.ui(0xFFFFFF, 0.34)), rimMid: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0.5), FlowdKit.ui(0xFFFFFF, 0.1)), rimTo: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF, 0.6), FlowdKit.ui(0xFFFFFF, 0.05)), rimWidth: 1,
        highlight: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF), FlowdKit.ui(0xFFFFFF, 0.2)), lowlight: FlowdKit.dyn(FlowdKit.ui(0x08112A, 0.06), FlowdKit.ui(0x000000, 0.35)), edge: FlowdKit.dyn(FlowdKit.ui(0x08112A, 0.12), FlowdKit.ui(0x020514, 0.55)),
        solid: FlowdKit.dyn(FlowdKit.ui(0xFFFFFF), FlowdKit.ui(0x101012)),
        shadows: FlowdElevation.level(4),
        usesGlassEffect: true, interactive: false, fallbackMaterial: .thickMaterial,
        fallbackTintOpacityLight: 0.5, fallbackTintOpacityDark: 0.55,
        strokeOpacityLight: 0.6, strokeOpacityDark: 0.2
    )
    static let scrim: Color = FlowdKit.dyn(FlowdKit.ui(0x08112A, 0.34), FlowdKit.ui(0x000000, 0.62))
    static let pointerSheenRadius: CGFloat = 240
    // Clear glass (Glass.clear): only over media-rich content, under large bold content. Needs the dim layer.
    static let clearBlur: CGFloat = 10
    static let clearSaturation: Double = 1.5
    static let clearTint: Color = FlowdKit.fixed(0xFFFFFF, 0.03)
    static let clearDim: Color = FlowdKit.fixed(0x000000, 0.35)
}

// MARK: - Motion
// Springs are derived from stiffness / damping / mass: response = 2*pi / sqrt(k/m), dampingFraction = c / (2*sqrt(k*m)).

struct FlowdSpringSpec {
    let stiffness: Double
    let damping: Double
    let mass: Double
    let response: Double
    let dampingFraction: Double

    var animation: Animation {
        return Animation.spring(response: response, dampingFraction: dampingFraction)
    }
}

enum FlowdMotion {
    static let instant: TimeInterval = 0.08
    static let fast: TimeInterval = 0.15
    static let base: TimeInterval = 0.22
    static let slow: TimeInterval = 0.32
    static let slower: TimeInterval = 0.48
    static let hero: TimeInterval = 0.8
    static let stagger: TimeInterval = 0.04
    static let tapSpec: FlowdSpringSpec = FlowdSpringSpec(stiffness: 520, damping: 40, mass: 1, response: 0.276, dampingFraction: 0.877)
    static let tap: Animation = tapSpec.animation
    static let snappySpec: FlowdSpringSpec = FlowdSpringSpec(stiffness: 420, damping: 34, mass: 1, response: 0.307, dampingFraction: 0.83)
    static let snappy: Animation = snappySpec.animation
    static let smoothSpec: FlowdSpringSpec = FlowdSpringSpec(stiffness: 320, damping: 30, mass: 1, response: 0.351, dampingFraction: 0.839)
    static let smooth: Animation = smoothSpec.animation
    static let sheetSpec: FlowdSpringSpec = FlowdSpringSpec(stiffness: 380, damping: 36, mass: 1, response: 0.322, dampingFraction: 0.923)
    static let sheet: Animation = sheetSpec.animation
    static let gentleSpec: FlowdSpringSpec = FlowdSpringSpec(stiffness: 240, damping: 26, mass: 1, response: 0.406, dampingFraction: 0.839)
    static let gentle: Animation = gentleSpec.animation
    static let bouncySpec: FlowdSpringSpec = FlowdSpringSpec(stiffness: 300, damping: 22, mass: 1, response: 0.363, dampingFraction: 0.635)
    static let bouncy: Animation = bouncySpec.animation
    static func standard(_ duration: TimeInterval) -> Animation {
        return Animation.timingCurve(0.2, 0, 0, 1, duration: duration)
    }
    static func emphasized(_ duration: TimeInterval) -> Animation {
        return Animation.timingCurve(0.16, 1, 0.3, 1, duration: duration)
    }
    static func decelerate(_ duration: TimeInterval) -> Animation {
        return Animation.timingCurve(0, 0, 0.2, 1, duration: duration)
    }
    static func accelerate(_ duration: TimeInterval) -> Animation {
        return Animation.timingCurve(0.4, 0, 1, 1, duration: duration)
    }
    static func inOut(_ duration: TimeInterval) -> Animation {
        return Animation.timingCurve(0.65, 0, 0.35, 1, duration: duration)
    }
}

// MARK: - Typography
// SF Pro Rounded for display + every number, SF Pro for text, SF Mono for code. Sizes scale with Dynamic Type (ScaledMetric)
// unless `fixed`. Apply with `.flowdText(FlowdFont.title1)`.

struct FlowdTextStyle {
    let size: CGFloat
    let weight: Font.Weight
    let design: Font.Design
    let relativeTo: Font.TextStyle
    let trackingPt: CGFloat
    let lineHeight: CGFloat
    let uppercase: Bool
    let monospacedDigit: Bool
    let fixed: Bool

    /// Unscaled font (use where the modifier cannot be applied).
    var font: Font {
        let f: Font = Font.system(size: size, weight: weight, design: design)
        return monospacedDigit ? f.monospacedDigit() : f
    }

    /// Extra line spacing for a given point size (SF default line height is about 1.2 x size).
    func lineSpacing(for pointSize: CGFloat) -> CGFloat {
        return pointSize * (lineHeight - 1.2)
    }
}

struct FlowdTextModifier: ViewModifier {
    let style: FlowdTextStyle
    @ScaledMetric private var scaledSize: CGFloat

    init(style: FlowdTextStyle) {
        self.style = style
        self._scaledSize = ScaledMetric(wrappedValue: style.size, relativeTo: style.relativeTo)
    }

    func body(content: Content) -> some View {
        let pointSize: CGFloat = style.fixed ? style.size : scaledSize
        let base: Font = Font.system(size: pointSize, weight: style.weight, design: style.design)
        let font: Font = style.monospacedDigit ? base.monospacedDigit() : base
        let textCase: Text.Case? = style.uppercase ? Text.Case.uppercase : nil
        return content
            .font(font)
            .tracking(style.trackingPt)
            .lineSpacing(style.lineSpacing(for: pointSize))
            .textCase(textCase)
    }
}

extension View {
    func flowdText(_ style: FlowdTextStyle) -> some View {
        return modifier(FlowdTextModifier(style: style))
    }
}

enum FlowdFont {
    static let hero: FlowdTextStyle = FlowdTextStyle(size: 56, weight: .heavy, design: .rounded, relativeTo: .largeTitle, trackingPt: -1.8, lineHeight: 1.02, uppercase: false, monospacedDigit: false, fixed: true)
    static let largeTitle: FlowdTextStyle = FlowdTextStyle(size: 34, weight: .bold, design: .rounded, relativeTo: .largeTitle, trackingPt: -0.8, lineHeight: 1.1, uppercase: false, monospacedDigit: false, fixed: false)
    static let title1: FlowdTextStyle = FlowdTextStyle(size: 28, weight: .bold, design: .rounded, relativeTo: .title, trackingPt: -0.5, lineHeight: 1.15, uppercase: false, monospacedDigit: false, fixed: false)
    static let title2: FlowdTextStyle = FlowdTextStyle(size: 22, weight: .bold, design: .rounded, relativeTo: .title2, trackingPt: -0.3, lineHeight: 1.2, uppercase: false, monospacedDigit: false, fixed: false)
    static let title3: FlowdTextStyle = FlowdTextStyle(size: 20, weight: .semibold, design: .rounded, relativeTo: .title3, trackingPt: -0.2, lineHeight: 1.25, uppercase: false, monospacedDigit: false, fixed: false)
    static let headline: FlowdTextStyle = FlowdTextStyle(size: 17, weight: .semibold, design: .default, relativeTo: .headline, trackingPt: -0.2, lineHeight: 1.3, uppercase: false, monospacedDigit: false, fixed: false)
    static let body: FlowdTextStyle = FlowdTextStyle(size: 17, weight: .regular, design: .default, relativeTo: .body, trackingPt: 0, lineHeight: 1.4, uppercase: false, monospacedDigit: false, fixed: false)
    static let callout: FlowdTextStyle = FlowdTextStyle(size: 16, weight: .regular, design: .default, relativeTo: .callout, trackingPt: 0, lineHeight: 1.4, uppercase: false, monospacedDigit: false, fixed: false)
    static let subheadline: FlowdTextStyle = FlowdTextStyle(size: 15, weight: .regular, design: .default, relativeTo: .subheadline, trackingPt: 0, lineHeight: 1.35, uppercase: false, monospacedDigit: false, fixed: false)
    static let footnote: FlowdTextStyle = FlowdTextStyle(size: 13, weight: .regular, design: .default, relativeTo: .footnote, trackingPt: 0, lineHeight: 1.35, uppercase: false, monospacedDigit: false, fixed: false)
    static let caption1: FlowdTextStyle = FlowdTextStyle(size: 12, weight: .medium, design: .default, relativeTo: .caption, trackingPt: 0.1, lineHeight: 1.3, uppercase: false, monospacedDigit: false, fixed: false)
    static let caption2: FlowdTextStyle = FlowdTextStyle(size: 11, weight: .medium, design: .default, relativeTo: .caption2, trackingPt: 0.1, lineHeight: 1.3, uppercase: false, monospacedDigit: false, fixed: false)
    static let overline: FlowdTextStyle = FlowdTextStyle(size: 11, weight: .semibold, design: .default, relativeTo: .caption2, trackingPt: 0.9, lineHeight: 1.2, uppercase: true, monospacedDigit: false, fixed: false)
    static let button: FlowdTextStyle = FlowdTextStyle(size: 16, weight: .semibold, design: .rounded, relativeTo: .body, trackingPt: 0, lineHeight: 1.2, uppercase: false, monospacedDigit: false, fixed: false)
    static let figureHero: FlowdTextStyle = FlowdTextStyle(size: 64, weight: .heavy, design: .rounded, relativeTo: .largeTitle, trackingPt: -2, lineHeight: 1, uppercase: false, monospacedDigit: true, fixed: true)
    static let figureXL: FlowdTextStyle = FlowdTextStyle(size: 44, weight: .bold, design: .rounded, relativeTo: .largeTitle, trackingPt: -1.2, lineHeight: 1, uppercase: false, monospacedDigit: true, fixed: false)
    static let figureLg: FlowdTextStyle = FlowdTextStyle(size: 32, weight: .bold, design: .rounded, relativeTo: .title, trackingPt: -0.7, lineHeight: 1.05, uppercase: false, monospacedDigit: true, fixed: false)
    static let figureMd: FlowdTextStyle = FlowdTextStyle(size: 22, weight: .bold, design: .rounded, relativeTo: .title2, trackingPt: -0.3, lineHeight: 1.1, uppercase: false, monospacedDigit: true, fixed: false)
    static let figureSm: FlowdTextStyle = FlowdTextStyle(size: 15, weight: .semibold, design: .rounded, relativeTo: .subheadline, trackingPt: 0, lineHeight: 1.3, uppercase: false, monospacedDigit: true, fixed: false)
    static let code: FlowdTextStyle = FlowdTextStyle(size: 13, weight: .regular, design: .monospaced, relativeTo: .footnote, trackingPt: 0, lineHeight: 1.4, uppercase: false, monospacedDigit: true, fixed: false)
}

// MARK: - Meta

enum FlowdTheme {
    static let name: String = "Black Glass"
    static let version: String = "1.0.0"
}
