-- flowd tests: the full demo world (supabase/seed.full.sql). GENERATED by supabase/tools/gen-seed.mjs: do not edit.
-- Run with the full seed loaded:  node supabase/tools/verify-pglite.mjs --seed-file seed.full.sql   or   sh supabase/tools/test-psql.sh --seed-full
-- Every expected number below is computed from packages/contract/fixtures by the generator.
begin;

-- 1. the ledger is whole: balanced transactions, escrow reconciled with every bounty, no negative floors (also proven by the deferred triggers at COMMIT)
select tap.ok('audit_ledger is clean after the full seed', (public.audit_ledger() ->> 'ok')::boolean);
select tap.eq('ledger legs / transactions / accounts', (select (select count(*) from public.ledger) || '/' || (select count(*) from public.ledger_transactions) || '/' || (select count(*) from public.ledger_balances))::text, '4275/1633/149');
select tap.eq('the ledger nets to zero across all accounts', (select coalesce(sum(amount_cents), 0) from public.ledger)::text, '0');
select tap.eq('brand wallet balances (fixtures) equal the wallet accounts on the ledger', (select coalesce(sum(amount_cents), 0) from public.ledger where account like 'wallet:%')::text, '505157');

-- 2. one row count per loaded table
select tap.eq('every loaded table holds exactly its fixture rows', (select string_agg(t || '=' || n, ', ' order by t) from (values
    ('activity_log', (select count(*) from public.activity_log))
  , ('ad_daily', (select count(*) from public.ad_daily))
  , ('admin_metrics', (select count(*) from public.admin_metrics))
  , ('ads', (select count(*) from public.ads))
  , ('api_keys', (select count(*) from public.api_keys))
  , ('app_metrics_daily', (select count(*) from public.app_metrics_daily))
  , ('apps', (select count(*) from public.apps))
  , ('attribution_links', (select count(*) from public.attribution_links))
  , ('auction_bids', (select count(*) from public.auction_bids))
  , ('auctions', (select count(*) from public.auctions))
  , ('audit_reports', (select count(*) from public.audit_reports))
  , ('auto_approve_rules', (select count(*) from public.auto_approve_rules))
  , ('bounties', (select count(*) from public.bounties))
  , ('bounty_saves', (select count(*) from public.bounty_saves))
  , ('brand_lists', (select count(*) from public.brand_lists))
  , ('brand_members', (select count(*) from public.brand_members))
  , ('brand_scorecards', (select count(*) from public.brand_scorecards))
  , ('brands', (select count(*) from public.brands))
  , ('case_studies', (select count(*) from public.case_studies))
  , ('changelog', (select count(*) from public.changelog))
  , ('chat_messages', (select count(*) from public.chat_messages))
  , ('compliance_check_items', (select count(*) from public.compliance_check_items))
  , ('compliance_checks', (select count(*) from public.compliance_checks))
  , ('conversions', (select count(*) from public.conversions))
  , ('creator_reputation', (select count(*) from public.creator_reputation))
  , ('creators', (select count(*) from public.creators))
  , ('crew_members', (select count(*) from public.crew_members))
  , ('crews', (select count(*) from public.crews))
  , ('daily_drops', (select count(*) from public.daily_drops))
  , ('dispute_events', (select count(*) from public.dispute_events))
  , ('disputes', (select count(*) from public.disputes))
  , ('drop_claims', (select count(*) from public.drop_claims))
  , ('drop_items', (select count(*) from public.drop_items))
  , ('fatigue_alerts', (select count(*) from public.fatigue_alerts))
  , ('feedback_notes', (select count(*) from public.feedback_notes))
  , ('flo_suggestions', (select count(*) from public.flo_suggestions))
  , ('formats', (select count(*) from public.formats))
  , ('fraud_flags', (select count(*) from public.fraud_flags))
  , ('hooks', (select count(*) from public.hooks))
  , ('integrations', (select count(*) from public.integrations))
  , ('invoices', (select count(*) from public.invoices))
  , ('leaderboard_entries', (select count(*) from public.leaderboard_entries))
  , ('leaderboards', (select count(*) from public.leaderboards))
  , ('ledger', (select count(*) from public.ledger))
  , ('ledger_transactions', (select count(*) from public.ledger_transactions))
  , ('lesson_progress', (select count(*) from public.lesson_progress))
  , ('lessons', (select count(*) from public.lessons))
  , ('market_series', (select count(*) from public.market_series))
  , ('ml_models', (select count(*) from public.ml_models))
  , ('money_clock', (select count(*) from public.money_clock))
  , ('notification_prefs', (select count(*) from public.notification_prefs))
  , ('notifications', (select count(*) from public.notifications))
  , ('offer_code_pool', (select count(*) from public.offer_code_pool))
  , ('offer_messages', (select count(*) from public.offer_messages))
  , ('offers', (select count(*) from public.offers))
  , ('payout_methods', (select count(*) from public.payout_methods))
  , ('payout_runs', (select count(*) from public.payout_runs))
  , ('payouts', (select count(*) from public.payouts))
  , ('post_metrics_daily', (select count(*) from public.post_metrics_daily))
  , ('post_metrics_hourly', (select count(*) from public.post_metrics_hourly))
  , ('posts', (select count(*) from public.posts))
  , ('proofs', (select count(*) from public.proofs))
  , ('qa_checks', (select count(*) from public.qa_checks))
  , ('rate_cards', (select count(*) from public.rate_cards))
  , ('referrals', (select count(*) from public.referrals))
  , ('revenuecat_events', (select count(*) from public.revenuecat_events))
  , ('rights_grants', (select count(*) from public.rights_grants))
  , ('rights_renewals', (select count(*) from public.rights_renewals))
  , ('rule_audit_log', (select count(*) from public.rule_audit_log))
  , ('scam_reports', (select count(*) from public.scam_reports))
  , ('social_accounts', (select count(*) from public.social_accounts))
  , ('spec_licenses', (select count(*) from public.spec_licenses))
  , ('specs', (select count(*) from public.specs))
  , ('state_of_app_ugc', (select count(*) from public.state_of_app_ugc))
  , ('streaks', (select count(*) from public.streaks))
  , ('submission_versions', (select count(*) from public.submission_versions))
  , ('submissions', (select count(*) from public.submissions))
  , ('tax_docs', (select count(*) from public.tax_docs))
  , ('tax_profiles', (select count(*) from public.tax_profiles))
  , ('test_plans', (select count(*) from public.test_plans))
  , ('testimonials', (select count(*) from public.testimonials))
  , ('threads', (select count(*) from public.threads))
  , ('ticker_events', (select count(*) from public.ticker_events))
  , ('tier_history', (select count(*) from public.tier_history))
  , ('tournament_entries', (select count(*) from public.tournament_entries))
  , ('tournaments', (select count(*) from public.tournaments))
  , ('trends', (select count(*) from public.trends))
  , ('users', (select count(*) from public.users))
  , ('verifications', (select count(*) from public.verifications))
  , ('video_analyses', (select count(*) from public.video_analyses))
  , ('view_snapshots', (select count(*) from public.view_snapshots))
  , ('waitlist_entries', (select count(*) from public.waitlist_entries))
  , ('webhook_deliveries', (select count(*) from public.webhook_deliveries))
  , ('webhooks', (select count(*) from public.webhooks))
  , ('wellbeing_settings', (select count(*) from public.wellbeing_settings))
  , ('world', (select count(*) from public.world))
  , ('wrapped', (select count(*) from public.wrapped))
) as c(t, n)), 'activity_log=190, ad_daily=111, admin_metrics=1, ads=9, api_keys=8, app_metrics_daily=1881, apps=25, attribution_links=471, auction_bids=16, auctions=8, audit_reports=8, auto_approve_rules=6, bounties=49, bounty_saves=94, brand_lists=13, brand_members=52, brand_scorecards=22, brands=26, case_studies=6, changelog=14, chat_messages=177, compliance_check_items=3344, compliance_checks=418, conversions=4046, creator_reputation=90, creators=90, crew_members=68, crews=8, daily_drops=35, dispute_events=39, disputes=15, drop_claims=1505, drop_items=209, fatigue_alerts=5, feedback_notes=291, flo_suggestions=62, formats=11, fraud_flags=13, hooks=84, integrations=46, invoices=113, leaderboard_entries=510, leaderboards=25, ledger=4275, ledger_transactions=1633, lesson_progress=294, lessons=10, market_series=819, ml_models=8, money_clock=613, notification_prefs=7, notifications=242, offer_code_pool=109, offer_messages=80, offers=36, payout_methods=75, payout_runs=14, payouts=332, post_metrics_daily=13197, post_metrics_hourly=1372, posts=418, proofs=114, qa_checks=11144, rate_cards=39, referrals=55, revenuecat_events=1487, rights_grants=190, rights_renewals=1, rule_audit_log=19, scam_reports=22, social_accounts=134, spec_licenses=8, specs=30, state_of_app_ugc=1, streaks=73, submission_versions=796, submissions=704, tax_docs=72, tax_profiles=77, test_plans=4, testimonials=8, threads=63, ticker_events=44, tier_history=86, tournament_entries=127, tournaments=8, trends=18, users=144, verifications=40, video_analyses=796, view_snapshots=6669, waitlist_entries=19759, webhook_deliveries=160, webhooks=8, wellbeing_settings=12, world=1, wrapped=6');

-- 3. read models computed by views reproduce the fixture read models
select tap.eq('the demo world is dated 2026-10-03', (select to_char(demo_now at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') from public.world)::text, '2026-10-03T14:00:00Z');
select tap.eq('v_waitlist_totals reproduces the waitlist (creators / brands / invites accepted)', (select creators || '/' || brands || '/' || invites_accepted from public.v_waitlist_totals)::text, '18412/1347/2222');
select tap.eq('v_waitlist_leaders reproduces the top five (handle and referrals)', (select string_agg(handle || ':' || referrals, ',' order by position) from (select * from public.v_waitlist_leaders order by position limit 5) x)::text, 'theo.tests.apps:168,pixel.priya:152,sleepy.sasha:128,sparkloop.studio:112,ravi.reviews:90');
select tap.eq('v_ticker_totals: paid payouts and what they paid', (select payouts_count || '/' || total_paid_cents from public.v_ticker_totals)::text, '286/2628095');
select tap.eq('bounties by status: live / settled / draft', (select (select count(*) from public.bounties where status = 'live') || '/' || (select count(*) from public.bounties where status = 'settled') || '/' || (select count(*) from public.bounties where status = 'draft'))::text, '23/11/2');
select tap.eq('posts by status: live / window_closed / cleared / paid', (select (select count(*) from public.posts where status = 'live') || '/' || (select count(*) from public.posts where status = 'window_closed') || '/' || (select count(*) from public.posts where status = 'cleared') || '/' || (select count(*) from public.posts where status = 'paid'))::text, '30/1/24/348');
select tap.eq('cr_maya: tier, lifetime cleared, approved of decided', (select tier || '/' || lifetime_cleared_cents || '/' || approved_count || '/' || decided_count from public.creators where id = 'cr_maya')::text, 'silver/164000/21/27');
select tap.eq('post_metrics_hourly rows land in their monthly partitions', (select count(*) from public.post_metrics_hourly)::text, '1372');

-- 4. row level security on the full world (the real roles; the numbers are what each persona may see by the policies of 0002_rls.sql)
select tap.as_user_by_auth('5014ee48-6c48-5805-87fc-6511b5b2719c');            -- cr_maya
select tap.eq('the creator sees only her own Money Clock rows', (select count(*) from public.money_clock)::text, '55');
select tap.eq('the creator sees only her own creator-account ledger legs', (select count(*) from public.ledger)::text, '88');
select tap.eq('the creator sees her submissions, posts and payouts', (select (select count(*) from public.submissions) || '/' || (select count(*) from public.posts) || '/' || (select count(*) from public.payouts))::text, '31/20/15');
select tap.eq('the creator sees exactly one creators row (her own) and no brands', (select (select count(*) from public.creators) || '/' || (select count(*) from public.brands))::text, '1/0');
select tap.eq('the creator never sees conversions, API keys or RevenueCat events', (select (select count(*) from public.conversions) || '/' || (select count(*) from public.api_keys) || '/' || (select count(*) from public.revenuecat_events))::text, '0/0/0');
select tap.as_owner();
select tap.as_user_by_auth('db0302c8-6815-5fff-b52a-7f47cf17158f');            -- br_lumi
select tap.eq('the brand member sees one workspace and its one app', (select (select count(*) from public.brands) || '/' || (select count(*) from public.apps))::text, '1/1');
select tap.eq('the brand member sees the wallet and escrow legs of the workspace, not creator or platform legs', (select count(*) from public.ledger)::text, '177');
select tap.eq('the brand member sees the submissions, posts, conversions and RevenueCat events of the app', (select (select count(*) from public.submissions) || '/' || (select count(*) from public.posts) || '/' || (select count(*) from public.conversions) || '/' || (select count(*) from public.revenuecat_events))::text, '113/71/766/439');
select tap.eq('the brand member sees no Money Clock and no payouts', (select (select count(*) from public.money_clock) || '/' || (select count(*) from public.payouts))::text, '0/0');
select tap.as_owner();
select tap.as_user_by_auth('faff34ac-a32a-56f7-b5ac-41c08414a1bb');            -- Ops
select tap.eq('Ops sees every ledger leg, creator and brand', (select (select count(*) from public.ledger) || '/' || (select count(*) from public.creators) || '/' || (select count(*) from public.brands))::text, '4275/90/26');
select tap.as_owner();
select tap.as_anon();
select tap.ok('the public can read the public bounty feed and the waitlist leaders', (select count(*) from public.v_public_bounties) > 0 and (select count(*) from public.v_waitlist_leaders) = 25);
select tap.raises('the public cannot read the ledger', 'select count(*) from public.ledger', '42501');
select tap.raises('the public cannot read users', 'select count(*) from public.users', '42501');
select tap.as_owner();

select 'seed-full/full-world.test.sql: passed' as result;
rollback;
