// API surface summary for the backend agent (openapi.yaml) and the mock API (apps/web/src/app/api/v1).
// Base path /api/v1 on api.joinflowd.io. Resource = fixture entity. This is the contract the clients code against;
// openapi.yaml is the detailed, machine-readable form and must not contradict this file.

export const API_CONVENTIONS = [
  { title: 'Auth', body: 'Bearer session token (demo: POST /auth/demo-login). Roles: public, creator, brand (a brand_member, scoped to their workspace by role), admin. API keys (fd_live_ / fd_test_) act as a brand with scopes read, write, financial; writes made with an API key are drafts by default and money movements need the financial scope.' },
  { title: 'Money and time', body: 'Money is integer cents with a _cents suffix; rates are cpm_cents; ratios are 0..1; timestamps are ISO-8601 UTC with Z; dates YYYY-MM-DD. Every response that shows an earning includes its state, eta_at and reason (Money Clock). No endpoint returns formatted money.' },
  { title: 'Pagination and filters', body: 'Cursor pagination: ?limit= (default 50, max 200) & ?cursor=; responses are { data: [...], next_cursor, total? }. Filters are plain query params named after fields (?status=live&app_id=...&q=...). Sort with ?sort=-created_at. ?expand= takes a comma list of ref fields to inline (e.g. expand=app,brand).' },
  { title: 'Idempotency', body: 'Every POST that moves money or creates a settlement artefact (fund, top-up, decision, payout, accept, claim, webhook ingest) accepts an Idempotency-Key header; repeated keys return the original response. Webhook ingest is idempotent on the RevenueCat event id.' },
  { title: 'Errors', body: 'Non-2xx responses are { code, message, hint } with a stable snake_case code. Common: validation_failed (422), reason_required (422), not_found (404), forbidden (403), tier_locked (403), bounty_not_funded (409), pool_exhausted (409), sla_not_started (409), revision_limit (409), appeal_used (409), below_minimum (422), method_missing (409), tax_info_missing (409), identity_check_required (409), idempotency_conflict (409), rate_limited (429), conflict (409).' },
  { title: 'Demo mode', body: 'The mock API is an in-memory singleton seeded from the fixtures. POST /admin/demo/advance moves the demo clock (24 h / 72 h) and runs window close, fraud check, clearing and the Friday payout when due; POST /admin/demo/reset restores the seed. Responses carry header X-Flowd-Demo: 1.' },
  { title: 'Webhooks (outbound)', body: 'Signed with HMAC-SHA256 in the X-Flowd-Signature header (t=<unix>,v1=<hex>); events are WebhookEventType; deliveries retry with exponential backoff and are listed in the endpoint\'s deliveries.' },
];

const e = (m, p, who, summary, res, errs = '') => ({ m, p, who, summary, res, errs: errs ? errs.split(',').map((s) => s.trim()) : [] });

export const API_GROUPS = [
  { id: 'session', title: 'Session', note: 'Demo role switching and the world manifest.', endpoints: [
    e('POST', '/auth/demo-login', 'public', 'Start a demo session as creator, brand or admin.', 'Session'),
    e('POST', '/auth/logout', 'any', 'End the session.', '204'),
    e('GET', '/me', 'any', 'The signed-in user with role, persona ids and demo flag.', 'Session'),
    e('GET', '/world', 'any', 'World manifest: now, personas, row counts.', 'World'),
    e('GET', '/health', 'public', 'Liveness and demo clock.', 'Health'),
    e('POST', '/events', 'any', 'Analytics events (rules in PRODUCT_SPEC section 10).', '202'),
  ] },
  { id: 'brands', title: 'Apps, brands and team', note: 'Workspaces, apps, members, roles, activity and CRM lists.', endpoints: [
    e('GET', '/apps', 'brand', 'Apps in the workspace.', 'Page<App>'),
    e('POST', '/apps', 'brand', 'Add an app (store URL -> metadata).', 'App', 'validation_failed'),
    e('POST', '/apps/lookup', 'public', 'Resolve an App Store URL to mock metadata and a generated icon.', 'AppLookup', 'validation_failed'),
    e('GET', '/apps/{id}', 'brand', 'App with attribution health.', 'App'),
    e('PATCH', '/apps/{id}', 'brand', 'Update app metadata, MMP, defaults.', 'App'),
    e('GET', '/brands/{id}', 'any', 'Brand profile (public fields for non-members).', 'Brand'),
    e('PATCH', '/brands/{id}', 'brand', 'Update workspace profile, timeout policy, compliance defaults, billing profile.', 'Brand', 'forbidden'),
    e('GET', '/brands/{id}/scorecard', 'any', 'Brand Scorecard (public).', 'BrandScorecard'),
    e('GET', '/brands/{id}/members', 'brand', 'Members and roles.', 'Page<BrandMember>'),
    e('POST', '/brands/{id}/members', 'brand', 'Invite a member (role) or create a client-approval link.', 'BrandMember', 'forbidden,validation_failed'),
    e('PATCH', '/brands/{id}/members/{memberId}', 'brand', 'Change role.', 'BrandMember', 'forbidden'),
    e('DELETE', '/brands/{id}/members/{memberId}', 'brand', 'Remove a member.', '204', 'forbidden'),
    e('GET', '/brands/{id}/activity', 'brand', 'Team activity log (filter by action, member; CSV with ?format=csv).', 'Page<ActivityEntry>'),
    e('GET', '/brands/{id}/lists', 'brand', 'CRM lists.', 'Page<BrandList>'),
    e('POST', '/brands/{id}/lists', 'brand', 'Create a list or add creators.', 'BrandList'),
    e('PATCH', '/brands/{id}/plan', 'brand', 'Change plan (Free, Pro, Scale).', 'Brand', 'forbidden'),
  ] },
  { id: 'bounties', title: 'Bounties', note: 'Builder, lint, price, escrow and lifecycle.', endpoints: [
    e('GET', '/bounties', 'any', 'List bounties (brand: own workspace; creator: visible to them).', 'Page<Bounty>'),
    e('POST', '/bounties', 'brand', 'Create a draft bounty.', 'Bounty', 'validation_failed'),
    e('GET', '/bounties/{id}', 'any', 'Bounty with brief, rights card, pay math, funded flag.', 'Bounty', 'not_found'),
    e('PATCH', '/bounties/{id}', 'brand', 'Edit a draft or an allowed field of a live bounty (extend, caps).', 'Bounty', 'conflict'),
    e('POST', '/bounties/lint', 'brand', 'Brief Lint a brief (same ruleset as the client).', 'BriefLint'),
    e('POST', '/bounties/price', 'brand', 'Pay Math, funding breakdown, all-in CPM and price-vs-fill suggestion.', 'PriceQuote'),
    e('POST', '/bounties/draft', 'brand', 'AI draft from an App Store link (graceful failure -> manual).', 'Bounty'),
    e('POST', '/bounties/{id}/publish', 'brand', 'Publish: lint must pass; moves to awaiting_funding (or live if funded).', 'Bounty', 'validation_failed'),
    e('POST', '/bounties/{id}/fund', 'brand', 'Fund escrow from the wallet (matched budget and fee waiver applied on the first bounty).', 'Bounty', 'below_minimum,idempotency_conflict'),
    e('POST', '/bounties/{id}/top-up', 'brand', 'Add budget to a live bounty.', 'Bounty'),
    e('POST', '/bounties/{id}/pause', 'brand', 'Pause (existing work continues).', 'Bounty'),
    e('POST', '/bounties/{id}/resume', 'brand', 'Resume.', 'Bounty'),
    e('POST', '/bounties/{id}/close', 'brand', 'End now; settlement follows when windows close.', 'Bounty'),
    e('POST', '/bounties/{id}/cancel', 'brand', 'Cancel (only with zero approved submissions); escrow refunded.', 'Bounty', 'conflict'),
    e('POST', '/bounties/{id}/feature', 'brand', 'Pin to the top of the feed (flat weekly fee).', 'Bounty'),
    e('GET', '/bounties/{id}/funnel', 'brand', 'Views to paid funnel, per creator and per video, tracked vs estimated.', 'Funnel'),
    e('GET', '/bounties/{id}/creators', 'brand', 'Creators on the bounty with results.', 'Page<CreatorResult>'),
  ] },
  { id: 'feed', title: 'Feed, Daily Drop and saves', note: 'Creator discovery.', endpoints: [
    e('GET', '/feed', 'creator', 'Ranked bounty feed with match score, expected earnings and gates.', 'Page<FeedItem>'),
    e('GET', '/drops/today', 'creator', 'Today\'s Daily Drop (upcoming, live or sold out) with true spots.', 'DailyDrop'),
    e('GET', '/drops/{id}', 'creator', 'A drop.', 'DailyDrop'),
    e('POST', '/drops/{id}/claim', 'creator', 'Claim a spot (24 h reservation to submit).', 'BountySave', 'tier_locked,pool_exhausted,idempotency_conflict'),
    e('GET', '/saves', 'creator', 'Saved, joined and submitted bounties.', 'Page<BountySave>'),
    e('PUT', '/saves/{bountyId}', 'creator', 'Save or join a bounty.', 'BountySave'),
    e('DELETE', '/saves/{bountyId}', 'creator', 'Unsave.', '204'),
  ] },
  { id: 'submissions', title: 'Submissions and review', note: 'Versioned submissions, timecoded feedback, decisions, appeals, auto-approve.', endpoints: [
    e('GET', '/submissions', 'any', 'Creator: own; brand: for the workspace.', 'Page<Submission>'),
    e('POST', '/submissions', 'creator', 'Submit (creates v1, takes a Reserved Slot).', 'Submission', 'pool_exhausted,tier_locked,validation_failed'),
    e('POST', '/uploads', 'creator', 'Start a resumable upload (returns upload URL and asset id).', 'UploadSession'),
    e('GET', '/submissions/{id}', 'any', 'Submission with versions, decision and notes.', 'Submission'),
    e('GET', '/submissions/{id}/analysis', 'any', 'Video analysis of a version (?version=).', 'VideoAnalysis'),
    e('GET', '/submissions/{id}/notes', 'any', 'Timecoded feedback notes.', 'Page<FeedbackNote>'),
    e('POST', '/submissions/{id}/feedback', 'brand', 'Add a timecoded note (category, severity).', 'FeedbackNote'),
    e('PATCH', '/feedback/{id}', 'any', 'Resolve (creator) or dismiss (brand) a note.', 'FeedbackNote'),
    e('POST', '/submissions/{id}/decision', 'brand', 'Approve, request changes or reject. Rejection needs reason_code and evidence.', 'Submission', 'reason_required,revision_limit,sla_not_started'),
    e('POST', '/submissions/{id}/revise', 'creator', 'Upload the next version (v+1), carrying open must-fix notes.', 'Submission', 'revision_limit'),
    e('POST', '/submissions/{id}/appeal', 'creator', 'One appeal per rejection (Ops decides in 72 h).', 'Dispute', 'appeal_used'),
    e('POST', '/submissions/{id}/withdraw', 'creator', 'Withdraw and release the reservation.', 'Submission'),
    e('POST', '/submissions/{id}/post', 'creator', 'Attach the post URL; opens the 72-hour window.', 'Post', 'validation_failed'),
    e('GET', '/review/queue', 'brand', 'Review queue sorted by QA flags, band, age; fraud-hold lane.', 'Page<ReviewItem>'),
    e('GET', '/review/rules', 'brand', 'Auto-approve rules.', 'Page<AutoApproveRule>'),
    e('PUT', '/review/rules/{id}', 'brand', 'Create or update a rule.', 'AutoApproveRule'),
    e('POST', '/review/rules/dry-run', 'brand', 'Dry run on the last 50 submissions.', 'DryRun'),
    e('POST', '/review/rules/{id}/enable', 'brand', 'Enable (needs a dry run on the current conditions).', 'AutoApproveRule', 'conflict'),
    e('POST', '/review/rules/{id}/kill', 'brand', 'Kill switch.', 'AutoApproveRule'),
  ] },
  { id: 'scoring', title: 'Scoring', note: 'Checklist scores shared with the client engines.', endpoints: [
    e('POST', '/score/hook', 'any', 'Hook Score from observations or an uploaded clip (bands plus timecoded reasons).', 'ScoreCard'),
    e('POST', '/score/flow', 'any', 'Flow Score against a brief and format.', 'ScoreCard'),
    e('POST', '/score/preflight', 'creator', 'Pre-flight: disclosure, music, claims, AI flag, 9:16, length, safe zones.', 'PreflightResult'),
  ] },
  { id: 'posts', title: 'Posts, View Ledger and ledger', note: 'Verified views, snapshots, disputes, double-entry.', endpoints: [
    e('GET', '/posts', 'any', 'Posts (creator: own; brand: workspace).', 'Page<Post>'),
    e('GET', '/posts/{id}', 'any', 'Post with funnel, earnings, fraud assessment, retention.', 'Post'),
    e('GET', '/posts/{id}/ledger', 'creator', 'View Ledger: snapshots, source split, verified vs excluded with the plain-language cause.', 'ViewLedger'),
    e('GET', '/posts/{id}/metrics', 'any', 'Daily (and hourly for recent posts) metrics.', 'PostMetrics'),
    e('POST', '/posts/{id}/dispute', 'creator', 'One-tap dispute with a snapshot range, reason and note.', 'Dispute'),
    e('POST', '/posts/{id}/remove', 'creator', 'Record a deletion (earns nothing if before the window closes).', 'Post'),
    e('GET', '/ledger', 'any', 'Ledger rows (brand: own accounts; creator: own; admin: all) with filters account, bounty, post, type.', 'Page<LedgerEntry>'),
    e('GET', '/ledger/{txnId}', 'any', 'All legs of a transaction.', 'Page<LedgerEntry>'),
  ] },
  { id: 'wallet', title: 'Wallet, Money Clock and payouts', note: 'Pending, cleared and paid with dates and reasons.', endpoints: [
    e('GET', '/wallet', 'any', 'Creator: Money Clock summary; brand: escrow held / reserved / settled / available.', 'Wallet'),
    e('GET', '/money-clock', 'creator', 'Earning rows with state, eta_at and reason.', 'Page<MoneyClockRow>'),
    e('POST', '/wallet/topup', 'brand', 'Fund the wallet by card or bank (mock).', 'Wallet', 'idempotency_conflict'),
    e('PUT', '/wallet/auto-topup', 'brand', 'Auto top-up threshold and amount.', 'AutoTopUp'),
    e('GET', '/payouts', 'creator', 'Payout history and upcoming.', 'Page<Payout>'),
    e('GET', '/payouts/{id}', 'creator', 'A payout with its earning rows and proof.', 'Payout'),
    e('GET', '/payouts/preview', 'creator', 'Instant cash-out preview: fee, net, free allowance, blocked reason.', 'PayoutPreview'),
    e('POST', '/payouts/instant', 'creator', 'Instant cash-out (fee shown first).', 'Payout', 'below_minimum,method_missing,tax_info_missing,identity_check_required'),
    e('GET', '/payout-methods', 'creator', 'Payout methods.', 'Page<PayoutMethod>'),
    e('POST', '/payout-methods', 'creator', 'Add a bank or debit card (Connect sheet, mock).', 'PayoutMethod'),
    e('DELETE', '/payout-methods/{id}', 'creator', 'Remove.', '204'),
    e('GET', '/invoices', 'brand', 'Invoices.', 'Page<Invoice>'),
    e('GET', '/invoices/{id}', 'brand', 'Invoice with lines.', 'Invoice'),
    e('PATCH', '/invoices/{id}', 'brand', 'Edit PO number, cost centre, VAT id.', 'Invoice'),
    e('POST', '/proofs', 'creator', 'Create a public proof page (payout, month, tier-up, wrapped).', 'Proof'),
    e('DELETE', '/proofs/{id}', 'creator', 'Revoke a proof page.', '204'),
  ] },
  { id: 'tax', title: 'Tax Desk', note: 'Just-in-time W-9. Not tax advice.', endpoints: [
    e('GET', '/tax/summary', 'creator', 'Profile, YTD, 1099-NEC threshold progress, set-aside.', 'TaxProfile'),
    e('POST', '/tax/w9', 'creator', 'Submit a W-9 (or W-8BEN).', 'TaxProfile', 'validation_failed'),
    e('PATCH', '/tax/set-aside', 'creator', 'Adjust the set-aside percentage.', 'TaxProfile'),
    e('GET', '/tax/docs', 'creator', 'Collected and issued documents.', 'Page<TaxDoc>'),
    e('GET', '/tax/export.csv', 'creator', 'Earnings CSV for the tax year.', 'text/csv'),
  ] },
  { id: 'market', title: 'Offers, rate cards, auctions, specs and market', note: 'Pricing and trade.', endpoints: [
    e('GET', '/offers', 'any', 'Offers for the signed-in side.', 'Page<Offer>'),
    e('POST', '/offers', 'brand', 'Send an invite, direct offer or re-buy.', 'Offer', 'validation_failed'),
    e('GET', '/offers/{id}', 'any', 'Offer with thread.', 'Offer'),
    e('POST', '/offers/{id}/messages', 'any', 'Message in the thread (in-app only).', 'Offer'),
    e('POST', '/offers/{id}/accept', 'any', 'Accept the latest terms; the brand wallet funds the direct bounty.', 'Offer', 'bounty_not_funded,idempotency_conflict'),
    e('POST', '/offers/{id}/counter', 'any', 'Counter (max 3 rounds).', 'Offer', 'conflict'),
    e('POST', '/offers/{id}/decline', 'any', 'Decline.', 'Offer'),
    e('POST', '/offers/{id}/withdraw', 'brand', 'Withdraw.', 'Offer'),
    e('GET', '/rate-card', 'creator', 'The creator\'s rate card with the market suggestion.', 'RateCard'),
    e('PUT', '/rate-card', 'creator', 'Update the rate card (Silver and above).', 'RateCard', 'tier_locked'),
    e('GET', '/auctions', 'any', 'Auctions (brand sees only its own bid while open).', 'Page<Auction>'),
    e('POST', '/auctions', 'creator', 'Create an auction (Platinum and above).', 'Auction', 'tier_locked'),
    e('GET', '/auctions/{id}', 'any', 'Auction.', 'Auction'),
    e('POST', '/auctions/{id}/bids', 'brand', 'Place a sealed maximum bid (escrow hold).', 'Bid', 'idempotency_conflict'),
    e('DELETE', '/auctions/{id}/bids/{bidId}', 'brand', 'Withdraw a bid before close.', '204'),
    e('POST', '/auctions/{id}/cancel', 'creator', 'Cancel.', 'Auction'),
    e('GET', '/specs', 'any', 'Spec Market (brand: listed specs; creator: own).', 'Page<Spec>'),
    e('POST', '/specs', 'creator', 'Upload a spec.', 'Spec'),
    e('POST', '/specs/{id}/score', 'creator', 'Submit for scoring and listing (Flow points 55+).', 'Spec'),
    e('POST', '/specs/{id}/license', 'brand', 'License a spec (rights, term, price; take rate on top).', 'Spec', 'idempotency_conflict'),
    e('DELETE', '/specs/{id}', 'creator', 'Withdraw.', '204'),
    e('GET', '/market/clearing', 'any', 'Clearing CPM series by category with p25-p75 band.', 'Page<MarketSeriesPoint>'),
    e('POST', '/market/suggest', 'brand', 'Suggested CPM and price-vs-fill curve with confidence.', 'PriceSuggestion'),
    e('GET', '/market/ticker', 'public', 'Public payout ticker (ledger-backed).', 'Ticker'),
    e('GET', '/report/state-of-app-ugc', 'public', 'State of App UGC report.', 'StateOfAppUgc'),
  ] },
  { id: 'attribution', title: 'Attribution Kit', note: 'Links, codes, RevenueCat ingest. CPA pays only on link and code.', endpoints: [
    e('GET', '/r/{code}', 'public', 'Resolve a tracking code (landing data) and log a click.', 'LinkResolution', 'not_found'),
    e('POST', '/attribution/events', 'public', 'SDK first-launch attribute write (code, install id).', '202'),
    e('POST', '/webhooks/revenuecat', 'public', 'RevenueCat webhook ingest (idempotent on event id, signature checked).', 'RevenueCatEvent'),
    e('GET', '/attribution/health', 'brand', 'Coverage meter, last event, SDK status, code pool usage.', 'AttributionHealth'),
    e('GET', '/attribution/codes', 'brand', 'Offer-code pool.', 'Page<OfferCode>'),
    e('POST', '/attribution/codes/rotate', 'brand', 'Rotate codes (respecting the 10-per-SKU cap).', 'Page<OfferCode>'),
    e('POST', '/attribution/test-event', 'brand', 'Send a test conversion through the pipeline.', 'RevenueCatEvent'),
    e('GET', '/conversions', 'brand', 'Conversions by source and confidence.', 'Page<Conversion>'),
  ] },
  { id: 'rights', title: 'Rights, promotion and fatigue', note: 'Rights Vault, Spark and partnership permissions, Winner promotion.', endpoints: [
    e('GET', '/rights', 'any', 'Rights grants (creator: my licences; brand: Rights Vault with expiry buckets).', 'Page<RightsGrant>'),
    e('POST', '/rights/{id}/renew', 'brand', 'Request renewal (25% of base fee per 30 days; price preview).', 'RightsGrant'),
    e('POST', '/rights/{id}/permission', 'creator', 'Grant or decline a Spark code / partnership permission.', 'RightsGrant'),
    e('POST', '/rights/{id}/revoke', 'any', 'Revoke for misuse beyond the Rights Card.', 'RightsGrant'),
    e('GET', '/promotions', 'brand', 'Ads.', 'Page<Ad>'),
    e('POST', '/promotions', 'brand', 'Promote a winner (creator consent -> platform permission).', 'Ad', 'forbidden,conflict'),
    e('POST', '/promotions/{id}/launch', 'brand', 'Launch an authorised ad.', 'Ad'),
    e('POST', '/promotions/{id}/pause', 'brand', 'Pause or resume.', 'Ad'),
    e('POST', '/promotions/{id}/stop', 'brand', 'Stop.', 'Ad'),
    e('GET', '/fatigue-alerts', 'brand', 'Fatigue alerts.', 'Page<FatigueAlert>'),
    e('POST', '/fatigue-alerts/{id}/refresh', 'brand', 'Create a refresh bounty from a fatigued winner.', 'Bounty'),
    e('POST', '/fatigue-alerts/{id}/dismiss', 'brand', 'Dismiss.', 'FatigueAlert'),
    e('GET', '/test-plans', 'brand', 'Hook x body x CTA plans.', 'Page<TestPlan>'),
    e('POST', '/test-plans', 'brand', 'Create a plan.', 'TestPlan'),
    e('GET', '/library', 'brand', 'Creative Intelligence Library: tagged posts, hook leaderboards.', 'Page<LibraryItem>'),
    e('GET', '/compliance', 'brand', 'Compliance audits.', 'Page<ComplianceAudit>'),
    e('POST', '/compliance/{id}/waive', 'brand', 'Waive a failed check with a logged reason.', 'ComplianceAudit'),
  ] },
  { id: 'people', title: 'Creators, reputation and progression', note: 'Profiles, tiers, streaks, leaderboards, crews, tournaments, Academy, referrals.', endpoints: [
    e('GET', '/creators', 'brand', 'Discover creators with filters (niche, tier, approval, reliability, platform, price, US audience).', 'Page<CreatorCard>'),
    e('GET', '/creators/{idOrHandle}', 'any', 'Creator profile (public fields; verified stats).', 'Creator'),
    e('GET', '/creators/{id}/reputation', 'any', 'Reputation with components and reasons.', 'CreatorReputation'),
    e('PATCH', '/me/profile', 'creator', 'Update handle, bio, niches, portfolio, storefront.', 'Creator', 'validation_failed'),
    e('GET', '/social-accounts', 'creator', 'Linked accounts with Account Health.', 'Page<SocialAccount>'),
    e('POST', '/social-accounts', 'creator', 'Link an account (mock OAuth, read-only).', 'SocialAccount'),
    e('DELETE', '/social-accounts/{id}', 'creator', 'Disconnect.', '204'),
    e('GET', '/tiers', 'any', 'Tier thresholds and perks (from constants).', 'Tiers'),
    e('GET', '/tiers/me', 'creator', 'Progress, history, grace hold.', 'TierStatus'),
    e('GET', '/streaks/me', 'creator', 'Weekly streak, freezes, history.', 'Streak'),
    e('POST', '/streaks/rest-week', 'creator', 'Declare a rest week.', 'Streak', 'conflict'),
    e('GET', '/leaderboards', 'creator', 'Cohort, niche and global boards (?scope=, ?metric=).', 'Page<Leaderboard>'),
    e('GET', '/tournaments', 'any', 'Tournaments.', 'Page<Tournament>'),
    e('GET', '/tournaments/{id}', 'any', 'Tournament with rounds and standings.', 'Tournament'),
    e('POST', '/tournaments/{id}/entries', 'creator', 'Enter (submit a hook).', 'TournamentEntry', 'tier_locked'),
    e('GET', '/crews', 'creator', 'Crews (mine, discover).', 'Page<Crew>'),
    e('POST', '/crews', 'creator', 'Create a crew (Gold and above).', 'Crew', 'tier_locked'),
    e('POST', '/crews/{id}/join', 'creator', 'Join.', 'CrewMember'),
    e('POST', '/crews/{id}/leave', 'creator', 'Leave.', '204'),
    e('GET', '/referrals', 'any', 'My referrals and reward window.', 'Page<Referral>'),
    e('POST', '/referrals', 'any', 'Create an invite.', 'Referral'),
    e('GET', '/academy', 'creator', 'Lessons with progress.', 'Page<Lesson>'),
    e('GET', '/academy/{slug}', 'creator', 'A lesson.', 'Lesson'),
    e('POST', '/academy/{slug}/complete', 'creator', 'Submit the quiz; award the badge.', 'LessonProgress'),
    e('GET', '/remix', 'creator', 'Formats, hooks and trends for the Remix library.', 'RemixLibrary'),
    e('GET', '/wrapped', 'creator', 'Wrapped recaps (?period=month|year).', 'Page<Wrapped>'),
    e('GET', '/threads', 'any', 'Inbox threads.', 'Page<ChatThread>'),
    e('POST', '/threads/{id}/messages', 'any', 'Send a message (in-app only; Scam Shield screens it).', 'ChatThread'),
    e('GET', '/notifications', 'any', 'Notifications.', 'Page<Notification>'),
    e('POST', '/notifications/read', 'any', 'Mark read.', '204'),
    e('GET', '/settings/notifications', 'any', 'Notification preferences.', 'NotificationPrefs'),
    e('PUT', '/settings/notifications', 'any', 'Update.', 'NotificationPrefs'),
    e('GET', '/settings/wellbeing', 'creator', 'Wellbeing Mode.', 'WellbeingSettings'),
    e('PUT', '/settings/wellbeing', 'creator', 'Update (quiet hours, numbers-off, pace, pause, rest weeks).', 'WellbeingSettings'),
    e('POST', '/verifications', 'any', 'Start an ID / age / business / tax / payout-method verification.', 'Verification'),
  ] },
  { id: 'flo', title: 'Flo and free tools', note: 'Mock engine behind an AIProvider; public tools need no auth.', endpoints: [
    e('POST', '/flo/chat', 'any', 'Flo copilot (Server-Sent Events stream; outputs recorded as flo_suggestions).', 'SSE<FloSuggestion>'),
    e('POST', '/tools/hook-score', 'public', 'Free Hook Score from text or analysed clip observations.', 'ScoreCard'),
    e('POST', '/tools/app-audit', 'public', 'Free App UGC Audit from an App Store link.', 'AuditReport'),
    e('GET', '/audits/{slug}', 'public', 'Shareable audit report.', 'AuditReport'),
    e('POST', '/tools/earnings', 'public', 'Earnings calculator (p25 / median / p75).', 'EarningsEstimate'),
    e('POST', '/tools/budget', 'public', 'Smart Budget planner bands.', 'BudgetPlan'),
    e('POST', '/tools/price', 'public', 'All-in price calculator by plan.', 'PriceComparison'),
  ] },
  { id: 'safety', title: 'Safety', note: 'Scam Shield.', endpoints: [
    e('POST', '/reports', 'any', 'Report a brand, bounty, creator, message or offer (returns case id and SLA).', 'ScamReport'),
    e('GET', '/reports/mine', 'any', 'My reports and status.', 'Page<ScamReport>'),
    e('GET', '/disputes', 'any', 'Disputes and appeals visible to me.', 'Page<Dispute>'),
    e('GET', '/disputes/{id}', 'any', 'Dispute with timeline.', 'Dispute'),
    e('POST', '/disputes/{id}/events', 'any', 'Reply or add evidence.', 'Dispute'),
  ] },
  { id: 'developers', title: 'Developers and integrations', note: 'API keys, webhooks, MCP, integrations.', endpoints: [
    e('GET', '/api-keys', 'brand', 'Keys (prefix and last four only).', 'Page<ApiKey>'),
    e('POST', '/api-keys', 'brand', 'Create (secret shown once).', 'ApiKeyCreated', 'forbidden'),
    e('DELETE', '/api-keys/{id}', 'brand', 'Revoke.', '204'),
    e('GET', '/webhook-endpoints', 'brand', 'Endpoints with recent deliveries.', 'Page<Webhook>'),
    e('POST', '/webhook-endpoints', 'brand', 'Create.', 'Webhook'),
    e('POST', '/webhook-endpoints/{id}/test', 'brand', 'Send a test event.', 'WebhookDelivery'),
    e('POST', '/mcp', 'brand', 'MCP server (JSON-RPC 2.0): tools create_bounty, fund_bounty, list_submissions, decide_submission, get_funnel; writes are drafts unless the key has financial scope.', 'JsonRpc'),
    e('GET', '/integrations', 'brand', 'Integrations and status.', 'Page<Integration>'),
    e('POST', '/integrations/{kind}/connect', 'brand', 'Connect (mock OAuth / key).', 'Integration'),
    e('DELETE', '/integrations/{id}', 'brand', 'Disconnect.', '204'),
  ] },
  { id: 'admin', title: 'Admin', note: 'Control tower and queues. Role admin only.', endpoints: [
    e('GET', '/admin/targets', 'admin', 'Control tower: targets vs actuals, market health, queues, next payout run.', 'AdminMetrics'),
    e('GET', '/admin/fraud', 'admin', 'Fraud queue sorted by risk and money at stake.', 'Page<FraudFlag>'),
    e('GET', '/admin/fraud/{id}', 'admin', 'Fraud case with evidence.', 'FraudFlag'),
    e('POST', '/admin/fraud/{id}/decision', 'admin', 'Clear, hold, claw back or ban with a reason (audited).', 'FraudFlag', 'reason_required'),
    e('GET', '/admin/disputes', 'admin', 'Dispute queue with SLA timers.', 'Page<Dispute>'),
    e('POST', '/admin/disputes/{id}/decision', 'admin', 'Resolve: upheld, partially upheld, rejected; release to next payout.', 'Dispute', 'reason_required'),
    e('GET', '/admin/verification', 'admin', 'Verification queue (creator ID, brand business, tax).', 'Page<Verification>'),
    e('POST', '/admin/verification/{id}/decision', 'admin', 'Approve, request info or reject with a reason code.', 'Verification', 'reason_required'),
    e('GET', '/admin/payouts', 'admin', 'Payout runs, holds, failures, instant volume.', 'Page<PayoutRun>'),
    e('POST', '/admin/payouts/{id}/release', 'admin', 'Release a hold.', 'Payout'),
    e('GET', '/admin/ledger', 'admin', 'Ledger explorer with balance proof and anomaly detector.', 'LedgerExplorer'),
    e('GET', '/admin/sla', 'admin', 'Review SLA desk: stale and breached submissions.', 'Page<Submission>'),
    e('POST', '/admin/sla/{submissionId}/approve-if-clean', 'admin', 'Approve if every QA check passes.', 'Submission'),
    e('GET', '/admin/safety', 'admin', 'Scam reports queue.', 'Page<ScamReport>'),
    e('POST', '/admin/safety/{id}/action', 'admin', 'Triage, confirm, takedown, strike or suspend.', 'ScamReport'),
    e('GET', '/admin/ml', 'admin', 'Model monitoring and calibration.', 'Page<MlModel>'),
    e('GET', '/admin/bounties', 'admin', 'Bounty registry.', 'Page<Bounty>'),
    e('GET', '/admin/creators', 'admin', 'Creator registry.', 'Page<Creator>'),
    e('GET', '/admin/brands', 'admin', 'Brand registry.', 'Page<Brand>'),
    e('POST', '/admin/tier-override', 'admin', 'Override a tier (logged).', 'Creator', 'reason_required'),
    e('POST', '/admin/demo/advance', 'admin', 'Advance the demo clock by 24 h or 72 h and run due jobs.', 'World'),
    e('POST', '/admin/demo/reset', 'admin', 'Reset to the seed.', 'World'),
  ] },
  { id: 'public', title: 'Public pages', note: 'Unauthenticated, cacheable.', endpoints: [
    e('GET', '/public/bounties/{id}', 'public', 'Public bounty page data.', 'Bounty'),
    e('GET', '/public/creators/{handle}', 'public', 'Storefront with verified stats.', 'Storefront'),
    e('GET', '/public/proofs/{id}', 'public', 'Proof page (always with the tier median line).', 'Proof'),
    e('GET', '/public/scorecards/{brandId}', 'public', 'Public Brand Scorecard.', 'BrandScorecard'),
    e('GET', '/public/tournaments/{id}', 'public', 'Public tournament page.', 'Tournament'),
    e('GET', '/public/waitlist', 'public', 'Waitlist totals and leaders.', 'Waitlist'),
    e('POST', '/public/waitlist', 'public', 'Join the waitlist (email, kind, referral code).', 'WaitlistJoined'),
    e('GET', '/public/changelog', 'public', 'Changelog.', 'Page<ChangelogEntry>'),
    e('GET', '/public/case-studies', 'public', 'Case studies and testimonials.', 'CaseStudies'),
  ] },
];

export const API_TYPES_NOTE = 'Response names that are not fixture entities (Session, Funnel, PriceQuote, FeedItem, ReviewItem, ViewLedger, Wallet, PayoutPreview, LinkResolution, AttributionHealth, ...) are API read-models composed from entities; openapi.yaml defines them. They never add new money fields: every amount is reproducible from the entities.';
