// Entities: the marketplace work graph. Bounty -> Submission (versions) -> Post -> metrics / conversions / ads.
import { entity, req, opt } from './dsl.mjs';

export const ENTITIES_WORK = [
  entity('Bounty', 'bnty', 'A funded offer to creators. Cannot be live until fully escrowed (the Funded badge). Money fields reconcile with the ledger: escrow_funded = reserved + spent + remaining + refunded.', [
    req('id', 'id'),
    req('app_id', 'ref:apps'),
    req('brand_id', 'ref:brands', 'Denormalised from the app.'),
    opt('owner_member_id', 'ref:brand_members', 'The one named owner of the review queue for this bounty. Absent on platform bounties.'),
    opt('created_by_member_id', 'ref:brand_members'),
    req('title', 'string'),
    req('type', 'enum:BountyType'),
    req('status', 'enum:BountyStatus'),
    req('visibility', 'enum:Visibility'),
    req('funding_source', 'enum:FundingSource'),
    req('is_first_bounty', 'bool', 'The brand\'s first bounty: fee waived and matched budget up to $500.'),
    req('is_starter', 'bool', 'A flowd-funded small starter bounty for new creators (First-Dollar Path).'),
    req('featured', 'bool', 'Pinned at the top of the feed (flat weekly fee).'),
    opt('featured_until', 'iso'),
    // rates
    req('cpm_cents', 'cents', 'Cents per 1,000 verified views inside the 72h window. 0 for cpa, install_only and direct.'),
    req('cpa_install_cents', 'cents'),
    req('cpa_trial_cents', 'cents'),
    req('cpa_paid_cents', 'cents'),
    req('flat_fee_cents', 'cents', 'Direct bounties only; 0 otherwise.'),
    req('ad_commission_rate', 'ratio', '0.10 default; applies if the post is promoted as an ad (60 days).'),
    req('per_video_cap_cents', 'cents', 'Max pool pay (CPM + CPA) for one post. Default $250.'),
    opt('per_creator_cap_cents', 'cents'),
    // money
    req('budget_cents', 'cents', 'The creator-pay pool B.'),
    req('take_rate', 'ratio', 'Plan take rate at funding time (12% / 10% / 8%, 6% for cpa / install_only, 0 when waived).'),
    req('fee_reserve_cents', 'cents', 'round(budget_cents x take_rate). Held in escrow with the budget.'),
    req('escrow_funded_cents', 'cents', 'Total locked in escrow: wallet funding plus matched_cents. 0 until funded.'),
    req('matched_cents', 'cents', 'flowd matched budget included in escrow_funded_cents.'),
    req('funded', 'bool', 'The Funded badge. True when escrow_funded_cents >= budget_cents + fee_reserve_cents.'),
    opt('funded_at', 'iso'),
    req('reserved_cents', 'cents', 'Sum of open submissions\' reserved_cents.'),
    req('spent_cents', 'cents', 'Creator pay + fees already settled out of escrow.'),
    req('remaining_cents', 'cents', 'Unreserved, unspent escrow available for new reservations.'),
    req('refunded_cents', 'cents', 'Returned to the wallet at settlement. 0 until settled.'),
    // content
    req('brief', 'obj:Brief'),
    req('rights_card', 'obj:RightsCard'),
    req('deliverables', 'obj:Deliverables'),
    req('eligibility', 'obj:Eligibility'),
    req('brief_lint', 'obj:BriefLint'),
    opt('lint_overrides', 'obj:LintOverride[]', 'Ops overrides of lint findings (admin log).'),
    req('pay_math', 'obj:PayMath'),
    req('format_ids', 'enum:FormatId[]', 'Recommended formats, best first.'),
    req('art', 'art', 'Generated bounty cover.'),
    // schedule
    req('starts_at', 'iso'),
    req('ends_at', 'iso'),
    opt('published_at', 'iso'),
    opt('first_submission_at', 'iso'),
    opt('filled_at', 'iso', 'When remaining_cents first fell below one reservation unit.'),
    opt('time_to_fill_hours', 'number'),
    opt('ended_at', 'iso'),
    opt('settled_at', 'iso'),
    req('review_sla_hours', 'int', 'Default 72.'),
    // results
    req('counts', 'obj:BountyCounts'),
    req('funnel', 'obj:FunnelCounts', 'Lifetime funnel of the bounty\'s posts.'),
    req('all_in_cpm_cents', 'cents', 'The brand\'s all-in effective CPM: round(card_charge x cpm / budget) (FORMULAS: funding). 0 when cpm_cents is 0 (cpa, install_only, direct).'),
    req('created_at', 'iso'),
    req('updated_at', 'iso'),
  ], { table: 'bounties', owner: 'core', group: 'Bounties' }),

  entity('Submission', 'sub', 'A creator\'s video for a bounty. Versioned: v2 does not overwrite v1. Takes a reservation of the per-video cap on submit.', [
    req('id', 'id'),
    req('bounty_id', 'ref:bounties'),
    req('creator_id', 'ref:creators'),
    req('brand_id', 'ref:brands'),
    req('app_id', 'ref:apps'),
    req('status', 'enum:SubmissionStatus'),
    req('version', 'int', 'Current version number (1-based). Equals versions.length.'),
    req('versions', 'obj:SubmissionVersion[]', 'All versions, oldest first.'),
    req('source', 'enum:SubmissionSource'),
    opt('format_id', 'enum:FormatId'),
    req('title', 'string', 'Short internal title, e.g. "Confession hook v2".'),
    req('revision_round', 'int', 'Revision rounds used (0 to 2 free; more are paid by the brand).'),
    req('reserved_cents', 'cents', 'Reservation held against the bounty pool: per_video_cap x (1 + take_rate) while open; 0 once settled, rejected or withdrawn.'),
    req('flow_band', 'enum:ScoreBand', 'Current version.'),
    req('flow_points', 'int'),
    req('hook_band', 'enum:ScoreBand'),
    req('hook_points', 'int'),
    req('rights_card', 'obj:RightsCard', 'Snapshot of the bounty Rights Card the creator accepted at submit; later edits to the bounty do not change it.'),
    req('rights_accepted_at', 'iso', 'Equals submitted_at.'),
    req('fraud_evidence', 'obj:FraudEvidence'),
    req('submitted_at', 'iso', 'First submission time (v1).'),
    opt('sla_due_at', 'iso', 'submitted_at of the current version + review_sla_hours. Present while in review.'),
    req('sla_state', 'enum:SlaState'),
    opt('sla_breached_at', 'iso'),
    opt('decision', 'obj:Decision', 'The latest decision.'),
    req('auto_approved', 'bool'),
    opt('approved_at', 'iso'),
    opt('post_id', 'ref:posts'),
    opt('link_id', 'ref:attribution_links', 'Issued at approval.'),
    opt('posted_at', 'iso'),
    opt('released_at', 'iso'),
    req('updated_at', 'iso'),
  ], { table: 'submissions', owner: 'core', group: 'Submissions' }),

  entity('VideoAnalysis', 'va', 'Machine analysis of one submission version: transcript, scenes, beats, hook, QA checks and checklist scores. One row per (submission, version).', [
    req('id', 'id', 'va_<submission number>_v<version>.'),
    req('submission_id', 'ref:submissions'),
    req('version', 'int'),
    req('duration_ms', 'int'),
    req('language', 'string'),
    req('transcript', 'obj:TranscriptSegment[]'),
    req('transcript_text', 'text', 'The segments joined with spaces.'),
    req('on_screen_text', 'obj:OnScreenText[]'),
    req('scenes', 'obj:SceneCut[]'),
    req('hook', 'obj:HookAnalysis'),
    req('beats', 'obj:BeatHit[]'),
    req('tags', 'obj:VideoTags'),
    req('checks', 'obj:QaCheck[]', 'One entry per QaCheckType that ran.'),
    req('hook_score', 'obj:ScoreCard', 'Hook Score checklist (weights sum to 100).'),
    req('flow_score', 'obj:ScoreCard', 'Flow Score checklist (weights sum to 100).'),
    req('phash', 'string', '16 hex chars: perceptual hash for duplicate detection.'),
    opt('duplicate_of_submission_id', 'ref:submissions'),
    req('analysed_at', 'iso'),
  ], { table: 'video_analyses', owner: 'core', group: 'Submissions' }),

  entity('Post', 'post', 'A posted video on a creator\'s own account. Opens the 72-hour view window. Money legs settle on the ledger.', [
    req('id', 'id'),
    req('submission_id', 'ref:submissions'),
    req('creator_id', 'ref:creators'),
    req('brand_id', 'ref:brands'),
    req('app_id', 'ref:apps'),
    req('bounty_id', 'ref:bounties'),
    req('social_account_id', 'ref:social_accounts'),
    req('platform', 'enum:Platform'),
    req('platform_post_id', 'string', 'Fictional platform id.'),
    req('url', 'string', 'Fictional post URL on the platform domain (text only).'),
    req('caption', 'text', 'Includes the auto-disclosure (#ad + brand wording).'),
    req('hashtags', 'string[]'),
    req('thumb', 'art'),
    req('duration_ms', 'int'),
    req('posted_at', 'iso'),
    req('window_ends_at', 'iso', 'posted_at + 72 hours.'),
    req('status', 'enum:PostStatus'),
    opt('hold_reason', 'enum:HoldReason', 'Required when status = held.'),
    opt('cleared_at', 'iso'),
    opt('paid_at', 'iso'),
    opt('removed_at', 'iso'),
    req('tracking_link_id', 'ref:attribution_links'),
    opt('promo_code', 'string'),
    req('views', 'int', 'Latest verified views (lifetime, as of now). Equals the sum of post_metrics_daily.views; never less than window_views and never less than the last view snapshot.'),
    req('window_views', 'int', 'Verified views counted for CPM pay: views at window_ends_at (or so far, while live). Never more than views.'),
    req('views_invalid', 'int', 'Views reversed after proven fraud (0 normally).'),
    req('likes', 'int'),
    req('comments', 'int'),
    req('shares', 'int'),
    req('saves', 'int'),
    req('retention', 'obj:Retention'),
    req('funnel', 'obj:FunnelCounts', 'Lifetime funnel. Equals the sum of post_metrics_daily and tracked conversions.'),
    req('earnings', 'obj:EarningsBreakdown'),
    req('fraud', 'obj:FraudAssessment'),
    req('flow_band', 'enum:ScoreBand', 'Band at submission.'),
    opt('ad_id', 'ref:ads'),
    req('is_winner', 'bool', 'Flagged as a winner (top decile on trial rate for its bounty); eligible for Winner promotion.'),
    opt('why_it_won', 'string[]', 'Plain-English "why it won" reasons written after settlement, e.g. "Hook landed at 1.4 s", "App on screen by 0:02".'),
    req('tags', 'obj:VideoTags'),
  ], { table: 'posts', owner: 'core', group: 'Posts' }),

  entity('ViewSnapshot', 'vsn', 'A View Ledger snapshot: a timestamped, source-labelled view count of a post. 13 snapshots across the 72h window (every 6h, t = 0..72h, fewer while the window is still open), then one every 7 days until now. The snapshot at window_ends_at has views_verified equal to the post\'s window_views.', [
    req('id', 'id'),
    req('post_id', 'ref:posts'),
    req('taken_at', 'iso'),
    req('views_reported', 'int', 'What the platform reported.'),
    req('views_verified', 'int', 'After fraud filtering. Non-decreasing per post.'),
    req('views_invalid', 'int', 'Cumulative views excluded at this snapshot: views_reported - views_verified.'),
    opt('exclusions', 'obj:ViewExclusion[]', 'Why views were excluded, in plain words. When present, the views add up to views_invalid.'),
    req('delta_verified', 'int', 'views_verified minus the previous snapshot.'),
    req('source', 'enum:SnapshotSource'),
    opt('sources', 'map:ratio', 'Traffic-source mix summing to 1.', { keys: 'TrafficSource' }),
    opt('geo', 'map:ratio', 'Audience country mix summing to 1.', { keys: 'Country' }),
    req('flags', 'enum:SnapshotFlag[]'),
    req('fraud_score', 'int'),
    opt('note', 'string'),
  ], { table: 'view_snapshots', owner: 'core', group: 'Posts' }),

  entity('PostMetricsDaily', null, 'Per-post daily metrics (UTC day). Sums equal the post\'s lifetime numbers. Key: (post_id, date).', [
    req('post_id', 'ref:posts'),
    req('date', 'date'),
    req('views', 'int'),
    req('likes', 'int'),
    req('comments', 'int'),
    req('shares', 'int'),
    req('saves', 'int'),
    req('clicks', 'int', 'Tracked visits (link clicks + code lookups).'),
    req('installs', 'int', 'Tracked (link + code) installs.'),
    req('trials', 'int'),
    req('paid', 'int'),
    req('est_installs', 'int', 'MMP + survey + modelled.'),
    req('est_trials', 'int'),
    req('est_paid', 'int'),
  ], { table: 'post_metrics_daily', owner: 'core', key: ['post_id', 'date'], group: 'Posts' }),

  entity('PostMetricsHourly', null, 'Per-post hourly deltas for the most recent days (UTC dates from 2026-09-30 to now), the training-data grain. Sums over a UTC day equal the daily row. Key: (post_id, ts).', [
    req('post_id', 'ref:posts'),
    req('ts', 'iso', 'Start of the hour.'),
    req('views', 'int', 'Views during this hour (delta).'),
    req('likes', 'int'),
    req('comments', 'int'),
    req('shares', 'int'),
    req('fraud_score', 'int'),
  ], { table: 'post_metrics_hourly', owner: 'core', key: ['post_id', 'ts'], group: 'Posts' }),

  entity('AppMetricsDaily', null, 'Per-app daily rollup of post metrics and spend (derived; equals the sum of its posts\' daily rows). Key: (app_id, date).', [
    req('app_id', 'ref:apps'),
    req('date', 'date'),
    req('views', 'int'),
    req('clicks', 'int'),
    req('installs', 'int'),
    req('trials', 'int'),
    req('paid', 'int'),
    req('est_installs', 'int'),
    req('est_trials', 'int'),
    req('est_paid', 'int'),
    req('revenue_cents', 'cents', 'First-payment revenue of tracked paid conversions that day.'),
    req('posts_live', 'int', 'Posts in their window that day.'),
    req('new_posts', 'int'),
    req('new_submissions', 'int'),
    req('approvals', 'int'),
    req('creator_pay_cents', 'cents', 'Creator earnings settled out of escrow that day.'),
    req('fee_cents', 'cents', 'Platform fees settled that day.'),
  ], { table: 'app_metrics_daily', owner: 'core', key: ['app_id', 'date'], group: 'Posts' }),

  entity('Conversion', 'conv', 'A batch of identical funnel events: (post, kind, source, UTC day). quantity > 1 means several events. CPA is paid only when source is link or code.', [
    req('id', 'id'),
    req('post_id', 'ref:posts'),
    req('link_id', 'ref:attribution_links'),
    req('app_id', 'ref:apps'),
    req('bounty_id', 'ref:bounties'),
    req('creator_id', 'ref:creators'),
    req('kind', 'enum:ConversionKind'),
    req('source', 'enum:ConversionSource'),
    req('confidence', 'enum:ConversionConfidence', 'link/code = deterministic, mmp = matched, survey = self_reported, modelled = modelled.'),
    req('quantity', 'int', '>= 1.'),
    req('occurred_on', 'date'),
    req('first_at', 'iso'),
    req('revenue_cents', 'cents', 'Gross first-payment revenue of the batch (paid only; 0 otherwise).'),
    opt('country', 'enum:Country'),
    req('status', 'enum:ConversionStatus'),
    req('payable', 'bool', 'True only for deterministic sources that are not rejected or refunded.'),
    req('capped', 'bool', 'The per-video cap stopped CPA pay for (part of) this batch.'),
    opt('cleared_at', 'iso'),
    opt('ledger_txn_id', 'string', 'The cpa settlement transaction (txn_<n>).'),
    opt('reject_reason', 'string'),
  ], { table: 'conversions', owner: 'core', group: 'Attribution' }),

  entity('AttributionLink', 'lnk', 'A per-creator, per-bounty tracking link (deferred deep link) plus an optional promo code. Issued at approval.', [
    req('id', 'id'),
    req('creator_id', 'ref:creators'),
    req('bounty_id', 'ref:bounties'),
    req('app_id', 'ref:apps'),
    opt('post_id', 'ref:posts', 'Set when the post exists.'),
    req('code', 'string', 'Short slug, e.g. "maya-lumi7". Unique.'),
    req('short_url', 'string', 'joinflowd.io/r/<code>.'),
    req('deep_link', 'string', 'Fictional app scheme, e.g. "lumi://r/maya-lumi7".'),
    opt('promo_code', 'string', 'From the offer-code pool, e.g. "MAYA-LUMI". Pooled and rotated, not one code per creator forever.'),
    req('status', 'enum:AttributionLinkStatus'),
    req('created_at', 'iso'),
    req('clicks', 'int', 'Equals the post funnel clicks.'),
    req('installs', 'int'),
    req('trials', 'int'),
    req('paid', 'int'),
    opt('last_click_at', 'iso'),
  ], { table: 'attribution_links', owner: 'core', group: 'Attribution' }),

  entity('Ad', 'ad', 'Winner promotion: an organic post run as a Spark / partnership ad. Commission is 10% of ad-attributed revenue for 60 days; the platform fee is 1% of spend.', [
    req('id', 'id'),
    req('post_id', 'ref:posts'),
    req('brand_id', 'ref:brands'),
    req('app_id', 'ref:apps'),
    req('bounty_id', 'ref:bounties'),
    req('creator_id', 'ref:creators'),
    req('platform', 'enum:AdPlatform'),
    req('kind', 'enum:AdKind'),
    req('status', 'enum:AdStatus'),
    opt('external_ad_id', 'string', 'Fictional ad-platform id.'),
    opt('spark_code', 'string', 'Fictional Spark authorization code.'),
    opt('code_duration_days', 'int', 'One of 7, 30, 60, 365.'),
    opt('code_expires_at', 'iso'),
    req('permission_requested_at', 'iso'),
    opt('permission_granted_at', 'iso'),
    opt('started_at', 'iso'),
    opt('ended_at', 'iso'),
    req('daily_budget_cents', 'cents'),
    req('spend_cents', 'cents', 'Lifetime spend. Equals the sum of daily.spend_cents.'),
    req('impressions', 'int'),
    req('clicks', 'int'),
    req('installs', 'int'),
    req('trials', 'int'),
    req('paid', 'int'),
    req('revenue_cents', 'cents', 'Ad-attributed revenue (lifetime).'),
    req('commission_rate', 'ratio'),
    opt('commission_window_ends_at', 'iso', 'started_at + 60 days.'),
    req('commission_cents', 'cents', 'Commission accrued inside the window: commission_rate x revenue inside the window.'),
    req('platform_fee_cents', 'cents', '1% of spend_cents.'),
    req('daily', 'obj:AdDaily[]'),
    opt('fatigue', 'obj:FatigueInfo'),
    opt('rights_ends_at', 'iso', 'Ads stop automatically at this time.'),
  ], { table: 'ads', owner: 'core', group: 'Ads' }),
];
