// Entities: market (offers, auctions, specs) and rights. Owner ext.
import { entity, req, opt } from './dsl.mjs';

export const ENTITIES_MARKET = [
  entity('Offer', 'offer', 'An offer between a brand and a creator: an invite to an open bounty, a direct offer bought from a rate card, or a re-buy of a winner. Carries the negotiation thread (max 3 counter rounds, 7-day expiry). Accepting a direct offer funds a private direct bounty from the brand wallet.', [
    req('id', 'id'),
    req('kind', 'enum:OfferKind'),
    req('status', 'enum:OfferStatus', 'Says who has the ball: awaiting_creator or awaiting_brand.'),
    req('brand_id', 'ref:brands'),
    req('app_id', 'ref:apps'),
    req('creator_id', 'ref:creators'),
    req('created_by_member_id', 'ref:brand_members'),
    req('title', 'string', 'e.g. "Two new hooks on Glow-up reveal".'),
    opt('bounty_id', 'ref:bounties', 'Invite: the open bounty. Direct / re-buy: the private direct bounty, set when the offer is accepted.'),
    opt('rate_card_id', 'ref:rate_cards', 'The rate card the offer was bought from.'),
    opt('rebuy_of_post_id', 'ref:posts', 'Re-buy: the winning post the new hooks are based on.'),
    req('amount_cents', 'cents', 'Current total price for the deliverables (the latest counter). 0 for invites, which pay the bounty\'s rates.'),
    req('original_amount_cents', 'cents', 'The opening amount.'),
    opt('ask_cents', 'cents', 'The creator\'s rate-card ask at the time, for comparison.'),
    opt('suggested', 'obj:RateSuggestion', 'The market-suggested band shown inside the offer.'),
    req('take_rate', 'ratio', 'Brand plan take rate applied on top of the amount.'),
    req('all_in_cents', 'cents', 'amount_cents + round(amount_cents x take_rate): what the brand pays in total.'),
    req('deliverables', 'obj:Deliverables'),
    req('rights_card', 'obj:RightsCard'),
    req('turnaround_days', 'int'),
    req('message', 'text', 'The brand\'s opening note.'),
    req('rounds', 'int', 'Counter rounds used (0 to 3).'),
    req('escrow_funded', 'bool', 'True once the brand wallet funded the direct bounty (on accept).'),
    req('thread', 'obj:OfferMessage[]', 'Oldest first. The first message is the opening offer.'),
    req('expires_at', 'iso', 'created_at + 7 days (reset on each counter).'),
    req('created_at', 'iso'),
    req('updated_at', 'iso'),
    opt('accepted_at', 'iso'),
    opt('closed_at', 'iso', 'Declined, expired, withdrawn or completed.'),
  ], { table: 'offers', owner: 'ext', group: 'Market' }),

  entity('Auction', 'auc', 'A creator\'s sealed-bid auction for a few weekly slots (Platinum and Elite). Second price: the k highest bids win and all pay the highest losing bid, or the reserve if no losing bid exists.', [
    req('id', 'id'),
    req('creator_id', 'ref:creators'),
    req('title', 'string'),
    req('description', 'text'),
    req('status', 'enum:AuctionStatus'),
    req('slots', 'int', '1 to 5.'),
    req('reserve_cents', 'cents', 'Minimum bid and the clearing price floor.'),
    req('deliverables', 'obj:Deliverables'),
    req('rights_card', 'obj:RightsCard'),
    req('opens_at', 'iso'),
    req('closes_at', 'iso', 'At least 72 hours after opens_at, at most 7 days.'),
    req('art', 'art'),
    req('bids', 'obj:Bid[]', 'All bids. Sealed: the API only shows a brand its own bid until the auction closes.'),
    req('bids_count', 'int'),
    opt('clearing_price_cents', 'cents', 'The uniform price winners pay. Set when awarded.'),
    opt('winning_bid_ids', 'string[]'),
    opt('resulting_bounty_ids', 'ref:bounties[]', 'The private direct bounties created for the winners.'),
    opt('awarded_at', 'iso'),
    req('created_at', 'iso'),
    req('updated_at', 'iso'),
  ], { table: 'auctions', owner: 'ext', group: 'Market' }),

  entity('Spec', 'spec', 'A pre-made, pre-scored video that brands can license off the shelf (Spec Market). Either made speculatively by a creator or released from a bounty after 30 unused days (the original brand keeps first refusal for 7 days).', [
    req('id', 'id'),
    req('creator_id', 'ref:creators'),
    req('title', 'string'),
    req('description', 'text'),
    req('status', 'enum:SpecStatus'),
    req('source', 'enum:SpecSource'),
    req('art', 'art', 'Generated spec cover.'),
    req('video', 'obj:VideoMeta'),
    opt('format_id', 'enum:FormatId'),
    req('hook_text', 'string'),
    req('hook_type', 'enum:HookType'),
    req('category', 'enum:Category', 'Best-fit app category.'),
    req('flow_band', 'enum:ScoreBand'),
    req('flow_points', 'int', 'Must be 55 or more to list.'),
    req('hook_band', 'enum:ScoreBand'),
    req('hook_points', 'int'),
    req('qa_pass', 'int'),
    req('qa_warn', 'int'),
    req('qa_fail', 'int'),
    req('tags', 'obj:VideoTags'),
    req('price_cents', 'cents', 'Licence price to the creator (the brand pays the take rate on top).'),
    req('paid_ads_days', 'int', 'Paid-ad usage included. Default 90.'),
    req('exclusive', 'bool'),
    req('rights_card', 'obj:RightsCard'),
    req('stats', 'obj:SpecStats'),
    req('licenses', 'obj:SpecLicense[]', 'stats.licenses equals licenses.length.'),
    opt('source_submission_id', 'ref:submissions', 'Released-from-bounty specs only.'),
    opt('source_bounty_id', 'ref:bounties'),
    opt('source_brand_id', 'ref:brands', 'The brand holding first refusal.'),
    opt('first_refusal_ends_at', 'iso', 'released_at + 7 days.'),
    opt('listed_at', 'iso'),
    req('created_at', 'iso'),
    req('updated_at', 'iso'),
  ], { table: 'specs', owner: 'ext', group: 'Market' }),

  entity('RightsGrant', 'rg', 'A usage-rights grant on a post: organic (always), paid-ad usage (default 90 days), a Spark code or a partnership permission. Powers the Rights Vault with expiry alerts at 30, 14 and 7 days.', [
    req('id', 'id'),
    req('post_id', 'ref:posts'),
    req('submission_id', 'ref:submissions'),
    req('bounty_id', 'ref:bounties'),
    req('brand_id', 'ref:brands'),
    req('app_id', 'ref:apps'),
    req('creator_id', 'ref:creators'),
    req('scope', 'enum:RightsScope'),
    req('status', 'enum:RightsGrantStatus'),
    opt('platform', 'enum:AdPlatform'),
    opt('spark_code', 'string', 'Fictional Spark authorization code (spark_code scope).'),
    opt('code_duration_days', 'int', 'One of 7, 30, 60, 365.'),
    req('starts_at', 'iso'),
    opt('ends_at', 'iso', 'Absent for organic posting, which has no end.'),
    req('base_fee_cents', 'cents', 'The fee renewals are priced from: the post\'s settled creator pay (or the flat fee for direct bounties).'),
    req('renewal_pct_per_30d', 'ratio', 'Default 0.25.'),
    req('renewal_price_cents', 'cents', 'round(base_fee_cents x renewal_pct_per_30d) per 30 days.'),
    req('renewals', 'obj:Renewal[]'),
    req('alerts_sent', 'int[]', 'Subset of 30, 14, 7: the expiry alerts already sent.'),
    opt('ad_id', 'ref:ads', 'The ad that depends on this grant.'),
    req('ai_likeness', 'bool', 'Always false in this build.'),
    opt('revoked_at', 'iso'),
    opt('revoke_reason', 'string'),
    req('created_at', 'iso'),
    req('updated_at', 'iso'),
  ], { table: 'rights_grants', owner: 'ext', group: 'Rights' }),
];
