// Entities: trust and safety (feedback, disputes, scam reports, fraud flags, verification, tax, compliance) and payout runs.
// Owner ext.
import { entity, req, opt } from './dsl.mjs';

export const ENTITIES_TRUST = [
  entity('FeedbackNote', 'note', 'A timecoded feedback note on a submission version: anchored to a moment in the video, with a category and a severity. Must-fix notes carry over to the next version until the creator ticks them off. Qa_checks live inside video_analyses.checks.', [
    req('id', 'id'),
    req('submission_id', 'ref:submissions'),
    req('bounty_id', 'ref:bounties'),
    req('creator_id', 'ref:creators'),
    req('version', 'int', 'The submission version the note was written on.'),
    req('author_member_id', 'ref:brand_members'),
    req('t_ms', 'int', 'Position in the video.'),
    opt('t_end_ms', 'int', 'End of a range, when the note covers a span.'),
    req('category', 'enum:FeedbackCategory'),
    req('severity', 'enum:FeedbackSeverity'),
    req('status', 'enum:FeedbackStatus'),
    req('body', 'text', 'About the video, never the person.'),
    opt('reason_code', 'enum:ReasonCode', 'Set when the note supports a request-changes or reject decision.'),
    opt('resolved_in_version', 'int'),
    opt('resolved_at', 'iso'),
    req('created_at', 'iso'),
  ], { table: 'feedback_notes', owner: 'ext', group: 'Submissions' }),

  entity('Dispute', 'disp', 'A dispute or appeal. One-tap from a post or a rejection; a human replies within 24 hours and resolves within 5 business days. Undisputed money is never blocked by a dispute on other items.', [
    req('id', 'id'),
    req('kind', 'enum:DisputeKind'),
    req('status', 'enum:DisputeStatus'),
    req('opened_by', 'enum:PartyKind'),
    opt('creator_id', 'ref:creators'),
    req('brand_id', 'ref:brands', 'The brand on the other side of the dispute.'),
    opt('bounty_id', 'ref:bounties'),
    opt('submission_id', 'ref:submissions', 'Required for rejection_appeal.'),
    opt('post_id', 'ref:posts'),
    opt('payout_id', 'ref:payouts'),
    opt('rejection_reason_code', 'enum:ReasonCode', 'rejection_appeal: the code being appealed.'),
    opt('range_from', 'iso', 'Snapshot range the dispute covers (view_count and flagged_botting).'),
    opt('range_to', 'iso'),
    req('reason', 'string'),
    req('note', 'text'),
    req('evidence', 'obj:Evidence[]', 'Ledger and snapshot evidence attached automatically.'),
    req('amount_in_dispute_cents', 'cents'),
    req('events', 'obj:DisputeEvent[]', 'Timeline, oldest first.'),
    req('opened_at', 'iso'),
    req('reply_due_at', 'iso', 'opened_at + 24 hours.'),
    opt('first_reply_at', 'iso'),
    req('resolution_due_at', 'iso', 'opened_at + 5 days (appeals: + 72 hours).'),
    opt('resolved_at', 'iso'),
    opt('outcome', 'enum:DisputeOutcome'),
    opt('outcome_text', 'text'),
    opt('adjustment_cents', 'cents', 'Amount released or reversed on a (partly) upheld outcome.'),
    opt('assigned_admin_user_id', 'ref:users'),
    req('updated_at', 'iso'),
  ], { table: 'disputes', owner: 'ext', group: 'Trust' }),

  entity('ScamReport', 'scam', 'A Scam Shield report from a creator or brand about a brand, bounty, creator, message or offer. Triage SLA 24 hours.', [
    req('id', 'id'),
    req('case_id', 'string', '"SR-2026-0042".'),
    req('reporter_kind', 'enum:PartyKind'),
    opt('reporter_creator_id', 'ref:creators'),
    opt('reporter_brand_id', 'ref:brands'),
    req('target_kind', 'enum:ReportTargetKind'),
    req('target_id', 'string', 'The id of the target (brand, bounty, creator, message or offer).'),
    req('reason', 'enum:ScamReason'),
    req('description', 'text'),
    req('evidence_refs', 'string[]', 'Message ids or screenshot names (mock).'),
    req('status', 'enum:ReportStatus'),
    req('created_at', 'iso'),
    req('sla_due_at', 'iso', 'created_at + 24 hours.'),
    opt('triaged_at', 'iso'),
    opt('resolved_at', 'iso'),
    opt('action_taken', 'string', 'e.g. "Brand suspended, bounty removed".'),
    opt('assigned_admin_user_id', 'ref:users'),
  ], { table: 'scam_reports', owner: 'ext', group: 'Trust' }),

  entity('FraudFlag', 'flag', 'A post in the admin fraud queue (fraud score 40 or above): evidence, money at stake and the decision. Delivered legitimate views are always paid; only proven fraud is clawed back.', [
    req('id', 'id'),
    req('post_id', 'ref:posts'),
    req('creator_id', 'ref:creators'),
    req('brand_id', 'ref:brands'),
    req('bounty_id', 'ref:bounties'),
    req('status', 'enum:FraudFlagStatus'),
    req('score', 'int', 'Equals the post\'s fraud.score at flag time.'),
    req('band', 'enum:FraudBand'),
    req('signals', 'obj:FraudSignalHit[]'),
    req('curve_shape', 'enum:CurveShape'),
    req('curve', 'obj:HourlyEnvelope'),
    req('money_at_stake_cents', 'cents'),
    req('hold_placed', 'bool'),
    opt('duplicate_of_post_id', 'ref:posts'),
    req('audience_us_ratio', 'ratio'),
    req('account_age_days', 'int'),
    req('opened_at', 'iso'),
    req('sla_due_at', 'iso', 'opened_at + 24 hours.'),
    opt('reviewed_at', 'iso'),
    opt('reviewed_by_user_id', 'ref:users'),
    opt('decision_note', 'text'),
    opt('invalid_views', 'int', 'Views reversed when confirmed.'),
  ], { table: 'fraud_flags', owner: 'ext', group: 'Trust' }),

  entity('Verification', 'ver', 'An item in the admin verification queue: creator identity / age, brand business, tax, or payout method. Just-in-time for creators (at first approval).', [
    req('id', 'id'),
    req('subject_kind', 'enum:PartyKind'),
    opt('creator_id', 'ref:creators'),
    opt('brand_id', 'ref:brands'),
    req('kind', 'enum:VerificationKind'),
    req('status', 'enum:VerificationStatus'),
    req('provider', 'string', 'e.g. "Stripe Identity (mock)".'),
    req('documents', 'obj:DocRef[]'),
    req('submitted_at', 'iso'),
    req('sla_due_at', 'iso', 'submitted_at + 24 hours.'),
    opt('decided_at', 'iso'),
    opt('decided_by_user_id', 'ref:users'),
    opt('reason', 'enum:VerificationReason', 'Required when needs_info or rejected.'),
    opt('note', 'text'),
    req('blocks_payout', 'bool', 'True while the item holds money (creators) or the Verified badge (brands).'),
  ], { table: 'verifications', owner: 'ext', group: 'Trust' }),

  entity('TaxProfile', 'taxp', 'A creator\'s Tax Desk profile: just-in-time W-9 or W-8BEN, year-to-date totals, 1099-NEC threshold progress and the set-aside estimate. Not tax advice.', [
    req('id', 'id'),
    req('creator_id', 'ref:creators'),
    req('status', 'enum:TaxStatus'),
    opt('form', 'enum:TaxForm'),
    opt('legal_name', 'string'),
    opt('entity_type', 'enum:TaxEntityType'),
    opt('tin_last4', 'string', 'Only the last four digits are ever stored.'),
    opt('address', 'obj:Address'),
    req('country', 'enum:Country'),
    req('tax_year', 'int', '2026.'),
    req('ytd_cleared_cents', 'cents', 'Cleared and paid earnings in the tax year (excludes carry-over).'),
    req('ytd_paid_cents', 'cents'),
    req('threshold_cents', 'cents', '200000 ($2,000 for 2026 payments).'),
    req('threshold_progress', 'ratio', 'ytd_paid_cents / threshold_cents, capped at 1.'),
    req('form_1099_required', 'bool', 'US creators at or above the threshold.'),
    req('set_aside_rate', 'ratio', 'The creator\'s set-aside percentage (default 0.25).'),
    req('set_aside_cents', 'cents', 'round(ytd_cleared_cents x set_aside_rate).'),
    opt('requested_at', 'iso', 'First approval time.'),
    opt('submitted_at', 'iso'),
    opt('verified_at', 'iso'),
    opt('expires_at', 'iso', 'W-8BEN: three years after signing.'),
    req('updated_at', 'iso'),
  ], { table: 'tax_profiles', owner: 'ext', group: 'Trust' }),

  entity('TaxDoc', 'taxd', 'A tax document: a collected W-9 or W-8BEN, or an issued 1099-NEC.', [
    req('id', 'id'),
    req('creator_id', 'ref:creators'),
    req('kind', 'enum:TaxDocKind'),
    req('status', 'enum:TaxDocStatus'),
    req('tax_year', 'int'),
    opt('amount_cents', 'cents', '1099-NEC box 1.'),
    req('file_ref', 'string', 'Mock file name, e.g. "W9-cr_maya.pdf".'),
    req('created_at', 'iso'),
    opt('issued_at', 'iso'),
  ], { table: 'tax_docs', owner: 'ext', group: 'Trust' }),

  entity('ComplianceAudit', 'cc', 'The post-level compliance audit (disclosure audio + on-screen, caption, platform label, music, banned claims, AI label, tracking link). A failure blocks settlement until fixed or waived with a logged reason.', [
    req('id', 'id'),
    req('post_id', 'ref:posts'),
    req('submission_id', 'ref:submissions'),
    req('bounty_id', 'ref:bounties'),
    req('brand_id', 'ref:brands'),
    req('creator_id', 'ref:creators'),
    req('checks', 'obj:ComplianceCheckItem[]', 'One item per ComplianceCheckType (8).'),
    req('overall', 'enum:ComplianceResult', 'fail if any check failed, else warn if any warned, else pass.'),
    req('blocks_settlement', 'bool', 'True when overall is fail and not waived or fixed.'),
    req('checked_at', 'iso'),
    opt('waived_by_member_id', 'ref:brand_members'),
    opt('waive_reason', 'string'),
    opt('fixed_at', 'iso'),
  ], { table: 'compliance_checks', owner: 'ext', group: 'Trust' }),

  entity('PayoutRun', 'run', 'A weekly payout run: Fridays 18:00 UTC. A projection of the payouts it created, with named holds. id = run_<YYYY-MM-DD> of the Friday.', [
    req('id', 'id', 'run_<YYYY-MM-DD>.'),
    req('run_date', 'date'),
    req('scheduled_for', 'iso', 'Friday 18:00:00Z.'),
    req('status', 'enum:RunStatus'),
    req('payouts_count', 'int', 'Equals the count of payouts with this run_id.'),
    req('total_gross_cents', 'cents'),
    req('total_fee_cents', 'cents', 'Always 0 for weekly runs.'),
    req('total_net_cents', 'cents'),
    req('paid_count', 'int'),
    req('failed_count', 'int'),
    req('held_count', 'int'),
    req('held_cents', 'cents'),
    req('holds', 'obj:HoldSummary[]'),
    opt('initiated_at', 'iso'),
    opt('completed_at', 'iso'),
  ], { table: 'payout_runs', owner: 'ext', group: 'Money' }),
];
