// Entities: the money graph and market read-models. Owner core.
import { entity, req, opt } from './dsl.mjs';

export const ENTITIES_MONEY = [
  entity('LedgerEntry', 'ledg', 'One leg of a double-entry transaction. Rows with the same txn_id sum to exactly 0 (signed amounts: credit +, debit -). Append-only: only status, cleared_at, paid_at and payout_id change.', [
    req('id', 'id'),
    req('txn_id', 'string', '"txn_<n>". All legs of one transaction share it; the legs net to 0.'),
    req('entry_type', 'enum:LedgerType'),
    req('account', 'string', '"<kind>:<id>": wallet:br_x | escrow:bnty_x | creator:cr_x | platform:fees|subscriptions|matching|promo|processing | external:card|bank.'),
    req('amount_cents', 'int', 'Signed. Credit to the account is positive.'),
    req('status', 'enum:LedgerStatus', 'Meaningful on creator-account earning rows; everything else is cleared (or paid once withdrawn).'),
    req('posted_at', 'iso'),
    opt('cleared_at', 'iso'),
    opt('paid_at', 'iso'),
    opt('brand_id', 'ref:brands'),
    opt('bounty_id', 'ref:bounties'),
    opt('post_id', 'ref:posts'),
    opt('submission_id', 'ref:submissions'),
    opt('creator_id', 'ref:creators'),
    opt('conversion_id', 'ref:conversions'),
    opt('ad_id', 'ref:ads'),
    opt('payout_id', 'ref:payouts'),
    opt('invoice_id', 'ref:invoices'),
    opt('reverses_txn_id', 'string', 'Set on clawback rows.'),
    req('memo', 'string', 'Plain-English line shown in the wallet ledger.'),
  ], { table: 'ledger', owner: 'core', group: 'Money' }),

  entity('Payout', 'pay', 'Money leaving flowd to a creator\'s bank. Weekly (Fri 18:00 UTC, free) or instant (1.5% fee, min $0.50, max $15).', [
    req('id', 'id'),
    req('creator_id', 'ref:creators'),
    req('kind', 'enum:PayoutKind'),
    req('status', 'enum:PayoutStatus'),
    req('gross_cents', 'cents', 'Sum of the cleared earning rows included.'),
    req('fee_cents', 'cents', 'Instant fee; 0 for weekly and for free instant perks.'),
    req('net_cents', 'cents', 'gross_cents - fee_cents.'),
    opt('run_id', 'string', 'Weekly run id "run_YYYY-MM-DD" (the Friday). Matches payout_runs.'),
    req('requested_at', 'iso'),
    req('scheduled_for', 'iso', 'For weekly: the Friday 18:00 UTC run. For instant: requested_at.'),
    opt('initiated_at', 'iso'),
    opt('paid_at', 'iso'),
    opt('failed_reason', 'string'),
    opt('hold_reason', 'enum:HoldReason'),
    req('method_label', 'string', 'e.g. "Bank account ••4821".'),
    opt('stripe_transfer_id', 'string', 'Mock "tr_<n>".'),
    opt('ledger_txn_id', 'string', 'The payout transaction (creator -gross, bank +net, fees +fee).'),
    req('item_count', 'int', 'Earning rows included.'),
    req('tier_at_payout', 'enum:Tier'),
    req('free_instant', 'bool', 'A tier perk made this instant payout free.'),
    req('proof_id', 'string', '"prf_<8 chars>". Public proof page joinflowd.io/p/<proof_id>; ext proofs.json has the row.'),
  ], { table: 'payouts', owner: 'core', group: 'Money' }),

  entity('Invoice', 'inv', 'A brand invoice (funding, subscription, ad fee, renewals) with finance-pack fields.', [
    req('id', 'id'),
    req('brand_id', 'ref:brands'),
    req('number', 'string', '"FD-2026-0042".'),
    req('kind', 'enum:InvoiceKind'),
    req('status', 'enum:InvoiceStatus'),
    opt('bounty_id', 'ref:bounties'),
    req('line_items', 'obj:LineItem[]'),
    req('subtotal_cents', 'cents'),
    req('processing_cents', 'cents'),
    req('tax_cents', 'cents'),
    req('total_cents', 'cents', 'subtotal + processing + tax. For funding invoices this is the card charge.'),
    opt('po_number', 'string'),
    opt('cost_center', 'string'),
    opt('vat_id', 'string'),
    req('reverse_charge', 'bool'),
    req('issued_at', 'iso'),
    req('due_at', 'iso'),
    opt('paid_at', 'iso'),
    opt('ledger_txn_id', 'string'),
    req('pdf_ref', 'string', 'Mock file name, e.g. "FD-2026-0042.pdf".'),
  ], { table: 'invoices', owner: 'core', group: 'Money' }),

  entity('MoneyClockRow', 'mc', 'The Money Clock: one earning row with its state, a dated ETA and a named reason. A projection of posts, conversions and the ledger. Never a bare "pending".', [
    req('id', 'id'),
    req('creator_id', 'ref:creators'),
    req('bounty_id', 'ref:bounties'),
    req('app_id', 'ref:apps'),
    opt('post_id', 'ref:posts'),
    opt('conversion_id', 'ref:conversions'),
    req('source', 'enum:MoneyClockSource'),
    req('state', 'enum:MoneyClockState'),
    req('amount_cents', 'cents', 'Current amount. For accruing rows a live estimate.'),
    req('estimated', 'bool', 'True while accruing.'),
    req('earned_at', 'iso', 'When the earning started accruing.'),
    opt('eta_at', 'iso', 'When it moves to the next state. Required for accruing, pending and cleared rows.'),
    req('reason', 'enum:MoneyClockReason'),
    req('reason_text', 'string', 'Plain English with the date, e.g. "Clears Sat 2:00 PM UTC after the view check."'),
    req('label', 'string', 'e.g. "Lumi: Glow-up reveal".'),
    opt('ledger_id', 'ref:ledger', 'The creator earning row; absent while accruing.'),
    opt('payout_id', 'ref:payouts'),
    opt('cleared_at', 'iso'),
    opt('paid_at', 'iso'),
  ], { table: 'money_clock', owner: 'core', group: 'Money' }),

  entity('MarketSeriesPoint', 'mkt', 'Daily market data per category (the clearing CPM series). "Clearing CPM" = median CPM of bounties that filled or are live and receiving submissions.', [
    req('id', 'id', 'mkt_<category>_<YYYY-MM-DD>.'),
    req('category', 'enum:Category'),
    req('date', 'date'),
    req('clearing_cpm_cents', 'cents', 'Median.'),
    req('p25_cpm_cents', 'cents'),
    req('p75_cpm_cents', 'cents'),
    req('open_bounties', 'int'),
    req('open_budget_cents', 'cents'),
    req('new_bounties', 'int'),
    req('submissions', 'int'),
    req('median_fill_hours', 'number'),
    req('median_views', 'int', 'Median verified views per post in the category (7-day trailing).'),
    req('trial_rate', 'ratio', 'Trials per install (7-day trailing).'),
    req('sample_n', 'int'),
  ], { table: 'market_series', owner: 'core', group: 'Market' }),

  entity('Ticker', 'tick', 'The public live payout ticker: totals plus recent events. Object-shaped file.', [
    req('totals', 'obj:TickerTotals'),
    req('events', 'obj:TickerEvent[]', 'Newest first; 40 to 80 events.'),
  ], { table: 'ticker', owner: 'core', shape: 'object', group: 'Market', fixtureDoc: 'One object: { totals, events }.' }),

  entity('BrandScorecard', 'bsc', 'Brand Scorecard: pay speed, decision time, approval fairness and the share of approved work actually run. Shown to creators before they apply.', [
    req('id', 'id', 'bsc_<brand slug>.'),
    req('brand_id', 'ref:brands'),
    req('window_days', 'int', '90.'),
    req('as_of', 'iso'),
    req('decisions_n', 'int', 'Decisions in the window.'),
    req('approved_n', 'int'),
    req('decision_hours_median', 'number'),
    req('decision_hours_p90', 'number'),
    req('sla_breaches', 'int'),
    req('approval_rate', 'ratio'),
    req('rejection_rate', 'ratio'),
    req('appeals_n', 'int'),
    req('appeals_overturned', 'int'),
    req('run_rate', 'ratio', 'Share of approved work posted or used within 30 days.'),
    req('pays_on_time_ratio', 'ratio', 'Share of commissions, direct offers and top-ups funded without delay.'),
    req('pay_speed_hours_median', 'number', 'Median hours from payment due to funded (commissions, direct offers).'),
    req('reply_hours_median', 'number'),
    req('funded_always', 'bool', 'Every live bounty was fully escrowed.'),
    req('reliability_score', 'int', '0..100 (FORMULAS: brand reliability).'),
    req('band', 'enum:BrandBand'),
    req('badges', 'enum:BrandBadge[]'),
    req('trend_30d', 'number', 'Score change over 30 days.'),
  ], { table: 'brand_scorecards', owner: 'core', group: 'Trust' }),

  entity('CreatorReputation', 'rep', 'Fair creator reputation: finished work only, recency-weighted, shown with reasons. Never penalises multi-brand work or pending samples.', [
    req('id', 'id', 'rep_<creator slug>.'),
    req('creator_id', 'ref:creators'),
    req('as_of', 'iso'),
    req('provisional', 'bool', 'Fewer than 5 finished decisions: "Building history". Brands see a range, not a verdict.'),
    req('reliability_score', 'int'),
    req('approval_rate_finished', 'ratio', 'Recency-weighted (half-life 45 days).'),
    req('approval_rate_raw', 'ratio'),
    req('on_time_ratio', 'ratio'),
    req('post_through_ratio', 'ratio'),
    req('compliance_ratio', 'ratio'),
    req('clean_record_ratio', 'ratio'),
    req('finished_n', 'int'),
    req('fraud_flags_90d', 'int'),
    req('clawbacks_90d', 'int'),
    req('disputes_lost_90d', 'int'),
    req('academy_bonus_points', 'number'),
    req('components', 'obj:ReliabilityComponent[]'),
    req('reasons', 'string[]', 'Plain-English reasons shown on the creator\'s own profile.'),
    req('tier_progress', 'obj:TierProgress'),
  ], { table: 'creator_reputation', owner: 'core', group: 'Trust' }),
];
