// Entities: creator growth (drops, tournaments, crews, streaks, leaderboards, referrals, academy, trends, formats, hooks,
// tier history, wrapped, proofs, saves, wellbeing, notification prefs) and public content (waitlist, State of App UGC,
// case studies, testimonials, changelog). Owner ext.
import { entity, req, opt } from './dsl.mjs';

export const ENTITIES_GROWTH = [
  entity('DailyDrop', 'drop', 'The Daily Drop: one drop a day at 16:00 UTC with real inventory. spots_left is always a true count; claims are 24-hour reserved places to submit. Unclaimed spots return to the open feed.', [
    req('id', 'id', 'drop_<YYYY-MM-DD>.'),
    req('date', 'date'),
    req('release_at', 'iso', 'The date at 16:00:00Z.'),
    req('claim_window_ends_at', 'iso', 'release_at + 24 hours.'),
    req('status', 'enum:DropStatus', 'upcoming before release_at, live after, sold_out when every spot is claimed, closed after the claim window.'),
    req('headline', 'string', 'e.g. "Six new bounties. Real spots."'),
    req('items', 'obj:DropItem[]', 'Bounties released through the drop (visibility drop or open).'),
    req('spots_total', 'int', 'Sum of items.spots_total.'),
    req('spots_left', 'int', 'Sum of items.spots_left (a true count).'),
    req('claims_total', 'int', 'spots_total - spots_left.'),
    req('created_at', 'iso'),
  ], { table: 'daily_drops', owner: 'ext', group: 'Growth' }),

  entity('Tournament', 'tour', 'A sponsored tournament: a prize pool, hook battles in rounds (bracket) or a ranked leaderboard. Free entry. Prizes are paid as ledger rows of type prize from the platform promo account.', [
    req('id', 'id'),
    req('title', 'string'),
    req('tagline', 'string'),
    req('description', 'text'),
    req('status', 'enum:TournamentStatus'),
    req('format', 'enum:TournamentFormat'),
    req('art', 'art'),
    opt('sponsor_brand_id', 'ref:brands', 'Absent when funded by flowd.'),
    req('sponsor_label', 'string', '"flowd" or the sponsor brand name.'),
    req('prize_pool_cents', 'cents', 'Sum of prizes; at least $250.'),
    req('prizes', 'obj:Prize[]'),
    req('rounds', 'obj:TournamentRound[]', 'Empty for leaderboard format.'),
    req('rules', 'string[]'),
    opt('min_tier', 'enum:Tier'),
    opt('niche', 'enum:Niche'),
    opt('bounty_id', 'ref:bounties', 'The brief entrants answer.'),
    req('entries_count', 'int', 'Equals the number of tournament_entries rows.'),
    req('announced_at', 'iso'),
    req('entries_open_at', 'iso'),
    req('starts_at', 'iso'),
    req('ends_at', 'iso'),
    opt('winner_creator_ids', 'ref:creators[]', 'Set when complete.'),
    req('created_at', 'iso'),
  ], { table: 'tournaments', owner: 'ext', group: 'Growth' }),

  entity('TournamentEntry', 'tent', 'A creator\'s entry in a tournament: one hook video.', [
    req('id', 'id'),
    req('tournament_id', 'ref:tournaments'),
    req('creator_id', 'ref:creators'),
    req('status', 'enum:EntryStatus'),
    req('hook_text', 'string'),
    opt('submission_id', 'ref:submissions'),
    req('thumb', 'art'),
    req('hook_points', 'int'),
    req('hook_band', 'enum:ScoreBand'),
    req('seed', 'int', 'Bracket seed (1-based).'),
    req('round_reached', 'int'),
    opt('placement', 'int'),
    opt('prize_cents', 'cents'),
    req('entered_at', 'iso'),
    req('updated_at', 'iso'),
  ], { table: 'tournament_entries', owner: 'ext', group: 'Growth' }),

  entity('Crew', 'crew', 'A crew of 3 to 20 creators with a shared leaderboard and a platform-funded weekly goal bonus. Led by a Gold or above creator.', [
    req('id', 'id'),
    req('name', 'string'),
    req('tagline', 'string'),
    req('art', 'art', 'The crew badge.'),
    req('niche', 'enum:Niche'),
    req('lead_creator_id', 'ref:creators'),
    req('member_count', 'int', 'Equals the number of crew_members rows (3 to 20).'),
    req('open', 'bool', 'Anyone eligible can join without an invite.'),
    req('invite_code', 'string'),
    req('weekly_goal_cents', 'cents'),
    req('week_cleared_cents', 'cents', 'Sum of members\' cleared earnings this ISO week.'),
    req('week_rank', 'int', 'Rank among all crews this week.'),
    req('bonus_earned_total_cents', 'cents', 'Platform-funded bonuses paid to the crew so far.'),
    req('lifetime_cleared_cents', 'cents'),
    req('created_at', 'iso'),
  ], { table: 'crews', owner: 'ext', group: 'Growth' }),

  entity('CrewMember', 'cmem', 'A creator in a crew.', [
    req('id', 'id'),
    req('crew_id', 'ref:crews'),
    req('creator_id', 'ref:creators'),
    req('role', 'enum:CrewRole'),
    req('joined_at', 'iso'),
    req('week_cleared_cents', 'cents'),
    req('lifetime_cleared_cents', 'cents'),
  ], { table: 'crew_members', owner: 'ext', group: 'Growth' }),

  entity('Streak', 'stk', 'A creator\'s weekly posting streak. A week counts when the creator posts at least once in the ISO week (Monday to Sunday UTC). Earned freezes (1 per 4-week streak, max 2 banked), declared rest weeks, no inactivity penalty, no guilt copy.', [
    req('id', 'id', 'stk_<creator slug>.'),
    req('creator_id', 'ref:creators'),
    req('status', 'enum:StreakStatus'),
    req('current_weeks', 'int', 'Equals creators.streak_weeks.'),
    req('best_weeks', 'int'),
    req('freezes_banked', 'int', '0 to 2.'),
    req('freezes_earned_total', 'int'),
    req('freezes_used_total', 'int'),
    req('rest_weeks_used_quarter', 'int', 'At most 2 per quarter.'),
    req('iso_week', 'string', 'The current ISO week, e.g. "2026-W40".'),
    req('posts_this_week', 'int'),
    req('posted_this_week', 'bool'),
    req('week_ends_at', 'iso', 'Sunday 23:59:59Z of the current ISO week.'),
    req('next_freeze_in_weeks', 'int', 'Weeks of streak until the next freeze is earned (0 to 3).'),
    req('history', 'obj:WeekRecord[]', 'The last 12 ISO weeks, oldest first.'),
    req('updated_at', 'iso'),
  ], { table: 'streaks', owner: 'ext', group: 'Growth' }),

  entity('Leaderboard', 'lb', 'A weekly leaderboard: peer cohorts of about 30 by tier and niche (with a promotion zone and no demotion zone) plus public niche and global boards. Resets Monday 00:00 UTC.', [
    req('id', 'id', 'lb_<iso week in lower case, e.g. 2026-w40>_<scope>_<tier|all>_<niche|all>_<metric>.'),
    req('scope', 'enum:LeaderboardScope'),
    req('iso_week', 'string'),
    req('week_starts_at', 'iso'),
    req('reset_at', 'iso', 'Next Monday 00:00:00Z.'),
    req('metric', 'enum:LeaderboardMetric'),
    opt('tier', 'enum:Tier'),
    opt('niche', 'enum:Niche'),
    req('label', 'string', 'e.g. "Silver · AI tools · Cohort 3".'),
    req('cohort_size', 'int', 'Equals entries.length.'),
    req('promotion_zone_size', 'int', 'Top 5 on cohort boards; 0 otherwise.'),
    req('entries', 'obj:LeaderboardEntry[]', 'Ranked 1..n. Creators who opted out are excluded.'),
    req('updated_at', 'iso'),
  ], { table: 'leaderboards', owner: 'ext', group: 'Growth' }),

  entity('Referral', 'ref', 'A referral: single level, time-limited and platform-funded; the referred person is never charged. Creators earn 5% of a referee\'s cleared earnings for 90 days (capped at $100 per referee); agency partners earn 10% of platform fees for 12 months.', [
    req('id', 'id'),
    req('kind', 'enum:ReferralKind'),
    req('status', 'enum:ReferralStatus'),
    req('code', 'string'),
    opt('referrer_creator_id', 'ref:creators'),
    opt('referrer_brand_id', 'ref:brands', 'Agency partner referrals.'),
    opt('referee_creator_id', 'ref:creators'),
    opt('referee_brand_id', 'ref:brands'),
    req('referee_label', 'string', 'Public label: "@handle" or "A Silver creator".'),
    req('channel', 'string', '"link" | "code" | "qr".'),
    req('invited_at', 'iso'),
    opt('joined_at', 'iso'),
    opt('first_dollar_at', 'iso'),
    opt('reward_window_ends_at', 'iso', 'first_dollar_at + 90 days (creators) or + 12 months (brands).'),
    req('reward_rate', 'ratio'),
    req('reward_cap_cents', 'cents'),
    req('reward_earned_cents', 'cents'),
    req('created_at', 'iso'),
    req('updated_at', 'iso'),
  ], { table: 'referrals', owner: 'ext', group: 'Growth' }),

  entity('Lesson', 'lsn', 'An Academy lesson: free, five minutes or less, never required. Ten core lessons; each has a quiz and a badge.', [
    req('id', 'id', 'lsn_<slug>.'),
    req('slug', 'string'),
    req('topic', 'enum:LessonTopic'),
    req('order', 'int', '1 to 10.'),
    req('title', 'string'),
    req('summary', 'string'),
    req('read_minutes', 'int', '5 or fewer.'),
    req('blocks', 'obj:LessonBlock[]'),
    req('quiz', 'obj:QuizQuestion[]', 'Three questions.'),
    req('badge_label', 'string'),
    req('badge_art', 'art'),
    req('reliability_bonus_points', 'number', '0.5 per completed lesson, capped at 5 across the Academy.'),
    req('completions', 'int'),
    req('avg_quiz_score', 'ratio'),
    req('updated_at', 'iso'),
  ], { table: 'lessons', owner: 'ext', group: 'Growth' }),

  entity('LessonProgress', 'lsp', 'A creator\'s progress on a lesson.', [
    req('id', 'id'),
    req('creator_id', 'ref:creators'),
    req('lesson_id', 'ref:lessons'),
    req('status', 'enum:LessonStatus'),
    opt('quiz_score', 'ratio'),
    opt('started_at', 'iso'),
    opt('completed_at', 'iso'),
    req('badge_awarded', 'bool'),
  ], { table: 'lesson_progress', owner: 'ext', group: 'Growth' }),

  entity('Trend', 'trend', 'A Trend radar item: a rising or fading format, hook, topic or sound, built from public top ads and flowd\'s own settled winners.', [
    req('id', 'id'),
    req('kind', 'enum:TrendKind'),
    req('label', 'string'),
    req('description', 'text'),
    req('why_it_works', 'text'),
    req('direction', 'enum:TrendDirection'),
    req('weekly_change_ratio', 'number', 'Week-on-week change in usage, e.g. 0.32 = +32%.'),
    req('sparkline', 'number[]', 'Eight weekly usage points, oldest first.'),
    opt('format_id', 'enum:FormatId'),
    opt('hook_type', 'enum:HookType'),
    req('categories', 'enum:Category[]'),
    req('niches', 'enum:Niche[]'),
    req('sample_posts', 'int'),
    opt('sound_licensed_for_ads', 'bool', 'Sounds only. false = flag on promotion.'),
    req('art', 'art'),
    req('first_seen_at', 'iso'),
    req('updated_at', 'iso'),
  ], { table: 'trends', owner: 'ext', group: 'Growth' }),

  entity('Format', 'tmpl', 'A winning app-ad format template (11). The Studio supplies the beat structure, script, shot list, timing and checks. Exactly one row per FormatId; id is the FormatId value.', [
    req('id', 'id', 'Equals a FormatId value (tmpl_screen_reaction ...).'),
    req('name', 'string'),
    req('summary', 'text'),
    req('rank', 'int', '1 to 11, library order.'),
    req('mvp', 'bool', 'One of the first six formats.'),
    req('beats', 'obj:FormatBeat[]'),
    req('min_duration_s', 'int'),
    req('max_duration_s', 'int'),
    req('difficulty', 'enum:Difficulty'),
    req('faceless', 'bool'),
    req('best_for_categories', 'enum:Category[]'),
    req('best_for_niches', 'enum:Niche[]'),
    req('hook_types', 'enum:HookType[]', 'Hook types that pair well.'),
    req('recommended_cta', 'enum:CtaType[]'),
    req('example_script', 'text', 'A fill-in script with {app} and {feature} slots.'),
    req('shot_list', 'string[]'),
    req('why_it_works', 'text'),
    req('stats', 'obj:FormatStats'),
    req('art', 'art'),
  ], { table: 'formats', owner: 'ext', group: 'Content', key: ['id'] }),

  entity('Hook', 'hook', 'A fill-in hook from the hook library (7 types, 10 or more per type), pre-filled with the app\'s name and features at use time.', [
    req('id', 'id'),
    req('hook_type', 'enum:HookType'),
    req('template', 'string', 'With {app}, {feature} and {number} slots.'),
    req('fill_slots', 'string[]'),
    req('applies_to', 'enum:FormatId[]'),
    req('examples', 'obj:HookExample[]', 'Three or more category examples.'),
    req('when_to_use', 'text'),
    req('stats', 'obj:HookStats'),
  ], { table: 'hooks', owner: 'ext', group: 'Content' }),

  entity('TierEvent', 'tev', 'An entry in a creator\'s tier history: promotions, Elite grants, grace holds, carry-over.', [
    req('id', 'id'),
    req('creator_id', 'ref:creators'),
    req('kind', 'enum:TierEventKind'),
    opt('from_tier', 'enum:Tier'),
    req('to_tier', 'enum:Tier'),
    req('basis', 'enum:TierBasis'),
    req('at', 'iso'),
    req('stats', 'obj:TierStatsSnapshot'),
    req('note', 'string'),
  ], { table: 'tier_history', owner: 'ext', group: 'Identity' }),

  entity('Wrapped', 'wrap', 'A creator\'s Wrapped recap (monthly or yearly): 8 to 10 story cards. The typical-creator card is always included.', [
    req('id', 'id', 'wrap_<creator slug>_<YYYY-MM|YYYY>.'),
    req('creator_id', 'ref:creators'),
    req('period', 'enum:WrappedPeriod'),
    req('label', 'string', 'e.g. "September 2026".'),
    req('period_start', 'date'),
    req('period_end', 'date'),
    req('total_cleared_cents', 'cents'),
    req('views_total', 'int'),
    req('posts_count', 'int'),
    req('trials_total', 'int'),
    opt('best_post_id', 'ref:posts'),
    opt('best_hook_text', 'string'),
    opt('best_hook_type', 'enum:HookType'),
    opt('top_brand_id', 'ref:brands'),
    req('streak_weeks', 'int'),
    req('tier', 'enum:Tier'),
    req('tier_median_cents', 'cents', 'The tier median for the period, shown beside the creator\'s number.'),
    req('cards', 'obj:WrappedCard[]'),
    opt('proof_id', 'ref:proofs'),
    req('created_at', 'iso'),
  ], { table: 'wrapped', owner: 'ext', group: 'Growth' }),

  entity('Proof', 'prf', 'A public proof page for an earnings claim (joinflowd.io/p/<id>): a payout, a month, a tier-up or a Wrapped. Always carries the tier median beside the number. Revocable by the creator.', [
    req('id', 'id', 'prf_<8 lowercase alphanumerics>.'),
    req('kind', 'enum:ProofKind'),
    req('creator_id', 'ref:creators'),
    req('handle', 'string', 'Displayed handle (or "A Silver creator" when anonymous).'),
    req('anonymous', 'bool'),
    opt('payout_id', 'ref:payouts'),
    req('period_label', 'string'),
    req('period_start', 'date'),
    req('period_end', 'date'),
    req('amount_cents', 'cents'),
    req('tier', 'enum:Tier'),
    req('posts_count', 'int'),
    req('typical_median_cents', 'cents', 'Always shown beside the figure.'),
    req('typical_p25_cents', 'cents'),
    req('typical_p75_cents', 'cents'),
    req('ledger_hash', 'string', '12 lowercase hex characters: a hash of the ledger rows the claim rests on.'),
    req('art', 'art'),
    req('revoked', 'bool'),
    req('page_views', 'int'),
    req('created_at', 'iso'),
  ], { table: 'proofs', owner: 'ext', group: 'Growth' }),

  entity('BountySave', 'save', 'A creator\'s relationship to a bounty: saved, joined (claimed or started in Studio) or submitted.', [
    req('id', 'id'),
    req('creator_id', 'ref:creators'),
    req('bounty_id', 'ref:bounties'),
    req('stage', 'enum:SaveStage'),
    req('saved_at', 'iso'),
    opt('claimed_until', 'iso', 'Daily Drop claim expiry (claim + 24 hours).'),
    opt('drop_id', 'ref:daily_drops'),
    opt('submission_id', 'ref:submissions'),
    req('updated_at', 'iso'),
  ], { table: 'bounty_saves', owner: 'ext', group: 'Growth' }),

  entity('WellbeingSettings', 'wb', 'Wellbeing Mode for a creator: quiet hours, numbers-off, opt-in pace goal, pause that preserves tier and streak, rest weeks, leaderboard opt-out.', [
    req('id', 'id', 'wb_<creator slug>.'),
    req('creator_id', 'ref:creators'),
    req('enabled', 'bool'),
    req('quiet_hours', 'obj:QuietHours'),
    req('numbers_off', 'obj:NumbersOff'),
    req('pace_goal', 'obj:PaceGoal'),
    opt('paused_until', 'iso'),
    req('rest_weeks', 'string[]', 'ISO weeks declared as rest weeks, e.g. "2026-W36".'),
    req('leaderboard_opt_out', 'bool'),
    req('slack_mode', 'bool', 'Slack streaks: freezes and rest weeks are applied automatically.'),
    req('updated_at', 'iso'),
  ], { table: 'wellbeing_settings', owner: 'ext', group: 'Identity' }),

  entity('NotificationPrefs', 'npref', 'Notification preferences for a user (creator, brand member or admin).', [
    req('id', 'id', 'npref_<user slug>.'),
    req('user_id', 'ref:users'),
    req('push', 'bool'),
    req('email_digest', 'bool'),
    req('categories', 'map:bool', 'Keys: money, reviews, drop, offers, tournaments, tips, safety.'),
    req('quiet_hours', 'obj:QuietHours'),
    req('batch_non_cash', 'bool', 'Batch everything except cash events inside quiet hours.'),
    req('drop_reminder', 'bool', 'One opt-in Daily Drop reminder.'),
    req('updated_at', 'iso'),
  ], { table: 'notification_prefs', owner: 'ext', group: 'Identity' }),

  entity('Waitlist', 'waitlist', 'The ranked waitlist: totals and a leaderboard of the top referrers. Object-shaped file.', [
    req('totals', 'obj:WaitlistTotals'),
    req('leaders', 'obj:WaitlistLeader[]', 'Top 25 by referrals.'),
    req('demo_position', 'int', 'The position shown to the demo visitor.'),
    req('demo_referrals', 'int'),
  ], { table: 'waitlist', owner: 'ext', shape: 'object', group: 'Public', fixtureDoc: 'One object: { totals, leaders, demo_position, demo_referrals }.' }),

  entity('StateOfAppUgc', 'state', 'The State of App UGC report: clearing CPMs, top hook types and view-to-trial rates by category. Computed from the fixtures. Object-shaped file.', [
    req('quarter', 'string', '"2026-Q3".'),
    req('quarters', 'string[]', 'Selectable quarters (the demo has one real quarter and one partial).'),
    req('published_at', 'iso'),
    req('title', 'string'),
    req('settled_posts', 'int'),
    req('total_views', 'int'),
    req('total_paid_cents', 'cents'),
    req('categories', 'obj:StateCategoryRow[]', 'One row per Category (9).'),
    req('hooks', 'obj:StateHookRow[]', 'One row per HookType (7).'),
    req('formats', 'obj:StateFormatRow[]', 'One row per FormatId (11).'),
    req('methodology', 'text'),
    req('caveats', 'string[]'),
  ], { table: 'state_of_app_ugc', owner: 'ext', shape: 'object', group: 'Public', fixtureDoc: 'One object (see fields).' }),

  entity('CaseStudy', 'case', 'A public case study. Fictional in the demo (permission-based in production).', [
    req('id', 'id'),
    req('app_id', 'ref:apps'),
    req('brand_id', 'ref:brands'),
    req('title', 'string', 'e.g. "Sleepy brand, 2.1M views, 3,900 trials".'),
    req('summary', 'text'),
    req('quote', 'text'),
    req('quote_author', 'string', 'A fictional person.'),
    req('quote_role', 'string'),
    req('metrics', 'obj:CaseMetrics'),
    req('art', 'art'),
    req('fictional', 'bool', 'Always true in the demo.'),
    req('published_at', 'iso'),
  ], { table: 'case_studies', owner: 'ext', group: 'Public' }),

  entity('Testimonial', 'tst', 'A fictional testimonial for the marketing pages.', [
    req('id', 'id'),
    req('kind', 'enum:PartyKind'),
    req('quote', 'text'),
    req('author', 'string'),
    req('role', 'string'),
    opt('creator_id', 'ref:creators'),
    opt('brand_id', 'ref:brands'),
    opt('stat_label', 'string'),
    opt('stat_value', 'string'),
    req('avatar', 'art'),
    req('fictional', 'bool', 'Always true in the demo.'),
  ], { table: 'testimonials', owner: 'ext', group: 'Public' }),

  entity('ChangelogEntry', 'chg', 'A changelog entry.', [
    req('id', 'id'),
    req('date', 'date'),
    req('title', 'string'),
    req('body', 'text'),
    req('tags', 'enum:ChangelogTag[]'),
    req('audience', 'enum:PartyKind[]', 'Empty means everyone.'),
    opt('version', 'string'),
  ], { table: 'changelog', owner: 'ext', group: 'Public' }),
];
