// Enumerations added for the extension fixtures (payout runs, leaderboards, trust queues, wrapped, planning).
import { en, ev } from './dsl.mjs';

export const ENUMS_EXTRA = [
  en('ExclusionCause', 'Posts', 'Why views were excluded from the verified count (View Ledger). Always shown in plain words.', [
    ev('bot_pattern', 'Bot pattern', 'rose', 'Step-function curve typical of bought views.'),
    ev('cap_clustering', 'Cap clustering', 'rose', 'Views snapped to the per-video cap.'),
    ev('duplicate', 'Duplicate views', 'ember', 'The platform counted the same viewers twice, or a repost double-counted.'),
    ev('geo_outlier', 'Audience outside the target region', 'ember', 'Views from outside the target regions of the bounty.'),
    ev('removed_post', 'Post removed', 'neutral', 'The post was deleted before the window closed.'),
    ev('platform_adjustment', 'Platform adjustment', 'info', 'The platform itself revised its count (spam filtering).'),
  ]),
  en('StorefrontTheme', 'Identity', 'Look of a creator storefront (joinflowd.io/c/<handle>).', [
    ev('aurora', 'Aurora', 'accent', 'Flow gradient glow.'),
    ev('ink', 'Ink', 'neutral', 'Calm dark ink.'),
    ev('sunrise', 'Sunrise', 'ember', 'Warm ember and sun.'),
    ev('lagoon', 'Lagoon', 'info', 'Cool lagoon and mint.'),
  ]),
  en('RunStatus', 'Money', 'Weekly payout run lifecycle (Fridays 18:00 UTC).', [
    ev('scheduled', 'Scheduled', 'info', 'Not started. Preview shows creators, total and named holds.'),
    ev('running', 'Running', 'accent', 'The run has started; transfers are being created.'),
    ev('complete', 'Complete', 'mint', 'Every eligible payout was created; holds carry to the next run.'),
  ]),
  en('LeaderboardScope', 'Growth', 'Which population a leaderboard ranks.', [
    ev('cohort', 'Peer cohort', 'accent', 'About 30 creators in the same tier and niche, with a promotion zone.'),
    ev('niche', 'Niche board', 'info', 'Public weekly board for one niche.'),
    ev('global', 'Global board', 'sun', 'Public weekly board across all creators.'),
  ]),
  en('Difficulty', 'Content', 'How hard a format is to film.', [
    ev('easy', 'Easy', 'mint', 'Phone, no editing skills needed.'),
    ev('medium', 'Medium', 'info', 'A few cuts or a screen recording.'),
    ev('hard', 'Hard', 'ember', 'Several scenes or timing-sensitive edits.'),
  ]),
  en('TaxEntityType', 'Trust', 'Tax classification on a W-9 (self-declared).', [
    ev('individual', 'Individual', 'neutral', 'Individual or sole proprietor.'),
    ev('llc', 'LLC', 'neutral', 'Limited liability company.'),
    ev('s_corp', 'S corporation', 'neutral', 'S corporation.'),
    ev('c_corp', 'C corporation', 'neutral', 'C corporation.'),
    ev('partnership', 'Partnership', 'neutral', 'Partnership.'),
  ]),
  en('VerificationReason', 'Trust', 'Reason codes Ops uses when a verification is not approved.', [
    ev('document_unreadable', 'Document unreadable', 'ember', 'The photo is blurry or cut off.'),
    ev('name_mismatch', 'Name mismatch', 'ember', 'The ID name does not match the account or tax name.'),
    ev('underage', 'Under 18', 'rose', 'Creators must be 18 or older.'),
    ev('selfie_mismatch', 'Selfie mismatch', 'rose', 'The liveness selfie does not match the ID.'),
    ev('business_not_found', 'Business not found', 'ember', 'No matching legal entity for the brand.'),
    ev('bank_name_mismatch', 'Bank name mismatch', 'ember', 'The account holder differs from the verified creator.'),
    ev('tin_mismatch', 'TIN mismatch', 'ember', 'The taxpayer number does not match the name.'),
    ev('other', 'Other', 'neutral', 'Another reason, explained in the note.'),
  ]),
  en('PartyKind', 'Identity', 'A side of the market.', [
    ev('creator', 'Creator', 'accent', 'A creator.'),
    ev('brand', 'Brand', 'info', 'A brand or app team.'),
  ]),
  en('TierEventKind', 'Identity', 'Entries in a creator\'s tier history.', [
    ev('promoted', 'Promoted', 'sun', 'Reached a new tier by meeting its thresholds.'),
    ev('granted', 'Granted', 'sun', 'Placed in a tier after Ops review (Elite) or founding carry-over.'),
    ev('hold_started', 'Grace hold started', 'ember', 'Stats dipped below a threshold; 30 days before any drop.'),
    ev('hold_cleared', 'Grace hold cleared', 'mint', 'Stats recovered inside the 30 days; the tier stays.'),
    ev('demoted', 'Moved down', 'neutral', 'Stats stayed below the threshold for 30 days.'),
    ev('carry_over_applied', 'Carry-over applied', 'info', 'Verified prior history was counted toward the thresholds.'),
  ]),
  en('WrappedCardKind', 'Growth', 'A story card in Wrapped.', [
    ev('earnings', 'Earnings', 'mint', 'Cleared earnings in the period.'),
    ev('views', 'Views', 'info', 'Verified views delivered.'),
    ev('best_post', 'Best post', 'accent', 'The post with the highest earnings.'),
    ev('winning_hook', 'Winning hook', 'violet', 'The hook that drove the most trials.'),
    ev('trials', 'Trials started', 'mint', 'Trials started through the creator\'s links and codes.'),
    ev('streak', 'Streak', 'mint', 'Weekly streak and freezes.'),
    ev('tier', 'Tier', 'sun', 'Tier and progress.'),
    ev('top_brand', 'Top brand', 'info', 'The brand the creator worked with most.'),
    ev('typical', 'Typical creator', 'neutral', 'The tier median beside the creator\'s number. Always included.'),
    ev('share', 'Share', 'accent', 'The closing share card.'),
  ]),
  en('SpendTier', 'Platform', 'Test planner matrix size by spend.', [
    ev('starter', 'Starter', 'neutral', 'Up to $1,000: 4 to 6 cells.'),
    ev('growth', 'Growth', 'accent', '$1,000 to $5,000: 8 to 12 cells.'),
    ev('scale', 'Scale', 'sun', 'Over $5,000: 15 to 24 cells.'),
  ]),
  en('DisputeAction', 'Trust', 'Entries in a dispute timeline.', [
    ev('opened', 'Opened', 'info', 'The dispute was opened.'),
    ev('reply', 'Reply', 'neutral', 'A person replied.'),
    ev('evidence_requested', 'Evidence requested', 'ember', 'Ops asked for evidence.'),
    ev('evidence_added', 'Evidence added', 'info', 'A party added evidence.'),
    ev('review_started', 'Review started', 'accent', 'Ops started the review.'),
    ev('decision', 'Decision', 'mint', 'Ops decided.'),
    ev('withdrawn', 'Withdrawn', 'neutral', 'The opener withdrew.'),
  ]),
  en('RuleAuditAction', 'Platform', 'Entries in an auto-approve rule audit log.', [
    ev('created', 'Created', 'neutral', 'Rule created.'),
    ev('edited', 'Edited', 'neutral', 'Conditions or guardrails changed.'),
    ev('dry_run', 'Dry run', 'info', 'Dry run on the last 50 submissions.'),
    ev('enabled', 'Enabled', 'mint', 'Enabled after a dry run.'),
    ev('paused', 'Paused', 'ember', 'Paused by the brand or a guardrail.'),
    ev('resumed', 'Resumed', 'mint', 'Resumed.'),
    ev('killed', 'Killed', 'rose', 'Kill switch used.'),
    ev('spot_check', 'Spot-check', 'info', 'A human reviewed an auto-approved submission.'),
    ev('spot_check_overturned', 'Spot-check overturned', 'rose', 'A human disagreed with an auto-approval; the rule paused.'),
  ]),
];
