// Enumerations: submissions, review, QA, posts, views, fraud, conversions, attribution, ads.
import { en, ev } from './dsl.mjs';

export const ENUMS_WORK = [
  en('ScoreBand', 'Content', 'Checklist score band for Hook Score and Flow Score. Day-one scores are checklist scores, labelled as such.', [
    ev('A', 'A', 'mint', 'Strong: 85+ points.'),
    ev('B', 'B', 'accent', 'Good: 70 to 84.'),
    ev('C', 'C', 'info', 'Okay: 55 to 69.'),
    ev('D', 'D', 'ember', 'Needs work: 40 to 54.'),
    ev('E', 'E', 'rose', 'Fix before posting: under 40.'),
  ]),
  en('ScoreItemId', 'Content', 'A line of the Hook Score or Flow Score checklist (weights in CONSTANTS.scores).', [
    ev('hook_lands_2s', 'Hook lands by 2.0s', 'neutral', 'Hook Score item (20).'),
    ev('onscreen_text_matches', 'On-screen text mirrors the hook', 'neutral', 'Hook Score item (15).'),
    ev('face_early', 'Face in first second', 'neutral', 'Hook Score item (15).'),
    ev('app_visible_3s', 'App visible by 3s', 'neutral', 'Hook Score item (15).'),
    ev('pattern_interrupt', 'Pattern interrupt', 'neutral', 'Hook Score item (10).'),
    ev('proven_hook_type', 'Proven hook type', 'neutral', 'Hook Score item (10).'),
    ev('speech_starts_fast', 'Speech starts fast', 'neutral', 'Hook Score item (10).'),
    ev('captions_safe_zone', 'Captions in safe zones', 'neutral', 'Hook Score item (5) and Flow Score item (5).'),
    ev('hook_score', 'Hook Score', 'neutral', 'Flow Score item (30): the Hook Score scaled.'),
    ev('required_beats', 'Required beats', 'neutral', 'Flow Score item (25).'),
    ev('app_visible_early', 'App on screen early', 'neutral', 'Flow Score item (10).'),
    ev('disclosure', 'Disclosure', 'neutral', 'Flow Score item (10).'),
    ev('length_ok', 'Length 15 to 30s', 'neutral', 'Flow Score item (5).'),
    ev('single_cta_win_state', 'One CTA, win state', 'neutral', 'Flow Score item (5).'),
    ev('audio_clear', 'Audio clear', 'neutral', 'Flow Score item (5).'),
    ev('format_fit', 'Format fit', 'neutral', 'Flow Score item (5).'),
  ]),
  en('SubmissionSource', 'Submissions', 'How the video got to flowd.', [
    ev('studio', 'Studio', 'accent', 'Recorded in the flowd Studio (iOS).'),
    ev('web_studio', 'Web Studio lite', 'accent', 'Uploaded through the web Studio-lite flow.'),
    ev('camera_roll', 'Camera roll', 'neutral', 'Imported from the phone camera roll.'),
    ev('capcut', 'CapCut import', 'neutral', 'Exported from CapCut and imported.'),
  ]),
  en('SubmissionStatus', 'Submissions', 'Submission lifecycle. See state machine.', [
    ev('qa_pending', 'Checking', 'info', 'Uploaded; auto-QA, scoring and the reservation are running.'),
    ev('in_review', 'In review', 'accent', 'Waiting for the brand. The 72-hour SLA clock is running.'),
    ev('changes_requested', 'Changes requested', 'ember', 'The brand asked for changes with timecoded notes (revision round).'),
    ev('approved', 'Approved', 'mint', 'Approved; ready to post with the tracking link, code and #ad.'),
    ev('posted', 'Posted', 'mint', 'Posted to the creator\'s account; the 72-hour view window is running or done.'),
    ev('rejected', 'Not approved', 'rose', 'Rejected with a reason code and evidence. One appeal allowed.'),
    ev('appealed', 'Appeal open', 'ember', 'The creator appealed the rejection; Ops decides within 72 hours.'),
    ev('withdrawn', 'Withdrawn', 'neutral', 'The creator withdrew it; the reservation is released.'),
    ev('expired', 'Expired', 'neutral', 'Revisions were not resubmitted in 14 days; the reservation is released.'),
    ev('released', 'Released', 'violet', 'Approved but unused for 30 days; moved to the Spec Market (brand keeps first refusal).'),
  ]),
  en('DecisionAction', 'Submissions', 'How a decision was made.', [
    ev('approve', 'Approved', 'mint', 'A person approved it.'),
    ev('request_changes', 'Requested changes', 'ember', 'A person requested changes (needs at least one must-fix note).'),
    ev('reject', 'Rejected', 'rose', 'A person rejected it (reason code + evidence mandatory).'),
    ev('auto_approve', 'Auto-approved', 'violet', 'A guarded auto-approve rule approved it.'),
    ev('timeout_approve', 'Approved on timeout', 'violet', 'Approved at 72h under the approve-if-clean timeout policy.'),
    ev('auto_reject', 'Auto-blocked', 'rose', 'Blocked by a hard QA failure such as an exact duplicate (evidence attached).'),
    ev('appeal_overturn', 'Appeal overturned', 'mint', 'Ops overturned a rejection on appeal.'),
    ev('appeal_uphold', 'Appeal upheld', 'rose', 'Ops upheld the rejection on appeal.'),
  ]),
  en('SlaState', 'Submissions', 'Review SLA position of a submission.', [
    ev('on_track', 'On track', 'mint', 'Under 48 hours in the queue.'),
    ev('stale', 'Stale', 'ember', '48 to 72 hours in the queue.'),
    ev('breached', 'SLA breached', 'rose', 'Over 72 hours: escalated; the brand reliability score took a hit.'),
    ev('met', 'Decided in SLA', 'neutral', 'Decided inside 72 hours.'),
  ]),
  en('ReasonCode', 'Submissions', 'Reason codes for rejecting or requesting changes. Always about the video, never the person. Detail in REASON_CODE_INFO.', [
    ev('app_not_shown_early', 'App not on screen early', 'ember', 'The app isn\'t visible in the first 3 seconds.'),
    ev('hook_too_late', 'Hook lands too late', 'ember', 'The hook doesn\'t land by 2 seconds.'),
    ev('missing_required_beat', 'Missing a required beat', 'ember', 'A required beat from the brief is missing.'),
    ev('missing_disclosure', 'Disclosure missing', 'rose', '#ad is not in both the audio and on screen.'),
    ev('offer_not_stated', 'Offer not stated', 'ember', 'The free trial or promo isn\'t mentioned.'),
    ev('face_not_shown', 'Face required', 'ember', 'The brief requires a face on camera.'),
    ev('audio_unclear', 'Audio unclear', 'ember', 'Speech is hard to hear or has dead air.'),
    ev('music_not_licensed', 'Music not licensed for ads', 'rose', 'A track outside the commercial music library.'),
    ev('banned_claim', 'Banned claim', 'rose', 'A medical, income or guarantee claim the brand disallows.'),
    ev('off_brief', 'Doesn\'t match the brief', 'ember', 'The concept doesn\'t follow the stated brief.'),
    ev('low_video_quality', 'Video quality too low', 'ember', 'Dark, shaky or low resolution.'),
    ev('wrong_format', 'Wrong aspect or length', 'ember', 'Not 9:16 or outside the length range.'),
    ev('duplicate_content', 'Duplicate video', 'rose', 'Matches another video already submitted or posted.'),
    ev('unoriginal_clip', 'Unoriginal clip', 'rose', 'Reposted or stitched from someone else\'s content.'),
    ev('watermark_present', 'Watermark present', 'ember', 'Another app\'s watermark or logo is visible.'),
    ev('competitor_shown', 'Competitor shown', 'ember', 'A competing app is visible.'),
    ev('ai_content_undisclosed', 'AI content not labelled', 'rose', 'AI-generated media without the required label.'),
    ev('brand_safety', 'Brand-safety issue', 'rose', 'Content outside the brand\'s safety rules.'),
    ev('region_mismatch', 'Audience region mismatch', 'ember', 'Audience is outside the bounty\'s target regions.'),
    ev('other_requirement', 'Other stated requirement', 'ember', 'A requirement written in the brief that the video misses (must be quoted).'),
    ev('suspected_fraud', 'Suspected view fraud', 'rose', 'Admin-only: proven view fraud. Delivered legitimate views are still paid.'),
  ]),
  en('QaCheckType', 'Submissions', 'Automated QA checks run on every submission version.', [
    ev('disclosure_audio', 'Spoken disclosure', 'neutral', 'The #ad / paid-partnership line is spoken.'),
    ev('disclosure_onscreen', 'On-screen disclosure', 'neutral', '#ad is visible on screen.'),
    ev('music_licence', 'Music licence', 'neutral', 'Audio matches only commercial-library tracks.'),
    ev('banned_claims', 'Banned claims', 'neutral', 'No disallowed claims in transcript or on-screen text.'),
    ev('ai_content', 'AI-generated content', 'neutral', 'AI media detected and labelled where required.'),
    ev('duplicate', 'Duplicate check', 'neutral', 'Perceptual-hash comparison against all prior videos.'),
    ev('watermark', 'Watermark check', 'neutral', 'No other app\'s watermark or logo.'),
    ev('brief_beats', 'Brief beats', 'neutral', 'Required beats found in the transcript and frames.'),
    ev('safe_zone', 'Safe zones', 'neutral', 'On-screen text is inside TikTok and Reels safe zones.'),
    ev('aspect_ratio', 'Aspect ratio', 'neutral', '9:16.'),
    ev('length', 'Length', 'neutral', 'Inside the bounty\'s length range.'),
    ev('resolution', 'Resolution', 'neutral', 'At least 720x1280; 1080x1920 preferred.'),
    ev('audio_clarity', 'Audio clarity', 'neutral', 'Speech level and dead-air check.'),
    ev('moderation', 'Moderation', 'neutral', 'Safety moderation model.'),
  ]),
  en('QaResult', 'Submissions', 'Outcome of a QA check.', [
    ev('pass', 'Pass', 'mint', 'No issue.'),
    ev('warn', 'Warning', 'ember', 'Possible issue; a human decides.'),
    ev('fail', 'Fail', 'rose', 'Likely issue; shown first in the queue and blocks auto-approve.'),
  ]),
  en('FeedbackCategory', 'Submissions', 'Category of a timecoded feedback note.', [
    ev('hook', 'Hook', 'ember', 'The first 3 seconds.'),
    ev('offer', 'Offer', 'sun', 'The offer or trial wording.'),
    ev('disclosure', 'Disclosure', 'rose', '#ad and paid-partnership wording.'),
    ev('audio', 'Audio', 'info', 'Speech, music or sound.'),
    ev('brand', 'Brand', 'accent', 'App name, logo, colours or tone.'),
    ev('pacing', 'Pacing', 'neutral', 'Cuts, length and rhythm.'),
    ev('captions', 'Captions', 'neutral', 'Caption text and placement.'),
    ev('claims', 'Claims', 'rose', 'A claim that needs to change.'),
  ]),
  en('FeedbackSeverity', 'Submissions', 'How serious a note is.', [
    ev('must_fix', 'Must fix', 'rose', 'Must be resolved in the next version; carries over until ticked off.'),
    ev('suggestion', 'Suggestion', 'info', 'Optional improvement.'),
  ]),
  en('FeedbackStatus', 'Submissions', 'State of a feedback note.', [
    ev('open', 'Open', 'ember', 'Not yet addressed.'),
    ev('resolved', 'Resolved', 'mint', 'Addressed in a later version (the creator ticked it off).'),
    ev('dismissed', 'Dismissed', 'neutral', 'The brand withdrew the note.'),
  ]),
  en('EvidenceKind', 'Submissions', 'What a rejection or note points at.', [
    ev('timecode', 'Timecode', 'neutral', 'A moment in the video.'),
    ev('qa_check', 'QA check', 'neutral', 'An automated check result.'),
    ev('brief_requirement', 'Brief requirement', 'neutral', 'A quoted line from the brief.'),
    ev('transcript', 'Transcript', 'neutral', 'A quoted line from the transcript.'),
  ]),
  en('PostStatus', 'Posts', 'Post lifecycle (CPM / flat leg). Conversions and ad commission settle on their own ledger rows.', [
    ev('live', 'Live', 'info', 'Posted; the 72-hour view window is open. Earnings are pending and accruing.'),
    ev('window_closed', 'Window closed', 'info', '72 hours elapsed; the fraud and compliance check is running.'),
    ev('held', 'Held', 'ember', 'A fraud, compliance or dispute hold. Reason shown; human decision within 24 hours.'),
    ev('cleared', 'Cleared', 'mint', 'Checks passed. CPM earnings are cleared and wait for the weekly payout.'),
    ev('paid', 'Paid', 'mint', 'The CPM earnings were included in a payout.'),
    ev('removed', 'Removed', 'neutral', 'Deleted before the window closed; earns nothing.'),
    ev('clawed_back', 'Clawed back', 'rose', 'Proven fraud: invalid views reversed (delivered legitimate views still paid).'),
  ]),
  en('HoldReason', 'Posts', 'Why money or a post is held.', [
    ev('fraud_review', 'Fraud review', 'ember', 'Fraud score 40 or above; a human review within 24 hours.'),
    ev('dispute_open', 'Dispute open', 'ember', 'A dispute is open on the post or payout.'),
    ev('tax_info_missing', 'Tax info needed', 'ember', 'Add a W-9 (or W-8BEN) to release the payout.'),
    ev('identity_check', 'ID check needed', 'ember', 'Identity verification is required before the first payout.'),
    ev('payout_method_missing', 'Payout method needed', 'ember', 'Add a bank account or debit card.'),
    ev('compliance_fail', 'Disclosure check failed', 'rose', 'The posted video failed the disclosure audit.'),
    ev('admin_hold', 'Manual hold', 'rose', 'Placed by Ops; the reason is shown to the creator.'),
  ]),
  en('TrafficSource', 'Posts', 'Where views came from (View Ledger source breakdown).', [
    ev('fyp', 'For You / Explore', 'mint', 'Recommendation feed.'),
    ev('following', 'Following', 'neutral', 'The creator\'s followers.'),
    ev('profile', 'Profile', 'neutral', 'Profile visits.'),
    ev('search', 'Search', 'neutral', 'Search results.'),
    ev('sound', 'Sound page', 'neutral', 'Sound or audio page.'),
    ev('share', 'Shares', 'neutral', 'Direct shares and DMs.'),
    ev('other', 'Other / external', 'ember', 'External or unknown; a high share raises the fraud score.'),
  ]),
  en('SnapshotSource', 'Posts', 'How a View Ledger snapshot was captured.', [
    ev('platform_api', 'Platform API', 'mint', 'Pulled from the TikTok / Instagram / YouTube API.'),
    ev('creator_screenshot', 'Screenshot proof', 'info', 'Creator-supplied screenshot checked by the fraud model (fallback).'),
    ev('manual_adjust', 'Manual adjustment', 'ember', 'Ops corrected the count after a dispute.'),
  ]),
  en('SnapshotFlag', 'Posts', 'Anomaly markers on a View Ledger snapshot.', [
    ev('spike', 'Spike', 'ember', 'Hourly views far above baseline.'),
    ev('plateau', 'Plateau', 'info', 'Views stopped growing.'),
    ev('bot_pattern', 'Bot pattern', 'rose', 'Step-function curve typical of bought views.'),
    ev('geo_shift', 'Geo shift', 'ember', 'Audience country mix changed abruptly.'),
    ev('reconciled', 'Reconciled', 'mint', 'Reported and verified counts agree after review.'),
  ]),
  en('FraudSignal', 'Trust', 'Signals that make up a fraud score. Max points in CONSTANTS.fraud.signals.', [
    ev('view_spike_no_engagement', 'View spike, no engagement', 'rose', 'Views spike with no likes or comments.'),
    ev('cap_clustering', 'Cap clustering', 'rose', 'Earnings cluster just under the per-video cap.'),
    ev('bought_views_pattern', 'Bought-views pattern', 'rose', 'Step-function curve and "other" traffic.'),
    ev('geo_mismatch', 'Geo mismatch', 'ember', 'Audience outside the target region.'),
    ev('view_to_follower_outlier', 'View-to-follower outlier', 'ember', 'Views far above the follower count.'),
    ev('new_account', 'New account', 'ember', 'Account younger than 30 days.'),
    ev('duplicate_hash', 'Duplicate video', 'rose', 'Perceptual-hash match.'),
    ev('engagement_anomaly', 'Engagement anomaly', 'ember', 'Engagement ratios out of range.'),
    ev('traffic_source_anomaly', 'Traffic-source anomaly', 'ember', 'Most views from external sources.'),
    ev('curve_shape', 'Curve shape', 'ember', 'No natural decay.'),
  ]),
  en('FraudBand', 'Trust', 'Fraud score band.', [
    ev('clean', 'Clean', 'mint', 'Score 0 to 19. Auto-clears.'),
    ev('watch', 'Watch', 'info', 'Score 20 to 39. Auto-clears; logged.'),
    ev('review', 'Review', 'ember', 'Score 40 to 69. Held for a human review within 24 hours.'),
    ev('high', 'High risk', 'rose', 'Score 70 or above. Auto-held and queued for Ops.'),
  ]),
  en('CurveShape', 'Trust', 'Shape of a view curve (fraud evidence).', [
    ev('organic', 'Organic', 'mint', 'Fast rise, natural decay over 24 to 48 hours.'),
    ev('spiky', 'Spiky', 'ember', 'One or two large spikes with little in between.'),
    ev('flat', 'Flat', 'ember', 'Almost constant hourly views, no decay.'),
    ev('stepped', 'Stepped', 'rose', 'Step function: bought-views signature.'),
  ]),
  en('SceneKind', 'Content', 'Kind of scene segment found by video understanding.', [
    ev('face', 'Face to camera', 'neutral', 'Creator on camera.'),
    ev('screen_recording', 'Screen recording', 'accent', 'App screen recording.'),
    ev('broll', 'B-roll', 'neutral', 'Cutaway footage.'),
    ev('text_card', 'Text card', 'neutral', 'Full-screen text.'),
    ev('slide', 'Slide', 'neutral', 'Slideshow image.'),
  ]),
  en('ConversionKind', 'Attribution', 'Funnel event after a view.', [
    ev('install', 'Install', 'info', 'App installed (first launch).'),
    ev('trial', 'Trial started', 'accent', 'Free trial started.'),
    ev('paid', 'Paid subscription', 'mint', 'First paid period, or trial converted to paid.'),
  ]),
  en('ConversionSource', 'Attribution', 'How a conversion was attributed. CPA pays only on link and code.', [
    ev('link', 'Tracked link', 'mint', 'Deterministic: a per-creator deferred deep link. Payable.'),
    ev('code', 'Promo code', 'mint', 'Deterministic: a promo or offer code redeemed. Payable.'),
    ev('mmp', 'MMP match', 'info', 'Matched by AppsFlyer / Adjust / Branch. Reported, not paid.'),
    ev('survey', 'Survey answer', 'info', '"How did you hear about us?" Reported, not paid.'),
    ev('modelled', 'Modelled', 'violet', 'Statistical estimate of unattributed lift. Reported separately, never paid.'),
  ]),
  en('ConversionConfidence', 'Attribution', 'Confidence label shown next to every conversion count.', [
    ev('deterministic', 'Tracked', 'mint', 'Link or code. Counts toward tracked funnel and CPA pay.'),
    ev('matched', 'Matched', 'info', 'MMP match. Estimated funnel.'),
    ev('self_reported', 'Self-reported', 'info', 'Survey answer. Estimated funnel.'),
    ev('modelled', 'Modelled', 'violet', 'Estimate. Estimated funnel.'),
  ]),
  en('ConversionStatus', 'Attribution', 'Settlement state of a conversion batch.', [
    ev('pending', 'Pending', 'info', 'Inside its clearing window (install 24h, trial 72h, paid 168h).'),
    ev('cleared', 'Cleared', 'mint', 'Cleared; CPA pay (if payable) is on the ledger.'),
    ev('rejected', 'Rejected', 'rose', 'Duplicate, fraud or not attributable.'),
    ev('refunded', 'Refunded', 'rose', 'Refunded inside the window; CPA reversed.'),
  ]),
  en('AttributionLinkStatus', 'Attribution', 'State of a per-creator tracking link.', [
    ev('active', 'Active', 'mint', 'Resolving and attributing.'),
    ev('paused', 'Paused', 'ember', 'Paused with the bounty.'),
    ev('expired', 'Expired', 'neutral', 'Past the CPA window; still redirects, no longer attributes pay.'),
  ]),
  en('OfferCodeStatus', 'Attribution', 'State of a code in the offer-code pool.', [
    ev('available', 'Available', 'mint', 'Unassigned and ready.'),
    ev('assigned', 'Assigned', 'accent', 'Assigned to a creator and bounty.'),
    ev('exhausted', 'Exhausted', 'ember', 'Hit its redemption cap.'),
    ev('expired', 'Expired', 'neutral', 'Past its validity window.'),
    ev('retired', 'Retired', 'neutral', 'Taken out of rotation.'),
  ]),
  en('RcEventType', 'Attribution', 'RevenueCat webhook event types we ingest (lowercase mirror of the RevenueCat names).', [
    ev('initial_purchase', 'Initial purchase', 'accent', 'First purchase; with period_type trial this is a trial start.'),
    ev('renewal', 'Renewal', 'mint', 'Renewal; with is_trial_conversion true this is trial to paid.'),
    ev('cancellation', 'Cancellation', 'ember', 'Cancelled or refunded.'),
    ev('uncancellation', 'Un-cancellation', 'info', 'Resubscribed before expiry.'),
    ev('expiration', 'Expiration', 'neutral', 'Subscription ended.'),
    ev('billing_issue', 'Billing issue', 'ember', 'Payment failed.'),
    ev('product_change', 'Product change', 'neutral', 'Plan change.'),
    ev('non_renewing_purchase', 'One-time purchase', 'neutral', 'Non-subscription purchase.'),
    ev('test', 'Test', 'neutral', 'Webhook test event.'),
  ]),
  en('PeriodType', 'Attribution', 'RevenueCat period_type.', [
    ev('trial', 'Trial', 'accent', 'Free trial period.'),
    ev('intro', 'Intro', 'info', 'Introductory price period.'),
    ev('normal', 'Normal', 'mint', 'Full price period.'),
  ]),
  en('RcMatchStatus', 'Attribution', 'How a RevenueCat event was matched to a creator.', [
    ev('matched', 'Matched', 'mint', 'Matched to a conversion by subscriber attributes or offer code.'),
    ev('unmatched', 'Unmatched', 'ember', 'No flowd creator attributes or code on the event.'),
    ev('duplicate', 'Duplicate', 'neutral', 'Seen before (idempotent redelivery).'),
    ev('ignored', 'Ignored', 'neutral', 'Test or irrelevant event type.'),
  ]),
  en('AdKind', 'Ads', 'Type of promoted post.', [
    ev('spark_ad', 'Spark Ad', 'accent', 'TikTok Spark Ad using the creator\'s post and a Spark code.'),
    ev('partnership_ad', 'Partnership ad', 'accent', 'Meta partnership ad using a creator permission.'),
  ]),
  en('AdStatus', 'Ads', 'Winner promotion lifecycle. See state machine.', [
    ev('requested', 'Permission requested', 'info', 'Asked the creator for a Spark code or partnership permission.'),
    ev('authorised', 'Authorised', 'accent', 'Code or permission received; ready to launch.'),
    ev('live', 'Live', 'mint', 'Running as a paid ad. Ad commission accrues for 60 days.'),
    ev('paused', 'Paused', 'ember', 'Paused by the brand.'),
    ev('fatigued', 'Fatigued', 'ember', 'Results dropped 30% from peak; refresh suggested.'),
    ev('ended', 'Ended', 'neutral', 'Stopped by the brand.'),
    ev('expired', 'Expired', 'neutral', 'Spark code or rights term ended; ads stopped automatically.'),
    ev('declined', 'Declined', 'rose', 'The creator declined the permission request.'),
  ]),
];
