// Enumerations: money (ledger, payouts, invoices, Money Clock), market (offers, auctions, specs), rights,
// trust (disputes, scams, compliance, tax).
import { en, ev } from './dsl.mjs';

export const ENUMS_MONEY = [
  en('LedgerType', 'Money', 'Why a ledger row exists. Every transaction (txn_id) nets to zero.', [
    ev('wallet_topup', 'Wallet top-up', 'neutral', 'external:card -> wallet:brand. Card charge = amount + processing.'),
    ev('escrow_fund', 'Escrow funding', 'neutral', 'wallet:brand -> escrow:bounty (budget + fee reserve). The bounty may now go live.'),
    ev('matched_budget', 'Matched budget', 'mint', 'platform:matching -> escrow:bounty (first-bounty match, up to $500).'),
    ev('escrow_refund', 'Escrow refund', 'neutral', 'escrow:bounty -> wallet:brand when the bounty settles (unspent budget and fee reserve).'),
    ev('cpm', 'Views pay', 'mint', 'escrow:bounty -> creator: CPM leg of a post (credit row, pending then cleared then paid).'),
    ev('cpa', 'Conversion pay', 'mint', 'escrow:bounty -> creator: install / trial / paid bonus on a cleared conversion.'),
    ev('flat_fee', 'Flat fee', 'mint', 'escrow:bounty -> creator: direct offer, auction or spec licence price.'),
    ev('commission', 'Ad commission', 'mint', 'wallet:brand -> creator: 10% of ad-attributed revenue for 60 days.'),
    ev('rights_fee', 'Rights renewal', 'mint', 'wallet:brand -> creator: paid-ad usage renewal (25% of base fee per 30 days).'),
    ev('fee', 'Platform fee', 'neutral', 'escrow:bounty (or wallet) -> platform:fees: the take rate on a settled leg.'),
    ev('ad_fee', 'Ad fee', 'neutral', 'wallet:brand -> platform:fees: 1% of ad spend.'),
    ev('subscription_fee', 'Subscription', 'neutral', 'external:card -> platform:subscriptions: Pro / Scale plan.'),
    ev('processing', 'Card processing', 'neutral', 'external:card -> platform:processing: pass-through card cost (2.9% + $0.30).'),
    ev('payout', 'Payout', 'mint', 'creator -> external:bank: money leaves flowd. Debits cleared earnings.'),
    ev('payout_fee', 'Instant payout fee', 'neutral', 'creator -> platform:fees: 1.5% (min $0.50, max $15) on instant cash-outs.'),
    ev('bonus', 'Bonus', 'mint', 'platform:promo -> creator: starter-bounty first dollar, streak or crew bonus.'),
    ev('prize', 'Prize', 'sun', 'platform:promo -> creator: tournament prize.'),
    ev('referral', 'Referral reward', 'mint', 'platform:promo -> creator: 5% of a referee\'s cleared earnings for 90 days.'),
    ev('clawback', 'Clawback', 'rose', 'Reversal of earlier rows after proven fraud or refund (reverses_txn_id set).'),
    ev('adjustment', 'Adjustment', 'neutral', 'Manual correction by Ops with a memo.'),
  ]),
  en('LedgerStatus', 'Money', 'State of a ledger row (only status, cleared_at, paid_at and payout_id ever change).', [
    ev('pending', 'Pending', 'info', 'Written but waiting on the fraud check or a clearing window.'),
    ev('cleared', 'Cleared', 'mint', 'Cleared; counts toward lifetime cleared; waits for payout.'),
    ev('paid', 'Paid', 'mint', 'Included in a payout (payout_id set).'),
    ev('held', 'Held', 'ember', 'Held with a reason.'),
    ev('reversed', 'Reversed', 'rose', 'Reversed by a clawback transaction.'),
  ]),
  en('LedgerAccountKind', 'Money', 'Account kinds in the double-entry ledger. Account strings are "<kind>:<id>".', [
    ev('wallet', 'Brand wallet', 'neutral', 'wallet:br_x. Funds a brand deposited and has not locked to a bounty.'),
    ev('escrow', 'Bounty escrow', 'neutral', 'escrow:bnty_x. Funds locked to one bounty.'),
    ev('creator', 'Creator balance', 'mint', 'creator:cr_x. Earned money not yet withdrawn.'),
    ev('platform', 'flowd platform', 'accent', 'platform:fees | subscriptions | matching | promo | processing.'),
    ev('external', 'External', 'neutral', 'external:card | bank. The world outside flowd.'),
  ]),
  en('PayoutKind', 'Money', 'Payout kind.', [
    ev('weekly', 'Weekly', 'mint', 'Automatic, free, Fridays 18:00 UTC.'),
    ev('instant', 'Instant', 'sun', 'On demand, 1.5% fee (min $0.50, max $15); free for Gold x1 a week and Platinum+.'),
  ]),
  en('PayoutStatus', 'Money', 'Payout lifecycle.', [
    ev('scheduled', 'Scheduled', 'info', 'Will run at the next weekly payout.'),
    ev('processing', 'Processing', 'info', 'The payout run has started.'),
    ev('in_transit', 'In transit', 'accent', 'Transfer created; on its way to the bank.'),
    ev('paid', 'Paid', 'mint', 'Arrived.'),
    ev('failed', 'Failed', 'rose', 'The transfer failed (reason shown); it retries after the method is fixed.'),
    ev('held', 'Held', 'ember', 'Held for tax info, ID check, fraud review or a dispute.'),
    ev('cancelled', 'Cancelled', 'neutral', 'Cancelled before processing.'),
  ]),
  en('PayoutMethodKind', 'Money', 'Where a creator is paid.', [
    ev('bank', 'Bank account', 'neutral', 'Bank account via the Stripe-style Connect sheet (mocked).'),
    ev('debit_card', 'Debit card', 'neutral', 'Debit card (instant-capable).'),
  ]),
  en('PayoutMethodStatus', 'Money', 'Payout method state.', [
    ev('active', 'Active', 'mint', 'Verified and usable.'),
    ev('pending', 'Pending', 'info', 'Awaiting verification.'),
    ev('failed', 'Failed', 'rose', 'Verification or a transfer failed.'),
  ]),
  en('PaymentKind', 'Money', 'How a brand funds its wallet.', [
    ev('card', 'Card', 'neutral', 'Card, 2.9% + $0.30 processing.'),
    ev('ach', 'Bank transfer', 'neutral', 'ACH, lower processing, slower.'),
  ]),
  en('InvoiceKind', 'Money', 'Invoice type.', [
    ev('funding', 'Bounty funding', 'neutral', 'Escrow funding for a bounty: budget, fee and processing lines.'),
    ev('subscription', 'Subscription', 'neutral', 'Monthly Pro / Scale plan.'),
    ev('ad_fee', 'Ad fee', 'neutral', '1% of ad spend for a month.'),
    ev('rights_renewal', 'Rights renewal', 'neutral', 'Paid-ad usage renewal.'),
    ev('spec_license', 'Spec licence', 'neutral', 'Spec Market licence.'),
    ev('adjustment', 'Adjustment', 'neutral', 'Credit note or manual adjustment.'),
  ]),
  en('InvoiceStatus', 'Money', 'Invoice state.', [
    ev('draft', 'Draft', 'neutral', 'Not issued.'),
    ev('open', 'Open', 'info', 'Issued, awaiting payment.'),
    ev('paid', 'Paid', 'mint', 'Paid.'),
    ev('void', 'Void', 'neutral', 'Voided.'),
    ev('refunded', 'Refunded', 'info', 'Refunded in full or part.'),
  ]),
  en('MoneyClockSource', 'Money', 'What kind of earning a Money Clock row is.', [
    ev('cpm', 'Views', 'mint', 'CPM pay on verified views.'),
    ev('cpa_install', 'Installs', 'mint', 'Install bonus.'),
    ev('cpa_trial', 'Trials', 'mint', 'Trial bonus.'),
    ev('cpa_paid', 'Paid subs', 'mint', 'Paid subscription bonus.'),
    ev('ad_commission', 'Ad commission', 'mint', 'Commission on promoted-ad revenue.'),
    ev('flat_fee', 'Flat fee', 'mint', 'Direct offer, auction or spec licence.'),
    ev('rights_fee', 'Rights renewal', 'mint', 'Usage renewal payment.'),
    ev('prize', 'Prize', 'sun', 'Tournament prize.'),
    ev('bonus', 'Bonus', 'mint', 'Platform bonus.'),
    ev('referral', 'Referral', 'mint', 'Referral reward.'),
  ]),
  en('MoneyClockState', 'Money', 'Where earning money is on its way: accruing -> pending -> cleared -> paid.', [
    ev('accruing', 'Accruing', 'info', 'Window open; the amount is a live estimate that grows with verified views.'),
    ev('pending', 'Pending', 'info', 'Window closed or conversion in its clearing window; has a dated ETA and a named reason.'),
    ev('cleared', 'Cleared', 'mint', 'Cleared and waiting for the weekly payout (or an instant cash-out).'),
    ev('paid', 'Paid', 'mint', 'Paid out.'),
    ev('held', 'Held', 'ember', 'Held, with a named reason and the next step.'),
    ev('reversed', 'Reversed', 'rose', 'Reversed after a clawback.'),
  ]),
  en('MoneyClockReason', 'Money', 'Every non-final Money Clock row carries a named reason. Never a bare "pending".', [
    ev('window_open', 'Views still counting', 'info', 'The 72-hour window closes at eta_at.'),
    ev('fraud_check', 'View check running', 'info', 'Automated fraud and disclosure check; done within 12 hours.'),
    ev('awaiting_clearing_run', 'Next clearing run', 'info', 'Clears at the next daily 14:00 UTC run.'),
    ev('conversion_clearing', 'Conversion clearing', 'info', 'Install 24h / trial 72h / paid 168h check before CPA clears.'),
    ev('awaiting_weekly_payout', 'Next weekly payout', 'mint', 'Cleared. Pays out Friday 18:00 UTC.'),
    ev('payout_in_transit', 'On its way', 'accent', 'Transfer created; arriving at the bank.'),
    ev('held_fraud_review', 'Held: view review', 'ember', 'A human is reviewing the views; decision within 24 hours.'),
    ev('held_dispute', 'Held: dispute open', 'ember', 'Held while a dispute is open.'),
    ev('held_tax_info', 'Held: add W-9', 'ember', 'Add tax info to release.'),
    ev('held_identity_check', 'Held: ID check', 'ember', 'Verify identity to release.'),
    ev('held_payout_method', 'Held: payout method', 'ember', 'Add a payout method to release.'),
    ev('held_compliance', 'Held: disclosure', 'rose', 'The posted video failed the disclosure audit.'),
    ev('paid_out', 'Paid out', 'mint', 'Included in a completed payout.'),
    ev('reversed_clawback', 'Reversed', 'rose', 'Views or conversions invalidated.'),
  ]),
  en('TickerKind', 'Money', 'Public payout-ticker event kinds.', [
    ev('payout', 'Payout', 'mint', 'A creator was paid.'),
    ev('first_dollar', 'First dollar', 'mint', 'A creator\'s first cleared earnings.'),
    ev('tier_up', 'Tier up', 'sun', 'A creator reached a new tier.'),
    ev('bounty_filled', 'Bounty filled', 'accent', 'A bounty filled.'),
    ev('milestone', 'Milestone', 'sun', 'Platform milestone, e.g. total paid.'),
    ev('promoted', 'Promoted', 'accent', 'A post was promoted as a paid ad.'),
  ]),
  en('BrandBand', 'Trust', 'Brand reliability band shown on the Brand Scorecard.', [
    ev('new', 'New', 'neutral', 'Fewer than 10 decisions; not enough history. Shown as "New brand", never a misleading figure.'),
    ev('excellent', 'Excellent', 'mint', 'Reliability 90 or above.'),
    ev('good', 'Good', 'accent', '75 to 89.'),
    ev('fair', 'Fair', 'ember', '60 to 74.'),
    ev('poor', 'Poor', 'rose', 'Under 60.'),
  ]),
  en('BrandBadge', 'Trust', 'Badges on a Brand Scorecard.', [
    ev('fast_decisions', 'Fast decisions', 'mint', 'Median decision time under 24 hours.'),
    ev('funded_always', 'Always funded', 'mint', 'Every live bounty fully escrowed.'),
    ev('pays_on_time', 'Pays on time', 'mint', 'No late top-ups on commissions or direct offers.'),
    ev('fair_reviews', 'Fair reviews', 'mint', 'Rejections rarely overturned on appeal.'),
    ev('runs_what_it_approves', 'Runs what it approves', 'mint', 'Over 90% of approved work is posted or used.'),
  ]),
  en('OfferKind', 'Market', 'Kind of an offer.', [
    ev('invite', 'Invite', 'info', 'Brand invites a creator to an existing open bounty.'),
    ev('direct', 'Direct offer', 'sun', 'Brand buys from a rate card at the ask (or negotiates).'),
    ev('rebuy', 'Re-buy', 'violet', 'Brand pays the creator of a winner for new hooks or variants.'),
  ]),
  en('OfferStatus', 'Market', 'Offer / negotiation state: who has the ball.', [
    ev('awaiting_creator', 'Awaiting creator', 'info', 'The creator needs to accept, counter or decline.'),
    ev('awaiting_brand', 'Awaiting brand', 'info', 'The creator countered; the brand needs to respond.'),
    ev('accepted', 'Accepted', 'mint', 'Agreed; a private direct bounty is funded from the brand wallet.'),
    ev('declined', 'Declined', 'rose', 'Declined.'),
    ev('expired', 'Expired', 'neutral', 'No response in 7 days.'),
    ev('withdrawn', 'Withdrawn', 'neutral', 'Withdrawn by the sender.'),
    ev('completed', 'Completed', 'mint', 'Video delivered, approved and paid.'),
  ]),
  en('OfferMessageType', 'Market', 'Message types in a negotiation thread.', [
    ev('offer', 'Offer', 'sun', 'Opening offer with amount and rights.'),
    ev('counter', 'Counter', 'ember', 'Counter-offer (max 3 rounds).'),
    ev('message', 'Message', 'neutral', 'Free text.'),
    ev('accept', 'Accept', 'mint', 'Accepted the latest terms.'),
    ev('decline', 'Decline', 'rose', 'Declined.'),
    ev('withdraw', 'Withdraw', 'neutral', 'Withdrawn.'),
    ev('system', 'System', 'neutral', 'System note (escrow funded, expiry reminder).'),
  ]),
  en('AuthorRole', 'Market', 'Who wrote a message.', [
    ev('brand', 'Brand', 'info', 'A brand member.'),
    ev('creator', 'Creator', 'accent', 'The creator.'),
    ev('system', 'System', 'neutral', 'flowd.'),
  ]),
  en('AuctionStatus', 'Market', 'Sealed-bid auction lifecycle.', [
    ev('scheduled', 'Scheduled', 'info', 'Not open yet.'),
    ev('open', 'Open', 'mint', 'Accepting sealed bids. Bidders see only their own bid.'),
    ev('closed', 'Closed', 'info', 'Bids sealed; resolving.'),
    ev('awarded', 'Awarded', 'sun', 'The top bids won and pay the uniform clearing price (highest losing bid, or the reserve).'),
    ev('no_bids', 'No bids', 'neutral', 'Closed with no valid bids.'),
    ev('cancelled', 'Cancelled', 'rose', 'Cancelled by the creator or Ops before it closed.'),
  ]),
  en('BidStatus', 'Market', 'State of a sealed bid.', [
    ev('sealed', 'Sealed', 'info', 'Placed; hidden from other bidders.'),
    ev('won', 'Won', 'mint', 'A winning bid; pays the clearing price.'),
    ev('lost', 'Lost', 'neutral', 'Outbid.'),
    ev('withdrawn', 'Withdrawn', 'neutral', 'Withdrawn before close.'),
  ]),
  en('SpecStatus', 'Market', 'Spec Market listing state.', [
    ev('draft', 'Draft', 'neutral', 'Uploaded by the creator, not submitted.'),
    ev('scoring', 'Scoring', 'info', 'QA and checklist scoring running.'),
    ev('first_refusal', 'First refusal', 'ember', 'Released from a bounty; the original brand has 7 days of first refusal.'),
    ev('listed', 'Listed', 'mint', 'Available to license.'),
    ev('licensed', 'Licensed', 'sun', 'Licensed at least once.'),
    ev('withdrawn', 'Withdrawn', 'neutral', 'Taken down by the creator.'),
  ]),
  en('SpecSource', 'Market', 'Where a spec video came from.', [
    ev('creator_upload', 'Creator upload', 'accent', 'Made speculatively by the creator.'),
    ev('released_from_bounty', 'Released from a bounty', 'violet', 'Approved but unused for 30 days.'),
  ]),
  en('RightsScope', 'Rights', 'What a rights grant covers.', [
    ev('organic', 'Organic posting', 'mint', 'Posting on the creator\'s own account. Always included.'),
    ev('paid_ads', 'Paid-ad usage', 'accent', 'Running the video as an ad. Default 90 days, renewable at 25% of base fee per 30 days.'),
    ev('spark_code', 'Spark code', 'accent', 'TikTok Spark authorization code (7/30/60/365 days).'),
    ev('partnership_permission', 'Partnership permission', 'accent', 'Meta partnership-ad permission.'),
    ev('ai_likeness', 'AI likeness', 'rose', 'Off by default; needs explicit separate consent.'),
  ]),
  en('RightsGrantStatus', 'Rights', 'Rights grant lifecycle.', [
    ev('pending_permission', 'Awaiting creator', 'info', 'Brand asked for a Spark code or partnership permission.'),
    ev('active', 'Active', 'mint', 'In force.'),
    ev('expiring', 'Expiring', 'ember', 'Ends within 30 days (alerts at 30, 14 and 7 days).'),
    ev('renewal_requested', 'Renewal requested', 'info', 'The brand asked to renew (25% of base fee per 30 days).'),
    ev('expired', 'Expired', 'neutral', 'Ended; the ad stops automatically.'),
    ev('revoked', 'Revoked', 'rose', 'Revoked for misuse by the creator or Ops.'),
  ]),
  en('DisputeKind', 'Trust', 'What a dispute is about.', [
    ev('view_count', 'View count', 'info', 'The creator disputes the verified view count.'),
    ev('flagged_botting', 'Flagged as bot views', 'ember', 'The creator disputes a fraud flag.'),
    ev('late_payment', 'Late payment', 'ember', 'A payout or commission is late.'),
    ev('rights_misuse', 'Rights misuse', 'rose', 'Use of a video beyond the Rights Card.'),
    ev('wrong_attribution', 'Wrong attribution', 'info', 'A conversion was or was not credited.'),
    ev('rejection_appeal', 'Rejection appeal', 'ember', 'One appeal per rejection; Ops decides within 72 hours.'),
    ev('held_funds', 'Held funds', 'ember', 'Funds are held and the creator disputes the hold.'),
    ev('other', 'Other', 'neutral', 'Anything else.'),
  ]),
  en('DisputeStatus', 'Trust', 'Dispute lifecycle.', [
    ev('open', 'Open', 'info', 'Opened; a human replies within 24 hours.'),
    ev('evidence_requested', 'Evidence requested', 'ember', 'Ops asked a party for evidence.'),
    ev('under_review', 'Under review', 'accent', 'Ops is deciding.'),
    ev('resolved', 'Resolved', 'mint', 'Decided; see the outcome.'),
    ev('withdrawn', 'Withdrawn', 'neutral', 'Withdrawn by the opener.'),
  ]),
  en('DisputeOutcome', 'Trust', 'Result of a resolved dispute, from the opener\'s side.', [
    ev('upheld', 'Upheld', 'mint', 'In the opener\'s favour.'),
    ev('partially_upheld', 'Partly upheld', 'info', 'Partly in the opener\'s favour (amount adjusted).'),
    ev('rejected', 'Rejected', 'rose', 'Not upheld; reasons and evidence shared.'),
  ]),
  en('ScamReason', 'Trust', 'Scam Shield report reasons.', [
    ev('pay_to_join', 'Pay to join', 'rose', 'Asks creators to pay to take part.'),
    ev('off_platform_chat', 'Off-platform chat', 'rose', 'Pushes the conversation to WhatsApp, Telegram or email.'),
    ev('fake_brand', 'Fake brand', 'rose', 'Impersonates a brand.'),
    ev('burner_account_demand', 'Burner-account demand', 'rose', 'Demands a dedicated or fresh account.'),
    ev('no_escrow_claim', 'Claims unfunded work is funded', 'rose', 'Says a bounty is funded without a Funded badge.'),
    ev('suspicious_link', 'Suspicious link', 'rose', 'Phishing or malware link.'),
    ev('harassment', 'Harassment', 'rose', 'Abusive messages.'),
    ev('other', 'Other', 'neutral', 'Anything else.'),
  ]),
  en('ReportTargetKind', 'Trust', 'What a scam report points at.', [
    ev('brand', 'Brand', 'neutral', 'A brand workspace.'),
    ev('bounty', 'Bounty', 'neutral', 'A bounty.'),
    ev('creator', 'Creator', 'neutral', 'A creator.'),
    ev('message', 'Message', 'neutral', 'A chat message.'),
    ev('offer', 'Offer', 'neutral', 'An offer.'),
  ]),
  en('ReportStatus', 'Trust', 'Scam report triage state.', [
    ev('new', 'New', 'info', 'Not triaged.'),
    ev('triaged', 'Triaged', 'accent', 'Looked at by Ops.'),
    ev('confirmed', 'Confirmed', 'rose', 'Confirmed as a scam.'),
    ev('actioned', 'Actioned', 'neutral', 'Account suspended or content removed.'),
    ev('dismissed', 'Dismissed', 'neutral', 'Not a scam.'),
  ]),
  en('FraudFlagStatus', 'Trust', 'Fraud queue state for a flagged post.', [
    ev('open', 'Open', 'ember', 'Waiting for a human review.'),
    ev('monitoring', 'Monitoring', 'info', 'Watching further snapshots.'),
    ev('cleared', 'Cleared', 'mint', 'False positive; money released.'),
    ev('confirmed', 'Confirmed', 'rose', 'Fraud confirmed; invalid views reversed.'),
  ]),
  en('ComplianceCheckType', 'Trust', 'Checks in a post-level compliance audit.', [
    ev('caption_disclosure', 'Caption #ad', 'neutral', 'The caption starts with the required disclosure.'),
    ev('spoken_disclosure', 'Spoken disclosure', 'neutral', 'Disclosure is said in the video.'),
    ev('onscreen_disclosure', 'On-screen disclosure', 'neutral', 'Disclosure is visible in the video.'),
    ev('platform_label', 'Platform branded-content label', 'neutral', 'The platform paid-partnership toggle is on.'),
    ev('music_licence', 'Music licence', 'neutral', 'Commercial-library audio only.'),
    ev('banned_claims', 'Banned claims', 'neutral', 'No disallowed claims in the posted caption or video.'),
    ev('ai_label', 'AI label', 'neutral', 'AI content labelled.'),
    ev('tracking_link', 'Tracking link', 'neutral', 'The tracked link or code is present.'),
  ]),
  en('ComplianceResult', 'Trust', 'Outcome of a compliance check.', [
    ev('pass', 'Pass', 'mint', 'Compliant.'),
    ev('warn', 'Warning', 'ember', 'Minor issue; fix in the caption.'),
    ev('fail', 'Fail', 'rose', 'Failed; blocks settlement until fixed.'),
    ev('pending', 'Pending', 'info', 'Not checked yet.'),
  ]),
  en('TaxForm', 'Trust', 'Tax form a creator files.', [
    ev('w9', 'W-9', 'neutral', 'US persons.'),
    ev('w8ben', 'W-8BEN', 'neutral', 'Non-US persons.'),
  ]),
  en('TaxStatus', 'Trust', 'Tax profile state (just-in-time at first approval).', [
    ev('none', 'Not needed yet', 'neutral', 'No approval yet.'),
    ev('requested', 'Requested', 'ember', 'First approval happened; the form is requested before the first payout.'),
    ev('submitted', 'Submitted', 'info', 'Submitted; checking.'),
    ev('verified', 'Verified', 'mint', 'Verified.'),
    ev('rejected', 'Rejected', 'rose', 'Mismatch (name / TIN); resubmit.'),
    ev('expired', 'Expired', 'ember', 'W-8BEN older than 3 years.'),
  ]),
  en('TaxDocKind', 'Trust', 'Tax documents.', [
    ev('w9', 'W-9', 'neutral', 'Collected form.'),
    ev('w8ben', 'W-8BEN', 'neutral', 'Collected form.'),
    ev('form_1099_nec', '1099-NEC', 'neutral', 'Issued to US creators above the threshold ($2,000 for 2026).'),
  ]),
  en('TaxDocStatus', 'Trust', 'Tax document state.', [
    ev('draft', 'Draft', 'neutral', 'Being prepared.'),
    ev('issued', 'Issued', 'mint', 'Available to download.'),
    ev('corrected', 'Corrected', 'ember', 'Re-issued after a correction.'),
    ev('void', 'Void', 'neutral', 'Voided.'),
  ]),
];
