// Typed lookup tables attached to enums (emitted to types.ts) and the state machines.

/** Reason-code detail. Copy is about the video, never the person. needs_evidence: rejections must attach evidence. */
export const REASON_CODE_INFO = {
  app_not_shown_early: { applies_to: 'both', category: 'hook', qa_check: 'brief_beats', creator_copy: "The app isn't on screen in the first 3 seconds.", fix_hint: 'Cut to the app by 0:03, then come back to your face.' },
  hook_too_late: { applies_to: 'both', category: 'hook', qa_check: null, creator_copy: "The hook doesn't land until after 2 seconds.", fix_hint: 'Open on the hook line. Trim the intro or move the line to the very first frame.' },
  missing_required_beat: { applies_to: 'both', category: 'offer', qa_check: 'brief_beats', creator_copy: 'A beat the brief requires is missing.', fix_hint: 'Add the missing beat from the shot checklist, then re-check the score.' },
  missing_disclosure: { applies_to: 'both', category: 'disclosure', qa_check: 'disclosure_audio', creator_copy: '#ad needs to be spoken and shown on screen.', fix_hint: 'Say "this is a paid partnership" and keep #ad on screen for 2 seconds.' },
  offer_not_stated: { applies_to: 'both', category: 'offer', qa_check: 'brief_beats', creator_copy: "The free-trial offer isn't mentioned.", fix_hint: 'Say the offer out loud once, near the end, before the call to action.' },
  face_not_shown: { applies_to: 'both', category: 'hook', qa_check: null, creator_copy: 'This bounty needs a face on camera in the first seconds.', fix_hint: 'Re-record the opening with your face in frame.' },
  audio_unclear: { applies_to: 'both', category: 'audio', qa_check: 'audio_clarity', creator_copy: 'The speech is hard to hear or has dead air.', fix_hint: 'Move closer to the mic, cut silences, and re-export.' },
  music_not_licensed: { applies_to: 'both', category: 'audio', qa_check: 'music_licence', creator_copy: 'The music is not licensed for ads.', fix_hint: 'Swap it for a commercial-library track or remove the music.' },
  banned_claim: { applies_to: 'both', category: 'claims', qa_check: 'banned_claims', creator_copy: 'A claim in the video is on the brand\'s do-not-say list.', fix_hint: 'Rephrase using the approved wording in the brief.' },
  off_brief: { applies_to: 'both', category: 'brand', qa_check: null, creator_copy: "The concept doesn't follow the stated brief.", fix_hint: 'Re-read the brief TL;DR and pick one of the suggested formats.' },
  low_video_quality: { applies_to: 'both', category: 'pacing', qa_check: 'resolution', creator_copy: 'The video is too dark, shaky or low resolution.', fix_hint: 'Film near a window, hold steady, and export at 1080x1920.' },
  wrong_format: { applies_to: 'both', category: 'pacing', qa_check: 'aspect_ratio', creator_copy: 'The video is not 9:16 or is outside the allowed length.', fix_hint: 'Re-export at 1080x1920 and keep it between 15 and 30 seconds.' },
  duplicate_content: { applies_to: 'reject', category: 'brand', qa_check: 'duplicate', creator_copy: 'This video matches one that was already submitted or posted.', fix_hint: 'Film a new original take.' },
  unoriginal_clip: { applies_to: 'reject', category: 'brand', qa_check: 'duplicate', creator_copy: 'The video reuses someone else\'s footage.', fix_hint: 'Use only your own footage and screen recordings.' },
  watermark_present: { applies_to: 'both', category: 'brand', qa_check: 'watermark', creator_copy: "Another app's watermark or logo is visible.", fix_hint: 'Re-export your screen recording without overlays.' },
  competitor_shown: { applies_to: 'both', category: 'brand', qa_check: null, creator_copy: 'A competing app is visible on screen.', fix_hint: 'Crop or re-record the section.' },
  ai_content_undisclosed: { applies_to: 'both', category: 'disclosure', qa_check: 'ai_content', creator_copy: 'AI-generated media needs a visible AI label.', fix_hint: 'Add the "AI-generated" label on screen.' },
  brand_safety: { applies_to: 'reject', category: 'brand', qa_check: 'moderation', creator_copy: "The content is outside the brand's safety rules.", fix_hint: 'Review the do and don\'t list in the brief.' },
  region_mismatch: { applies_to: 'reject', category: 'brand', qa_check: null, creator_copy: "Your audience isn't in this bounty's target regions.", fix_hint: 'Look for bounties that match your audience; your next one may fit.' },
  other_requirement: { applies_to: 'both', category: 'brand', qa_check: null, creator_copy: 'A requirement written in the brief is missing.', fix_hint: 'The quoted requirement shows exactly what to change.' },
  suspected_fraud: { applies_to: 'admin', category: 'brand', qa_check: null, creator_copy: 'Views on this post were found to be invalid. Legitimate views delivered are still paid.', fix_hint: 'You can dispute this from the post.' },
};

/**
 * State machines. transitions: [from, to, actors, trigger, guard].
 * `null` as from = creation. Actors are ActorKind values.
 */
const T = (from, to, actors, trigger, guard = '') => ({ from, to, actors, trigger, guard });

export const STATE_MACHINES = [
  {
    name: 'bounty', enum: 'BountyStatus', initial: 'draft', terminal: ['settled', 'cancelled'],
    doc: 'A bounty cannot go live until fully escrowed (the Funded badge). Brief Lint blockers prevent publishing.',
    transitions: [
      T('draft', 'awaiting_funding', ['brand'], 'Publish', 'Brief Lint has no blockers; budget >= $100.'),
      T('draft', 'cancelled', ['brand'], 'Discard draft'),
      T('awaiting_funding', 'draft', ['brand'], 'Edit brief'),
      T('awaiting_funding', 'live', ['system'], 'Escrow fully funded', 'escrow_funded_cents >= budget_cents + fee_reserve_cents and starts_at <= now.'),
      T('awaiting_funding', 'scheduled', ['system'], 'Escrow fully funded', 'Funded but starts_at is in the future.'),
      T('awaiting_funding', 'cancelled', ['brand'], 'Cancel'),
      T('scheduled', 'live', ['system'], 'starts_at reached'),
      T('scheduled', 'cancelled', ['brand', 'admin'], 'Cancel', 'Escrow refunded to the wallet.'),
      T('live', 'paused', ['brand', 'admin'], 'Pause', 'Ops pauses for a compliance or scam review.'),
      T('paused', 'live', ['brand', 'admin'], 'Resume'),
      T('live', 'filled', ['system'], 'Budget fully reserved', 'remaining_cents < one reservation unit (per_video_cap + fee).'),
      T('filled', 'live', ['system'], 'Reservations released', 'A rejection, withdrawal or settlement freed at least one reservation unit and ends_at has not passed.'),
      T('live', 'ended', ['brand', 'system'], 'End now / ends_at reached'),
      T('paused', 'ended', ['brand', 'system'], 'End now / ends_at reached'),
      T('filled', 'ended', ['brand', 'system'], 'End now / ends_at reached'),
      T('live', 'cancelled', ['brand', 'admin'], 'Cancel', 'Only with zero approved submissions.'),
      T('paused', 'cancelled', ['brand', 'admin'], 'Cancel', 'Only with zero approved submissions.'),
      T('ended', 'settled', ['system'], 'All windows closed', 'Every post window and 30-day CPA window is closed; unspent escrow refunded to the wallet.'),
    ],
  },
  {
    name: 'submission', enum: 'SubmissionStatus', initial: 'qa_pending', terminal: ['posted', 'withdrawn', 'expired', 'released'],
    doc: 'Reservation is taken on submit (up to the per-video cap plus fee) and released on rejection, withdrawal or expiry. Approved posts are paid even if the pool later empties.',
    transitions: [
      T(null, 'qa_pending', ['creator'], 'Submit', 'Bounty is live or filled-with-capacity; creator tier early-access window open; a reservation can be taken.'),
      T('qa_pending', 'in_review', ['system'], 'QA and scoring complete', 'Starts the 72h SLA clock.'),
      T('qa_pending', 'rejected', ['system'], 'Hard QA failure', 'Exact duplicate or moderation fail; evidence attached.'),
      T('in_review', 'approved', ['brand', 'system'], 'Approve / auto-approve rule / timeout approve-if-clean', 'Auto-approve only when every guardrail passes.'),
      T('in_review', 'changes_requested', ['brand'], 'Request changes', 'At least one must-fix timecoded note; revision_round < 2 (extra rounds are paid by the brand).'),
      T('in_review', 'rejected', ['brand'], 'Reject', 'Reason code + evidence mandatory; must cite a stated requirement.'),
      T('in_review', 'withdrawn', ['creator'], 'Withdraw'),
      T('changes_requested', 'qa_pending', ['creator'], 'Resubmit', 'Creates version + 1; carries open must-fix notes.'),
      T('changes_requested', 'withdrawn', ['creator'], 'Withdraw'),
      T('changes_requested', 'expired', ['system'], 'No resubmission in 14 days'),
      T('approved', 'posted', ['creator', 'system'], 'Post detected and verified', 'Creates the post, opens the 72h window.'),
      T('approved', 'released', ['system'], 'Unused for 30 days', 'Not posted and not used; moves to the Spec Market (brand keeps first refusal for 7 days).'),
      T('approved', 'withdrawn', ['creator'], 'Withdraw', 'Before posting.'),
      T('rejected', 'appealed', ['creator'], 'Appeal', 'One appeal per rejection, within 7 days.'),
      T('appealed', 'approved', ['admin'], 'Overturn', 'Ops decides within 72h; brand notified; reliability effect on the brand.'),
      T('appealed', 'rejected', ['admin'], 'Uphold', 'No further appeal.'),
    ],
  },
  {
    name: 'post', enum: 'PostStatus', initial: 'live', terminal: ['paid', 'removed', 'clawed_back'],
    doc: 'Tracks the CPM / flat-fee leg. 72-hour window, then fraud and compliance check, then cleared. Conversions and ad commission settle on their own ledger rows.',
    transitions: [
      T(null, 'live', ['system'], 'Post verified', 'posted_at set; window_ends_at = posted_at + 72h.'),
      T('live', 'window_closed', ['system'], '72 hours elapsed'),
      T('live', 'removed', ['creator', 'system'], 'Post deleted before the window closes', 'Earns nothing.'),
      T('window_closed', 'cleared', ['system'], 'Fraud + compliance check passed', 'fraud score < 40 and compliance not failed; at the next daily clearing run.'),
      T('window_closed', 'held', ['system'], 'Fraud score >= 40 or compliance fail or dispute opened'),
      T('held', 'cleared', ['admin'], 'Hold resolved in favour of the creator'),
      T('held', 'clawed_back', ['admin'], 'Fraud confirmed', 'Invalid views reversed; delivered legitimate views still paid.'),
      T('cleared', 'paid', ['system'], 'Included in a weekly payout or an instant cash-out'),
      T('cleared', 'clawed_back', ['admin'], 'Proven fraud found after clearing', 'Only proven fraud can undo an approved, cleared post.'),
    ],
  },
  {
    name: 'ledger', enum: 'LedgerStatus', initial: 'pending', terminal: ['paid', 'reversed'],
    doc: 'Ledger rows are append-only. Only status, cleared_at, paid_at and payout_id are ever updated.',
    transitions: [
      T(null, 'pending', ['system'], 'Settlement writes the rows', 'The txn nets to zero.'),
      T('pending', 'cleared', ['system'], 'Clearing run', 'Fraud and compliance passed; conversion windows elapsed.'),
      T('pending', 'held', ['system', 'admin'], 'Hold placed'),
      T('held', 'cleared', ['admin', 'system'], 'Hold released'),
      T('cleared', 'paid', ['system'], 'Payout created', 'payout_id set.'),
      T('pending', 'reversed', ['admin', 'system'], 'Clawback'),
      T('cleared', 'reversed', ['admin'], 'Clawback', 'Proven fraud only.'),
      T('held', 'reversed', ['admin'], 'Clawback'),
    ],
  },
  {
    name: 'payout', enum: 'PayoutStatus', initial: 'scheduled', terminal: ['paid', 'cancelled'],
    doc: 'Weekly payouts run Fridays 18:00 UTC; instant payouts start at processing.',
    transitions: [
      T(null, 'scheduled', ['system'], 'Cleared earnings exist', 'Weekly auto-payout.'),
      T(null, 'processing', ['creator'], 'Instant cash-out', 'Fee previewed and confirmed first.'),
      T('scheduled', 'processing', ['system'], 'Weekly run starts', 'Fri 18:00 UTC; tax info, ID and payout method present.'),
      T('scheduled', 'held', ['system', 'admin'], 'Hold', 'Missing tax info, ID, payout method, fraud review or dispute.'),
      T('held', 'scheduled', ['system', 'admin'], 'Hold released'),
      T('scheduled', 'cancelled', ['creator', 'admin'], 'Cancel'),
      T('processing', 'in_transit', ['system'], 'Transfer created'),
      T('in_transit', 'paid', ['system'], 'Transfer confirmed'),
      T('processing', 'failed', ['system'], 'Transfer failed'),
      T('in_transit', 'failed', ['system'], 'Transfer returned'),
      T('failed', 'scheduled', ['system'], 'Method fixed; retry at the next run'),
    ],
  },
  {
    name: 'offer', enum: 'OfferStatus', initial: 'awaiting_creator', terminal: ['declined', 'expired', 'withdrawn', 'completed'],
    doc: 'Negotiation: at most 3 counter rounds; expires after 7 days with no response.',
    transitions: [
      T(null, 'awaiting_creator', ['brand'], 'Send offer / invite / re-buy'),
      T('awaiting_creator', 'accepted', ['creator'], 'Accept', 'Brand wallet funds the private direct bounty at acceptance.'),
      T('awaiting_creator', 'awaiting_brand', ['creator'], 'Counter'),
      T('awaiting_creator', 'declined', ['creator'], 'Decline'),
      T('awaiting_brand', 'accepted', ['brand'], 'Accept counter'),
      T('awaiting_brand', 'awaiting_creator', ['brand'], 'Counter back', 'Max 3 counter rounds.'),
      T('awaiting_brand', 'declined', ['brand'], 'Decline'),
      T('awaiting_creator', 'withdrawn', ['brand'], 'Withdraw'),
      T('awaiting_brand', 'withdrawn', ['brand'], 'Withdraw'),
      T('awaiting_creator', 'expired', ['system'], '7 days, no response'),
      T('awaiting_brand', 'expired', ['system'], '7 days, no response'),
      T('accepted', 'completed', ['system'], 'Video approved and paid'),
    ],
  },
  {
    name: 'auction', enum: 'AuctionStatus', initial: 'scheduled', terminal: ['awarded', 'no_bids', 'cancelled'],
    doc: 'Sealed-bid, second price. k slots: the k highest bids win and all pay the highest losing bid (or the reserve if there is none).',
    transitions: [
      T(null, 'scheduled', ['creator'], 'Create auction', 'Platinum or Elite creator.'),
      T('scheduled', 'open', ['system'], 'opens_at reached'),
      T('open', 'closed', ['system'], 'closes_at reached'),
      T('closed', 'awarded', ['system'], 'Resolve', 'Winners charged from their wallets; each creates a private direct bounty.'),
      T('closed', 'no_bids', ['system'], 'Resolve'),
      T('scheduled', 'cancelled', ['creator', 'admin'], 'Cancel'),
      T('open', 'cancelled', ['creator', 'admin'], 'Cancel', 'Bids released.'),
    ],
  },
  {
    name: 'dispute', enum: 'DisputeStatus', initial: 'open', terminal: ['resolved', 'withdrawn'],
    doc: 'One-tap dispute with a human reply SLA of 24 hours.',
    transitions: [
      T(null, 'open', ['creator', 'brand'], 'Open dispute'),
      T('open', 'evidence_requested', ['admin'], 'Request evidence'),
      T('evidence_requested', 'open', ['creator', 'brand'], 'Provide evidence'),
      T('open', 'under_review', ['admin'], 'Start review'),
      T('evidence_requested', 'under_review', ['admin'], 'Start review'),
      T('under_review', 'resolved', ['admin'], 'Decide', 'outcome set: upheld, partially_upheld or rejected.'),
      T('open', 'withdrawn', ['creator', 'brand'], 'Withdraw'),
      T('evidence_requested', 'withdrawn', ['creator', 'brand'], 'Withdraw'),
    ],
  },
  {
    name: 'rights_grant', enum: 'RightsGrantStatus', initial: 'pending_permission', terminal: ['expired', 'revoked'],
    doc: 'Expiry alerts at 30, 14 and 7 days. Ads stop automatically when rights end.',
    transitions: [
      T(null, 'active', ['system'], 'Approval creates the organic grant', 'Organic is always included.'),
      T(null, 'pending_permission', ['brand'], 'Request Spark code / partnership permission'),
      T('pending_permission', 'active', ['creator'], 'Creator grants permission or shares the code'),
      T('pending_permission', 'revoked', ['creator'], 'Creator declines'),
      T('active', 'expiring', ['system'], '30 days before ends_at'),
      T('expiring', 'renewal_requested', ['brand'], 'Request renewal', '25% of the base fee per 30 days.'),
      T('active', 'renewal_requested', ['brand'], 'Request renewal'),
      T('renewal_requested', 'active', ['creator', 'system'], 'Renewal accepted', 'ends_at extended; rights_fee charged to the wallet.'),
      T('expiring', 'expired', ['system'], 'ends_at reached', 'Running ads stop.'),
      T('active', 'expired', ['system'], 'ends_at reached'),
      T('active', 'revoked', ['creator', 'admin'], 'Revoke', 'Misuse beyond the Rights Card.'),
      T('expiring', 'revoked', ['creator', 'admin'], 'Revoke'),
    ],
  },
  {
    name: 'ad', enum: 'AdStatus', initial: 'requested', terminal: ['ended', 'expired', 'declined'],
    doc: 'Winner promotion. Ad commission is 10% of ad-attributed revenue for 60 days from the first live day; the platform fee is 1% of ad spend.',
    transitions: [
      T(null, 'requested', ['brand'], 'Promote winner', 'Pro plan; post is cleared; paid-ad rights active.'),
      T('requested', 'authorised', ['creator'], 'Grant permission / share Spark code'),
      T('requested', 'declined', ['creator'], 'Decline'),
      T('authorised', 'live', ['brand'], 'Launch', 'Ad account connected.'),
      T('authorised', 'expired', ['system'], 'Code or rights expired before launch'),
      T('live', 'paused', ['brand'], 'Pause'),
      T('paused', 'live', ['brand'], 'Resume'),
      T('live', 'fatigued', ['system'], 'Trial-start rate down 30% from peak'),
      T('fatigued', 'live', ['system'], 'Recovered'),
      T('live', 'ended', ['brand'], 'Stop'),
      T('paused', 'ended', ['brand'], 'Stop'),
      T('fatigued', 'ended', ['brand'], 'Stop'),
      T('live', 'expired', ['system'], 'Spark code or rights ended'),
      T('fatigued', 'expired', ['system'], 'Spark code or rights ended'),
    ],
  },
  {
    name: 'verification', enum: 'VerificationStatus', initial: 'not_started', terminal: [],
    doc: 'ID, age, business, tax and payout-method verifications. Just-in-time at first approval for creators.',
    transitions: [
      T('not_started', 'pending', ['creator', 'brand'], 'Submit'),
      T('pending', 'verified', ['system', 'admin'], 'Provider or Ops approves'),
      T('pending', 'needs_info', ['system', 'admin'], 'More information needed'),
      T('pending', 'rejected', ['system', 'admin'], 'Cannot verify'),
      T('needs_info', 'pending', ['creator', 'brand'], 'Resubmit'),
      T('rejected', 'pending', ['creator', 'brand'], 'Resubmit'),
      T('verified', 'expired', ['system'], 'Validity ended'),
      T('expired', 'pending', ['creator', 'brand'], 'Renew'),
    ],
  },
  {
    name: 'conversion', enum: 'ConversionStatus', initial: 'pending', terminal: ['rejected', 'refunded'],
    doc: 'Conversion batches clear after install 24h, trial 72h, paid 168h. CPA pays only on link and code sources.',
    transitions: [
      T(null, 'pending', ['system'], 'Attributed (link, code, MMP, survey or modelled)'),
      T('pending', 'cleared', ['system'], 'Clearing window elapsed', 'Payable sources write a cpa ledger row.'),
      T('pending', 'rejected', ['system'], 'Duplicate or fraud'),
      T('cleared', 'refunded', ['system'], 'Refund inside the window', 'CPA reversed.'),
    ],
  },
  {
    name: 'money_clock', enum: 'MoneyClockState', initial: 'accruing', terminal: ['paid', 'reversed'],
    doc: 'The creator-facing projection of earnings. Derived from posts, conversions and the ledger; never edited directly.',
    transitions: [
      T(null, 'accruing', ['system'], 'Post goes live'),
      T('accruing', 'pending', ['system'], 'Window closes / conversion tracked'),
      T('pending', 'cleared', ['system'], 'Clearing run'),
      T('pending', 'held', ['system', 'admin'], 'Hold'),
      T('held', 'cleared', ['admin', 'system'], 'Hold released'),
      T('cleared', 'paid', ['system'], 'Payout'),
      T('pending', 'reversed', ['admin'], 'Clawback'),
      T('cleared', 'reversed', ['admin'], 'Clawback'),
      T('held', 'reversed', ['admin'], 'Clawback'),
    ],
  },
  {
    name: 'daily_drop', enum: 'DropStatus', initial: 'upcoming', terminal: ['sold_out', 'closed'],
    doc: 'One drop a day at 16:00 UTC. Spots left is always a true count.',
    transitions: [
      T(null, 'upcoming', ['system'], 'Scheduled'),
      T('upcoming', 'live', ['system'], '16:00 UTC'),
      T('live', 'sold_out', ['system'], 'Last spot claimed'),
      T('live', 'closed', ['system'], 'Claim window ended (24h)', 'Unclaimed spots return to the open feed.'),
    ],
  },
  {
    name: 'tournament', enum: 'TournamentStatus', initial: 'announced', terminal: ['complete', 'cancelled'],
    doc: 'Sponsored prize pools; prizes paid as ledger rows of type prize.',
    transitions: [
      T(null, 'announced', ['admin'], 'Announce'),
      T('announced', 'open', ['system'], 'Entries open'),
      T('open', 'live', ['system'], 'Starts'),
      T('live', 'judging', ['system'], 'Final round ends'),
      T('judging', 'complete', ['system', 'admin'], 'Results verified, prizes paid'),
      T('announced', 'cancelled', ['admin'], 'Cancel'),
      T('open', 'cancelled', ['admin'], 'Cancel'),
    ],
  },
  {
    name: 'auto_approve_rule', enum: 'RuleStatus', initial: 'draft', terminal: [],
    doc: 'Guarded auto-approve: a dry run on the last 50 submissions is mandatory; 10% spot-check; kill switch.',
    transitions: [
      T('draft', 'dry_run', ['brand'], 'Run dry run'),
      T('dry_run', 'active', ['brand'], 'Enable', 'A dry run completed on the current conditions.'),
      T('dry_run', 'draft', ['brand'], 'Edit conditions'),
      T('active', 'paused', ['brand', 'system'], 'Pause / guardrail trip', 'Any clawback or fraud event pauses the rule.'),
      T('paused', 'active', ['brand'], 'Resume'),
      T('active', 'killed', ['brand'], 'Kill switch'),
      T('paused', 'killed', ['brand'], 'Kill switch'),
      T('killed', 'dry_run', ['brand'], 'Re-enable', 'Needs a fresh dry run.'),
    ],
  },
  {
    name: 'fatigue_alert', enum: 'FatigueStatus', initial: 'open', terminal: ['resolved', 'dismissed'],
    doc: 'Rule-based: trial-start rate down 30% from peak.',
    transitions: [
      T(null, 'open', ['system'], 'Detected'),
      T('open', 'acknowledged', ['brand'], 'Acknowledge'),
      T('open', 'dismissed', ['brand'], 'Dismiss'),
      T('acknowledged', 'refreshing', ['brand'], 'Create refresh bounty'),
      T('refreshing', 'resolved', ['system', 'brand'], 'Refresh live / recovered'),
      T('acknowledged', 'dismissed', ['brand'], 'Dismiss'),
    ],
  },
  {
    name: 'spec', enum: 'SpecStatus', initial: 'draft', terminal: ['withdrawn'],
    doc: 'Spec Market. A spec needs Flow Score 55+ (band C) to list. Released-from-bounty specs start in first refusal.',
    transitions: [
      T(null, 'draft', ['creator'], 'Upload spec'),
      T('draft', 'scoring', ['creator'], 'Submit for scoring'),
      T('scoring', 'listed', ['system'], 'Scored and QA passed', 'Flow points >= 55.'),
      T('scoring', 'draft', ['system'], 'Below listing score or QA failed'),
      T(null, 'first_refusal', ['system'], 'Released from a bounty', 'Source brand has 7 days of first refusal.'),
      T('first_refusal', 'licensed', ['brand'], 'Original brand licenses it'),
      T('first_refusal', 'listed', ['system'], '7 days elapsed'),
      T('listed', 'licensed', ['brand'], 'License', 'Take rate applies on top of the price.'),
      T('licensed', 'listed', ['system'], 'Non-exclusive: stays listed'),
      T('listed', 'withdrawn', ['creator'], 'Withdraw'),
      T('draft', 'withdrawn', ['creator'], 'Withdraw'),
    ],
  },
  {
    name: 'referral', enum: 'ReferralStatus', initial: 'invited', terminal: ['complete', 'expired'],
    doc: 'Single level, platform-funded; the referred person is never charged.',
    transitions: [
      T(null, 'invited', ['creator', 'brand'], 'Invite'),
      T('invited', 'joined', ['system'], 'Signs up with the code'),
      T('invited', 'expired', ['system'], 'Unused for 30 days'),
      T('joined', 'first_dollar', ['system'], 'First cleared earnings (creators) / first funded bounty (brands)'),
      T('first_dollar', 'earning', ['system'], 'Reward window opens'),
      T('earning', 'complete', ['system'], '90 days, 12 months or cap reached'),
    ],
  },
  {
    name: 'fraud_flag', enum: 'FraudFlagStatus', initial: 'open', terminal: ['cleared', 'confirmed'],
    doc: 'Admin fraud queue (fraud score 40+).',
    transitions: [
      T(null, 'open', ['system'], 'Score 40 or above'),
      T('open', 'monitoring', ['admin'], 'Watch more snapshots'),
      T('monitoring', 'open', ['system'], 'New anomaly'),
      T('open', 'cleared', ['admin'], 'False positive'),
      T('monitoring', 'cleared', ['admin'], 'False positive'),
      T('open', 'confirmed', ['admin'], 'Confirm fraud'),
      T('monitoring', 'confirmed', ['admin'], 'Confirm fraud'),
    ],
  },
  {
    name: 'scam_report', enum: 'ReportStatus', initial: 'new', terminal: ['actioned', 'dismissed'],
    doc: 'Scam Shield reports from creators or brands.',
    transitions: [
      T(null, 'new', ['creator', 'brand'], 'Report'),
      T('new', 'triaged', ['admin'], 'Triage'),
      T('triaged', 'confirmed', ['admin'], 'Confirm'),
      T('triaged', 'dismissed', ['admin'], 'Dismiss'),
      T('confirmed', 'actioned', ['admin'], 'Suspend / remove'),
    ],
  },
  {
    name: 'invoice', enum: 'InvoiceStatus', initial: 'draft', terminal: ['void', 'refunded'],
    doc: 'Brand invoices (funding, subscription, ad fee).',
    transitions: [
      T(null, 'draft', ['system'], 'Created'),
      T('draft', 'open', ['system'], 'Issued'),
      T('open', 'paid', ['system'], 'Paid'),
      T('open', 'void', ['system', 'admin'], 'Voided'),
      T('paid', 'refunded', ['admin'], 'Refund'),
    ],
  },
  {
    name: 'tax_profile', enum: 'TaxStatus', initial: 'none', terminal: [],
    doc: 'Tax Desk. W-9 is requested just in time at the first approval, before the first payout.',
    transitions: [
      T('none', 'requested', ['system'], 'First approval'),
      T('requested', 'submitted', ['creator'], 'Submit form'),
      T('submitted', 'verified', ['system', 'admin'], 'Verified'),
      T('submitted', 'rejected', ['system', 'admin'], 'Name or TIN mismatch'),
      T('rejected', 'submitted', ['creator'], 'Resubmit'),
      T('verified', 'expired', ['system'], 'W-8BEN older than 3 years'),
      T('expired', 'submitted', ['creator'], 'Renew'),
    ],
  },
];
