/**
 * Flo, the in-app copilot: the provider interface and what it returns. The mock engine and the Claude provider both implement
 * `AIProvider`, and every screen talks to the interface, so swapping engines changes no UI (docs/DECISIONS.md, feature 29).
 */

import type {
  AuditHook,
  BountyType,
  Brief,
  Category,
  Cents,
  Deliverables,
  FloAction,
  FloKind,
  FloSurface,
  FormatId,
  IsoTimestamp,
  PayMath,
  RightsCard,
} from "@/lib/contract/types";
import type { Funding } from "@/lib/engine/pricing";
import type { FloTask, FloTaskKind } from "./schemas";

export type { FloTask, FloTaskKind, FloTaskOf, FloApp, FloBounty, FloFormat, FloScoreItem, NextActionSignals } from "./schemas";

/** The one id of the engine that answered. */
export type FloEngine = "mock" | "claude" | "remote";

/** Where an answer came from. `fixture` is a saved suggestion replayed from the demo world; `mock` was generated by the deterministic engine. */
export type FloSource = "fixture" | "mock" | "claude";

/** The honest label every Flo answer carries (BRAND.md 4.3): Flo is checklist-based and can be wrong. */
export const FLO_LABEL = "Checklist-based and can be wrong. Check it against the brief before you post.";
export const FLO_DRAFT_LABEL = "A draft to edit. Brief Lint decides what can go live.";
export const FLO_ESTIMATE_LABEL = "An estimate from market data. Not a promise.";

/** One Brief Lint finding, in the short form the builder shows beside a Flo draft. */
export interface DraftLintFinding {
  code: string;
  severity: "blocker" | "warning" | "info";
  title: string;
  message: string;
  fix: string;
}

/**
 * A bounty drafted from an App Store listing. The words (title, brief, hooks) come from Flo; the numbers (price, budget, fee, Pay Math)
 * and the lint come from the engine, always. Apply it to the builder, edit it, and Brief Lint still decides what can go live.
 */
export interface BountyDraft {
  category: Category;
  app: { name: string; slug: string; category: Category; store_url: string; tagline: string; features: string[] };
  title: string;
  type: BountyType;
  brief: Brief;
  cpm_cents: Cents;
  cpa_install_cents: Cents;
  cpa_trial_cents: Cents;
  cpa_paid_cents: Cents;
  per_video_cap_cents: Cents;
  budget_cents: Cents;
  rights_card: RightsCard;
  deliverables: Deliverables;
  format_ids: FormatId[];
  /** Ten scored hooks from the audit generator, best first. Checklist scores of the words only. */
  hooks: AuditHook[];
  /** Where the price comes from. */
  pricing: {
    clearing_cpm_cents: Cents;
    p25_cpm_cents: Cents;
    p75_cpm_cents: Cents;
    fill_hours_p50: number;
    confidence: number;
    thin_market: boolean;
    basis: string;
  };
  funding: Funding;
  /** What the budget buys at the clearing price (an estimate). */
  estimate: { views: number; trials_median: number; cost_per_trial_cents: Cents | null };
  pay_math: PayMath | null;
  lint: { can_publish: boolean; blockers: number; warnings: number; infos: number; findings: DraftLintFinding[] };
  /** Why each number is what it is, one line each. */
  rationale: string[];
  starts_at: IsoTimestamp;
  ends_at: IsoTimestamp;
}

/** What Flo returns. It maps onto the contract's `FloSuggestion` (see `toFloSuggestion`) so history is stored the same way. */
export interface FloResult {
  /** The contract kind to store it under. A comment reply is stored as a `caption`. */
  kind: FloKind;
  /** What was asked for. */
  task_kind: FloTaskKind;
  surface: FloSurface;
  title: string;
  /** The answer, as separate options (three scripts, three hooks, five bullets). */
  outputs: string[];
  /** Secondary lines the UI may show under the options ("Your hook scores 41 now"). */
  notes: string[];
  actions: FloAction[];
  /** "flo-mock-1" or the Claude model id. */
  model: string;
  latency_ms: number;
  /** The honesty label to show with the answer. */
  label: string;
  source: FloSource;
  /** A saved suggestion this answer replayed. */
  fixture_id?: string;
  /** The remote engine failed and the local mock answered instead. */
  degraded?: boolean;
  /** `bounty_draft` only. */
  draft?: BountyDraft;
}

/** Events of a streamed answer. Options stream one after another; `done` carries the complete result. */
export type FloStreamEvent =
  | { type: "start"; task_kind: FloTaskKind; title: string; model: string; source: FloSource; outputs: number }
  | { type: "delta"; output: number; text: string }
  | { type: "output_end"; output: number }
  | { type: "done"; result: FloResult }
  | { type: "error"; message: string };

export interface TypewriterOptions {
  /** Characters per second. Default 120 (a fast typist; scripts finish in a few seconds). */
  charsPerSecond?: number;
  /** Pause before the first character, like thinking. Default 350. */
  firstTokenDelayMs?: number;
  /** Pause after a sentence ends. Default 140. */
  sentencePauseMs?: number;
  /** Pause after a line break. Default 70. */
  newlinePauseMs?: number;
  /** Pause between options. Default 220. */
  outputPauseMs?: number;
  /** Random variation of each chunk's delay, 0 to 1. Default 0.3 (seeded: the same text types the same way). */
  jitter?: number;
  /** Never take longer than this in total; the speed rises to fit. Default 9000. */
  maxDurationMs?: number;
  /** No delays at all: whole options at once (reduced motion, tests, SSR). */
  instant?: boolean;
  signal?: AbortSignal;
  /** Replaces the timer (tests). Resolves after `ms`, or at once when aborted. */
  sleep?: (ms: number, signal?: AbortSignal) => Promise<void>;
  /** Seed for the jitter. */
  seed?: string;
}

export interface FloCallOptions {
  /** 0 is the first answer, 1 regenerates, and so on. Overrides `task.attempt`. */
  attempt?: number;
  /** Replay a saved suggestion when one matches (default true when the provider has any). */
  useFixtures?: boolean;
  /** Streaming pace. */
  typewriter?: TypewriterOptions;
  signal?: AbortSignal;
}

/** The copilot. `generate` returns the whole answer; `stream` yields it as it "types". */
export interface AIProvider {
  readonly id: FloEngine;
  readonly model: string;
  generate(task: FloTask, options?: FloCallOptions): Promise<FloResult>;
  stream(task: FloTask, options?: FloCallOptions): AsyncGenerator<FloStreamEvent, void, void>;
}

/** Thrown by a provider that cannot answer (a network error, a refusal, a malformed reply). The server and the client fall back to the mock. */
export class FloError extends Error {
  readonly code: "unavailable" | "refused" | "invalid_output" | "guard" | "validation" | "aborted";
  constructor(code: FloError["code"], message: string, options?: { cause?: unknown }) {
    super(message, options);
    this.name = "FloError";
    this.code = code;
  }
}
