// Tables that are not 1:1 with a contract entity:
//   * the 15 embedded arrays DOMAIN.md section 6.1 normalises (submission_versions, qa_checks, offer_messages, ...),
//   * read-model replacements (ticker_events, waitlist_entries),
//   * backend infrastructure (ledger_transactions, ledger_balances, wallet_holds, encrypted_secrets, idempotency_keys,
//     inbound_events, job_runs, audit_log, state_transitions, flowd_constants, brand_role_capabilities, ...).
// Columns are raw SQL (types spelled out) because there is no contract field to derive them from.

import { chk, uq, ix, col } from './table-kit.mjs';

const N = { notNull: true };
const now = { notNull: true, default: 'now()' };

export const LOCAL_TABLES = [
  // ── ledger infrastructure ────────────────────────────────────────────────────────────────────
  {
    name: 'ledger_transactions', group: 'Money', source: 'backend',
    doc: 'Header row of a ledger transaction. Guarantees txn ids are unique and that a retried posting (same idempotency key) returns the original transaction instead of posting twice.',
    columns: [
      col('id', 'text', { ...N, default: `'txn_' || lpad(nextval('public.ledger_txn_seq')::text, 9, '0')`, doc: 'txn_<n>. Every ledger leg of one transaction shares it.' }),
      col('kind', 'public.ledger_type', { ...N, doc: 'The primary LedgerType of the transaction (the legs may use sibling types, e.g. fee).' }),
      col('memo', 'text', { doc: 'Plain-English summary.' }),
      col('idempotency_key', 'text', { doc: 'Settlement is idempotent on (post, leg): e.g. settle:cpm:<post_id>, settle:cpa:<conversion_id>, payout:<payout_id>, topup:<payment_intent>.' }),
      col('actor_user_id', 'text', { ref: 'users', doc: 'The signed-in actor, when a human triggered it. Null for system jobs.' }),
      col('reverses_txn_id', 'text', { ref: 'ledger_transactions', doc: 'Clawbacks and refunds point at the transaction they reverse.' }),
      col('created_at', 'timestamptz', now),
    ],
    primaryKey: ['id'],
    checks: [chk('ledger_transactions_id_chk', `id ~ '^txn_[a-z0-9_]+$'`)],
    uniques: [uq('ledger_transactions_idem_key', { cols: ['idempotency_key'], where: 'idempotency_key is not null' })],
    indexes: [ix('ledger_transactions_created_idx', '(created_at desc)'), ix('ledger_transactions_reverses_idx', '(reverses_txn_id) where reverses_txn_id is not null')],
  },
  {
    name: 'ledger_balances', group: 'Money', source: 'backend',
    doc: 'Running balance per ledger account, maintained by an AFTER INSERT trigger on ledger. It is a cache of sum(amount_cents) per account; the ledger wins on any disagreement (public.audit_ledger() recomputes it). The row lock it takes serialises concurrent postings to one account, which is what makes double-spends impossible.',
    columns: [
      col('account', 'text', { ...N, doc: '"<kind>:<id>" as in ledger.account.' }),
      col('balance_cents', 'bigint', { ...N, default: '0', doc: 'Signed. Wallet, escrow and platform accounts may never be negative at commit (treasury accounts and external:* excepted).' }),
      col('updated_at', 'timestamptz', now),
    ],
    primaryKey: ['account'],
    checks: [chk('ledger_balances_account_chk', `account ~ '^(wallet|escrow|creator|platform|external):[a-z0-9_.-]+$'`)],
  },
  {
    name: 'wallet_holds', group: 'Money', source: 'backend',
    doc: 'Authorisation holds on a brand wallet (sealed auction bids, spec licence quotes). A hold moves no money and writes no ledger row; it reduces the available balance: wallet balance must stay >= the sum of active holds (checked at commit).',
    columns: [
      col('id', 'text', { ...N, default: `public.new_id('hold')` }),
      col('brand_id', 'text', { ...N, ref: 'brands' }),
      col('kind', 'text', { ...N, check: `kind in ('auction_bid', 'spec_license', 'other')` }),
      col('ref_id', 'text', { ...N, doc: 'The auction bid / spec the hold belongs to.' }),
      col('amount_cents', 'public.cents', { ...N, check: 'amount_cents > 0' }),
      col('status', 'text', { ...N, default: `'active'`, check: `status in ('active', 'released', 'captured')` }),
      col('created_at', 'timestamptz', now),
      col('released_at', 'timestamptz', {}),
    ],
    primaryKey: ['id'],
    uniques: [uq('wallet_holds_active_key', { cols: ['kind', 'ref_id'], where: `status = 'active'` })],
    indexes: [ix('wallet_holds_brand_idx', `(brand_id) where status = 'active'`)],
  },
  {
    name: 'payout_methods', group: 'Money', source: 'contract (creators.payout_method, normalised)',
    doc: 'A creator payout destination. Only the label and last four digits live here; Stripe Connect holds the real bank or card details.',
    columns: [
      col('id', 'text', { ...N, default: `public.new_id('pm')`, doc: 'pm_<n>.' }),
      col('creator_id', 'text', { ...N, ref: 'creators' }),
      col('kind', 'public.payout_method_kind', N),
      col('label', 'text', { ...N, doc: 'e.g. "Bank account".' }),
      col('last4', 'text', { ...N, check: `last4 ~ '^[0-9]{4}$'` }),
      col('status', 'public.payout_method_status', { ...N, default: `'pending'` }),
      col('instant_capable', 'boolean', { ...N, default: 'false' }),
      col('verified_at', 'timestamptz', {}),
      col('is_default', 'boolean', { ...N, default: 'false' }),
      col('stripe_external_account_id', 'text', { doc: 'Stripe ba_... / card_... on the connected account (an id, not a secret).' }),
      col('created_at', 'timestamptz', now),
      col('deleted_at', 'timestamptz', {}),
    ],
    primaryKey: ['id'],
    checks: [chk('payout_methods_id_chk', `id ~ '^pm_[a-z0-9_-]+$'`)],
    uniques: [uq('payout_methods_one_default_key', { cols: ['creator_id'], where: 'is_default and deleted_at is null' })],
    indexes: [ix('payout_methods_creator_idx', '(creator_id) where deleted_at is null')],
    flags: { softDelete: true },
  },

  // ── read-model replacements ──────────────────────────────────────────────────────────────────
  {
    name: 'ticker_events', group: 'Market', source: 'contract (ticker.events)', entity: 'TickerEvent',
    doc: 'The public live payout ticker feed (newest first in the read model). Public identity is the handle only or an anonymised label; written by payout, tier and fill jobs.',
    columns: [
      col('id', 'text', { ...N, default: `public.new_id('tick')` }),
      col('kind', 'public.ticker_kind', N),
      col('occurred_at', 'timestamptz', now),
      col('text', 'text', { ...N, doc: 'Ready to render: "@kai.frames was paid $84.20".' }),
      col('amount_cents', 'public.cents', {}),
      col('creator_id', 'text', { ref: 'creators' }),
      col('handle', 'text', { doc: 'Public handle; null when anonymous.' }),
      col('tier', 'public.tier', {}),
      col('bounty_id', 'text', { ref: 'bounties' }),
      col('app_name', 'text', {}),
      col('proof_id', 'text', { doc: 'prf_ id of a public proof page.' }),
    ],
    primaryKey: ['id'],
    checks: [chk('ticker_events_handle_chk', 'handle is null or creator_id is not null')],
    indexes: [ix('ticker_events_time_idx', '(occurred_at desc)')],
  },
  {
    name: 'waitlist_entries', group: 'Public', source: 'contract (waitlist, as rows)',
    doc: 'Waitlist sign-ups. The contract Waitlist read model (totals and ranked leaders: handles only, never emails) is built by v_waitlist_totals and v_waitlist_leaders.',
    columns: [
      col('id', 'text', { ...N, default: `public.new_id('wl')` }),
      col('email', 'text', { ...N }),
      col('kind', 'public.party_kind', N),
      col('handle', 'text', { doc: 'Public leaderboard handle. Never the email.' }),
      col('referral_code', 'text', { ...N, doc: 'This entry\'s own referral code.' }),
      col('referred_by_code', 'text', { doc: 'The code they signed up with.' }),
      col('referrals_count', 'public.nat', { ...N, default: '0' }),
      col('joined_at', 'timestamptz', now),
      col('invited_at', 'timestamptz', {}),
      col('invite_accepted_at', 'timestamptz', { doc: 'Set when the invited person accepted (the totals count it as an accepted invite).' }),
      col('converted_user_id', 'text', { ref: 'users', doc: 'The users row created from this entry, once they signed up.' }),
    ],
    primaryKey: ['id'],
    checks: [chk('waitlist_entries_email_chk', `email ~* '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$'`)],
    uniques: [uq('waitlist_entries_email_key', { expr: 'lower(email)' }), uq('waitlist_entries_code_key', { cols: ['referral_code'] })],
    indexes: [ix('waitlist_entries_rank_idx', '(referrals_count desc, joined_at)'), ix('waitlist_entries_referrer_idx', '(referred_by_code) where referred_by_code is not null')],
  },

  // ── normalised embedded arrays (DOMAIN.md section 6.1) ───────────────────────────────────────
  {
    name: 'submission_versions', group: 'Submissions', source: 'contract (submissions.versions)',
    doc: 'One uploaded version (v1, v2, v3) of a submission. Versions are never overwritten. The contract VideoMeta object is flattened into the video_* columns.',
    columns: [
      col('submission_id', 'text', { ...N, ref: 'submissions', onDelete: 'cascade' }),
      col('version', 'public.nat', { ...N, check: 'version >= 1' }),
      col('submitted_at', 'timestamptz', N),
      col('video_asset_id', 'text', { ...N, doc: 'vid_<n>: the Mux asset id.' }),
      col('video_duration_ms', 'public.nat', N),
      col('video_width', 'public.nat', N),
      col('video_height', 'public.nat', N),
      col('video_size_bytes', 'public.bignat', N),
      col('video_fps', 'public.nat', N),
      col('video_has_captions', 'boolean', N),
      col('video_language', 'text', N),
      col('video_art', 'public.art_seed', { ...N, doc: 'Generated thumbnail seed (the demo has no real video).' }),
      col('video_uploaded_at', 'timestamptz', N),
      col('storage_key', 'text', { doc: 'Cloudflare R2 key of the original upload (private bucket).' }),
      col('mux_playback_id', 'text', { doc: 'Signed Mux playback id for the review player.' }),
      col('flow_band', 'public.score_band', N),
      col('flow_points', 'public.nat', { ...N, check: 'flow_points <= 100' }),
      col('hook_band', 'public.score_band', N),
      col('hook_points', 'public.nat', { ...N, check: 'hook_points <= 100' }),
      col('qa_pass', 'public.nat', { ...N, default: '0' }),
      col('qa_warn', 'public.nat', { ...N, default: '0' }),
      col('qa_fail', 'public.nat', { ...N, default: '0' }),
      col('changes_summary', 'text', { doc: 'What the creator changed from the previous version.' }),
    ],
    primaryKey: ['submission_id', 'version'],
    indexes: [ix('submission_versions_asset_idx', '(video_asset_id)')],
  },
  {
    name: 'qa_checks', group: 'Submissions', source: 'contract (video_analyses.checks)',
    doc: 'One automated QA check result per (video analysis, check type). A failed disclosure check blocks settlement.',
    columns: [
      col('video_analysis_id', 'text', { ...N, ref: 'video_analyses', onDelete: 'cascade' }),
      col('check_type', 'public.qa_check_type', { ...N, doc: 'Contract field "check" (a reserved word in SQL).' }),
      col('result', 'public.qa_result', N),
      col('message', 'text', N),
      col('evidence', 'jsonb', { jsonbKind: 'object', doc: 'Evidence value type: kind, ref, excerpt, t_ms.' }),
      col('blocks_settlement', 'boolean', { ...N, default: 'false' }),
      col('waived_by_user_id', 'text', { ref: 'users', doc: 'A brand member waived this warning.' }),
      col('waived_at', 'timestamptz', {}),
    ],
    primaryKey: ['video_analysis_id', 'check_type'],
    checks: [chk('qa_checks_waive_chk', `waived_by_user_id is null or result = 'warn'`)],
    indexes: [ix('qa_checks_result_idx', `(check_type, result)`)],
  },
  {
    name: 'offer_messages', group: 'Market', source: 'contract (offers.thread)',
    doc: 'The negotiation thread of an offer. Append-only: the first message is the opening offer; counters add a message. In-app only.',
    columns: [
      col('id', 'text', { ...N, default: `public.new_id('omsg')` }),
      col('offer_id', 'text', { ...N, ref: 'offers', onDelete: 'cascade' }),
      col('author_role', 'public.author_role', N),
      col('author_user_id', 'text', { ref: 'users' }),
      col('type', 'public.offer_message_type', N),
      col('amount_cents', 'public.cents', {}),
      col('rights_days', 'public.nat', {}),
      col('body', 'text', {}),
      col('sent_at', 'timestamptz', now),
      col('warning_code', 'public.scam_reason', { doc: 'Scam Shield annotation on a risky message.' }),
    ],
    primaryKey: ['id'],
    indexes: [ix('offer_messages_thread_idx', '(offer_id, sent_at)')],
    flags: { appendOnly: true, realtime: true },
  },
  {
    name: 'auction_bids', group: 'Market', source: 'contract (auctions.bids)',
    doc: 'Sealed bids. RLS shows a brand only its own bid while the auction is open; the creator and everyone else see bids only after close.',
    columns: [
      col('id', 'text', { ...N, default: `public.new_id('bid')` }),
      col('auction_id', 'text', { ...N, ref: 'auctions', onDelete: 'cascade' }),
      col('brand_id', 'text', { ...N, ref: 'brands' }),
      col('bidder_member_id', 'text', { ...N, ref: 'brand_members' }),
      col('amount_cents', 'public.cents', { ...N, doc: 'The maximum the brand will pay per slot (second price).' }),
      col('status', 'public.bid_status', { ...N, default: `'sealed'` }),
      col('placed_at', 'timestamptz', now),
      col('escrow_hold_cents', 'public.cents', { ...N, default: '0', doc: 'Held from the brand wallet while open (see wallet_holds).' }),
      col('wallet_hold_id', 'text', { ref: 'wallet_holds' }),
      col('pays_cents', 'public.cents', { doc: 'The uniform clearing price a winner actually paid.' }),
      col('note', 'text', {}),
    ],
    primaryKey: ['id'],
    checks: [chk('auction_bids_won_chk', `status <> 'won' or pays_cents is not null`)],
    uniques: [uq('auction_bids_brand_open_key', { cols: ['auction_id', 'brand_id'], where: `status in ('sealed', 'won')` })],
    indexes: [ix('auction_bids_auction_idx', '(auction_id, amount_cents desc)'), ix('auction_bids_brand_idx', '(brand_id)')],
  },
  {
    name: 'spec_licenses', group: 'Market', source: 'contract (specs.licenses)',
    doc: 'A brand licence of a spec. Paid from the wallet (price + take rate) in one ledger transaction.',
    columns: [
      col('id', 'text', { ...N, default: `public.new_id('lic')` }),
      col('spec_id', 'text', { ...N, ref: 'specs' }),
      col('brand_id', 'text', { ...N, ref: 'brands' }),
      col('licensed_at', 'timestamptz', now),
      col('price_cents', 'public.cents', { ...N, doc: 'Creator price; the brand also pays the take rate on top.' }),
      col('paid_ads_days', 'public.nat', N),
      col('ends_at', 'timestamptz', {}),
      col('ledger_txn_id', 'text', { ref: 'ledger_transactions' }),
    ],
    primaryKey: ['id'],
    uniques: [uq('spec_licenses_spec_brand_key', { cols: ['spec_id', 'brand_id'] })],
    indexes: [ix('spec_licenses_brand_idx', '(brand_id, licensed_at desc)')],
  },
  {
    name: 'rights_renewals', group: 'Rights', source: 'contract (rights_grants.renewals)',
    doc: 'A paid renewal of paid-ad usage (25% of the base fee per 30 days, charged to the brand wallet).',
    columns: [
      col('id', 'text', { ...N, default: `public.new_id('renew')` }),
      col('grant_id', 'text', { ...N, ref: 'rights_grants', onDelete: 'cascade' }),
      col('renewed_at', 'timestamptz', now),
      col('days', 'public.nat', { ...N, check: 'days > 0 and days % 30 = 0' }),
      col('fee_cents', 'public.cents', N),
      col('ledger_txn_id', 'text', { ref: 'ledger_transactions' }),
      col('requested_by_member_id', 'text', { ref: 'brand_members' }),
    ],
    primaryKey: ['id'],
    indexes: [ix('rights_renewals_grant_idx', '(grant_id, renewed_at desc)')],
  },
  {
    name: 'drop_items', group: 'Growth', source: 'contract (daily_drops.items)',
    doc: 'A bounty released through a Daily Drop with real inventory. spots_left is derived: spots_total - count(drop_claims).',
    columns: [
      col('drop_id', 'text', { ...N, ref: 'daily_drops', onDelete: 'cascade' }),
      col('bounty_id', 'text', { ...N, ref: 'bounties' }),
      col('spots_total', 'public.nat', { ...N, check: 'spots_total >= 1' }),
      col('position', 'public.nat', { ...N, default: '0' }),
    ],
    primaryKey: ['drop_id', 'bounty_id'],
    indexes: [ix('drop_items_bounty_idx', '(bounty_id)')],
  },
  {
    name: 'drop_claims', group: 'Growth', source: 'contract (daily_drops.items[].claims)',
    doc: 'A creator claimed a drop spot: a 24-hour reserved place to submit. Claims are unique per creator and item.',
    columns: [
      col('drop_id', 'text', { ...N }),
      col('bounty_id', 'text', { ...N }),
      col('creator_id', 'text', { ...N, ref: 'creators' }),
      col('claimed_at', 'timestamptz', now),
      col('expires_at', 'timestamptz', { ...N, doc: 'claimed_at + 24 hours.' }),
    ],
    primaryKey: ['drop_id', 'bounty_id', 'creator_id'],
    compositeFks: [{ name: 'drop_claims_item_fkey', columns: ['drop_id', 'bounty_id'], table: 'drop_items', refColumns: ['drop_id', 'bounty_id'], onDelete: 'cascade' }],
    checks: [chk('drop_claims_expiry_chk', 'expires_at > claimed_at')],
    indexes: [ix('drop_claims_creator_idx', '(creator_id, claimed_at desc)')],
    flags: { realtime: true },
  },
  {
    name: 'leaderboard_entries', group: 'Growth', source: 'contract (leaderboards.entries)',
    doc: 'Ranked rows of a weekly leaderboard, recomputed on Monday 00:00 UTC. Creators who opted out of leaderboards are excluded.',
    columns: [
      col('leaderboard_id', 'text', { ...N, ref: 'leaderboards', onDelete: 'cascade' }),
      col('creator_id', 'text', { ...N, ref: 'creators' }),
      col('rank', 'public.nat', { ...N, check: 'rank >= 1' }),
      col('value', 'numeric(18,4)', { ...N, doc: 'The ranked metric (cents, ratio or points).' }),
      col('delta_rank', 'integer', { ...N, default: '0', doc: 'Change vs last week (positive = moved up).' }),
      col('zone', 'public.leaderboard_zone', { ...N, default: `'steady'` }),
    ],
    primaryKey: ['leaderboard_id', 'creator_id'],
    uniques: [uq('leaderboard_entries_rank_key', { cols: ['leaderboard_id', 'rank'] })],
    indexes: [ix('leaderboard_entries_creator_idx', '(creator_id)')],
  },
  {
    name: 'dispute_events', group: 'Trust', source: 'contract (disputes.events)',
    doc: 'The append-only timeline of a dispute.',
    columns: [
      col('id', 'bigint', { ...N, generated: 'generated always as identity' }),
      col('dispute_id', 'text', { ...N, ref: 'disputes', onDelete: 'cascade' }),
      col('occurred_at', 'timestamptz', now),
      col('actor', 'public.actor_kind', N),
      col('action', 'public.dispute_action', N),
      col('text', 'text', N),
      col('user_id', 'text', { ref: 'users' }),
    ],
    primaryKey: ['id'],
    indexes: [ix('dispute_events_dispute_idx', '(dispute_id, occurred_at)')],
    flags: { appendOnly: true, realtime: true },
  },
  {
    name: 'chat_messages', group: 'Platform', source: 'contract (threads.messages)',
    doc: 'A message in an in-app thread. In-app chat only; Scam Shield annotates risky messages. Append-only except read_at.',
    columns: [
      col('id', 'text', { ...N, default: `public.new_id('msg')` }),
      col('thread_id', 'text', { ...N, ref: 'threads', onDelete: 'cascade' }),
      col('author_role', 'public.author_role', N),
      col('author_user_id', 'text', { ref: 'users' }),
      col('kind', 'public.message_kind', { ...N, default: `'text'` }),
      col('body', 'text', N),
      col('sent_at', 'timestamptz', now),
      col('warning_code', 'public.scam_reason', { doc: 'Set on kind = warning.' }),
      col('read_at', 'timestamptz', {}),
    ],
    primaryKey: ['id'],
    indexes: [ix('chat_messages_thread_idx', '(thread_id, sent_at)')],
    flags: { appendOnly: true, appendOnlyColumns: ['read_at'], realtime: true },
  },
  {
    name: 'webhook_deliveries', group: 'Platform', source: 'contract (webhooks.deliveries)',
    doc: 'Outbound webhook deliveries with the retry state (the outbox). Payloads are signed with HMAC-SHA256 at send time; the read model shows the last 20 per endpoint. Retention: 30 days.',
    columns: [
      col('id', 'text', { ...N, default: `public.new_id('whd')` }),
      col('webhook_id', 'text', { ...N, ref: 'webhooks', onDelete: 'cascade' }),
      col('event', 'public.webhook_event_type', N),
      col('event_id', 'uuid', { ...N, default: 'gen_random_uuid()', doc: 'Stable id of the event (deliveries of one event share it; receivers dedupe on it).' }),
      col('payload', 'jsonb', { ...N, jsonbKind: 'object' }),
      col('status', 'public.delivery_status', { ...N, default: `'retrying'` }),
      col('status_code', 'integer', {}),
      col('attempt', 'public.nat', { ...N, default: '0' }),
      col('next_retry_at', 'timestamptz', {}),
      col('attempted_at', 'timestamptz', { doc: 'Contract field "at".' }),
      col('latency_ms', 'public.nat', {}),
      col('response_excerpt', 'text', { doc: 'First 512 bytes of the receiver response.' }),
      col('created_at', 'timestamptz', now),
    ],
    primaryKey: ['id'],
    indexes: [
      ix('webhook_deliveries_endpoint_idx', '(webhook_id, created_at desc)'),
      ix('webhook_deliveries_retry_idx', `(next_retry_at) where status = 'retrying'`),
      ix('webhook_deliveries_event_idx', '(event_id)'),
    ],
  },
  {
    name: 'rule_audit_log', group: 'Platform', source: 'contract (auto_approve_rules.audit)',
    doc: 'Append-only audit trail of an auto-approve rule (created, dry run, enabled, paused, killed, spot-checks).',
    columns: [
      col('id', 'bigint', { ...N, generated: 'generated always as identity' }),
      col('rule_id', 'text', { ...N, ref: 'auto_approve_rules', onDelete: 'cascade' }),
      col('occurred_at', 'timestamptz', now),
      col('actor_member_id', 'text', { ref: 'brand_members' }),
      col('action', 'public.rule_audit_action', N),
      col('note', 'text', N),
    ],
    primaryKey: ['id'],
    indexes: [ix('rule_audit_log_rule_idx', '(rule_id, occurred_at)')],
    flags: { appendOnly: true },
  },
  {
    name: 'ad_daily', group: 'Ads', source: 'contract (ads.daily)',
    doc: 'One day of a promoted ad. ads.spend_cents equals the sum of spend_cents here (public.rollup_ad()).',
    columns: [
      col('ad_id', 'text', { ...N, ref: 'ads', onDelete: 'cascade' }),
      col('date', 'date', N),
      col('spend_cents', 'public.cents', { ...N, default: '0' }),
      col('impressions', 'public.bignat', { ...N, default: '0' }),
      col('clicks', 'public.nat', { ...N, default: '0' }),
      col('installs', 'public.nat', { ...N, default: '0' }),
      col('trials', 'public.nat', { ...N, default: '0' }),
      col('paid', 'public.nat', { ...N, default: '0' }),
      col('revenue_cents', 'public.cents', { ...N, default: '0' }),
    ],
    primaryKey: ['ad_id', 'date'],
    indexes: [ix('ad_daily_date_idx', '(date)')],
  },
  {
    name: 'compliance_check_items', group: 'Trust', source: 'contract (compliance_checks.checks)',
    doc: 'One check inside a post-level compliance audit (eight per audit). A failed item blocks settlement until fixed or waived with a logged reason.',
    columns: [
      col('compliance_check_id', 'text', { ...N, ref: 'compliance_checks', onDelete: 'cascade' }),
      col('type', 'public.compliance_check_type', N),
      col('result', 'public.compliance_result', N),
      col('message', 'text', N),
      col('evidence', 'jsonb', { jsonbKind: 'object' }),
      col('blocks_settlement', 'boolean', { ...N, default: 'false' }),
    ],
    primaryKey: ['compliance_check_id', 'type'],
    indexes: [ix('compliance_check_items_fail_idx', `(compliance_check_id) where result = 'fail'`)],
  },

  // ── secrets and plumbing (service role only; no client policy) ───────────────────────────────
  {
    name: 'social_account_tokens', group: 'Security', source: 'backend (BLUEPRINT social_accounts.oauth_token (encrypted))',
    doc: 'OAuth tokens of linked social accounts, encrypted with AES-256-GCM by the edge functions (envelope key from the secret manager, key_version for rotation). No RLS policy exists for clients: only the service role reads it. The contract never carries tokens.',
    columns: [
      col('social_account_id', 'text', { ...N, ref: 'social_accounts', onDelete: 'cascade' }),
      col('ciphertext', 'bytea', { ...N, doc: 'AES-256-GCM(JSON {access_token, refresh_token}).' }),
      col('nonce', 'bytea', { ...N, doc: '96-bit nonce, unique per encryption.' }),
      col('key_version', 'smallint', { ...N, default: '1' }),
      col('scopes', 'text[]', { ...N, default: `'{}'` }),
      col('expires_at', 'timestamptz', { doc: 'Access token expiry.' }),
      col('refresh_expires_at', 'timestamptz', {}),
      col('rotated_at', 'timestamptz', {}),
      col('created_at', 'timestamptz', now),
    ],
    primaryKey: ['social_account_id'],
    indexes: [ix('social_account_tokens_expiry_idx', '(expires_at)')],
  },
  {
    name: 'encrypted_secrets', group: 'Security', source: 'backend',
    doc: 'Generic encrypted secrets: integration credentials, webhook signing secrets, RevenueCat webhook keys. AES-256-GCM like social_account_tokens; service role only. API keys are different: only a sha256 hash is stored (api_keys.key_hash).',
    columns: [
      col('id', 'text', { ...N, default: `public.new_id('sec')` }),
      col('owner_table', 'text', { ...N, check: `owner_table in ('integrations', 'webhooks', 'apps', 'brands')` }),
      col('owner_id', 'text', N),
      col('purpose', 'text', { ...N, doc: 'e.g. signing, revenuecat_webhook, oauth.' }),
      col('ciphertext', 'bytea', N),
      col('nonce', 'bytea', N),
      col('key_version', 'smallint', { ...N, default: '1' }),
      col('last4', 'text', { doc: 'Last four characters, for display.' }),
      col('created_at', 'timestamptz', now),
      col('rotated_at', 'timestamptz', {}),
    ],
    primaryKey: ['id'],
    uniques: [uq('encrypted_secrets_owner_key', { cols: ['owner_table', 'owner_id', 'purpose'] })],
  },
  {
    name: 'idempotency_keys', group: 'Security', source: 'backend',
    doc: 'API idempotency (Idempotency-Key header) for every POST that moves money or creates a settlement artefact. A repeated key returns the stored response; the same key with a different request hash is idempotency_conflict (409). Rows expire after 24 hours.',
    columns: [
      col('scope', 'text', { ...N, doc: 'The caller: usr_x or api_key:key_x.' }),
      col('idem_key', 'text', { ...N, doc: 'The Idempotency-Key header value.' }),
      col('method', 'text', N),
      col('path', 'text', N),
      col('request_hash', 'text', { ...N, doc: 'sha256 of method, path and canonical body.' }),
      col('status', 'text', { ...N, default: `'in_progress'`, check: `status in ('in_progress', 'completed')` }),
      col('response_status', 'integer', {}),
      col('response_body', 'jsonb', {}),
      col('created_at', 'timestamptz', now),
      col('expires_at', 'timestamptz', { ...N, default: `now() + interval '24 hours'` }),
    ],
    primaryKey: ['scope', 'idem_key'],
    indexes: [ix('idempotency_keys_expiry_idx', '(expires_at)')],
  },
  {
    name: 'inbound_events', group: 'Security', source: 'backend',
    doc: 'Webhook inbox: every inbound provider event is stored once (unique on provider + event id) before any processing, so redeliveries are idempotent and failures are replayable.',
    columns: [
      col('id', 'text', { ...N, default: `public.new_id('inb')` }),
      col('provider', 'text', { ...N, check: `provider in ('revenuecat', 'stripe', 'tiktok', 'instagram', 'meta', 'mmp', 'other')` }),
      col('event_id', 'text', { ...N, doc: 'The provider event id (RevenueCat event id, Stripe evt_...).' }),
      col('event_type', 'text', {}),
      col('payload', 'jsonb', { ...N }),
      col('signature_valid', 'boolean', { ...N, default: 'false' }),
      col('status', 'text', { ...N, default: `'received'`, check: `status in ('received', 'processed', 'ignored', 'failed', 'dead')` }),
      col('attempts', 'public.nat', { ...N, default: '0' }),
      col('error', 'text', {}),
      col('received_at', 'timestamptz', now),
      col('processed_at', 'timestamptz', {}),
    ],
    primaryKey: ['id'],
    uniques: [uq('inbound_events_provider_event_key', { cols: ['provider', 'event_id'] })],
    indexes: [ix('inbound_events_status_idx', `(status, received_at) where status in ('received', 'failed')`)],
  },
  {
    name: 'job_runs', group: 'Security', source: 'backend',
    doc: 'One row per scheduled job run. Claiming a run is an insert on (job, scheduled_for): a second invocation of the same slot (pg_cron retry, manual rerun) conflicts and skips, so jobs are idempotent.',
    columns: [
      col('id', 'text', { ...N, default: `public.new_id('job')` }),
      col('job', 'text', { ...N, doc: 'settle-window, sync-views, weekly-payouts, expiry-alerts, daily-drop, housekeeping ...' }),
      col('scheduled_for', 'timestamptz', N),
      col('started_at', 'timestamptz', now),
      col('finished_at', 'timestamptz', {}),
      col('status', 'text', { ...N, default: `'running'`, check: `status in ('running', 'succeeded', 'failed', 'skipped')` }),
      col('stats', 'jsonb', { ...N, default: `'{}'::jsonb`, jsonbKind: 'object' }),
      col('error', 'text', {}),
    ],
    primaryKey: ['id'],
    uniques: [uq('job_runs_slot_key', { cols: ['job', 'scheduled_for'] })],
    indexes: [ix('job_runs_recent_idx', '(job, started_at desc)')],
  },
  {
    name: 'audit_log', group: 'Security', source: 'backend',
    doc: 'Append-only audit trail of privileged actions: admin decisions (fraud, disputes, verification, tier override, lint override, holds), plan or key changes, manual ledger adjustments and constant changes. Brand-visible activity is activity_log.',
    columns: [
      col('id', 'bigint', { ...N, generated: 'generated always as identity' }),
      col('occurred_at', 'timestamptz', now),
      col('actor_user_id', 'text', { ref: 'users' }),
      col('actor_kind', 'public.actor_kind', { ...N, default: `'system'` }),
      col('action', 'text', { ...N, doc: 'e.g. fraud.confirm, dispute.resolve, tier.override, ledger.adjustment.' }),
      col('target_table', 'text', {}),
      col('target_id', 'text', {}),
      col('reason', 'text', { doc: 'Mandatory for admin actions (reason_required).' }),
      col('before', 'jsonb', {}),
      col('after', 'jsonb', {}),
      col('request_id', 'text', {}),
    ],
    primaryKey: ['id'],
    indexes: [ix('audit_log_target_idx', '(target_table, target_id, occurred_at desc)'), ix('audit_log_actor_idx', '(actor_user_id, occurred_at desc)'), ix('audit_log_action_idx', '(action, occurred_at desc)')],
    flags: { appendOnly: true },
  },

  {
    name: 'devices', group: 'Platform', source: 'backend',
    doc: 'A signed-in device that can receive push notifications and Live Activity updates (APNs for the iOS app, FCM for Android next). A token is a routing id, not a credential: it only lets flowd send a push to that device. The owner registers and removes their own devices; the edge functions read them to deliver Daily Drop, payout and review notifications and to update the earnings Live Activity.',
    columns: [
      col('id', 'text', { ...N, default: `public.new_id('dev')` }),
      col('user_id', 'text', { ...N, ref: 'users', onDelete: 'cascade' }),
      col('platform', 'text', { ...N, check: `platform in ('ios', 'android', 'web')` }),
      col('push_token', 'text', { ...N, doc: 'APNs device token (hex), FCM registration token or a Web Push endpoint.' }),
      col('live_activity_token', 'text', { doc: 'ActivityKit push token of the running earnings Live Activity (iOS), when one is active.' }),
      col('environment', 'text', { ...N, default: `'production'`, check: `environment in ('production', 'sandbox')`, doc: 'APNs environment the token belongs to (TestFlight and debug builds are sandbox).' }),
      col('app_version', 'text', {}),
      col('locale', 'text', {}),
      col('created_at', 'timestamptz', now),
      col('last_seen_at', 'timestamptz', now),
      col('revoked_at', 'timestamptz', { doc: 'Set when the user signs out or the provider reports the token invalid (APNs 410).' }),
    ],
    primaryKey: ['id'],
    checks: [chk('devices_id_format_chk', `id ~ '^dev_[a-z0-9_.-]+$'`)],
    uniques: [uq('devices_token_key', { cols: ['platform', 'push_token'] })],
    indexes: [ix('devices_user_idx', '(user_id) where revoked_at is null')],
  },

  // ── reference data ───────────────────────────────────────────────────────────────────────────
  {
    name: 'state_transitions', group: 'Reference', source: 'contract (STATE_MACHINES) + backend extensions',
    doc: 'The 23 contract state machines as data: one row per allowed transition. private.assert_transition() reads it from the generic BEFORE INSERT/UPDATE triggers, so an illegal status change raises invalid_transition no matter which client attempted it. Generated by supabase/tools/gen-schema.mjs.',
    columns: [
      col('id', 'integer', { ...N, generated: 'generated always as identity' }),
      col('machine', 'text', N),
      col('from_state', 'text', { doc: 'Null = creation.' }),
      col('to_state', 'text', N),
      col('actors', 'text[]', { ...N, doc: 'ActorKind values allowed to trigger it (informational: RLS and functions enforce who).' }),
      col('trigger_text', 'text', {}),
      col('guard_text', 'text', {}),
      col('source', 'text', { ...N, default: `'contract'`, check: `source in ('contract', 'backend_extension')` }),
    ],
    primaryKey: ['id'],
    uniques: [uq('state_transitions_edge_key', { expr: `machine, coalesce(from_state, '~'), to_state` })],
  },
  {
    name: 'flowd_constants', group: 'Reference', source: 'contract (CONSTANTS)',
    doc: 'Every contract constant, flattened to dotted paths (fees.instant_payout_rate, tiers.thresholds.gold.lifetime_cleared_cents ...). SQL functions read it through private.kn(); the generator rewrites it from packages/contract/schema/constants.mjs, so SQL, web and iOS can never disagree. Changes outside a migration must write audit_log.',
    columns: [
      col('path', 'text', N),
      col('value', 'jsonb', N),
      col('source', 'text', {}),
      col('note', 'text', {}),
      col('updated_at', 'timestamptz', now),
    ],
    primaryKey: ['path'],
  },
  {
    name: 'brand_role_capabilities', group: 'Reference', source: 'backend',
    doc: 'Which capability each BrandMemberRole holds. RLS policies and functions ask private.brand_can(brand_id, capability); editing this table changes the permission model without touching a policy.',
    columns: [
      col('role', 'public.brand_member_role', N),
      col('capability', 'text', N),
    ],
    primaryKey: ['role', 'capability'],
  },
];
