import { useId, type ComponentPropsWithRef } from "react";
import Image from "next/image";
import { cn } from "@/lib/utils";
import "./brand.css";

/** Geometry copied from brand/logo/*.svg (generated by brand/src/build-logos.mjs). Paths are the approved artwork: never edit. */
const RIBBON = "M34 214C66 214 84 196 90 170C98 134 100 112 112 88C124 64 144 52 172 52L196 52";
const CROSSBAR = "M62 138L168 138";
const WORD_LETTERS =
  "M8.5 95.5C21.3 95.5 28.5 85.83 30.9 71.87C34.1 52.54 34.9 40.72 39.7 27.83C44.5 14.94 52.5 8.5 61.3 8.5L68.5 8.5M90.5 8.5L90.5 95.5M114.5 71A26.5 26.5 0 0 1 167.5 71A26.5 26.5 0 0 1 114.5 71M188.5 46.5L211 95.5L233.5 50.5L256 95.5L278.5 46.5M298.5 71A26.5 26.5 0 0 1 351.5 71A26.5 26.5 0 0 1 298.5 71M351.5 8.5L351.5 95.5";
/** The crossbar of the wordmark's f: the one mint accent. */
const WORD_BAR = "M19.5 46.5L58.5 46.5";

export type LogoVariant = "lockup" | "stacked" | "mark" | "wordmark";

/**
 * Colour of the logo. The logo is FLAT (no gradients): one structural colour (ink on light, ice on dark) plus the mint crossbar.
 *  - `auto`      follows the in-app theme (ink + mint on light, ice + mint on dark). The right default.
 *  - `on-dark`   forces the ice version (a dark surface in a light theme: footers, photography).
 *  - `on-light`  forces the ink version.
 *  - `mono`      one colour, `currentColor`: set it with `text-white` / `text-fg`. For saturated surfaces and one-colour print.
 */
export type LogoTone = "auto" | "on-dark" | "on-light" | "mono";

const ASPECT: Record<LogoVariant, { w: number; h: number; minWidth: number }> = {
  lockup: { w: 368, h: 114, minWidth: 96 },
  stacked: { w: 368, h: 290, minWidth: 96 },
  mark: { w: 256, h: 256, minWidth: 16 },
  wordmark: { w: 364, h: 110, minWidth: 64 },
};

interface Palette {
  /** ribbon / letters */
  f: string;
  /** crossbar accent */
  bar: string;
  /** stacked lockup tile */
  tileBg: string;
  tileF: string;
  tileBar: string;
}

const PALETTE: Record<Exclude<LogoTone, "mono">, Palette> = {
  auto: { f: "var(--fd-fg)", bar: "var(--fd-mint-solid)", tileBg: "var(--fd-fg)", tileF: "var(--fd-bg)", tileBar: "var(--fd-mint-500)" },
  "on-dark": { f: "var(--fd-abyss-50)", bar: "var(--fd-mint-500)", tileBg: "var(--fd-abyss-50)", tileF: "var(--fd-abyss-950)", tileBar: "var(--fd-mint-600)" },
  "on-light": { f: "var(--fd-abyss-950)", bar: "var(--fd-mint-600)", tileBg: "var(--fd-abyss-950)", tileF: "var(--fd-abyss-50)", tileBar: "var(--fd-mint-500)" },
};

export interface LogoProps extends Omit<ComponentPropsWithRef<"svg">, "children" | "viewBox" | "width" | "height"> {
  variant?: LogoVariant;
  tone?: LogoTone;
  /** Height in px (the width follows the artwork). Clamped so the logo never goes under its minimum width (BRAND.md 5.3). Default 28. */
  height?: number;
  /** Play the approved ribbon draw-on once (600 ms; a fade under reduced motion). The only animation the mark may have. */
  drawOn?: boolean;
  /** Hide from assistive tech (when the name is printed next to the logo). */
  decorative?: boolean;
}

/**
 * The flowd logo as inline SVG, so it follows the in-app theme without a flash and without the OS-only `prefers-color-scheme`
 * trick of the adaptive files. Flat colour only. Variants: lockup (default; the full-colour wordmark, whose f carries the mint
 * crossbar: nav, footer, email), stacked (app tile above the wordmark: splash, posters), mark (the f alone, 16px minimum) and
 * wordmark (one colour, no accent). Never add a gradient, stretch, tilt, glow or set the wordmark in a font.
 */
export function Logo({ variant = "lockup", tone = "auto", height = 28, drawOn = false, decorative = false, className, ...props }: LogoProps) {
  const uid = `fd-logo-${useId().replace(/[^a-zA-Z0-9_-]/g, "")}`;
  const spec = ASPECT[variant];
  const width = Math.max(Math.round((height * spec.w) / spec.h), spec.minWidth);
  const renderedHeight = Math.round((width * spec.h) / spec.w);
  const mono = tone === "mono";
  const pal: Palette = mono
    ? { f: "currentColor", bar: "currentColor", tileBg: "currentColor", tileF: "currentColor", tileBar: "currentColor" }
    : PALETTE[tone];

  const mark = (transform: string, f: string, bar: string, barClass?: string) => (
    <g transform={transform} fill="none" strokeLinecap="round" strokeLinejoin="round">
      <path d={RIBBON} stroke={f} strokeWidth={40} {...(drawOn ? { pathLength: 1, className: "fd-br-draw" } : {})} />
      <path
        d={CROSSBAR}
        stroke={bar}
        strokeWidth={34}
        {...(drawOn ? { pathLength: 1 } : {})}
        className={cn(drawOn && "fd-br-draw", barClass)}
        style={drawOn ? { animationDelay: "120ms" } : undefined}
      />
    </g>
  );
  const word = (transform: string, letters: string, bar: string) => (
    <g transform={transform} fill="none" strokeLinecap="round" strokeLinejoin="round">
      <path d={WORD_LETTERS} stroke={letters} strokeWidth={17} />
      <path d={WORD_BAR} stroke={bar} strokeWidth={16} />
    </g>
  );

  // Stacked: a flat rounded tile with the mark inside. In mono the mark is knocked out of the tile (works on any background).
  const tileTransform = "translate(138 33) scale(0.4554) translate(-14 -32)";
  const stackedTile = mono ? (
    <>
      <defs>
        <mask id={uid} maskUnits="userSpaceOnUse" x="109" y="4" width="150" height="150">
          <rect x="109" y="4" width="150" height="150" fill="#fff" />
          <g transform={tileTransform} fill="none" strokeLinecap="round" strokeLinejoin="round" stroke="#000">
            <path d={RIBBON} strokeWidth={40} />
            <path d={CROSSBAR} strokeWidth={34} />
          </g>
        </mask>
      </defs>
      <rect x="109" y="4" width="150" height="150" rx="34" fill="currentColor" mask={`url(#${uid})`} />
    </>
  ) : (
    <>
      <rect x="109" y="4" width="150" height="150" rx="34" fill={pal.tileBg} />
      {mark(tileTransform, pal.tileF, pal.tileBar, tone === "auto" ? "fd-logo-tilebar" : undefined)}
    </>
  );

  return (
    <svg
      viewBox={`0 0 ${spec.w} ${spec.h}`}
      width={width}
      height={renderedHeight}
      role={decorative ? undefined : "img"}
      aria-label={decorative ? undefined : "flowd"}
      aria-hidden={decorative || undefined}
      focusable="false"
      className={cn("block shrink-0", className)}
      {...props}
    >
      {variant === "lockup" ? word("translate(4 4)", pal.f, pal.bar) : null}
      {variant === "stacked" ? (
        <>
          {stackedTile}
          {word("translate(4 180)", pal.f, pal.bar)}
        </>
      ) : null}
      {variant === "mark" ? mark("translate(13 -5)", pal.f, pal.bar) : null}
      {variant === "wordmark" ? word("translate(2 2)", pal.f, pal.f) : null}
    </svg>
  );
}

export interface FlowdAppIconProps {
  /** Edge in px (default 64). Rendered as a rounded preview; the iOS asset is the full-bleed 1024 PNG, never this. */
  size?: number;
  className?: string;
  /** `true` when the name is printed next to the icon. */
  decorative?: boolean;
}

/** The flowd app icon (flat ink tile, ribbon-f, mint crossbar) as the rounded web preview. For the product's own icon only. */
export function FlowdAppIcon({ size = 64, className, decorative = false }: FlowdAppIconProps) {
  return (
    <Image
      src="/brand/app-icon-rounded.svg"
      alt={decorative ? "" : "flowd app icon"}
      width={size}
      height={size}
      unoptimized
      className={cn("block shrink-0", className)}
      style={{ width: size, height: size }}
    />
  );
}
