// Query parameters of GET endpoints beyond pagination (limit, cursor, sort, expand), keyed "GET /path". Same compact notation as request bodies.
// Filters are plain query params named after the fields they filter (packages/contract/schema/api.mjs, "Pagination and filters").

export const QUERIES = {
  'GET /bounties': 'status?:enum:BountyStatus; app_id?:ref:apps; type?:enum:BountyType; category?:enum:Category; visibility?:enum:Visibility; funded?:bool; min_cpm_cents?:cents; q?:string -- Matches title and brief.',
  'GET /bounties/{id}/funnel': 'from?:date; to?:date',
  'GET /feed': 'niche?:enum:Niche; platform?:enum:Platform; type?:enum:BountyType; min_match?:int; min_cpm_cents?:cents; include_locked?:bool -- Show bounties the creator cannot take yet, with how to unlock them (default true).',
  'GET /saves': 'stage?:enum:SaveStage',
  'GET /submissions': 'status?:enum:SubmissionStatus; bounty_id?:ref:bounties; creator_id?:ref:creators; sla_state?:enum:SlaState',
  'GET /submissions/{id}/analysis': 'version?:int -- Defaults to the latest version.',
  'GET /submissions/{id}/notes': 'version?:int; status?:enum:FeedbackStatus',
  'GET /review/queue': 'bounty_id?:ref:bounties; sla_state?:enum:SlaState; fraud_hold?:bool; flow_band?:enum:ScoreBand; q?:string',
  'GET /posts': 'status?:enum:PostStatus; bounty_id?:ref:bounties; creator_id?:ref:creators; platform?:enum:Platform; is_winner?:bool',
  'GET /posts/{id}/metrics': 'granularity?:string -- daily (default) or hourly (posts from the last 30 days).; from?:date; to?:date',
  'GET /ledger': 'account?:string -- e.g. wallet:br_lumi, escrow:bnty_lumi_glowup, creator:cr_maya.; bounty_id?:ref:bounties; post_id?:ref:posts; type?:enum:LedgerType; status?:enum:LedgerStatus; txn_id?:string; from?:iso; to?:iso',
  'GET /money-clock': 'state?:enum:MoneyClockState; bounty_id?:ref:bounties',
  'GET /payouts': 'status?:enum:PayoutStatus; kind?:enum:PayoutKind',
  'GET /payouts/preview': 'amount_cents?:cents -- Defaults to the whole cleared balance (instant cash-out pays all of it).',
  'GET /invoices': 'status?:enum:InvoiceStatus; kind?:enum:InvoiceKind; bounty_id?:ref:bounties',
  'GET /tax/docs': 'tax_year?:int',
  'GET /tax/export.csv': 'tax_year?:int -- Defaults to the current tax year.',
  'GET /offers': 'status?:enum:OfferStatus; kind?:enum:OfferKind; creator_id?:ref:creators',
  'GET /auctions': 'status?:enum:AuctionStatus; mine?:bool',
  'GET /specs': 'status?:enum:SpecStatus; category?:enum:Category; min_flow_points?:int; max_price_cents?:cents; q?:string',
  'GET /market/clearing': 'category?:enum:Category; from?:date; to?:date',
  'GET /attribution/health': 'app_id?:ref:apps',
  'GET /attribution/codes': 'app_id?:ref:apps; status?:enum:OfferCodeStatus',
  'GET /conversions': 'kind?:enum:ConversionKind; source?:enum:ConversionSource; confidence?:enum:ConversionConfidence; status?:enum:ConversionStatus; bounty_id?:ref:bounties; post_id?:ref:posts; from?:date; to?:date',
  'GET /rights': 'status?:enum:RightsGrantStatus; scope?:enum:RightsScope; expiring_within_days?:int -- The Rights Vault expiry buckets: 7, 14 and 30.',
  'GET /promotions': 'status?:enum:AdStatus; bounty_id?:ref:bounties',
  'GET /fatigue-alerts': 'status?:enum:FatigueStatus',
  'GET /test-plans': 'status?:enum:TestPlanStatus',
  'GET /library': 'format_id?:enum:FormatId; hook_type?:enum:HookType; cta_type?:enum:CtaType; is_winner?:bool; q?:string',
  'GET /compliance': 'overall?:enum:ComplianceResult; blocks_settlement?:bool',
  'GET /creators': 'q?:string -- Handle or name.; niche?:enum:Niche; tier?:enum:Tier; platform?:enum:Platform; country?:enum:Country; min_approval?:ratio; min_reliability?:int; max_price_cents?:cents; min_us_audience?:ratio; open_to_offers?:bool',
  'GET /leaderboards': 'scope?:enum:LeaderboardScope -- cohort (peer group of about 30), niche or global.; metric?:enum:LeaderboardMetric',
  'GET /tournaments': 'status?:enum:TournamentStatus',
  'GET /crews': 'mine?:bool; niche?:enum:Niche; open?:bool',
  'GET /referrals': 'status?:enum:ReferralStatus',
  'GET /academy': 'topic?:enum:LessonTopic; status?:enum:LessonStatus',
  'GET /wrapped': 'period?:enum:WrappedPeriod',
  'GET /threads': 'kind?:enum:ThreadKind',
  'GET /notifications': 'unread?:bool; kind?:enum:NotificationKind',
  'GET /disputes': 'status?:enum:DisputeStatus; kind?:enum:DisputeKind',
  'GET /reports/mine': 'status?:enum:ReportStatus',
  'GET /brands/{id}/activity': 'action?:enum:ActivityAction; member_id?:ref:brand_members; from?:iso; to?:iso; format?:string -- json (default) or csv.',
  'GET /integrations': 'kind?:enum:IntegrationKind',
  'GET /admin/fraud': 'status?:enum:FraudFlagStatus; band?:enum:FraudBand',
  'GET /admin/disputes': 'status?:enum:DisputeStatus; overdue?:bool',
  'GET /admin/verification': 'kind?:enum:VerificationKind; status?:enum:VerificationStatus',
  'GET /admin/payouts': 'status?:enum:PayoutStatus; run_id?:string',
  'GET /admin/ledger': 'account?:string; type?:enum:LedgerType; from?:iso; to?:iso',
  'GET /admin/sla': 'sla_state?:enum:SlaState',
  'GET /admin/safety': 'status?:enum:ReportStatus',
  'GET /admin/bounties': 'status?:enum:BountyStatus; q?:string',
  'GET /admin/creators': 'tier?:enum:Tier; verification_status?:enum:VerificationStatus; q?:string',
  'GET /admin/brands': 'plan?:enum:Plan; verification?:enum:VerificationStatus; q?:string',
  'GET /public/changelog': 'tag?:enum:ChangelogTag',
  'GET /public/waitlist': 'kind?:string -- creator or brand.',
};
