// JS/TS emitters: dist/tokens.mjs (resolved tokens + derived spring helpers) and dist/tokens.d.ts (types mirroring the JSON).
import { springSpec } from './motion.mjs';

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const key = (k) => (IDENT.test(k) ? k : JSON.stringify(k));
const union = (names) => names.map((n) => JSON.stringify(n)).join(' | ');

function typeOf(v, indent = '') {
  if (v === null) return 'null';
  const t = typeof v;
  if (t === 'string' || t === 'number' || t === 'boolean') return t;
  if (Array.isArray(v)) {
    if (!v.length) return 'never[]';
    const kinds = v.map((x) => (Array.isArray(x) ? 'array' : typeof x));
    if (kinds.every((k) => k === kinds[0])) {
      if (kinds[0] === 'object') return `Array<${typeOf(v[0], indent)}>`;
      if (kinds[0] === 'array') return `Array<${typeOf(v[0], indent)}>`;
      return `${kinds[0]}[]`;
    }
    return `[${v.map((x) => typeOf(x, indent)).join(', ')}]`; // mixed primitives -> tuple (e.g. aurora stops)
  }
  const inner = `${indent}  `;
  const rows = Object.entries(v).map(([k, x]) => `${inner}${key(k)}: ${typeOf(x, inner)};`);
  return `{\n${rows.join('\n')}\n${indent}}`;
}

export function emitMjs(t) {
  const springs = Object.fromEntries(Object.entries(t.motion.spring).map(([k, s]) => [k, { ...springSpec(s), use: s.use }]));
  const motionSpring = Object.fromEntries(Object.entries(t.motion.spring).map(([k, s]) => [k, { type: 'spring', stiffness: s.stiffness, damping: s.damping, mass: s.mass }]));
  return `// flowd design tokens — GENERATED by packages/tokens/build.mjs from tokens.json. Do not edit by hand.
// Resolved (aliases expanded) token tree for JS consumers: canvas/SVG charts, motion/react transitions, tests.
// In styles prefer CSS variables: cssVar('surface') -> 'var(--fd-surface)'.

export const tokens = ${JSON.stringify(t, null, 2)};

/** Derived spring models: stiffness/damping/mass plus SwiftUI response/dampingFraction and motion.dev bounce/duration. */
export const springs = ${JSON.stringify(springs, null, 2)};

/** Ready for motion/react: <motion.div transition={motionSpring.snappy} /> */
export const motionSpring = ${JSON.stringify(motionSpring, null, 2)};

export const cssVar = (name) => \`var(--fd-\${name})\`;

export default tokens;
`;
}

export function emitDts(t) {
  const sem = Object.keys(t.color.semantic.dark);
  const text = Object.keys(t.typography.scale);
  const tiers = Object.keys(t.tier).filter((k) => k !== 'note');
  return `// flowd design tokens — GENERATED by packages/tokens/build.mjs from tokens.json. Do not edit by hand.

export type ThemeName = 'dark' | 'light';
export type SemanticColorName = ${union(sem)};
export type PrimitiveHue = ${union(Object.keys(t.color.primitive).filter((k) => typeof t.color.primitive[k] === 'object'))};
export type GlassLayerId = 'L1' | 'L2' | 'L3';
export type SpringName = ${union(Object.keys(t.motion.spring))};
export type DurationName = ${union(Object.keys(t.motion.duration))};
export type EasingName = ${union(Object.keys(t.motion.easing))};
export type TextStyleName = ${union(text)};
export type TierId = ${union(tiers)};
export type RadiusName = ${union(Object.keys(t.radius).filter((k) => k !== 'note'))};
export type ZIndexName = ${union(Object.keys(t.zIndex))};
export type BreakpointName = ${union(Object.keys(t.breakpoints))};
export type GradientName = ${union(Object.keys(t.gradient))};
export type ChartHue = ${union(t.chart.order)};

export interface SpringSpec {
  stiffness: number;
  damping: number;
  mass: number;
  /** SwiftUI .spring(response:) */
  response: number;
  /** SwiftUI .spring(dampingFraction:) */
  dampingFraction: number;
  /** motion.dev spring bounce */
  bounce: number;
  /** motion.dev perceptual duration (seconds) */
  duration: number;
  /** time for the response to settle within 0.2% (seconds) */
  settleSec: number;
  use: string;
}

export interface MotionSpring {
  type: 'spring';
  stiffness: number;
  damping: number;
  mass: number;
}

export interface Tokens ${typeOf(t)}

export declare const tokens: Tokens;
export declare const springs: Record<SpringName, SpringSpec>;
export declare const motionSpring: Record<SpringName, MotionSpring>;
/** cssVar('surface') -> 'var(--fd-surface)' */
export declare function cssVar(name: string): string;
export default tokens;
`;
}
