// SwiftUI emitter -> dist/Tokens.swift. Imports SwiftUI/UIKit/Foundation only. Written to be compile-safe without a compiler:
// explicit types, no clever inference, no force unwraps, availability-free APIs (iOS 17+ target).
import { parseColor } from './color.mjs';
import { camel } from './tokens.mjs';
import { springModel } from './motion.mjs';

const r4 = (n) => (Math.round(n * 10000) / 10000).toString();
const hex6 = (c) => `0x${[c.r, c.g, c.b].map((v) => Math.round(v).toString(16).padStart(2, '0')).join('').toUpperCase()}`;

/** 'FlowdKit.ui(0xRRGGBB)' or with alpha */
function ui(str) {
  const c = parseColor(str);
  return c.a >= 0.9995 ? `FlowdKit.ui(${hex6(c)})` : `FlowdKit.ui(${hex6(c)}, ${r4(c.a)})`;
}
const dyn = (light, dark) => `FlowdKit.dyn(${ui(light)}, ${ui(dark)})`;
function fixed(str) {
  const c = parseColor(str);
  return c.a >= 0.9995 ? `FlowdKit.fixed(${hex6(c)})` : `FlowdKit.fixed(${hex6(c)}, ${r4(c.a)})`;
}
const stopsSwift = (stops) => stops.map((s) => `            .init(color: ${fixed(s.color)}, location: ${r4(s.at / 100)})`).join(',\n');
const q = (s) => JSON.stringify(s);

const SPACING_SWIFT = { xxs: 'xxs', xs: 'xs', sm: 'sm', md: 'md', lg: 'lg', xl: 'xl', '2xl': 'xxl', '3xl': 'xxxl', '4xl': 'huge', '5xl': 'giant', '6xl': 'jumbo', '7xl': 'mega' };
const RADIUS_SWIFT = { sm: 'sm', md: 'md', lg: 'lg', xl: 'xl', '2xl': 'xxl', '3xl': 'xxxl', pill: 'pill' };
const WEIGHT_SWIFT = { regular: '.regular', medium: '.medium', semibold: '.semibold', bold: '.bold', heavy: '.heavy' };
const DESIGN_SWIFT = { rounded: '.rounded', default: '.default', monospaced: '.monospaced' };
const TEXTSTYLE_SWIFT = { largeTitle: '.largeTitle', title: '.title', title2: '.title2', title3: '.title3', headline: '.headline', body: '.body', callout: '.callout', subheadline: '.subheadline', footnote: '.footnote', caption: '.caption', caption2: '.caption2' };

function shadowsSwift(layers) {
  return `[\n${layers.map((l) => `            FlowdShadow(color: ${dyn(l.light.color, l.dark.color)}, radius: ${r4(l.dark.blur / 2)}, x: ${l.dark.x}, y: ${l.dark.y})`).join(',\n')}\n        ]`;
}

export function emitSwift(t) {
  const sem = t.color.semantic;
  const out = [];
  const push = (...s) => out.push(...s);

  push(`// flowd design tokens — GENERATED by packages/tokens/build.mjs from tokens.json. Do not edit by hand.
// Target: iOS 17+, Swift 5 language mode. Imports SwiftUI + UIKit only.
// Source of truth: packages/tokens/tokens.json (theme "${t.$meta.theme}", v${t.$meta.version}).
//
// Naming: FlowdColor (semantic, light/dark dynamic), FlowdPrimitive (raw ramps), FlowdGradient, FlowdAurora, FlowdTier,
// FlowdChart, FlowdSpacing, FlowdRadius, FlowdLayout, FlowdElevation, FlowdGlassSpec, FlowdMotion, FlowdFont.
// Feature views must not read these directly for glass: go through the DesignSystem wrappers.

import SwiftUI
import UIKit
import Foundation

// MARK: - Helpers

enum FlowdKit {
    /// sRGB UIColor from 0xRRGGBB.
    static func ui(_ hex: UInt32, _ alpha: CGFloat = 1) -> UIColor {
        let r: CGFloat = CGFloat((hex >> 16) & 0xFF) / 255
        let g: CGFloat = CGFloat((hex >> 8) & 0xFF) / 255
        let b: CGFloat = CGFloat(hex & 0xFF) / 255
        return UIColor(red: r, green: g, blue: b, alpha: alpha)
    }

    /// A colour that resolves to \`light\` or \`dark\` from the trait collection (follows the app's colour scheme override too).
    static func dyn(_ light: UIColor, _ dark: UIColor) -> Color {
        let provider: (UITraitCollection) -> UIColor = { (traits: UITraitCollection) -> UIColor in
            return traits.userInterfaceStyle == .dark ? dark : light
        }
        return Color(uiColor: UIColor(dynamicProvider: provider))
    }

    /// A theme-independent sRGB colour.
    static func fixed(_ hex: UInt32, _ alpha: Double = 1) -> Color {
        let r: Double = Double((hex >> 16) & 0xFF) / 255
        let g: Double = Double((hex >> 8) & 0xFF) / 255
        let b: Double = Double(hex & 0xFF) / 255
        return Color(.sRGB, red: r, green: g, blue: b, opacity: alpha)
    }

    /// CSS-style gradient angle (0deg = to top, 90deg = to right, 135deg = to bottom-right) -> unit points.
    static func start(angle: Double) -> UnitPoint {
        let r: Double = angle * Double.pi / 180
        return UnitPoint(x: 0.5 - sin(r) / 2, y: 0.5 + cos(r) / 2)
    }

    static func end(angle: Double) -> UnitPoint {
        let r: Double = angle * Double.pi / 180
        return UnitPoint(x: 0.5 + sin(r) / 2, y: 0.5 - cos(r) / 2)
    }

    static func linear(_ stops: [Gradient.Stop], angle: Double) -> LinearGradient {
        return LinearGradient(stops: stops, startPoint: start(angle: angle), endPoint: end(angle: angle))
    }
}
`);

  // ---- primitives
  push('// MARK: - Primitives (raw ramps; use FlowdColor in product code)\n\nenum FlowdPrimitive {');
  for (const [hue, ramp] of Object.entries(t.color.primitive)) {
    if (typeof ramp === 'string') push(`    static let ${hue}: Color = ${fixed(ramp)}`);
    else for (const [step, hex] of Object.entries(ramp)) push(`    static let ${hue}${step}: Color = ${fixed(hex)}`);
  }
  push('}\n');

  // ---- semantic colour
  push('// MARK: - Semantic colour (dynamic light / dark)\n\nenum FlowdColor {');
  for (const k of Object.keys(sem.dark)) push(`    static let ${camel(k)}: Color = ${dyn(sem.light[k], sem.dark[k])}`);
  push('}\n');

  // ---- gradients
  push('// MARK: - Gradients\n\nenum FlowdGradient {');
  for (const [name, g] of Object.entries(t.gradient)) {
    push(`    static let ${name}Stops: [Gradient.Stop] = [\n${stopsSwift(g.stops)}\n    ]`);
    push(`    static let ${name}: LinearGradient = FlowdKit.linear(${name}Stops, angle: ${g.angle})`);
  }
  push('}\n');

  // ---- aurora
  push(`// MARK: - Aurora (L0 background)
// Each orb is a RadialGradient centred at (x, y) as a fraction of the container, with radius = \`radius\` x the container's longer side.

struct FlowdAuroraStop {
    let opacity: Double
    let location: Double
}

struct FlowdAuroraOrb: Identifiable {
    let id: String
    let color: Color
    let x: CGFloat
    let y: CGFloat
    let radius: CGFloat
    let stops: [FlowdAuroraStop]
}

enum FlowdAurora {
    static let base: Color = ${dyn(t.aurora.light.base, t.aurora.dark.base)}
    static let driftSeconds: Double = ${t.aurora.drift.durationSec}
    static let darkNoiseOpacity: Double = ${t.aurora.dark.noise}
    static let lightNoiseOpacity: Double = ${t.aurora.light.noise}
`);
  for (const theme of ['dark', 'light']) {
    push(`    static let ${theme}Orbs: [FlowdAuroraOrb] = [`);
    push(t.aurora[theme].orbs.map((o) => `        FlowdAuroraOrb(id: ${q(o.id)}, color: ${fixed(o.stops[0][0])}, x: ${r4(o.x / 100)}, y: ${r4(o.y / 100)}, radius: ${r4(o.r)}, stops: [${o.stops.map(([, a, at]) => `FlowdAuroraStop(opacity: ${r4(a)}, location: ${r4(at / 100)})`).join(', ')}])`).join(',\n'));
    push('    ]');
  }
  push('\n    static func orbs(isDark: Bool) -> [FlowdAuroraOrb] {\n        return isDark ? darkOrbs : lightOrbs\n    }\n}\n');

  // ---- tiers
  push(`// MARK: - Tiers (Bronze -> Elite)

struct FlowdTierStyle: Identifiable {
    let id: String
    let label: String
    let chevrons: Int
    let hasRing: Bool
    let gradient: LinearGradient
    let ink: Color
    let glow: Color
    let rim: Color
}

enum FlowdTier {`);
  const tierIds = Object.keys(t.tier).filter((k) => k !== 'note');
  for (const id of tierIds) {
    const x = t.tier[id];
    const stops = x.stops.map(([c, at]) => `            .init(color: ${fixed(c)}, location: ${r4(at / 100)})`).join(',\n');
    push(`    static let ${id}: FlowdTierStyle = FlowdTierStyle(
        id: ${q(id)}, label: ${q(x.label)}, chevrons: ${x.chevrons}, hasRing: ${x.ring ? 'true' : 'false'},
        gradient: FlowdKit.linear([
${stops}
        ], angle: ${x.angle}),
        ink: ${fixed(x.ink)}, glow: ${fixed(x.glow)}, rim: ${fixed(x.rim)}
    )`);
  }
  push(`    static let all: [FlowdTierStyle] = [${tierIds.join(', ')}]\n}\n`);

  // ---- charts
  const chart = t.chart;
  const dynArr = (name, key) => `    static let ${name}: [Color] = [\n${chart[key].light.map((c, i) => `        ${dyn(c, chart[key].dark[i])}`).join(',\n')}\n    ]`;
  push('// MARK: - Charts (validated with the dataviz skill; fixed hue order, never cycled)\n\nenum FlowdChart {');
  push(`    static let categoricalOrder: [String] = [${chart.order.map(q).join(', ')}]`);
  push(dynArr('categorical', 'categorical'));
  push(dynArr('sequential', 'sequential'));
  push(dynArr('ordinal', 'ordinal'));
  push(dynArr('diverging', 'diverging'));
  for (const k of Object.keys(chart.status.light)) push(`    static let ${k}: Color = ${dyn(chart.status.light[k], chart.status.dark[k])}`);
  push(`    static let surface: Color = ${dyn(chart.surface.light, chart.surface.dark)}`);
  push(`    static let grid: Color = ${dyn(chart.grid.light, chart.grid.dark)}`);
  push(`    static let axis: Color = ${dyn(chart.axis.light, chart.axis.dark)}`);
  push(`    static let lineWidth: CGFloat = ${chart.mark.lineWidth}`);
  push(`    static let barRadius: CGFloat = ${chart.mark.barRadius}`);
  push(`    static let markGap: CGFloat = ${chart.mark.gap}`);
  push('}\n');

  // ---- spacing / radius / layout
  push('// MARK: - Spacing (4pt grid)\n\nenum FlowdSpacing {');
  for (const [k, v] of Object.entries(t.spacing.named)) push(`    static let ${SPACING_SWIFT[k]}: CGFloat = ${v}`);
  push('    /// n x 4pt\n    static func unit(_ n: CGFloat) -> CGFloat {\n        return n * 4\n    }\n}\n');

  push('// MARK: - Radius (concentric: child = parent - padding)\n\nenum FlowdRadius {');
  for (const [k, v] of Object.entries(t.radius)) if (k !== 'note') push(`    static let ${RADIUS_SWIFT[k]}: CGFloat = ${v}`);
  push('    static func concentric(outer: CGFloat, padding: CGFloat) -> CGFloat {\n        return max(0, outer - padding)\n    }\n}\n');

  const L = t.spacing.layout;
  push(`// MARK: - Layout

enum FlowdLayout {
    static let hitTarget: CGFloat = ${L.hitTarget}
    static let gutter: CGFloat = ${L.gutterMobile}
    static let tabBarHeight: CGFloat = ${L.tabBarHeight}
    static let headerHeight: CGFloat = ${L.headerHeight}
    static let focusRingWidth: CGFloat = ${L.focusRingWidth}
}
`);

  // ---- elevation
  push(`// MARK: - Elevation
// CSS blur (px) maps to SwiftUI radius = blur / 2. SwiftUI has no spread: use the layers as-is.

struct FlowdShadow {
    let color: Color
    let radius: CGFloat
    let x: CGFloat
    let y: CGFloat
}

enum FlowdElevation {`);
  for (const lvl of Object.keys(t.elevation.dark)) {
    const layers = t.elevation.dark[lvl].map((d, i) => ({ dark: d, light: t.elevation.light[lvl][i] }));
    push(`    static let level${lvl}: [FlowdShadow] = ${shadowsSwift(layers)}`);
  }
  push('    static func level(_ n: Int) -> [FlowdShadow] {\n        switch n {\n        case 1: return level1\n        case 2: return level2\n        case 3: return level3\n        case 4: return level4\n        default: return []\n        }\n    }');
  for (const [name, gl] of Object.entries(t.elevation.glow)) push(`    static let glow${name[0].toUpperCase()}${name.slice(1)}: Color = ${dyn(gl.light, gl.dark)}`);
  push('}\n');

  // ---- glass spec
  push(`// MARK: - Glass material spec
// iOS 26+: DesignSystem wrappers call glassEffect and ignore blur/fill. iOS 17-25: Material fallback + tint + rim stroke built from this spec.

struct FlowdGlassLayerSpec {
    let id: String
    let defaultRadius: CGFloat
    let blur: CGFloat
    let saturation: Double
    let fill: Color
    let fillOverMedia: Color
    let sheenFrom: Color
    let sheenTo: Color
    let rimFrom: Color
    let rimMid: Color
    let rimTo: Color
    let rimWidth: CGFloat
    let highlight: Color
    let lowlight: Color
    let edge: Color
    let solid: Color
    let shadows: [FlowdShadow]
    let usesGlassEffect: Bool
    let interactive: Bool
    let fallbackMaterial: Material
    let fallbackTintOpacityLight: Double
    let fallbackTintOpacityDark: Double
    let strokeOpacityLight: Double
    let strokeOpacityDark: Double
}

enum FlowdGlassSpec {`);
  const radiusOf = { L1: t.radius['2xl'], L2: t.radius.pill, L3: t.radius['3xl'] };
  const materialOf = { thinMaterial: '.thinMaterial', ultraThinMaterial: '.ultraThinMaterial', thickMaterial: '.thickMaterial', regularMaterial: '.regularMaterial' };
  for (const id of ['L1', 'L2', 'L3']) {
    const d = t.glass.dark[id], l = t.glass.light[id], ios = t.glass.ios[id];
    push(`    static let ${id.toLowerCase()}: FlowdGlassLayerSpec = FlowdGlassLayerSpec(
        id: ${q(id)}, defaultRadius: ${radiusOf[id]}, blur: ${d.blur}, saturation: ${d.saturate},
        fill: ${dyn(l.fill, d.fill)},
        fillOverMedia: ${dyn(l.fillOverMedia, d.fillOverMedia)},
        sheenFrom: ${dyn(l.sheen.from, d.sheen.from)}, sheenTo: ${dyn(l.sheen.to, d.sheen.to)},
        rimFrom: ${dyn(l.rim.from, d.rim.from)}, rimMid: ${dyn(l.rim.mid, d.rim.mid)}, rimTo: ${dyn(l.rim.to, d.rim.to)}, rimWidth: ${d.rim.width},
        highlight: ${dyn(l.highlight, d.highlight)}, lowlight: ${dyn(l.lowlight, d.lowlight)}, edge: ${dyn(l.edge, d.edge)},
        solid: ${dyn(l.solid, d.solid)},
        shadows: FlowdElevation.level(${d.elevation}),
        usesGlassEffect: ${ios.usesGlassEffect ? 'true' : 'false'}, interactive: ${ios.interactive ? 'true' : 'false'}, fallbackMaterial: ${materialOf[ios.fallbackMaterial]},
        fallbackTintOpacityLight: ${ios.fallbackTintOpacityLight}, fallbackTintOpacityDark: ${ios.fallbackTintOpacityDark},
        strokeOpacityLight: ${ios.strokeOpacityLight}, strokeOpacityDark: ${ios.strokeOpacityDark}
    )`);
  }
  push(`    static let scrim: Color = ${dyn(t.glass.light.L3.scrim, t.glass.dark.L3.scrim)}
    static let pointerSheenRadius: CGFloat = ${t.glass.dark.pointerSheen.radius}
    // Clear glass (Glass.clear): only over media-rich content, under large bold content. Needs the dim layer.
    static let clearBlur: CGFloat = ${t.glass.clear.blur}
    static let clearSaturation: Double = ${t.glass.clear.saturate}
    static let clearTint: Color = ${fixed(t.glass.clear.tint)}
    static let clearDim: Color = ${fixed(t.glass.clear.dim)}
}
`);

  // ---- motion
  push(`// MARK: - Motion
// Springs are derived from stiffness / damping / mass: response = 2*pi / sqrt(k/m), dampingFraction = c / (2*sqrt(k*m)).

struct FlowdSpringSpec {
    let stiffness: Double
    let damping: Double
    let mass: Double
    let response: Double
    let dampingFraction: Double

    var animation: Animation {
        return Animation.spring(response: response, dampingFraction: dampingFraction)
    }
}

enum FlowdMotion {`);
  for (const [k, ms] of Object.entries(t.motion.duration)) push(`    static let ${k}: TimeInterval = ${r4(ms / 1000)}`);
  push(`    static let stagger: TimeInterval = ${r4(t.motion.stagger / 1000)}`);
  for (const [k, spec] of Object.entries(t.motion.spring)) {
    const m = springModel(spec);
    push(`    static let ${k}Spec: FlowdSpringSpec = FlowdSpringSpec(stiffness: ${m.stiffness}, damping: ${m.damping}, mass: ${m.mass}, response: ${m.response}, dampingFraction: ${m.dampingFraction})`);
    push(`    static let ${k}: Animation = ${k}Spec.animation`);
  }
  for (const [k, b] of Object.entries(t.motion.easing)) {
    push(`    static func ${k}(_ duration: TimeInterval) -> Animation {\n        return Animation.timingCurve(${b.join(', ')}, duration: duration)\n    }`);
  }
  push('}\n');

  // ---- typography
  push(`// MARK: - Typography
// SF Pro Rounded for display + every number, SF Pro for text, SF Mono for code. Sizes scale with Dynamic Type (ScaledMetric)
// unless \`fixed\`. Apply with \`.flowdText(FlowdFont.title1)\`.

struct FlowdTextStyle {
    let size: CGFloat
    let weight: Font.Weight
    let design: Font.Design
    let relativeTo: Font.TextStyle
    let trackingPt: CGFloat
    let lineHeight: CGFloat
    let uppercase: Bool
    let monospacedDigit: Bool
    let fixed: Bool

    /// Unscaled font (use where the modifier cannot be applied).
    var font: Font {
        let f: Font = Font.system(size: size, weight: weight, design: design)
        return monospacedDigit ? f.monospacedDigit() : f
    }

    /// Extra line spacing for a given point size (SF default line height is about 1.2 x size).
    func lineSpacing(for pointSize: CGFloat) -> CGFloat {
        return pointSize * (lineHeight - 1.2)
    }
}

struct FlowdTextModifier: ViewModifier {
    let style: FlowdTextStyle
    @ScaledMetric private var scaledSize: CGFloat

    init(style: FlowdTextStyle) {
        self.style = style
        self._scaledSize = ScaledMetric(wrappedValue: style.size, relativeTo: style.relativeTo)
    }

    func body(content: Content) -> some View {
        let pointSize: CGFloat = style.fixed ? style.size : scaledSize
        let base: Font = Font.system(size: pointSize, weight: style.weight, design: style.design)
        let font: Font = style.monospacedDigit ? base.monospacedDigit() : base
        let textCase: Text.Case? = style.uppercase ? Text.Case.uppercase : nil
        return content
            .font(font)
            .tracking(style.trackingPt)
            .lineSpacing(style.lineSpacing(for: pointSize))
            .textCase(textCase)
    }
}

extension View {
    func flowdText(_ style: FlowdTextStyle) -> some View {
        return modifier(FlowdTextModifier(style: style))
    }
}

enum FlowdFont {`);
  for (const [name, s] of Object.entries(t.typography.ios.scale)) {
    push(`    static let ${name}: FlowdTextStyle = FlowdTextStyle(size: ${s.size}, weight: ${WEIGHT_SWIFT[s.weight]}, design: ${DESIGN_SWIFT[s.design]}, relativeTo: ${TEXTSTYLE_SWIFT[s.textStyle]}, trackingPt: ${s.trackingPt}, lineHeight: ${s.lineHeight}, uppercase: ${s.uppercase ? 'true' : 'false'}, monospacedDigit: ${s.monospacedDigit ? 'true' : 'false'}, fixed: ${s.fixed ? 'true' : 'false'})`);
  }
  push('}\n');

  push(`// MARK: - Meta

enum FlowdTheme {
    static let name: String = ${q(t.$meta.theme)}
    static let version: String = ${q(t.$meta.version)}
}
`);
  return out.join('\n');
}
