import {
  Activity, ArrowRightLeft, Banknote, BadgeCheck, Bell, BookOpen, BrainCircuit, Building2, CalendarClock, Calculator, ChartColumn,
  CircleHelp, CirclePlay, Clapperboard, Clock, CodeXml, Compass, Copy, Crown, Database, Eye, FileCheck2, FileText, Fingerprint, Flag,
  FlaskConical, Flame, Gauge, Gavel, Globe, GraduationCap, Handshake, HeartPulse, House, Inbox, KeyRound, Keyboard, Layers,
  LayoutDashboard, Library, Lightbulb, Link2, ListChecks, Lock, LogOut, Mail, Medal, Megaphone, Moon, Network, Newspaper, Package,
  Palette, Percent, PiggyBank, Plug, Receipt, RefreshCw, Rocket, Scale, ScrollText, Search, Settings, Share2, ShieldAlert,
  ShieldCheck, Siren, Smartphone, Sparkles, Store, Sun, Tag, Target, Ticket, TrendingUp, Trophy, UserPlus, UserRound, Users,
  UsersRound, Video, WalletMinimal, WandSparkles, Wrench, Zap, type LucideIcon,
} from "lucide-react";
import type { SearchIconName } from "./types";

/** The palette's icon names mapped to lucide components. Complete by type: adding a name to `SearchIconName` fails the build until it is here. */
export const SEARCH_ICONS: Readonly<Record<SearchIconName, LucideIcon>> = {
  home: House,
  dashboard: LayoutDashboard,
  target: Target,
  wallet: WalletMinimal,
  review: ListChecks,
  inbox: Inbox,
  chart: ChartColumn,
  library: Library,
  flask: FlaskConical,
  megaphone: Megaphone,
  shield: ShieldCheck,
  filecheck: FileCheck2,
  scale: Scale,
  gauge: Gauge,
  users: Users,
  user: UserRound,
  handshake: Handshake,
  store: Store,
  gavel: Gavel,
  link: Link2,
  plug: Plug,
  team: UsersRound,
  building: Building2,
  code: CodeXml,
  settings: Settings,
  sparkles: Sparkles,
  film: Clapperboard,
  receipt: Receipt,
  trophy: Trophy,
  medal: Medal,
  flame: Flame,
  graduation: GraduationCap,
  share: Share2,
  heart: HeartPulse,
  shieldalert: ShieldAlert,
  moon: Moon,
  sun: Sun,
  palette: Palette,
  keyboard: Keyboard,
  logout: LogOut,
  refresh: RefreshCw,
  clock: Clock,
  zap: Zap,
  calculator: Calculator,
  piggy: PiggyBank,
  badge: BadgeCheck,
  file: FileText,
  news: Newspaper,
  help: CircleHelp,
  activity: Activity,
  phone: Smartphone,
  rocket: Rocket,
  tag: Tag,
  search: Search,
  compass: Compass,
  crown: Crown,
  banknote: Banknote,
  trend: TrendingUp,
  network: Network,
  database: Database,
  eye: Eye,
  swap: ArrowRightLeft,
  copy: Copy,
  bell: Bell,
  book: BookOpen,
  mail: Mail,
  lock: Lock,
  layers: Layers,
  play: CirclePlay,
  scroll: ScrollText,
  fingerprint: Fingerprint,
  globe: Globe,
  userplus: UserPlus,
  key: KeyRound,
  siren: Siren,
  flag: Flag,
  ticket: Ticket,
  percent: Percent,
  video: Video,
  bulb: Lightbulb,
  package: Package,
  calendar: CalendarClock,
  wrench: Wrench,
  brain: BrainCircuit,
  wand: WandSparkles,
};
