-- flowd 0002: row-level security, grants and auth plumbing
--
-- Model
--   * Roles come from public.users.role (creator | brand_member | admin). Brand members get capabilities from
--     public.brand_role_capabilities (owner, admin, reviewer, finance, viewer, client_approver); members of an agency
--     workspace inherit their role on the workspaces the agency manages (brands.agency_id).
--   * Clients (anon, authenticated) get SELECT through policies and a deliberately small set of direct writes
--     (profile and configuration edits, with COLUMN-level grants so money, tier and status columns cannot be written).
--   * Everything that moves money or changes a state machine goes through the API server using the service role and the
--     SECURITY DEFINER functions of 0003. service_role bypasses RLS; the invariants of 0001 still apply to it.
--   * Tables with no policy (ledger_balances, social_account_tokens, encrypted_secrets, idempotency_keys, inbound_events,
--     job_runs, audit_log, state_transitions, payout_runs, fraud_flags, ml_models, admin_metrics, waitlist_entries) are
--     readable by the service role only; admin screens read them through the API.
--   * Admins read everything that has any client grant (a generated "<table>_admin_select" policy at the end).
--   * Public (anon) reads go through the views of 0004 or the small public catalogues granted below.
--
-- Performance: policies call helpers as (select private.f()) so Postgres evaluates them once per statement.

-- ===========================================================================
-- 1. Baseline privileges: nothing is granted by default
-- ===========================================================================
revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
revoke execute on all functions in schema public from public, anon, authenticated;

alter default privileges in schema public revoke all on tables from anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;
alter default privileges in schema public revoke execute on functions from anon, authenticated;
alter default privileges revoke execute on functions from public;

grant usage on schema public to anon, authenticated, service_role;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;
grant execute on all functions in schema public to service_role;

-- ids are generated by column defaults, which run as the inserting role
grant execute on function public.new_id(text) to anon, authenticated;

-- ===========================================================================
-- 2. Helpers (SECURITY DEFINER so they can read the tables the policies protect without recursing into them)
-- ===========================================================================
create or replace function public.default_art_seed(p_seed text, p_label text default null)
returns jsonb
language sql
immutable
parallel safe
as $$
  select jsonb_strip_nulls(jsonb_build_object(
    'hue_a', (abs(hashtext(p_seed)) % 360),
    'hue_b', ((abs(hashtext(p_seed)) + 40) % 360),
    'hue_c', ((abs(hashtext(p_seed)) + 190) % 360),
    'pattern', (array['orbs', 'rings'])[1 + (abs(hashtext(p_seed || 'p')) % 2)],
    'seed', abs(hashtext(p_seed || 's')),
    'label', left(p_label, 24)
  ));
$$;
grant execute on function public.default_art_seed(text, text) to anon, authenticated;

create or replace function private.current_user_id()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select u.id from public.users u where u.auth_user_id = auth.uid() and u.deleted_at is null limit 1;
$$;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((select u.role = 'admin' and u.status = 'active' from public.users u where u.auth_user_id = auth.uid() and u.deleted_at is null limit 1), false);
$$;

create or replace function private.current_creator_id()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select c.id
  from public.creators c
  join public.users u on u.id = c.user_id
  where u.auth_user_id = auth.uid() and u.deleted_at is null and c.deleted_at is null
  limit 1;
$$;

-- Workspaces the caller belongs to (active membership), plus the workspaces an agency of theirs manages.
create or replace function private.my_brand_ids()
returns setof text
language sql
stable
security definer
set search_path = ''
as $$
  select m.brand_id
  from public.brand_members m
  join public.users u on u.id = m.user_id
  join public.brands b on b.id = m.brand_id and b.deleted_at is null
  where u.auth_user_id = auth.uid() and u.deleted_at is null and m.status = 'active'
  union
  select mb.id
  from public.brands mb
  where mb.deleted_at is null
    and mb.agency_id in (
      select m.brand_id
      from public.brand_members m
      join public.users u on u.id = m.user_id
      where u.auth_user_id = auth.uid() and u.deleted_at is null and m.status = 'active'
    );
$$;

-- Does the caller hold a capability on a workspace? (capabilities come from brand_role_capabilities)
create or replace function private.brand_can(p_brand_id text, p_capability text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.brand_members m
    join public.users u on u.id = m.user_id
    join public.brand_role_capabilities c on c.role = m.role
    where u.auth_user_id = auth.uid() and u.deleted_at is null
      and m.status = 'active'
      and c.capability = p_capability
      and (m.brand_id = p_brand_id or m.brand_id = (select b.agency_id from public.brands b where b.id = p_brand_id))
  );
$$;

create or replace function private.creator_tier_at_least(p_creator_id text, p_tier public.tier)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((select c.tier >= p_tier from public.creators c where c.id = p_creator_id), false);
$$;

create or replace function private.my_crew_ids()
returns setof text
language sql
stable
security definer
set search_path = ''
as $$
  select cm.crew_id from public.crew_members cm where cm.creator_id = private.current_creator_id();
$$;

-- Cohort boards are visible to their members only; niche and global boards to every signed-in user.
create or replace function private.can_see_leaderboard(p_leaderboard_id text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.leaderboards l
    where l.id = p_leaderboard_id
      and (l.scope in ('niche', 'global')
           or exists (select 1 from public.leaderboard_entries e where e.leaderboard_id = l.id and e.creator_id = private.current_creator_id()))
  );
$$;

-- Sealed bids: a brand sees only its own bid while the auction is open. After close the auction's creator and the
-- brands that bid can see every bid (second-price outcomes are transparent to the participants).
create or replace function private.auction_bids_visible(p_auction_id text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.auctions a
    where a.id = p_auction_id
      and a.status in ('closed', 'awarded', 'no_bids')
      and (a.creator_id = private.current_creator_id()
           or exists (select 1 from public.auction_bids b where b.auction_id = a.id and b.brand_id in (select private.my_brand_ids())))
  );
$$;

grant execute on function
  private.current_user_id(), private.is_admin(), private.current_creator_id(), private.my_brand_ids(),
  private.brand_can(text, text), private.creator_tier_at_least(text, public.tier), private.my_crew_ids(),
  private.can_see_leaderboard(text), private.auction_bids_visible(text)
to anon, authenticated, service_role;

-- ===========================================================================
-- 3. New auth user -> public.users (creator by default; the role comes from app_metadata, which only the server can set)
-- ===========================================================================
create or replace function private.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role public.role;
  v_name text;
  v_providers public.auth_provider[];
begin
  v_role := case new.raw_app_meta_data ->> 'role'
    when 'brand_member' then 'brand_member'::public.role
    else 'creator'::public.role  -- admin is never self-assigned: Ops promote users through the admin API
  end;
  v_name := coalesce(nullif(new.raw_user_meta_data ->> 'full_name', ''), nullif(new.raw_user_meta_data ->> 'name', ''), split_part(coalesce(new.email, 'creator'), '@', 1));
  select coalesce(array_agg(p::public.auth_provider), array['email']::public.auth_provider[])
    into v_providers
  from jsonb_array_elements_text(coalesce(new.raw_app_meta_data -> 'providers', '[]'::jsonb)) p
  where p in ('apple', 'google', 'email');
  insert into public.users (id, role, email, display_name, avatar, auth_providers, status, age_verified, locale, timezone, created_at, auth_user_id)
  values (
    public.new_id('usr'), v_role, coalesce(new.email, new.id::text || '@users.invalid'), v_name,
    public.default_art_seed(new.id::text, upper(left(v_name, 2))), v_providers, 'active', false,
    coalesce(nullif(new.raw_user_meta_data ->> 'locale', ''), 'en-US'), 'UTC', now(), new.id
  )
  on conflict do nothing;
  return new;
end
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_auth_user();

-- ===========================================================================
-- 4. Enable RLS on every table
-- ===========================================================================
alter table public.world enable row level security;
alter table public.users enable row level security;
alter table public.creators enable row level security;
alter table public.social_accounts enable row level security;
alter table public.rate_cards enable row level security;
alter table public.brands enable row level security;
alter table public.brand_members enable row level security;
alter table public.apps enable row level security;
alter table public.tier_history enable row level security;
alter table public.wellbeing_settings enable row level security;
alter table public.notification_prefs enable row level security;
alter table public.ledger enable row level security;
alter table public.payouts enable row level security;
alter table public.invoices enable row level security;
alter table public.money_clock enable row level security;
alter table public.payout_runs enable row level security;
alter table public.ledger_transactions enable row level security;
alter table public.ledger_balances enable row level security;
alter table public.wallet_holds enable row level security;
alter table public.payout_methods enable row level security;
alter table public.market_series enable row level security;
alter table public.offers enable row level security;
alter table public.auctions enable row level security;
alter table public.specs enable row level security;
alter table public.ticker_events enable row level security;
alter table public.offer_messages enable row level security;
alter table public.auction_bids enable row level security;
alter table public.spec_licenses enable row level security;
alter table public.brand_scorecards enable row level security;
alter table public.creator_reputation enable row level security;
alter table public.disputes enable row level security;
alter table public.scam_reports enable row level security;
alter table public.fraud_flags enable row level security;
alter table public.verifications enable row level security;
alter table public.tax_profiles enable row level security;
alter table public.tax_docs enable row level security;
alter table public.compliance_checks enable row level security;
alter table public.dispute_events enable row level security;
alter table public.compliance_check_items enable row level security;
alter table public.bounties enable row level security;
alter table public.submissions enable row level security;
alter table public.video_analyses enable row level security;
alter table public.feedback_notes enable row level security;
alter table public.submission_versions enable row level security;
alter table public.qa_checks enable row level security;
alter table public.posts enable row level security;
alter table public.view_snapshots enable row level security;
alter table public.post_metrics_daily enable row level security;
alter table public.post_metrics_hourly enable row level security;
alter table public.app_metrics_daily enable row level security;
alter table public.conversions enable row level security;
alter table public.attribution_links enable row level security;
alter table public.revenuecat_events enable row level security;
alter table public.offer_code_pool enable row level security;
alter table public.ads enable row level security;
alter table public.ad_daily enable row level security;
alter table public.rights_grants enable row level security;
alter table public.rights_renewals enable row level security;
alter table public.daily_drops enable row level security;
alter table public.tournaments enable row level security;
alter table public.tournament_entries enable row level security;
alter table public.crews enable row level security;
alter table public.crew_members enable row level security;
alter table public.streaks enable row level security;
alter table public.leaderboards enable row level security;
alter table public.referrals enable row level security;
alter table public.lessons enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.trends enable row level security;
alter table public.wrapped enable row level security;
alter table public.proofs enable row level security;
alter table public.bounty_saves enable row level security;
alter table public.drop_items enable row level security;
alter table public.drop_claims enable row level security;
alter table public.leaderboard_entries enable row level security;
alter table public.formats enable row level security;
alter table public.hooks enable row level security;
alter table public.state_of_app_ugc enable row level security;
alter table public.case_studies enable row level security;
alter table public.testimonials enable row level security;
alter table public.changelog enable row level security;
alter table public.audit_reports enable row level security;
alter table public.waitlist_entries enable row level security;
alter table public.notifications enable row level security;
alter table public.integrations enable row level security;
alter table public.api_keys enable row level security;
alter table public.webhooks enable row level security;
alter table public.activity_log enable row level security;
alter table public.auto_approve_rules enable row level security;
alter table public.test_plans enable row level security;
alter table public.fatigue_alerts enable row level security;
alter table public.devices enable row level security;
alter table public.flo_suggestions enable row level security;
alter table public.ml_models enable row level security;
alter table public.threads enable row level security;
alter table public.brand_lists enable row level security;
alter table public.chat_messages enable row level security;
alter table public.webhook_deliveries enable row level security;
alter table public.rule_audit_log enable row level security;
alter table public.admin_metrics enable row level security;
alter table public.social_account_tokens enable row level security;
alter table public.encrypted_secrets enable row level security;
alter table public.idempotency_keys enable row level security;
alter table public.inbound_events enable row level security;
alter table public.job_runs enable row level security;
alter table public.audit_log enable row level security;
alter table public.state_transitions enable row level security;
alter table public.flowd_constants enable row level security;
alter table public.brand_role_capabilities enable row level security;

-- ===========================================================================
-- 5. Public catalogues (anon + authenticated read-only). No personal data in any of these.
-- ===========================================================================
grant select on public.market_series, public.formats, public.hooks, public.lessons, public.trends, public.changelog,
  public.case_studies, public.testimonials, public.state_of_app_ugc, public.brand_scorecards, public.audit_reports,
  public.tournaments, public.ticker_events, public.flowd_constants to anon, authenticated;

create policy market_series_public_select on public.market_series for select to anon, authenticated using (true);
create policy formats_public_select on public.formats for select to anon, authenticated using (true);
create policy hooks_public_select on public.hooks for select to anon, authenticated using (true);
create policy lessons_public_select on public.lessons for select to anon, authenticated using (true);
create policy trends_public_select on public.trends for select to anon, authenticated using (true);
create policy changelog_public_select on public.changelog for select to anon, authenticated using (true);
create policy case_studies_public_select on public.case_studies for select to anon, authenticated using (true);
create policy testimonials_public_select on public.testimonials for select to anon, authenticated using (true);
create policy state_of_app_ugc_public_select on public.state_of_app_ugc for select to anon, authenticated using (true);
create policy brand_scorecards_public_select on public.brand_scorecards for select to anon, authenticated using (true);
create policy audit_reports_public_select on public.audit_reports for select to anon, authenticated using (true);
create policy tournaments_public_select on public.tournaments for select to anon, authenticated using (true);
create policy ticker_events_public_select on public.ticker_events for select to anon, authenticated using (true);
create policy flowd_constants_public_select on public.flowd_constants for select to anon, authenticated using (true);

grant select on public.world, public.brand_role_capabilities, public.tournament_entries, public.daily_drops, public.drop_items to authenticated;
create policy world_select on public.world for select to authenticated using (true);
create policy brand_role_capabilities_select on public.brand_role_capabilities for select to authenticated using (true);
create policy tournament_entries_select on public.tournament_entries for select to authenticated using (true);
create policy daily_drops_select on public.daily_drops for select to authenticated using (true);
create policy drop_items_select on public.drop_items for select to authenticated using (true);

-- Proofs are public by design (joinflowd.io/p/<id>): the creator chose to share the claim. Revoked proofs vanish.
grant select on public.proofs to anon, authenticated;
create policy proofs_public_select on public.proofs for select to anon, authenticated using (not revoked);
create policy proofs_owner_select on public.proofs for select to authenticated using (creator_id = (select private.current_creator_id()));

-- ===========================================================================
-- 6. Identity
-- ===========================================================================
-- users: yourself, your teammates (so a workspace can list its members), admins (see the end).
grant select on public.users to authenticated;
grant update (display_name, avatar, locale, timezone, last_seen_at) on public.users to authenticated;
create policy users_self_select on public.users for select to authenticated
  using (auth_user_id = auth.uid() and deleted_at is null);
create policy users_team_select on public.users for select to authenticated
  using (deleted_at is null and id in (
    select m.user_id from public.brand_members m where m.brand_id in (select private.my_brand_ids()) and m.status <> 'removed'));
create policy users_self_update on public.users for update to authenticated
  using (auth_user_id = auth.uid() and deleted_at is null)
  with check (auth_user_id = auth.uid());

-- creators: the owner sees the full row (money, tier, stripe id). Brands and the public use v_creator_cards (0004).
grant select on public.creators to authenticated;
grant update (display_name, bio, avatar, niches, languages, storefront, portfolio, open_to_offers, paused_until, last_active_at) on public.creators to authenticated;
create policy creators_self_select on public.creators for select to authenticated
  using (id = (select private.current_creator_id()));
create policy creators_self_update on public.creators for update to authenticated
  using (id = (select private.current_creator_id()))
  with check (id = (select private.current_creator_id()));

-- social accounts: the owner reads and sets the primary account. Linking and unlinking go through OAuth on the server.
grant select on public.social_accounts to authenticated;
grant update (is_primary) on public.social_accounts to authenticated;
create policy social_accounts_owner_select on public.social_accounts for select to authenticated
  using (creator_id = (select private.current_creator_id()) and deleted_at is null);
create policy social_accounts_owner_update on public.social_accounts for update to authenticated
  using (creator_id = (select private.current_creator_id()) and deleted_at is null)
  with check (creator_id = (select private.current_creator_id()));

-- rate cards: Silver and above publish one; brands browse open ones to buy at the ask.
grant select on public.rate_cards to authenticated;
grant insert (id, creator_id, status, price_per_video_cents, min_cpm_cents, paid_usage_days, paid_usage_pct_per_30d, turnaround_days,
              max_videos_per_month, platforms, format_ids, categories_excluded, accepts_direct_offers, packages) on public.rate_cards to authenticated;
grant update (status, price_per_video_cents, min_cpm_cents, paid_usage_days, paid_usage_pct_per_30d, turnaround_days,
              max_videos_per_month, platforms, format_ids, categories_excluded, accepts_direct_offers, packages, deleted_at) on public.rate_cards to authenticated;
create policy rate_cards_owner_select on public.rate_cards for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy rate_cards_brand_select on public.rate_cards for select to authenticated
  using (deleted_at is null and accepts_direct_offers and status <> 'paused' and exists (select 1 from private.my_brand_ids()));
create policy rate_cards_owner_insert on public.rate_cards for insert to authenticated
  with check (creator_id = (select private.current_creator_id()) and private.creator_tier_at_least(creator_id, 'silver'));
create policy rate_cards_owner_update on public.rate_cards for update to authenticated
  using (creator_id = (select private.current_creator_id()))
  with check (creator_id = (select private.current_creator_id()) and private.creator_tier_at_least(creator_id, 'silver'));

-- brands: members read their workspaces; owners and admins edit the profile columns. Plan, wallet and billing are server-only.
grant select on public.brands to authenticated;
grant update (name, tagline, logo, website, country, timeout_policy, review_sla_hours, compliance_defaults) on public.brands to authenticated;
create policy brands_member_select on public.brands for select to authenticated
  using (deleted_at is null and id in (select private.my_brand_ids()));
create policy brands_team_update on public.brands for update to authenticated
  using (deleted_at is null and private.brand_can(id, 'team.manage'))
  with check (private.brand_can(id, 'team.manage'));

-- brand members: members see their workspace roster; invitations and role changes go through the API (activity-logged).
grant select on public.brand_members to authenticated;
create policy brand_members_select on public.brand_members for select to authenticated
  using (brand_id in (select private.my_brand_ids()) or user_id = (select private.current_user_id()));

-- apps
grant select on public.apps to authenticated;
grant insert (id, brand_id, name, tagline, category, icon, brand_colors, features, app_store_id, bundle_id, store_url, pricing,
              avg_first_payment_cents, rating, rating_count, status, connected_at, revenuecat_project_id, mmp, sdk_status, default_hashtags) on public.apps to authenticated;
grant update (name, tagline, category, icon, brand_colors, features, store_url, pricing, avg_first_payment_cents, rating, rating_count,
              mmp, default_hashtags, deleted_at) on public.apps to authenticated;
create policy apps_member_select on public.apps for select to authenticated
  using (deleted_at is null and brand_id in (select private.my_brand_ids()));
create policy apps_member_insert on public.apps for insert to authenticated
  with check (private.brand_can(brand_id, 'bounty.write'));
create policy apps_member_update on public.apps for update to authenticated
  using (deleted_at is null and private.brand_can(brand_id, 'bounty.write'))
  with check (private.brand_can(brand_id, 'bounty.write'));

-- creator-owned settings and history
grant select on public.tier_history, public.wellbeing_settings, public.notification_prefs, public.streaks, public.wrapped, public.lesson_progress to authenticated;
create policy tier_history_owner_select on public.tier_history for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy streaks_owner_select on public.streaks for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy wrapped_owner_select on public.wrapped for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy lesson_progress_owner_select on public.lesson_progress for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy wellbeing_settings_owner_select on public.wellbeing_settings for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy notification_prefs_owner_select on public.notification_prefs for select to authenticated
  using (user_id = (select private.current_user_id()));

grant update (enabled, quiet_hours, numbers_off, pace_goal, paused_until, rest_weeks, leaderboard_opt_out, slack_mode) on public.wellbeing_settings to authenticated;
create policy wellbeing_settings_owner_update on public.wellbeing_settings for update to authenticated
  using (creator_id = (select private.current_creator_id()))
  with check (creator_id = (select private.current_creator_id()));
grant update (push, email_digest, categories, quiet_hours, batch_non_cash, drop_reminder) on public.notification_prefs to authenticated;
create policy notification_prefs_owner_update on public.notification_prefs for update to authenticated
  using (user_id = (select private.current_user_id()))
  with check (user_id = (select private.current_user_id()));

-- push devices: a person registers, refreshes and removes their own (the edge functions read every token as service_role)
grant select, delete on public.devices to authenticated;
grant insert (user_id, platform, push_token, live_activity_token, environment, app_version, locale) on public.devices to authenticated;
grant update (push_token, live_activity_token, environment, app_version, locale, last_seen_at, revoked_at) on public.devices to authenticated;
create policy devices_owner_select on public.devices for select to authenticated
  using (user_id = (select private.current_user_id()));
create policy devices_owner_insert on public.devices for insert to authenticated
  with check (user_id = (select private.current_user_id()));
create policy devices_owner_update on public.devices for update to authenticated
  using (user_id = (select private.current_user_id()))
  with check (user_id = (select private.current_user_id()));
create policy devices_owner_delete on public.devices for delete to authenticated
  using (user_id = (select private.current_user_id()));

-- ===========================================================================
-- 7. Money
-- ===========================================================================
-- ledger: a creator sees their own creator-account rows; a brand member with finance.read sees the wallet and escrow
-- legs of their workspace. Nobody sees another party's legs. No client write policy exists: the ledger is append-only
-- and only public.post_ledger_txn() (service role) writes it.
grant select on public.ledger, public.ledger_transactions to authenticated;
create policy ledger_creator_select on public.ledger for select to authenticated
  using (account_kind = 'creator' and creator_id = (select private.current_creator_id()));
create policy ledger_brand_wallet_select on public.ledger for select to authenticated
  using (account_kind = 'wallet' and private.brand_can(brand_id, 'finance.read'));
create policy ledger_brand_escrow_select on public.ledger for select to authenticated
  using (account_kind = 'escrow' and private.brand_can((select b.brand_id from public.bounties b where b.id = ledger.bounty_id), 'finance.read'));
create policy ledger_transactions_select on public.ledger_transactions for select to authenticated
  using (exists (select 1 from public.ledger l where l.txn_id = ledger_transactions.id));

grant select on public.wallet_holds to authenticated;
create policy wallet_holds_brand_select on public.wallet_holds for select to authenticated
  using (private.brand_can(brand_id, 'finance.read'));

grant select on public.invoices to authenticated;
grant update (po_number, cost_center, vat_id) on public.invoices to authenticated;
create policy invoices_brand_select on public.invoices for select to authenticated
  using (private.brand_can(brand_id, 'finance.read'));
create policy invoices_brand_update on public.invoices for update to authenticated
  using (private.brand_can(brand_id, 'finance.write'))
  with check (private.brand_can(brand_id, 'finance.write'));

grant select on public.payouts, public.payout_methods, public.money_clock to authenticated;
create policy payouts_owner_select on public.payouts for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy payout_methods_owner_select on public.payout_methods for select to authenticated
  using (creator_id = (select private.current_creator_id()) and deleted_at is null);
create policy money_clock_owner_select on public.money_clock for select to authenticated
  using (creator_id = (select private.current_creator_id()));

-- ===========================================================================
-- 8. Bounties, submissions, posts
-- ===========================================================================
-- bounties: members see all of their workspace's bounties; every signed-in user sees public live ones; a private or
-- invite-only bounty is visible to the creator it was offered to.
grant select on public.bounties to authenticated;
grant insert (id, app_id, brand_id, owner_member_id, created_by_member_id, title, type, visibility, cpm_cents, cpa_install_cents, cpa_trial_cents,
              cpa_paid_cents, flat_fee_cents, ad_commission_rate, per_video_cap_cents, per_creator_cap_cents, budget_cents, brief, rights_card,
              deliverables, eligibility, brief_lint, pay_math, format_ids, art, starts_at, ends_at, review_sla_hours, all_in_cpm_cents) on public.bounties to authenticated;
grant update (owner_member_id, title, type, visibility, cpm_cents, cpa_install_cents, cpa_trial_cents, cpa_paid_cents, flat_fee_cents,
              ad_commission_rate, per_video_cap_cents, per_creator_cap_cents, budget_cents, brief, rights_card, deliverables, eligibility,
              brief_lint, pay_math, format_ids, art, starts_at, ends_at, review_sla_hours, all_in_cpm_cents) on public.bounties to authenticated;
create policy bounties_member_select on public.bounties for select to authenticated
  using (brand_id in (select private.my_brand_ids()));
create policy bounties_public_select on public.bounties for select to authenticated
  using (visibility in ('open', 'drop') and status in ('live', 'paused', 'filled', 'ended', 'settled'));
create policy bounties_invited_select on public.bounties for select to authenticated
  using (exists (select 1 from public.offers o where o.bounty_id = bounties.id and o.creator_id = (select private.current_creator_id())));
create policy bounties_member_insert on public.bounties for insert to authenticated
  with check (
    private.brand_can(brand_id, 'bounty.write')
    and exists (select 1 from public.apps a where a.id = app_id and a.brand_id = bounties.brand_id)
  );
create policy bounties_member_update on public.bounties for update to authenticated
  using (status in ('draft', 'awaiting_funding') and private.brand_can(brand_id, 'bounty.write'))
  with check (status in ('draft', 'awaiting_funding') and private.brand_can(brand_id, 'bounty.write'));

-- submissions and everything hanging off them: the creator who made it and the workspace that owns the bounty.
grant select on public.submissions, public.submission_versions, public.video_analyses, public.qa_checks, public.feedback_notes to authenticated;
create policy submissions_creator_select on public.submissions for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy submissions_brand_select on public.submissions for select to authenticated
  using (brand_id in (select private.my_brand_ids()) and private.brand_can(brand_id, 'read'));
create policy submission_versions_select on public.submission_versions for select to authenticated
  using (exists (select 1 from public.submissions s where s.id = submission_versions.submission_id));
create policy video_analyses_select on public.video_analyses for select to authenticated
  using (exists (select 1 from public.submissions s where s.id = video_analyses.submission_id));
create policy qa_checks_select on public.qa_checks for select to authenticated
  using (exists (select 1 from public.video_analyses va where va.id = qa_checks.video_analysis_id));
create policy feedback_notes_select on public.feedback_notes for select to authenticated
  using (exists (select 1 from public.submissions s where s.id = feedback_notes.submission_id));

grant update (status, resolved_in_version, resolved_at) on public.feedback_notes to authenticated;
create policy feedback_notes_creator_update on public.feedback_notes for update to authenticated
  using (creator_id = (select private.current_creator_id()))
  with check (creator_id = (select private.current_creator_id()) and status in ('open', 'resolved'));

-- posts and the View Ledger
grant select on public.posts, public.view_snapshots, public.post_metrics_daily, public.post_metrics_hourly to authenticated;
create policy posts_creator_select on public.posts for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy posts_brand_select on public.posts for select to authenticated
  using (brand_id in (select private.my_brand_ids()));
create policy view_snapshots_select on public.view_snapshots for select to authenticated
  using (exists (select 1 from public.posts p where p.id = view_snapshots.post_id));
create policy post_metrics_daily_select on public.post_metrics_daily for select to authenticated
  using (exists (select 1 from public.posts p where p.id = post_metrics_daily.post_id));
create policy post_metrics_hourly_select on public.post_metrics_hourly for select to authenticated
  using (exists (select 1 from public.posts p where p.id = post_metrics_hourly.post_id));

-- saves (creators): save, unsave and mark joined. Claims, drops and submissions are server-managed columns.
grant select, delete on public.bounty_saves to authenticated;
grant insert (id, creator_id, bounty_id, stage) on public.bounty_saves to authenticated;
grant update (stage) on public.bounty_saves to authenticated;
create policy bounty_saves_owner_select on public.bounty_saves for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy bounty_saves_owner_insert on public.bounty_saves for insert to authenticated
  with check (creator_id = (select private.current_creator_id()) and stage = 'saved');
create policy bounty_saves_owner_update on public.bounty_saves for update to authenticated
  using (creator_id = (select private.current_creator_id()))
  with check (creator_id = (select private.current_creator_id()) and stage in ('saved', 'joined'));
create policy bounty_saves_owner_delete on public.bounty_saves for delete to authenticated
  using (creator_id = (select private.current_creator_id()) and stage = 'saved');

-- ===========================================================================
-- 9. Attribution, ads, rights
-- ===========================================================================
-- conversions carry the app's revenue, so only the brand side reads them; creators see their funnel on posts.funnel
grant select on public.conversions, public.app_metrics_daily, public.revenuecat_events to authenticated;
create policy conversions_brand_select on public.conversions for select to authenticated
  using (exists (select 1 from public.apps a where a.id = conversions.app_id));
create policy app_metrics_daily_brand_select on public.app_metrics_daily for select to authenticated
  using (exists (select 1 from public.apps a where a.id = app_metrics_daily.app_id));
create policy revenuecat_events_brand_select on public.revenuecat_events for select to authenticated
  using (exists (select 1 from public.apps a where a.id = revenuecat_events.app_id and private.brand_can(a.brand_id, 'integrations.manage')));

grant select on public.attribution_links, public.offer_code_pool to authenticated;
create policy attribution_links_creator_select on public.attribution_links for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy attribution_links_brand_select on public.attribution_links for select to authenticated
  using (exists (select 1 from public.apps a where a.id = attribution_links.app_id));
create policy offer_code_pool_creator_select on public.offer_code_pool for select to authenticated
  using (assigned_creator_id = (select private.current_creator_id()));
create policy offer_code_pool_brand_select on public.offer_code_pool for select to authenticated
  using (exists (select 1 from public.apps a where a.id = offer_code_pool.app_id and private.brand_can(a.brand_id, 'integrations.manage')));

grant select on public.ads, public.ad_daily, public.rights_grants, public.rights_renewals to authenticated;
create policy ads_creator_select on public.ads for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy ads_brand_select on public.ads for select to authenticated
  using (brand_id in (select private.my_brand_ids()));
create policy ad_daily_select on public.ad_daily for select to authenticated
  using (exists (select 1 from public.ads a where a.id = ad_daily.ad_id));
create policy rights_grants_creator_select on public.rights_grants for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy rights_grants_brand_select on public.rights_grants for select to authenticated
  using (brand_id in (select private.my_brand_ids()));
create policy rights_renewals_select on public.rights_renewals for select to authenticated
  using (exists (select 1 from public.rights_grants g where g.id = rights_renewals.grant_id));

-- ===========================================================================
-- 10. Market: offers, auctions, specs
-- ===========================================================================
grant select on public.offers, public.offer_messages, public.auctions, public.auction_bids, public.specs, public.spec_licenses to authenticated;
create policy offers_creator_select on public.offers for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy offers_brand_select on public.offers for select to authenticated
  using (brand_id in (select private.my_brand_ids()));
create policy offer_messages_select on public.offer_messages for select to authenticated
  using (exists (select 1 from public.offers o where o.id = offer_messages.offer_id));

-- auctions are visible to every signed-in user (brands bid, creators watch); sealed bids follow the rules in section 2
create policy auctions_select on public.auctions for select to authenticated
  using (deleted_at is null or creator_id = (select private.current_creator_id()));
create policy auction_bids_own_select on public.auction_bids for select to authenticated
  using (brand_id in (select private.my_brand_ids()));
create policy auction_bids_closed_select on public.auction_bids for select to authenticated
  using (private.auction_bids_visible(auction_id));

create policy specs_owner_select on public.specs for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy specs_listed_select on public.specs for select to authenticated
  using (deleted_at is null and status in ('listed', 'licensed'));
create policy specs_first_refusal_select on public.specs for select to authenticated
  using (deleted_at is null and status = 'first_refusal' and source_brand_id in (select private.my_brand_ids()));
create policy spec_licenses_brand_select on public.spec_licenses for select to authenticated
  using (brand_id in (select private.my_brand_ids()));
create policy spec_licenses_creator_select on public.spec_licenses for select to authenticated
  using (exists (select 1 from public.specs s where s.id = spec_licenses.spec_id and s.creator_id = (select private.current_creator_id())));

-- ===========================================================================
-- 11. Trust
-- ===========================================================================
grant select on public.creator_reputation, public.disputes, public.dispute_events, public.scam_reports, public.verifications,
  public.tax_profiles, public.tax_docs, public.compliance_checks, public.compliance_check_items to authenticated;
create policy creator_reputation_owner_select on public.creator_reputation for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy disputes_creator_select on public.disputes for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy disputes_brand_select on public.disputes for select to authenticated
  using (brand_id in (select private.my_brand_ids()) and private.brand_can(brand_id, 'read'));
create policy dispute_events_select on public.dispute_events for select to authenticated
  using (exists (select 1 from public.disputes d where d.id = dispute_events.dispute_id));
create policy scam_reports_reporter_select on public.scam_reports for select to authenticated
  using (reporter_creator_id = (select private.current_creator_id()) or reporter_brand_id in (select private.my_brand_ids()));
create policy verifications_creator_select on public.verifications for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy verifications_brand_select on public.verifications for select to authenticated
  using (brand_id in (select private.my_brand_ids()) and private.brand_can(brand_id, 'workspace.manage'));
create policy tax_profiles_owner_select on public.tax_profiles for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy tax_docs_owner_select on public.tax_docs for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy compliance_checks_creator_select on public.compliance_checks for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy compliance_checks_brand_select on public.compliance_checks for select to authenticated
  using (brand_id in (select private.my_brand_ids()));
create policy compliance_check_items_select on public.compliance_check_items for select to authenticated
  using (exists (select 1 from public.compliance_checks c where c.id = compliance_check_items.compliance_check_id));

-- ===========================================================================
-- 12. Growth
-- ===========================================================================
grant select on public.crews, public.crew_members, public.leaderboards, public.leaderboard_entries, public.referrals, public.drop_claims to authenticated;
create policy crews_select on public.crews for select to authenticated
  using (deleted_at is null);
create policy crew_members_select on public.crew_members for select to authenticated
  using (crew_id in (select private.my_crew_ids()));
create policy leaderboards_select on public.leaderboards for select to authenticated
  using (private.can_see_leaderboard(id));
create policy leaderboard_entries_select on public.leaderboard_entries for select to authenticated
  using (private.can_see_leaderboard(leaderboard_id));
create policy referrals_select on public.referrals for select to authenticated
  using (referrer_creator_id = (select private.current_creator_id())
         or referee_creator_id = (select private.current_creator_id())
         or referrer_brand_id in (select private.my_brand_ids())
         or referee_brand_id in (select private.my_brand_ids()));
create policy drop_claims_owner_select on public.drop_claims for select to authenticated
  using (creator_id = (select private.current_creator_id()));

-- ===========================================================================
-- 13. Platform
-- ===========================================================================
grant select on public.notifications to authenticated;
grant update (read_at) on public.notifications to authenticated;
create policy notifications_owner_select on public.notifications for select to authenticated
  using (recipient_user_id = (select private.current_user_id()));
create policy notifications_owner_update on public.notifications for update to authenticated
  using (recipient_user_id = (select private.current_user_id()))
  with check (recipient_user_id = (select private.current_user_id()));

grant select on public.integrations, public.api_keys, public.webhooks, public.webhook_deliveries, public.activity_log, public.auto_approve_rules,
  public.rule_audit_log, public.test_plans, public.fatigue_alerts, public.brand_lists to authenticated;
create policy integrations_member_select on public.integrations for select to authenticated
  using (deleted_at is null and private.brand_can(brand_id, 'read'));
create policy api_keys_member_select on public.api_keys for select to authenticated
  using (private.brand_can(brand_id, 'api.manage'));
create policy webhooks_member_select on public.webhooks for select to authenticated
  using (deleted_at is null and private.brand_can(brand_id, 'api.manage'));
create policy webhook_deliveries_select on public.webhook_deliveries for select to authenticated
  using (exists (select 1 from public.webhooks w where w.id = webhook_deliveries.webhook_id));
create policy activity_log_member_select on public.activity_log for select to authenticated
  using (private.brand_can(brand_id, 'read'));
create policy auto_approve_rules_member_select on public.auto_approve_rules for select to authenticated
  using (deleted_at is null and private.brand_can(brand_id, 'review'));
create policy rule_audit_log_select on public.rule_audit_log for select to authenticated
  using (exists (select 1 from public.auto_approve_rules r where r.id = rule_audit_log.rule_id));
create policy test_plans_member_select on public.test_plans for select to authenticated
  using (private.brand_can(brand_id, 'read'));
create policy fatigue_alerts_member_select on public.fatigue_alerts for select to authenticated
  using (private.brand_can(brand_id, 'read'));
create policy brand_lists_member_select on public.brand_lists for select to authenticated
  using (deleted_at is null and private.brand_can(brand_id, 'read'));

grant select on public.flo_suggestions, public.threads, public.chat_messages to authenticated;
grant update (helpful) on public.flo_suggestions to authenticated;
create policy flo_suggestions_creator_select on public.flo_suggestions for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy flo_suggestions_brand_select on public.flo_suggestions for select to authenticated
  using (brand_id in (select private.my_brand_ids()));
create policy flo_suggestions_creator_update on public.flo_suggestions for update to authenticated
  using (creator_id = (select private.current_creator_id()))
  with check (creator_id = (select private.current_creator_id()));
create policy threads_creator_select on public.threads for select to authenticated
  using (creator_id = (select private.current_creator_id()));
create policy threads_brand_select on public.threads for select to authenticated
  using (brand_id in (select private.my_brand_ids()));
create policy chat_messages_select on public.chat_messages for select to authenticated
  using (exists (select 1 from public.threads t where t.id = chat_messages.thread_id));

-- ===========================================================================
-- 14. Admins read every table that has any client grant (writes go through the admin API, audited in audit_log)
-- ===========================================================================
do $admin$
declare
  t record;
begin
  for t in
    select c.relname
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind in ('r', 'p') and not c.relispartition
      and has_table_privilege('authenticated', c.oid, 'select')
  loop
    execute format(
      'create policy %I on public.%I for select to authenticated using ((select private.is_admin()))',
      t.relname || '_admin_select', t.relname
    );
  end loop;
end
$admin$;

-- ===========================================================================
-- 15. Storage buckets (private) and their policies. Skipped on vanilla Postgres where the storage schema is absent.
--     Path convention: <owner id>/<file>.
-- ===========================================================================
do $storage$
begin
  if to_regclass('storage.buckets') is not null and to_regclass('storage.objects') is not null then
    insert into storage.buckets (id, name, public) values
      ('tax-docs', 'tax-docs', false),
      ('invoices', 'invoices', false),
      ('evidence', 'evidence', false),
      ('uploads', 'uploads', false)
    on conflict (id) do nothing;

    execute $p$create policy "tax_docs_owner_read" on storage.objects for select to authenticated
      using (bucket_id = 'tax-docs' and (storage.foldername(name))[1] = (select private.current_creator_id()))$p$;
    execute $p$create policy "invoices_finance_read" on storage.objects for select to authenticated
      using (bucket_id = 'invoices' and private.brand_can((storage.foldername(name))[1], 'finance.read'))$p$;
    execute $p$create policy "evidence_party_read" on storage.objects for select to authenticated
      using (bucket_id = 'evidence' and exists (select 1 from public.disputes d where d.id = (storage.foldername(name))[1]))$p$;
    execute $p$create policy "evidence_party_write" on storage.objects for insert to authenticated
      with check (bucket_id = 'evidence' and exists (select 1 from public.disputes d where d.id = (storage.foldername(name))[1]))$p$;
    execute $p$create policy "uploads_owner_read" on storage.objects for select to authenticated
      using (bucket_id = 'uploads' and (storage.foldername(name))[1] = (select private.current_creator_id()))$p$;
    execute $p$create policy "uploads_owner_write" on storage.objects for insert to authenticated
      with check (bucket_id = 'uploads' and (storage.foldername(name))[1] = (select private.current_creator_id()))$p$;
  end if;
end
$storage$;
